<?php

use Illuminate\Database\Seeder;

class state16TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of IN - Indiana.
        //If the table 'cities' exists, insert the data to the table.
        if (DB::table('cities')->get()->count() >= 0) {
            DB::table('cities')->insert([
                ['name' => 'Berne', 'state_id' => 16],
                ['name' => 'Decatur', 'state_id' => 16],
                ['name' => 'Geneva', 'state_id' => 16],
                ['name' => 'Linn Grove', 'state_id' => 16],
                ['name' => 'Monroe', 'state_id' => 16],
                ['name' => 'Pleasant Mills', 'state_id' => 16],
                ['name' => 'Preble', 'state_id' => 16],
                ['name' => 'Arcola', 'state_id' => 16],
                ['name' => 'Grabill', 'state_id' => 16],
                ['name' => 'Harlan', 'state_id' => 16],
                ['name' => 'Hoagland', 'state_id' => 16],
                ['name' => 'Huntertown', 'state_id' => 16],
                ['name' => 'Leo', 'state_id' => 16],
                ['name' => 'Monroeville', 'state_id' => 16],
                ['name' => 'New Haven', 'state_id' => 16],
                ['name' => 'Woodburn', 'state_id' => 16],
                ['name' => 'Yoder', 'state_id' => 16],
                ['name' => 'Zanesville', 'state_id' => 16],
                ['name' => 'Fort Wayne', 'state_id' => 16],
                ['name' => 'Columbus', 'state_id' => 16],
                ['name' => 'Clifford', 'state_id' => 16],
                ['name' => 'Elizabethtown', 'state_id' => 16],
                ['name' => 'Grammer', 'state_id' => 16],
                ['name' => 'Hartsville', 'state_id' => 16],
                ['name' => 'Hope', 'state_id' => 16],
                ['name' => 'Jonesville', 'state_id' => 16],
                ['name' => 'Taylorsville', 'state_id' => 16],
                ['name' => 'Ambia', 'state_id' => 16],
                ['name' => 'Boswell', 'state_id' => 16],
                ['name' => 'Earl Park', 'state_id' => 16],
                ['name' => 'Fowler', 'state_id' => 16],
                ['name' => 'Otterbein', 'state_id' => 16],
                ['name' => 'Oxford', 'state_id' => 16],
                ['name' => 'Talbot', 'state_id' => 16],
                ['name' => 'Templeton', 'state_id' => 16],
                ['name' => 'Hartford City', 'state_id' => 16],
                ['name' => 'Montpelier', 'state_id' => 16],
                ['name' => 'Lebanon', 'state_id' => 16],
                ['name' => 'Thorntown', 'state_id' => 16],
                ['name' => 'Whitestown', 'state_id' => 16],
                ['name' => 'Zionsville', 'state_id' => 16],
                ['name' => 'Advance', 'state_id' => 16],
                ['name' => 'Jamestown', 'state_id' => 16],
                ['name' => 'Morgantown', 'state_id' => 16],
                ['name' => 'Helmsburg', 'state_id' => 16],
                ['name' => 'Nashville', 'state_id' => 16],
                ['name' => 'Bringhurst', 'state_id' => 16],
                ['name' => 'Burlington', 'state_id' => 16],
                ['name' => 'Burrows', 'state_id' => 16],
                ['name' => 'Camden', 'state_id' => 16],
                ['name' => 'Cutler', 'state_id' => 16],
                ['name' => 'Delphi', 'state_id' => 16],
                ['name' => 'Flora', 'state_id' => 16],
                ['name' => 'Rockfield', 'state_id' => 16],
                ['name' => 'Yeoman', 'state_id' => 16],
                ['name' => 'Galveston', 'state_id' => 16],
                ['name' => 'Lake Cicott', 'state_id' => 16],
                ['name' => 'Logansport', 'state_id' => 16],
                ['name' => 'Lucerne', 'state_id' => 16],
                ['name' => 'New Waverly', 'state_id' => 16],
                ['name' => 'Onward', 'state_id' => 16],
                ['name' => 'Royal Center', 'state_id' => 16],
                ['name' => 'Twelve Mile', 'state_id' => 16],
                ['name' => 'Walton', 'state_id' => 16],
                ['name' => 'Young America', 'state_id' => 16],
                ['name' => 'Bethlehem', 'state_id' => 16],
                ['name' => 'Borden', 'state_id' => 16],
                ['name' => 'Charlestown', 'state_id' => 16],
                ['name' => 'Henryville', 'state_id' => 16],
                ['name' => 'Clarksville', 'state_id' => 16],
                ['name' => 'Jeffersonville', 'state_id' => 16],
                ['name' => 'Marysville', 'state_id' => 16],
                ['name' => 'Memphis', 'state_id' => 16],
                ['name' => 'Nabb', 'state_id' => 16],
                ['name' => 'New Washington', 'state_id' => 16],
                ['name' => 'Otisco', 'state_id' => 16],
                ['name' => 'Sellersburg', 'state_id' => 16],
                ['name' => 'Underwood', 'state_id' => 16],
                ['name' => 'Bowling Green', 'state_id' => 16],
                ['name' => 'Brazil', 'state_id' => 16],
                ['name' => 'Carbon', 'state_id' => 16],
                ['name' => 'Centerpoint', 'state_id' => 16],
                ['name' => 'Clay City', 'state_id' => 16],
                ['name' => 'Coalmont', 'state_id' => 16],
                ['name' => 'Cory', 'state_id' => 16],
                ['name' => 'Harmony', 'state_id' => 16],
                ['name' => 'Knightsville', 'state_id' => 16],
                ['name' => 'Poland', 'state_id' => 16],
                ['name' => 'Staunton', 'state_id' => 16],
                ['name' => 'Colfax', 'state_id' => 16],
                ['name' => 'Forest', 'state_id' => 16],
                ['name' => 'Frankfort', 'state_id' => 16],
                ['name' => 'Kirklin', 'state_id' => 16],
                ['name' => 'Michigantown', 'state_id' => 16],
                ['name' => 'Mulberry', 'state_id' => 16],
                ['name' => 'Rossville', 'state_id' => 16],
                ['name' => 'Sedalia', 'state_id' => 16],
                ['name' => 'Eckerty', 'state_id' => 16],
                ['name' => 'English', 'state_id' => 16],
                ['name' => 'Grantsburg', 'state_id' => 16],
                ['name' => 'Leavenworth', 'state_id' => 16],
                ['name' => 'Marengo', 'state_id' => 16],
                ['name' => 'Milltown', 'state_id' => 16],
                ['name' => 'Sulphur', 'state_id' => 16],
                ['name' => 'Taswell', 'state_id' => 16],
                ['name' => 'Washington', 'state_id' => 16],
                ['name' => 'Cannelburg', 'state_id' => 16],
                ['name' => 'Elnora', 'state_id' => 16],
                ['name' => 'Montgomery', 'state_id' => 16],
                ['name' => 'Odon', 'state_id' => 16],
                ['name' => 'Plainville', 'state_id' => 16],
                ['name' => 'Aurora', 'state_id' => 16],
                ['name' => 'Dillsboro', 'state_id' => 16],
                ['name' => 'Guilford', 'state_id' => 16],
                ['name' => 'Lawrenceburg', 'state_id' => 16],
                ['name' => 'Moores Hill', 'state_id' => 16],
                ['name' => 'West Harrison', 'state_id' => 16],
                ['name' => 'Clarksburg', 'state_id' => 16],
                ['name' => 'Greensburg', 'state_id' => 16],
                ['name' => 'Millhousen', 'state_id' => 16],
                ['name' => 'New Point', 'state_id' => 16],
                ['name' => 'Saint Paul', 'state_id' => 16],
                ['name' => 'Westport', 'state_id' => 16],
                ['name' => 'Ashley', 'state_id' => 16],
                ['name' => 'Auburn', 'state_id' => 16],
                ['name' => 'Butler', 'state_id' => 16],
                ['name' => 'Corunna', 'state_id' => 16],
                ['name' => 'Garrett', 'state_id' => 16],
                ['name' => 'Saint Joe', 'state_id' => 16],
                ['name' => 'Spencerville', 'state_id' => 16],
                ['name' => 'Waterloo', 'state_id' => 16],
                ['name' => 'Muncie', 'state_id' => 16],
                ['name' => 'Albany', 'state_id' => 16],
                ['name' => 'Daleville', 'state_id' => 16],
                ['name' => 'Eaton', 'state_id' => 16],
                ['name' => 'Gaston', 'state_id' => 16],
                ['name' => 'Oakville', 'state_id' => 16],
                ['name' => 'Selma', 'state_id' => 16],
                ['name' => 'Yorktown', 'state_id' => 16],
                ['name' => 'Birdseye', 'state_id' => 16],
                ['name' => 'Celestine', 'state_id' => 16],
                ['name' => 'Dubois', 'state_id' => 16],
                ['name' => 'Ferdinand', 'state_id' => 16],
                ['name' => 'Holland', 'state_id' => 16],
                ['name' => 'Huntingburg', 'state_id' => 16],
                ['name' => 'Ireland', 'state_id' => 16],
                ['name' => 'Jasper', 'state_id' => 16],
                ['name' => 'Saint Anthony', 'state_id' => 16],
                ['name' => 'Schnellville', 'state_id' => 16],
                ['name' => 'Bristol', 'state_id' => 16],
                ['name' => 'Elkhart', 'state_id' => 16],
                ['name' => 'Goshen', 'state_id' => 16],
                ['name' => 'Middlebury', 'state_id' => 16],
                ['name' => 'Millersburg', 'state_id' => 16],
                ['name' => 'Nappanee', 'state_id' => 16],
                ['name' => 'New Paris', 'state_id' => 16],
                ['name' => 'Wakarusa', 'state_id' => 16],
                ['name' => 'Glenwood', 'state_id' => 16],
                ['name' => 'Bentonville', 'state_id' => 16],
                ['name' => 'Connersville', 'state_id' => 16],
                ['name' => 'Floyds Knobs', 'state_id' => 16],
                ['name' => 'Georgetown', 'state_id' => 16],
                ['name' => 'Greenville', 'state_id' => 16],
                ['name' => 'Mount Saint Francis', 'state_id' => 16],
                ['name' => 'New Albany', 'state_id' => 16],
                ['name' => 'Attica', 'state_id' => 16],
                ['name' => 'Covington', 'state_id' => 16],
                ['name' => 'Hillsboro', 'state_id' => 16],
                ['name' => 'Kingman', 'state_id' => 16],
                ['name' => 'Mellott', 'state_id' => 16],
                ['name' => 'Newtown', 'state_id' => 16],
                ['name' => 'Veedersburg', 'state_id' => 16],
                ['name' => 'Wallace', 'state_id' => 16],
                ['name' => 'West College Corner', 'state_id' => 16],
                ['name' => 'Bath', 'state_id' => 16],
                ['name' => 'Brookville', 'state_id' => 16],
                ['name' => 'Cedar Grove', 'state_id' => 16],
                ['name' => 'Laurel', 'state_id' => 16],
                ['name' => 'Metamora', 'state_id' => 16],
                ['name' => 'New Trenton', 'state_id' => 16],
                ['name' => 'Oldenburg', 'state_id' => 16],
                ['name' => 'Akron', 'state_id' => 16],
                ['name' => 'Athens', 'state_id' => 16],
                ['name' => 'Delong', 'state_id' => 16],
                ['name' => 'Fulton', 'state_id' => 16],
                ['name' => 'Grass Creek', 'state_id' => 16],
                ['name' => 'Kewanna', 'state_id' => 16],
                ['name' => 'Leiters Ford', 'state_id' => 16],
                ['name' => 'Rochester', 'state_id' => 16],
                ['name' => 'Haubstadt', 'state_id' => 16],
                ['name' => 'Hazleton', 'state_id' => 16],
                ['name' => 'Buckskin', 'state_id' => 16],
                ['name' => 'Fort Branch', 'state_id' => 16],
                ['name' => 'Francisco', 'state_id' => 16],
                ['name' => 'Mackey', 'state_id' => 16],
                ['name' => 'Oakland City', 'state_id' => 16],
                ['name' => 'Owensville', 'state_id' => 16],
                ['name' => 'Patoka', 'state_id' => 16],
                ['name' => 'Princeton', 'state_id' => 16],
                ['name' => 'Somerville', 'state_id' => 16],
                ['name' => 'Fairmount', 'state_id' => 16],
                ['name' => 'Fowlerton', 'state_id' => 16],
                ['name' => 'Gas City', 'state_id' => 16],
                ['name' => 'Jonesboro', 'state_id' => 16],
                ['name' => 'Marion', 'state_id' => 16],
                ['name' => 'Matthews', 'state_id' => 16],
                ['name' => 'Swayzee', 'state_id' => 16],
                ['name' => 'Sweetser', 'state_id' => 16],
                ['name' => 'Upland', 'state_id' => 16],
                ['name' => 'Van Buren', 'state_id' => 16],
                ['name' => 'Bloomfield', 'state_id' => 16],
                ['name' => 'Jasonville', 'state_id' => 16],
                ['name' => 'Koleen', 'state_id' => 16],
                ['name' => 'Linton', 'state_id' => 16],
                ['name' => 'Lyons', 'state_id' => 16],
                ['name' => 'Midland', 'state_id' => 16],
                ['name' => 'Newberry', 'state_id' => 16],
                ['name' => 'Owensburg', 'state_id' => 16],
                ['name' => 'Scotland', 'state_id' => 16],
                ['name' => 'Solsberry', 'state_id' => 16],
                ['name' => 'Switz City', 'state_id' => 16],
                ['name' => 'Worthington', 'state_id' => 16],
                ['name' => 'Arcadia', 'state_id' => 16],
                ['name' => 'Atlanta', 'state_id' => 16],
                ['name' => 'Carmel', 'state_id' => 16],
                ['name' => 'Cicero', 'state_id' => 16],
                ['name' => 'Fishers', 'state_id' => 16],
                ['name' => 'Noblesville', 'state_id' => 16],
                ['name' => 'Sheridan', 'state_id' => 16],
                ['name' => 'Westfield', 'state_id' => 16],
                ['name' => 'Indianapolis', 'state_id' => 16],
                ['name' => 'Fortville', 'state_id' => 16],
                ['name' => 'Mccordsville', 'state_id' => 16],
                ['name' => 'Charlottesville', 'state_id' => 16],
                ['name' => 'Finly', 'state_id' => 16],
                ['name' => 'Greenfield', 'state_id' => 16],
                ['name' => 'Maxwell', 'state_id' => 16],
                ['name' => 'New Palestine', 'state_id' => 16],
                ['name' => 'Wilkinson', 'state_id' => 16],
                ['name' => 'Bradford', 'state_id' => 16],
                ['name' => 'Central', 'state_id' => 16],
                ['name' => 'Corydon', 'state_id' => 16],
                ['name' => 'Crandall', 'state_id' => 16],
                ['name' => 'Depauw', 'state_id' => 16],
                ['name' => 'Elizabeth', 'state_id' => 16],
                ['name' => 'Laconia', 'state_id' => 16],
                ['name' => 'Lanesville', 'state_id' => 16],
                ['name' => 'Mauckport', 'state_id' => 16],
                ['name' => 'New Middletown', 'state_id' => 16],
                ['name' => 'New Salisbury', 'state_id' => 16],
                ['name' => 'Palmyra', 'state_id' => 16],
                ['name' => 'Ramsey', 'state_id' => 16],
                ['name' => 'Amo', 'state_id' => 16],
                ['name' => 'Brownsburg', 'state_id' => 16],
                ['name' => 'Clayton', 'state_id' => 16],
                ['name' => 'Coatesville', 'state_id' => 16],
                ['name' => 'Danville', 'state_id' => 16],
                ['name' => 'Avon', 'state_id' => 16],
                ['name' => 'Lizton', 'state_id' => 16],
                ['name' => 'North Salem', 'state_id' => 16],
                ['name' => 'Pittsboro', 'state_id' => 16],
                ['name' => 'Plainfield', 'state_id' => 16],
                ['name' => 'Stilesville', 'state_id' => 16],
                ['name' => 'Knightstown', 'state_id' => 16],
                ['name' => 'Dunreith', 'state_id' => 16],
                ['name' => 'Greensboro', 'state_id' => 16],
                ['name' => 'Kennard', 'state_id' => 16],
                ['name' => 'Lewisville', 'state_id' => 16],
                ['name' => 'Middletown', 'state_id' => 16],
                ['name' => 'Mooreland', 'state_id' => 16],
                ['name' => 'Mount Summit', 'state_id' => 16],
                ['name' => 'New Castle', 'state_id' => 16],
                ['name' => 'New Lisbon', 'state_id' => 16],
                ['name' => 'Shirley', 'state_id' => 16],
                ['name' => 'Spiceland', 'state_id' => 16],
                ['name' => 'Springport', 'state_id' => 16],
                ['name' => 'Straughn', 'state_id' => 16],
                ['name' => 'Sulphur Springs', 'state_id' => 16],
                ['name' => 'Kokomo', 'state_id' => 16],
                ['name' => 'Greentown', 'state_id' => 16],
                ['name' => 'Hemlock', 'state_id' => 16],
                ['name' => 'Oakford', 'state_id' => 16],
                ['name' => 'Russiaville', 'state_id' => 16],
                ['name' => 'West Middleton', 'state_id' => 16],
                ['name' => 'Andrews', 'state_id' => 16],
                ['name' => 'Bippus', 'state_id' => 16],
                ['name' => 'Huntington', 'state_id' => 16],
                ['name' => 'Markle', 'state_id' => 16],
                ['name' => 'Roanoke', 'state_id' => 16],
                ['name' => 'Warren', 'state_id' => 16],
                ['name' => 'Brownstown', 'state_id' => 16],
                ['name' => 'Cortland', 'state_id' => 16],
                ['name' => 'Crothersville', 'state_id' => 16],
                ['name' => 'Freetown', 'state_id' => 16],
                ['name' => 'Kurtz', 'state_id' => 16],
                ['name' => 'Medora', 'state_id' => 16],
                ['name' => 'Norman', 'state_id' => 16],
                ['name' => 'Seymour', 'state_id' => 16],
                ['name' => 'Vallonia', 'state_id' => 16],
                ['name' => 'Demotte', 'state_id' => 16],
                ['name' => 'Tefft', 'state_id' => 16],
                ['name' => 'Wheatfield', 'state_id' => 16],
                ['name' => 'Fair Oaks', 'state_id' => 16],
                ['name' => 'Remington', 'state_id' => 16],
                ['name' => 'Rensselaer', 'state_id' => 16],
                ['name' => 'Bryant', 'state_id' => 16],
                ['name' => 'Dunkirk', 'state_id' => 16],
                ['name' => 'Pennville', 'state_id' => 16],
                ['name' => 'Portland', 'state_id' => 16],
                ['name' => 'Redkey', 'state_id' => 16],
                ['name' => 'Salamonia', 'state_id' => 16],
                ['name' => 'Canaan', 'state_id' => 16],
                ['name' => 'Deputy', 'state_id' => 16],
                ['name' => 'Dupont', 'state_id' => 16],
                ['name' => 'Hanover', 'state_id' => 16],
                ['name' => 'Madison', 'state_id' => 16],
                ['name' => 'Butlerville', 'state_id' => 16],
                ['name' => 'Commiskey', 'state_id' => 16],
                ['name' => 'Hayden', 'state_id' => 16],
                ['name' => 'North Vernon', 'state_id' => 16],
                ['name' => 'Paris Crossing', 'state_id' => 16],
                ['name' => 'Scipio', 'state_id' => 16],
                ['name' => 'Vernon', 'state_id' => 16],
                ['name' => 'Bargersville', 'state_id' => 16],
                ['name' => 'Edinburgh', 'state_id' => 16],
                ['name' => 'Franklin', 'state_id' => 16],
                ['name' => 'Greenwood', 'state_id' => 16],
                ['name' => 'Needham', 'state_id' => 16],
                ['name' => 'Nineveh', 'state_id' => 16],
                ['name' => 'Trafalgar', 'state_id' => 16],
                ['name' => 'Whiteland', 'state_id' => 16],
                ['name' => 'Bicknell', 'state_id' => 16],
                ['name' => 'Bruceville', 'state_id' => 16],
                ['name' => 'Decker', 'state_id' => 16],
                ['name' => 'Edwardsport', 'state_id' => 16],
                ['name' => 'Freelandville', 'state_id' => 16],
                ['name' => 'Monroe City', 'state_id' => 16],
                ['name' => 'Oaktown', 'state_id' => 16],
                ['name' => 'Ragsdale', 'state_id' => 16],
                ['name' => 'Sandborn', 'state_id' => 16],
                ['name' => 'Vincennes', 'state_id' => 16],
                ['name' => 'Westphalia', 'state_id' => 16],
                ['name' => 'Wheatland', 'state_id' => 16],
                ['name' => 'Atwood', 'state_id' => 16],
                ['name' => 'Burket', 'state_id' => 16],
                ['name' => 'Claypool', 'state_id' => 16],
                ['name' => 'Etna Green', 'state_id' => 16],
                ['name' => 'Leesburg', 'state_id' => 16],
                ['name' => 'Mentone', 'state_id' => 16],
                ['name' => 'Milford', 'state_id' => 16],
                ['name' => 'North Webster', 'state_id' => 16],
                ['name' => 'Pierceton', 'state_id' => 16],
                ['name' => 'Syracuse', 'state_id' => 16],
                ['name' => 'Warsaw', 'state_id' => 16],
                ['name' => 'Winona Lake', 'state_id' => 16],
                ['name' => 'Silver Lake', 'state_id' => 16],
                ['name' => 'Shipshewana', 'state_id' => 16],
                ['name' => 'Topeka', 'state_id' => 16],
                ['name' => 'Howe', 'state_id' => 16],
                ['name' => 'Lagrange', 'state_id' => 16],
                ['name' => 'Mongo', 'state_id' => 16],
                ['name' => 'South Milford', 'state_id' => 16],
                ['name' => 'Stroh', 'state_id' => 16],
                ['name' => 'Wolcottville', 'state_id' => 16],
                ['name' => 'Cedar Lake', 'state_id' => 16],
                ['name' => 'Crown Point', 'state_id' => 16],
                ['name' => 'Dyer', 'state_id' => 16],
                ['name' => 'East Chicago', 'state_id' => 16],
                ['name' => 'Griffith', 'state_id' => 16],
                ['name' => 'Hammond', 'state_id' => 16],
                ['name' => 'Munster', 'state_id' => 16],
                ['name' => 'Highland', 'state_id' => 16],
                ['name' => 'Hobart', 'state_id' => 16],
                ['name' => 'Leroy', 'state_id' => 16],
                ['name' => 'Lowell', 'state_id' => 16],
                ['name' => 'Saint John', 'state_id' => 16],
                ['name' => 'Schererville', 'state_id' => 16],
                ['name' => 'Schneider', 'state_id' => 16],
                ['name' => 'Shelby', 'state_id' => 16],
                ['name' => 'Whiting', 'state_id' => 16],
                ['name' => 'Gary', 'state_id' => 16],
                ['name' => 'Lake Station', 'state_id' => 16],
                ['name' => 'Merrillville', 'state_id' => 16],
                ['name' => 'Hanna', 'state_id' => 16],
                ['name' => 'Kingsbury', 'state_id' => 16],
                ['name' => 'Kingsford Heights', 'state_id' => 16],
                ['name' => 'La Crosse', 'state_id' => 16],
                ['name' => 'La Porte', 'state_id' => 16],
                ['name' => 'Michigan City', 'state_id' => 16],
                ['name' => 'Mill Creek', 'state_id' => 16],
                ['name' => 'Rolling Prairie', 'state_id' => 16],
                ['name' => 'Union Mills', 'state_id' => 16],
                ['name' => 'Wanatah', 'state_id' => 16],
                ['name' => 'Westville', 'state_id' => 16],
                ['name' => 'Avoca', 'state_id' => 16],
                ['name' => 'Bedford', 'state_id' => 16],
                ['name' => 'Heltonville', 'state_id' => 16],
                ['name' => 'Huron', 'state_id' => 16],
                ['name' => 'Mitchell', 'state_id' => 16],
                ['name' => 'Oolitic', 'state_id' => 16],
                ['name' => 'Springville', 'state_id' => 16],
                ['name' => 'Tunnelton', 'state_id' => 16],
                ['name' => 'Williams', 'state_id' => 16],
                ['name' => 'Alexandria', 'state_id' => 16],
                ['name' => 'Anderson', 'state_id' => 16],
                ['name' => 'Elwood', 'state_id' => 16],
                ['name' => 'Frankton', 'state_id' => 16],
                ['name' => 'Ingalls', 'state_id' => 16],
                ['name' => 'Lapel', 'state_id' => 16],
                ['name' => 'Markleville', 'state_id' => 16],
                ['name' => 'Orestes', 'state_id' => 16],
                ['name' => 'Pendleton', 'state_id' => 16],
                ['name' => 'Summitville', 'state_id' => 16],
                ['name' => 'Beech Grove', 'state_id' => 16],
                ['name' => 'Camby', 'state_id' => 16],
                ['name' => 'West Newton', 'state_id' => 16],
                ['name' => 'Argos', 'state_id' => 16],
                ['name' => 'Bourbon', 'state_id' => 16],
                ['name' => 'Bremen', 'state_id' => 16],
                ['name' => 'Culver', 'state_id' => 16],
                ['name' => 'Donaldson', 'state_id' => 16],
                ['name' => 'Lapaz', 'state_id' => 16],
                ['name' => 'Plymouth', 'state_id' => 16],
                ['name' => 'Tippecanoe', 'state_id' => 16],
                ['name' => 'Tyner', 'state_id' => 16],
                ['name' => 'Crane', 'state_id' => 16],
                ['name' => 'Loogootee', 'state_id' => 16],
                ['name' => 'Shoals', 'state_id' => 16],
                ['name' => 'Amboy', 'state_id' => 16],
                ['name' => 'Bunker Hill', 'state_id' => 16],
                ['name' => 'Converse', 'state_id' => 16],
                ['name' => 'Deedsville', 'state_id' => 16],
                ['name' => 'Denver', 'state_id' => 16],
                ['name' => 'Macy', 'state_id' => 16],
                ['name' => 'Mexico', 'state_id' => 16],
                ['name' => 'Miami', 'state_id' => 16],
                ['name' => 'Peru', 'state_id' => 16],
                ['name' => 'Grissom Arb', 'state_id' => 16],
                ['name' => 'Bloomington', 'state_id' => 16],
                ['name' => 'Clear Creek', 'state_id' => 16],
                ['name' => 'Ellettsville', 'state_id' => 16],
                ['name' => 'Harrodsburg', 'state_id' => 16],
                ['name' => 'Smithville', 'state_id' => 16],
                ['name' => 'Stanford', 'state_id' => 16],
                ['name' => 'Stinesville', 'state_id' => 16],
                ['name' => 'Unionville', 'state_id' => 16],
                ['name' => 'Alamo', 'state_id' => 16],
                ['name' => 'Crawfordsville', 'state_id' => 16],
                ['name' => 'Darlington', 'state_id' => 16],
                ['name' => 'Ladoga', 'state_id' => 16],
                ['name' => 'Linden', 'state_id' => 16],
                ['name' => 'New Market', 'state_id' => 16],
                ['name' => 'New Richmond', 'state_id' => 16],
                ['name' => 'New Ross', 'state_id' => 16],
                ['name' => 'Waveland', 'state_id' => 16],
                ['name' => 'Waynetown', 'state_id' => 16],
                ['name' => 'Wingate', 'state_id' => 16],
                ['name' => 'Brooklyn', 'state_id' => 16],
                ['name' => 'Eminence', 'state_id' => 16],
                ['name' => 'Martinsville', 'state_id' => 16],
                ['name' => 'Monrovia', 'state_id' => 16],
                ['name' => 'Mooresville', 'state_id' => 16],
                ['name' => 'Paragon', 'state_id' => 16],
                ['name' => 'Lake Village', 'state_id' => 16],
                ['name' => 'Roselawn', 'state_id' => 16],
                ['name' => 'Sumava Resorts', 'state_id' => 16],
                ['name' => 'Thayer', 'state_id' => 16],
                ['name' => 'Brook', 'state_id' => 16],
                ['name' => 'Goodland', 'state_id' => 16],
                ['name' => 'Kentland', 'state_id' => 16],
                ['name' => 'Morocco', 'state_id' => 16],
                ['name' => 'Mount Ayr', 'state_id' => 16],
                ['name' => 'Albion', 'state_id' => 16],
                ['name' => 'Avilla', 'state_id' => 16],
                ['name' => 'Cromwell', 'state_id' => 16],
                ['name' => 'Kendallville', 'state_id' => 16],
                ['name' => 'Kimmell', 'state_id' => 16],
                ['name' => 'Laotto', 'state_id' => 16],
                ['name' => 'Ligonier', 'state_id' => 16],
                ['name' => 'Rome City', 'state_id' => 16],
                ['name' => 'Wawaka', 'state_id' => 16],
                ['name' => 'Wolflake', 'state_id' => 16],
                ['name' => 'Rising Sun', 'state_id' => 16],
                ['name' => 'French Lick', 'state_id' => 16],
                ['name' => 'Orleans', 'state_id' => 16],
                ['name' => 'Paoli', 'state_id' => 16],
                ['name' => 'West Baden Springs', 'state_id' => 16],
                ['name' => 'Coal City', 'state_id' => 16],
                ['name' => 'Freedom', 'state_id' => 16],
                ['name' => 'Gosport', 'state_id' => 16],
                ['name' => 'Patricksburg', 'state_id' => 16],
                ['name' => 'Quincy', 'state_id' => 16],
                ['name' => 'Spencer', 'state_id' => 16],
                ['name' => 'Bellmore', 'state_id' => 16],
                ['name' => 'Bloomingdale', 'state_id' => 16],
                ['name' => 'Bridgeton', 'state_id' => 16],
                ['name' => 'Marshall', 'state_id' => 16],
                ['name' => 'Mecca', 'state_id' => 16],
                ['name' => 'Montezuma', 'state_id' => 16],
                ['name' => 'Rockville', 'state_id' => 16],
                ['name' => 'Rosedale', 'state_id' => 16],
                ['name' => 'Branchville', 'state_id' => 16],
                ['name' => 'Bristow', 'state_id' => 16],
                ['name' => 'Cannelton', 'state_id' => 16],
                ['name' => 'Derby', 'state_id' => 16],
                ['name' => 'Leopold', 'state_id' => 16],
                ['name' => 'Rome', 'state_id' => 16],
                ['name' => 'Saint Croix', 'state_id' => 16],
                ['name' => 'Tell City', 'state_id' => 16],
                ['name' => 'Otwell', 'state_id' => 16],
                ['name' => 'Petersburg', 'state_id' => 16],
                ['name' => 'Spurgeon', 'state_id' => 16],
                ['name' => 'Stendal', 'state_id' => 16],
                ['name' => 'Velpen', 'state_id' => 16],
                ['name' => 'Winslow', 'state_id' => 16],
                ['name' => 'Beverly Shores', 'state_id' => 16],
                ['name' => 'Boone Grove', 'state_id' => 16],
                ['name' => 'Chesterton', 'state_id' => 16],
                ['name' => 'Hebron', 'state_id' => 16],
                ['name' => 'Kouts', 'state_id' => 16],
                ['name' => 'Portage', 'state_id' => 16],
                ['name' => 'Valparaiso', 'state_id' => 16],
                ['name' => 'Wheeler', 'state_id' => 16],
                ['name' => 'Cynthiana', 'state_id' => 16],
                ['name' => 'Griffin', 'state_id' => 16],
                ['name' => 'Mount Vernon', 'state_id' => 16],
                ['name' => 'New Harmony', 'state_id' => 16],
                ['name' => 'Poseyville', 'state_id' => 16],
                ['name' => 'Wadesville', 'state_id' => 16],
                ['name' => 'Monterey', 'state_id' => 16],
                ['name' => 'Star City', 'state_id' => 16],
                ['name' => 'Winamac', 'state_id' => 16],
                ['name' => 'Francesville', 'state_id' => 16],
                ['name' => 'Medaryville', 'state_id' => 16],
                ['name' => 'Bainbridge', 'state_id' => 16],
                ['name' => 'Cloverdale', 'state_id' => 16],
                ['name' => 'Fillmore', 'state_id' => 16],
                ['name' => 'Greencastle', 'state_id' => 16],
                ['name' => 'Putnamville', 'state_id' => 16],
                ['name' => 'Reelsville', 'state_id' => 16],
                ['name' => 'Roachdale', 'state_id' => 16],
                ['name' => 'Russellville', 'state_id' => 16],
                ['name' => 'Farmland', 'state_id' => 16],
                ['name' => 'Losantville', 'state_id' => 16],
                ['name' => 'Lynn', 'state_id' => 16],
                ['name' => 'Modoc', 'state_id' => 16],
                ['name' => 'Parker City', 'state_id' => 16],
                ['name' => 'Ridgeville', 'state_id' => 16],
                ['name' => 'Saratoga', 'state_id' => 16],
                ['name' => 'Union City', 'state_id' => 16],
                ['name' => 'Winchester', 'state_id' => 16],
                ['name' => 'Batesville', 'state_id' => 16],
                ['name' => 'Cross Plains', 'state_id' => 16],
                ['name' => 'Friendship', 'state_id' => 16],
                ['name' => 'Holton', 'state_id' => 16],
                ['name' => 'Milan', 'state_id' => 16],
                ['name' => 'Morris', 'state_id' => 16],
                ['name' => 'Napoleon', 'state_id' => 16],
                ['name' => 'Osgood', 'state_id' => 16],
                ['name' => 'Pierceville', 'state_id' => 16],
                ['name' => 'Sunman', 'state_id' => 16],
                ['name' => 'Versailles', 'state_id' => 16],
                ['name' => 'Arlington', 'state_id' => 16],
                ['name' => 'Carthage', 'state_id' => 16],
                ['name' => 'Falmouth', 'state_id' => 16],
                ['name' => 'Homer', 'state_id' => 16],
                ['name' => 'Manilla', 'state_id' => 16],
                ['name' => 'Mays', 'state_id' => 16],
                ['name' => 'Milroy', 'state_id' => 16],
                ['name' => 'Rushville', 'state_id' => 16],
                ['name' => 'Granger', 'state_id' => 16],
                ['name' => 'Lakeville', 'state_id' => 16],
                ['name' => 'Mishawaka', 'state_id' => 16],
                ['name' => 'New Carlisle', 'state_id' => 16],
                ['name' => 'North Liberty', 'state_id' => 16],
                ['name' => 'Notre Dame', 'state_id' => 16],
                ['name' => 'Osceola', 'state_id' => 16],
                ['name' => 'Walkerton', 'state_id' => 16],
                ['name' => 'Wyatt', 'state_id' => 16],
                ['name' => 'South Bend', 'state_id' => 16],
                ['name' => 'Austin', 'state_id' => 16],
                ['name' => 'Lexington', 'state_id' => 16],
                ['name' => 'Scottsburg', 'state_id' => 16],
                ['name' => 'Boggstown', 'state_id' => 16],
                ['name' => 'Fairland', 'state_id' => 16],
                ['name' => 'Fountaintown', 'state_id' => 16],
                ['name' => 'Gwynneville', 'state_id' => 16],
                ['name' => 'Morristown', 'state_id' => 16],
                ['name' => 'Shelbyville', 'state_id' => 16],
                ['name' => 'Waldron', 'state_id' => 16],
                ['name' => 'Flat Rock', 'state_id' => 16],
                ['name' => 'Dale', 'state_id' => 16],
                ['name' => 'Evanston', 'state_id' => 16],
                ['name' => 'Fulda', 'state_id' => 16],
                ['name' => 'Gentryville', 'state_id' => 16],
                ['name' => 'Lamar', 'state_id' => 16],
                ['name' => 'Lincoln City', 'state_id' => 16],
                ['name' => 'Mariah Hill', 'state_id' => 16],
                ['name' => 'Saint Meinrad', 'state_id' => 16],
                ['name' => 'Santa Claus', 'state_id' => 16],
                ['name' => 'Troy', 'state_id' => 16],
                ['name' => 'Chrisney', 'state_id' => 16],
                ['name' => 'Grandview', 'state_id' => 16],
                ['name' => 'Hatfield', 'state_id' => 16],
                ['name' => 'Richland', 'state_id' => 16],
                ['name' => 'Rockport', 'state_id' => 16],
                ['name' => 'North Judson', 'state_id' => 16],
                ['name' => 'San Pierre', 'state_id' => 16],
                ['name' => 'Grovertown', 'state_id' => 16],
                ['name' => 'Hamlet', 'state_id' => 16],
                ['name' => 'Knox', 'state_id' => 16],
                ['name' => 'Ora', 'state_id' => 16],
                ['name' => 'Angola', 'state_id' => 16],
                ['name' => 'Fremont', 'state_id' => 16],
                ['name' => 'Hamilton', 'state_id' => 16],
                ['name' => 'Hudson', 'state_id' => 16],
                ['name' => 'Orland', 'state_id' => 16],
                ['name' => 'Pleasant Lake', 'state_id' => 16],
                ['name' => 'Carlisle', 'state_id' => 16],
                ['name' => 'Dugger', 'state_id' => 16],
                ['name' => 'Fairbanks', 'state_id' => 16],
                ['name' => 'Farmersburg', 'state_id' => 16],
                ['name' => 'Graysville', 'state_id' => 16],
                ['name' => 'Hymera', 'state_id' => 16],
                ['name' => 'Merom', 'state_id' => 16],
                ['name' => 'Paxton', 'state_id' => 16],
                ['name' => 'Shelburn', 'state_id' => 16],
                ['name' => 'Sullivan', 'state_id' => 16],
                ['name' => 'Bennington', 'state_id' => 16],
                ['name' => 'East Enterprise', 'state_id' => 16],
                ['name' => 'Florence', 'state_id' => 16],
                ['name' => 'Patriot', 'state_id' => 16],
                ['name' => 'Vevay', 'state_id' => 16],
                ['name' => 'Lafayette', 'state_id' => 16],
                ['name' => 'West Lafayette', 'state_id' => 16],
                ['name' => 'Battle Ground', 'state_id' => 16],
                ['name' => 'Buck Creek', 'state_id' => 16],
                ['name' => 'Clarks Hill', 'state_id' => 16],
                ['name' => 'Dayton', 'state_id' => 16],
                ['name' => 'Montmorenci', 'state_id' => 16],
                ['name' => 'Romney', 'state_id' => 16],
                ['name' => 'Stockwell', 'state_id' => 16],
                ['name' => 'Westpoint', 'state_id' => 16],
                ['name' => 'Goldsmith', 'state_id' => 16],
                ['name' => 'Hobbs', 'state_id' => 16],
                ['name' => 'Kempton', 'state_id' => 16],
                ['name' => 'Sharpsville', 'state_id' => 16],
                ['name' => 'Tipton', 'state_id' => 16],
                ['name' => 'Windfall', 'state_id' => 16],
                ['name' => 'Brownsville', 'state_id' => 16],
                ['name' => 'Liberty', 'state_id' => 16],
                ['name' => 'Inglefield', 'state_id' => 16],
                ['name' => 'Evansville', 'state_id' => 16],
                ['name' => 'Blanford', 'state_id' => 16],
                ['name' => 'Clinton', 'state_id' => 16],
                ['name' => 'Dana', 'state_id' => 16],
                ['name' => 'Hillsdale', 'state_id' => 16],
                ['name' => 'Saint Bernice', 'state_id' => 16],
                ['name' => 'Universal', 'state_id' => 16],
                ['name' => 'Cayuga', 'state_id' => 16],
                ['name' => 'Newport', 'state_id' => 16],
                ['name' => 'Perrysville', 'state_id' => 16],
                ['name' => 'Terre Haute', 'state_id' => 16],
                ['name' => 'Fontanet', 'state_id' => 16],
                ['name' => 'Lewis', 'state_id' => 16],
                ['name' => 'New Goshen', 'state_id' => 16],
                ['name' => 'Pimento', 'state_id' => 16],
                ['name' => 'Prairie Creek', 'state_id' => 16],
                ['name' => 'Prairieton', 'state_id' => 16],
                ['name' => 'Riley', 'state_id' => 16],
                ['name' => 'Saint Mary Of The Woods', 'state_id' => 16],
                ['name' => 'Seelyville', 'state_id' => 16],
                ['name' => 'Shepardsville', 'state_id' => 16],
                ['name' => 'West Terre Haute', 'state_id' => 16],
                ['name' => 'La Fontaine', 'state_id' => 16],
                ['name' => 'Lagro', 'state_id' => 16],
                ['name' => 'Laketon', 'state_id' => 16],
                ['name' => 'Liberty Mills', 'state_id' => 16],
                ['name' => 'North Manchester', 'state_id' => 16],
                ['name' => 'Roann', 'state_id' => 16],
                ['name' => 'Servia', 'state_id' => 16],
                ['name' => 'Somerset', 'state_id' => 16],
                ['name' => 'Urbana', 'state_id' => 16],
                ['name' => 'Wabash', 'state_id' => 16],
                ['name' => 'Pine Village', 'state_id' => 16],
                ['name' => 'State Line', 'state_id' => 16],
                ['name' => 'West Lebanon', 'state_id' => 16],
                ['name' => 'Williamsport', 'state_id' => 16],
                ['name' => 'Boonville', 'state_id' => 16],
                ['name' => 'Chandler', 'state_id' => 16],
                ['name' => 'Elberfeld', 'state_id' => 16],
                ['name' => 'Lynnville', 'state_id' => 16],
                ['name' => 'Newburgh', 'state_id' => 16],
                ['name' => 'Tennyson', 'state_id' => 16],
                ['name' => 'Campbellsburg', 'state_id' => 16],
                ['name' => 'Fredericksburg', 'state_id' => 16],
                ['name' => 'Hardinsburg', 'state_id' => 16],
                ['name' => 'Pekin', 'state_id' => 16],
                ['name' => 'Salem', 'state_id' => 16],
                ['name' => 'Boston', 'state_id' => 16],
                ['name' => 'Cambridge City', 'state_id' => 16],
                ['name' => 'Centerville', 'state_id' => 16],
                ['name' => 'Dublin', 'state_id' => 16],
                ['name' => 'Economy', 'state_id' => 16],
                ['name' => 'Fountain City', 'state_id' => 16],
                ['name' => 'Greens Fork', 'state_id' => 16],
                ['name' => 'Hagerstown', 'state_id' => 16],
                ['name' => 'Milton', 'state_id' => 16],
                ['name' => 'Pershing', 'state_id' => 16],
                ['name' => 'Richmond', 'state_id' => 16],
                ['name' => 'Webster', 'state_id' => 16],
                ['name' => 'Williamsburg', 'state_id' => 16],
                ['name' => 'Bluffton', 'state_id' => 16],
                ['name' => 'Craigville', 'state_id' => 16],
                ['name' => 'Keystone', 'state_id' => 16],
                ['name' => 'Liberty Center', 'state_id' => 16],
                ['name' => 'Ossian', 'state_id' => 16],
                ['name' => 'Petroleum', 'state_id' => 16],
                ['name' => 'Poneto', 'state_id' => 16],
                ['name' => 'Uniondale', 'state_id' => 16],
                ['name' => 'Brookston', 'state_id' => 16],
                ['name' => 'Buffalo', 'state_id' => 16],
                ['name' => 'Burnettsville', 'state_id' => 16],
                ['name' => 'Chalmers', 'state_id' => 16],
                ['name' => 'Idaville', 'state_id' => 16],
                ['name' => 'Monon', 'state_id' => 16],
                ['name' => 'Monticello', 'state_id' => 16],
                ['name' => 'Reynolds', 'state_id' => 16],
                ['name' => 'Wolcott', 'state_id' => 16],
                ['name' => 'Churubusco', 'state_id' => 16],
                ['name' => 'Columbia City', 'state_id' => 16],
                ['name' => 'Larwill', 'state_id' => 16],
                ['name' => 'South Whitley', 'state_id' => 16]
            ]);
        }
    }
}
