<?php

use Illuminate\Database\Seeder;

class state25TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of MO - Missouri.
        //If the table 'cities' exists, insert the data to the table.
        if (DB::table('cities')->get()->count() >= 0) {
            DB::table('cities')->insert([
                ['name' => 'Kirksville', 'state_id' => 25],
                ['name' => 'Brashear', 'state_id' => 25],
                ['name' => 'Gibbs', 'state_id' => 25],
                ['name' => 'Greentop', 'state_id' => 25],
                ['name' => 'Novinger', 'state_id' => 25],
                ['name' => 'Amazonia', 'state_id' => 25],
                ['name' => 'Bolckow', 'state_id' => 25],
                ['name' => 'Cosby', 'state_id' => 25],
                ['name' => 'Fillmore', 'state_id' => 25],
                ['name' => 'Helena', 'state_id' => 25],
                ['name' => 'Rea', 'state_id' => 25],
                ['name' => 'Rosendale', 'state_id' => 25],
                ['name' => 'Savannah', 'state_id' => 25],
                ['name' => 'Saint Joseph', 'state_id' => 25],
                ['name' => 'Fairfax', 'state_id' => 25],
                ['name' => 'Rock Port', 'state_id' => 25],
                ['name' => 'Tarkio', 'state_id' => 25],
                ['name' => 'Watson', 'state_id' => 25],
                ['name' => 'Westboro', 'state_id' => 25],
                ['name' => 'Farber', 'state_id' => 25],
                ['name' => 'Laddonia', 'state_id' => 25],
                ['name' => 'Vandalia', 'state_id' => 25],
                ['name' => 'Benton City', 'state_id' => 25],
                ['name' => 'Martinsburg', 'state_id' => 25],
                ['name' => 'Mexico', 'state_id' => 25],
                ['name' => 'Rush Hill', 'state_id' => 25],
                ['name' => 'Thompson', 'state_id' => 25],
                ['name' => 'Wheaton', 'state_id' => 25],
                ['name' => 'Butterfield', 'state_id' => 25],
                ['name' => 'Cassville', 'state_id' => 25],
                ['name' => 'Eagle Rock', 'state_id' => 25],
                ['name' => 'Exeter', 'state_id' => 25],
                ['name' => 'Golden', 'state_id' => 25],
                ['name' => 'Monett', 'state_id' => 25],
                ['name' => 'Purdy', 'state_id' => 25],
                ['name' => 'Seligman', 'state_id' => 25],
                ['name' => 'Shell Knob', 'state_id' => 25],
                ['name' => 'Washburn', 'state_id' => 25],
                ['name' => 'Golden City', 'state_id' => 25],
                ['name' => 'Lamar', 'state_id' => 25],
                ['name' => 'Liberal', 'state_id' => 25],
                ['name' => 'Milford', 'state_id' => 25],
                ['name' => 'Mindenmines', 'state_id' => 25],
                ['name' => 'Adrian', 'state_id' => 25],
                ['name' => 'Amoret', 'state_id' => 25],
                ['name' => 'Amsterdam', 'state_id' => 25],
                ['name' => 'Butler', 'state_id' => 25],
                ['name' => 'Drexel', 'state_id' => 25],
                ['name' => 'Foster', 'state_id' => 25],
                ['name' => 'Hume', 'state_id' => 25],
                ['name' => 'Rich Hill', 'state_id' => 25],
                ['name' => 'Rockville', 'state_id' => 25],
                ['name' => 'Cole Camp', 'state_id' => 25],
                ['name' => 'Edwards', 'state_id' => 25],
                ['name' => 'Ionia', 'state_id' => 25],
                ['name' => 'Lincoln', 'state_id' => 25],
                ['name' => 'Warsaw', 'state_id' => 25],
                ['name' => 'Patton', 'state_id' => 25],
                ['name' => 'Gipsy', 'state_id' => 25],
                ['name' => 'Glenallen', 'state_id' => 25],
                ['name' => 'Leopold', 'state_id' => 25],
                ['name' => 'Marble Hill', 'state_id' => 25],
                ['name' => 'Sedgewickville', 'state_id' => 25],
                ['name' => 'Sturdivant', 'state_id' => 25],
                ['name' => 'Zalma', 'state_id' => 25],
                ['name' => 'Ashland', 'state_id' => 25],
                ['name' => 'Hartsburg', 'state_id' => 25],
                ['name' => 'Columbia', 'state_id' => 25],
                ['name' => 'Centralia', 'state_id' => 25],
                ['name' => 'Hallsville', 'state_id' => 25],
                ['name' => 'Harrisburg', 'state_id' => 25],
                ['name' => 'Rocheport', 'state_id' => 25],
                ['name' => 'Sturgeon', 'state_id' => 25],
                ['name' => 'Mid Missouri', 'state_id' => 25],
                ['name' => 'Agency', 'state_id' => 25],
                ['name' => 'De Kalb', 'state_id' => 25],
                ['name' => 'Easton', 'state_id' => 25],
                ['name' => 'Faucett', 'state_id' => 25],
                ['name' => 'Rushville', 'state_id' => 25],
                ['name' => 'Poplar Bluff', 'state_id' => 25],
                ['name' => 'Broseley', 'state_id' => 25],
                ['name' => 'Fagus', 'state_id' => 25],
                ['name' => 'Fisk', 'state_id' => 25],
                ['name' => 'Harviell', 'state_id' => 25],
                ['name' => 'Neelyville', 'state_id' => 25],
                ['name' => 'Qulin', 'state_id' => 25],
                ['name' => 'Rombauer', 'state_id' => 25],
                ['name' => 'Braymer', 'state_id' => 25],
                ['name' => 'Breckenridge', 'state_id' => 25],
                ['name' => 'Cowgill', 'state_id' => 25],
                ['name' => 'Hamilton', 'state_id' => 25],
                ['name' => 'Kidder', 'state_id' => 25],
                ['name' => 'Kingston', 'state_id' => 25],
                ['name' => 'Polo', 'state_id' => 25],
                ['name' => 'Williamsburg', 'state_id' => 25],
                ['name' => 'Holts Summit', 'state_id' => 25],
                ['name' => 'Mokane', 'state_id' => 25],
                ['name' => 'New Bloomfield', 'state_id' => 25],
                ['name' => 'Portland', 'state_id' => 25],
                ['name' => 'Steedman', 'state_id' => 25],
                ['name' => 'Tebbetts', 'state_id' => 25],
                ['name' => 'Auxvasse', 'state_id' => 25],
                ['name' => 'Fulton', 'state_id' => 25],
                ['name' => 'Kingdom City', 'state_id' => 25],
                ['name' => 'Camdenton', 'state_id' => 25],
                ['name' => 'Lake Ozark', 'state_id' => 25],
                ['name' => 'Linn Creek', 'state_id' => 25],
                ['name' => 'Osage Beach', 'state_id' => 25],
                ['name' => 'Sunrise Beach', 'state_id' => 25],
                ['name' => 'Climax Springs', 'state_id' => 25],
                ['name' => 'Stoutland', 'state_id' => 25],
                ['name' => 'Montreal', 'state_id' => 25],
                ['name' => 'Macks Creek', 'state_id' => 25],
                ['name' => 'Roach', 'state_id' => 25],
                ['name' => 'Cape Girardeau', 'state_id' => 25],
                ['name' => 'Burfordville', 'state_id' => 25],
                ['name' => 'Daisy', 'state_id' => 25],
                ['name' => 'Delta', 'state_id' => 25],
                ['name' => 'Dutchtown', 'state_id' => 25],
                ['name' => 'Friedheim', 'state_id' => 25],
                ['name' => 'Gordonville', 'state_id' => 25],
                ['name' => 'Jackson', 'state_id' => 25],
                ['name' => 'Millersville', 'state_id' => 25],
                ['name' => 'Oak Ridge', 'state_id' => 25],
                ['name' => 'Old Appleton', 'state_id' => 25],
                ['name' => 'Pocahontas', 'state_id' => 25],
                ['name' => 'Whitewater', 'state_id' => 25],
                ['name' => 'Bogard', 'state_id' => 25],
                ['name' => 'Bosworth', 'state_id' => 25],
                ['name' => 'Carrollton', 'state_id' => 25],
                ['name' => 'De Witt', 'state_id' => 25],
                ['name' => 'Hale', 'state_id' => 25],
                ['name' => 'Norborne', 'state_id' => 25],
                ['name' => 'Stet', 'state_id' => 25],
                ['name' => 'Tina', 'state_id' => 25],
                ['name' => 'Ellsinore', 'state_id' => 25],
                ['name' => 'Fremont', 'state_id' => 25],
                ['name' => 'Grandin', 'state_id' => 25],
                ['name' => 'Van Buren', 'state_id' => 25],
                ['name' => 'Belton', 'state_id' => 25],
                ['name' => 'Peculiar', 'state_id' => 25],
                ['name' => 'Pleasant Hill', 'state_id' => 25],
                ['name' => 'Raymore', 'state_id' => 25],
                ['name' => 'Strasburg', 'state_id' => 25],
                ['name' => 'Harrisonville', 'state_id' => 25],
                ['name' => 'Archie', 'state_id' => 25],
                ['name' => 'Cleveland', 'state_id' => 25],
                ['name' => 'Creighton', 'state_id' => 25],
                ['name' => 'East Lynne', 'state_id' => 25],
                ['name' => 'Freeman', 'state_id' => 25],
                ['name' => 'Garden City', 'state_id' => 25],
                ['name' => 'El Dorado Springs', 'state_id' => 25],
                ['name' => 'Jerico Springs', 'state_id' => 25],
                ['name' => 'Caplinger Mills', 'state_id' => 25],
                ['name' => 'Stockton', 'state_id' => 25],
                ['name' => 'Mendon', 'state_id' => 25],
                ['name' => 'Rothville', 'state_id' => 25],
                ['name' => 'Sumner', 'state_id' => 25],
                ['name' => 'Brunswick', 'state_id' => 25],
                ['name' => 'Dalton', 'state_id' => 25],
                ['name' => 'Keytesville', 'state_id' => 25],
                ['name' => 'Salisbury', 'state_id' => 25],
                ['name' => 'Triplett', 'state_id' => 25],
                ['name' => 'Billings', 'state_id' => 25],
                ['name' => 'Bruner', 'state_id' => 25],
                ['name' => 'Chadwick', 'state_id' => 25],
                ['name' => 'Chestnutridge', 'state_id' => 25],
                ['name' => 'Clever', 'state_id' => 25],
                ['name' => 'Garrison', 'state_id' => 25],
                ['name' => 'Highlandville', 'state_id' => 25],
                ['name' => 'Nixa', 'state_id' => 25],
                ['name' => 'Oldfield', 'state_id' => 25],
                ['name' => 'Ozark', 'state_id' => 25],
                ['name' => 'Sparta', 'state_id' => 25],
                ['name' => 'Spokane', 'state_id' => 25],
                ['name' => 'Alexandria', 'state_id' => 25],
                ['name' => 'Kahoka', 'state_id' => 25],
                ['name' => 'Luray', 'state_id' => 25],
                ['name' => 'Revere', 'state_id' => 25],
                ['name' => 'Saint Patrick', 'state_id' => 25],
                ['name' => 'Wayland', 'state_id' => 25],
                ['name' => 'Wyaconda', 'state_id' => 25],
                ['name' => 'Excelsior Springs', 'state_id' => 25],
                ['name' => 'Holt', 'state_id' => 25],
                ['name' => 'Kearney', 'state_id' => 25],
                ['name' => 'Liberty', 'state_id' => 25],
                ['name' => 'Missouri City', 'state_id' => 25],
                ['name' => 'Mosby', 'state_id' => 25],
                ['name' => 'Smithville', 'state_id' => 25],
                ['name' => 'Kansas City', 'state_id' => 25],
                ['name' => 'Cameron', 'state_id' => 25],
                ['name' => 'Gower', 'state_id' => 25],
                ['name' => 'Lathrop', 'state_id' => 25],
                ['name' => 'Plattsburg', 'state_id' => 25],
                ['name' => 'Trimble', 'state_id' => 25],
                ['name' => 'Turney', 'state_id' => 25],
                ['name' => 'Centertown', 'state_id' => 25],
                ['name' => 'Eugene', 'state_id' => 25],
                ['name' => 'Henley', 'state_id' => 25],
                ['name' => 'Lohman', 'state_id' => 25],
                ['name' => 'Russellville', 'state_id' => 25],
                ['name' => 'Saint Thomas', 'state_id' => 25],
                ['name' => 'Jefferson City', 'state_id' => 25],
                ['name' => 'Prairie Home', 'state_id' => 25],
                ['name' => 'Boonville', 'state_id' => 25],
                ['name' => 'Bunceton', 'state_id' => 25],
                ['name' => 'Pilot Grove', 'state_id' => 25],
                ['name' => 'Wooldridge', 'state_id' => 25],
                ['name' => 'Blackwater', 'state_id' => 25],
                ['name' => 'Otterville', 'state_id' => 25],
                ['name' => 'Bourbon', 'state_id' => 25],
                ['name' => 'Cherryville', 'state_id' => 25],
                ['name' => 'Cook Sta', 'state_id' => 25],
                ['name' => 'Cuba', 'state_id' => 25],
                ['name' => 'Davisville', 'state_id' => 25],
                ['name' => 'Leasburg', 'state_id' => 25],
                ['name' => 'Steelville', 'state_id' => 25],
                ['name' => 'Wesco', 'state_id' => 25],
                ['name' => 'Arcola', 'state_id' => 25],
                ['name' => 'Dadeville', 'state_id' => 25],
                ['name' => 'Everton', 'state_id' => 25],
                ['name' => 'Greenfield', 'state_id' => 25],
                ['name' => 'Lockwood', 'state_id' => 25],
                ['name' => 'South Greenfield', 'state_id' => 25],
                ['name' => 'Long Lane', 'state_id' => 25],
                ['name' => 'Buffalo', 'state_id' => 25],
                ['name' => 'Louisburg', 'state_id' => 25],
                ['name' => 'Tunas', 'state_id' => 25],
                ['name' => 'Urbana', 'state_id' => 25],
                ['name' => 'Windyville', 'state_id' => 25],
                ['name' => 'Altamont', 'state_id' => 25],
                ['name' => 'Coffey', 'state_id' => 25],
                ['name' => 'Gallatin', 'state_id' => 25],
                ['name' => 'Gilman City', 'state_id' => 25],
                ['name' => 'Jameson', 'state_id' => 25],
                ['name' => 'Jamesport', 'state_id' => 25],
                ['name' => 'Lock Springs', 'state_id' => 25],
                ['name' => 'Pattonsburg', 'state_id' => 25],
                ['name' => 'Winston', 'state_id' => 25],
                ['name' => 'Amity', 'state_id' => 25],
                ['name' => 'Clarksdale', 'state_id' => 25],
                ['name' => 'Maysville', 'state_id' => 25],
                ['name' => 'Osborn', 'state_id' => 25],
                ['name' => 'Stewartsville', 'state_id' => 25],
                ['name' => 'Union Star', 'state_id' => 25],
                ['name' => 'Weatherby', 'state_id' => 25],
                ['name' => 'Boss', 'state_id' => 25],
                ['name' => 'Jadwin', 'state_id' => 25],
                ['name' => 'Lake Spring', 'state_id' => 25],
                ['name' => 'Lenox', 'state_id' => 25],
                ['name' => 'Salem', 'state_id' => 25],
                ['name' => 'Ava', 'state_id' => 25],
                ['name' => 'Drury', 'state_id' => 25],
                ['name' => 'Squires', 'state_id' => 25],
                ['name' => 'Vanzant', 'state_id' => 25],
                ['name' => 'Arbyrd', 'state_id' => 25],
                ['name' => 'Cardwell', 'state_id' => 25],
                ['name' => 'Clarkton', 'state_id' => 25],
                ['name' => 'Gibson', 'state_id' => 25],
                ['name' => 'Holcomb', 'state_id' => 25],
                ['name' => 'Hornersville', 'state_id' => 25],
                ['name' => 'Kennett', 'state_id' => 25],
                ['name' => 'Malden', 'state_id' => 25],
                ['name' => 'Rives', 'state_id' => 25],
                ['name' => 'Senath', 'state_id' => 25],
                ['name' => 'Whiteoak', 'state_id' => 25],
                ['name' => 'Campbell', 'state_id' => 25],
                ['name' => 'Beaufort', 'state_id' => 25],
                ['name' => 'Berger', 'state_id' => 25],
                ['name' => 'Catawissa', 'state_id' => 25],
                ['name' => 'Gerald', 'state_id' => 25],
                ['name' => 'Gray Summit', 'state_id' => 25],
                ['name' => 'Labadie', 'state_id' => 25],
                ['name' => 'Leslie', 'state_id' => 25],
                ['name' => 'Lonedell', 'state_id' => 25],
                ['name' => 'Luebbering', 'state_id' => 25],
                ['name' => 'New Haven', 'state_id' => 25],
                ['name' => 'Pacific', 'state_id' => 25],
                ['name' => 'Robertsville', 'state_id' => 25],
                ['name' => 'Saint Albans', 'state_id' => 25],
                ['name' => 'Saint Clair', 'state_id' => 25],
                ['name' => 'Stanton', 'state_id' => 25],
                ['name' => 'Sullivan', 'state_id' => 25],
                ['name' => 'Union', 'state_id' => 25],
                ['name' => 'Villa Ridge', 'state_id' => 25],
                ['name' => 'Washington', 'state_id' => 25],
                ['name' => 'Rosebud', 'state_id' => 25],
                ['name' => 'Bland', 'state_id' => 25],
                ['name' => 'Gasconade', 'state_id' => 25],
                ['name' => 'Hermann', 'state_id' => 25],
                ['name' => 'Morrison', 'state_id' => 25],
                ['name' => 'Mount Sterling', 'state_id' => 25],
                ['name' => 'Owensville', 'state_id' => 25],
                ['name' => 'Albany', 'state_id' => 25],
                ['name' => 'Darlington', 'state_id' => 25],
                ['name' => 'Gentry', 'state_id' => 25],
                ['name' => 'King City', 'state_id' => 25],
                ['name' => 'Stanberry', 'state_id' => 25],
                ['name' => 'Mc Fall', 'state_id' => 25],
                ['name' => 'Ash Grove', 'state_id' => 25],
                ['name' => 'Bois D Arc', 'state_id' => 25],
                ['name' => 'Brookline', 'state_id' => 25],
                ['name' => 'Fair Grove', 'state_id' => 25],
                ['name' => 'Republic', 'state_id' => 25],
                ['name' => 'Strafford', 'state_id' => 25],
                ['name' => 'Turners', 'state_id' => 25],
                ['name' => 'Walnut Grove', 'state_id' => 25],
                ['name' => 'Willard', 'state_id' => 25],
                ['name' => 'Springfield', 'state_id' => 25],
                ['name' => 'Galt', 'state_id' => 25],
                ['name' => 'Laredo', 'state_id' => 25],
                ['name' => 'Spickard', 'state_id' => 25],
                ['name' => 'Trenton', 'state_id' => 25],
                ['name' => 'Bethany', 'state_id' => 25],
                ['name' => 'Blythedale', 'state_id' => 25],
                ['name' => 'Eagleville', 'state_id' => 25],
                ['name' => 'Hatfield', 'state_id' => 25],
                ['name' => 'Martinsville', 'state_id' => 25],
                ['name' => 'New Hampton', 'state_id' => 25],
                ['name' => 'Ridgeway', 'state_id' => 25],
                ['name' => 'Cainsville', 'state_id' => 25],
                ['name' => 'Blairstown', 'state_id' => 25],
                ['name' => 'Clinton', 'state_id' => 25],
                ['name' => 'Deepwater', 'state_id' => 25],
                ['name' => 'Montrose', 'state_id' => 25],
                ['name' => 'Urich', 'state_id' => 25],
                ['name' => 'Calhoun', 'state_id' => 25],
                ['name' => 'Windsor', 'state_id' => 25],
                ['name' => 'Cross Timbers', 'state_id' => 25],
                ['name' => 'Hermitage', 'state_id' => 25],
                ['name' => 'Pittsburg', 'state_id' => 25],
                ['name' => 'Preston', 'state_id' => 25],
                ['name' => 'Quincy', 'state_id' => 25],
                ['name' => 'Weaubleau', 'state_id' => 25],
                ['name' => 'Wheatland', 'state_id' => 25],
                ['name' => 'Craig', 'state_id' => 25],
                ['name' => 'Forest City', 'state_id' => 25],
                ['name' => 'Maitland', 'state_id' => 25],
                ['name' => 'Mound City', 'state_id' => 25],
                ['name' => 'Oregon', 'state_id' => 25],
                ['name' => 'Armstrong', 'state_id' => 25],
                ['name' => 'Fayette', 'state_id' => 25],
                ['name' => 'Franklin', 'state_id' => 25],
                ['name' => 'Glasgow', 'state_id' => 25],
                ['name' => 'New Franklin', 'state_id' => 25],
                ['name' => 'Mountain View', 'state_id' => 25],
                ['name' => 'Caulfield', 'state_id' => 25],
                ['name' => 'Brandsville', 'state_id' => 25],
                ['name' => 'West Plains', 'state_id' => 25],
                ['name' => 'Moody', 'state_id' => 25],
                ['name' => 'Peace Valley', 'state_id' => 25],
                ['name' => 'Pomona', 'state_id' => 25],
                ['name' => 'Pottersville', 'state_id' => 25],
                ['name' => 'Willow Springs', 'state_id' => 25],
                ['name' => 'Annapolis', 'state_id' => 25],
                ['name' => 'Arcadia', 'state_id' => 25],
                ['name' => 'Belleview', 'state_id' => 25],
                ['name' => 'Des Arc', 'state_id' => 25],
                ['name' => 'Ironton', 'state_id' => 25],
                ['name' => 'Middle Brook', 'state_id' => 25],
                ['name' => 'Pilot Knob', 'state_id' => 25],
                ['name' => 'Vulcan', 'state_id' => 25],
                ['name' => 'Bixby', 'state_id' => 25],
                ['name' => 'Viburnum', 'state_id' => 25],
                ['name' => 'Lees Summit', 'state_id' => 25],
                ['name' => 'Blue Springs', 'state_id' => 25],
                ['name' => 'Buckner', 'state_id' => 25],
                ['name' => 'Grain Valley', 'state_id' => 25],
                ['name' => 'Grandview', 'state_id' => 25],
                ['name' => 'Greenwood', 'state_id' => 25],
                ['name' => 'Independence', 'state_id' => 25],
                ['name' => 'Levasy', 'state_id' => 25],
                ['name' => 'Lone Jack', 'state_id' => 25],
                ['name' => 'Oak Grove', 'state_id' => 25],
                ['name' => 'Sibley', 'state_id' => 25],
                ['name' => 'Jasper', 'state_id' => 25],
                ['name' => 'Joplin', 'state_id' => 25],
                ['name' => 'Alba', 'state_id' => 25],
                ['name' => 'Asbury', 'state_id' => 25],
                ['name' => 'Avilla', 'state_id' => 25],
                ['name' => 'Carl Junction', 'state_id' => 25],
                ['name' => 'Carterville', 'state_id' => 25],
                ['name' => 'Carthage', 'state_id' => 25],
                ['name' => 'Duenweg', 'state_id' => 25],
                ['name' => 'La Russell', 'state_id' => 25],
                ['name' => 'Neck City', 'state_id' => 25],
                ['name' => 'Oronogo', 'state_id' => 25],
                ['name' => 'Purcell', 'state_id' => 25],
                ['name' => 'Reeds', 'state_id' => 25],
                ['name' => 'Sarcoxie', 'state_id' => 25],
                ['name' => 'Webb City', 'state_id' => 25],
                ['name' => 'Arnold', 'state_id' => 25],
                ['name' => 'Barnhart', 'state_id' => 25],
                ['name' => 'Cedar Hill', 'state_id' => 25],
                ['name' => 'Crystal City', 'state_id' => 25],
                ['name' => 'De Soto', 'state_id' => 25],
                ['name' => 'Dittmer', 'state_id' => 25],
                ['name' => 'Festus', 'state_id' => 25],
                ['name' => 'Fletcher', 'state_id' => 25],
                ['name' => 'Grubville', 'state_id' => 25],
                ['name' => 'Hematite', 'state_id' => 25],
                ['name' => 'Herculaneum', 'state_id' => 25],
                ['name' => 'High Ridge', 'state_id' => 25],
                ['name' => 'Hillsboro', 'state_id' => 25],
                ['name' => 'House Springs', 'state_id' => 25],
                ['name' => 'Imperial', 'state_id' => 25],
                ['name' => 'Kimmswick', 'state_id' => 25],
                ['name' => 'Liguori', 'state_id' => 25],
                ['name' => 'Mapaville', 'state_id' => 25],
                ['name' => 'Morse Mill', 'state_id' => 25],
                ['name' => 'Pevely', 'state_id' => 25],
                ['name' => 'Centerview', 'state_id' => 25],
                ['name' => 'Holden', 'state_id' => 25],
                ['name' => 'Kingsville', 'state_id' => 25],
                ['name' => 'Warrensburg', 'state_id' => 25],
                ['name' => 'Chilhowee', 'state_id' => 25],
                ['name' => 'Leeton', 'state_id' => 25],
                ['name' => 'Whiteman Air Force Base', 'state_id' => 25],
                ['name' => 'Knob Noster', 'state_id' => 25],
                ['name' => 'Knox City', 'state_id' => 25],
                ['name' => 'Newark', 'state_id' => 25],
                ['name' => 'Novelty', 'state_id' => 25],
                ['name' => 'Plevna', 'state_id' => 25],
                ['name' => 'Baring', 'state_id' => 25],
                ['name' => 'Edina', 'state_id' => 25],
                ['name' => 'Hurdland', 'state_id' => 25],
                ['name' => 'Eldridge', 'state_id' => 25],
                ['name' => 'Falcon', 'state_id' => 25],
                ['name' => 'Lebanon', 'state_id' => 25],
                ['name' => 'Lynchburg', 'state_id' => 25],
                ['name' => 'Conway', 'state_id' => 25],
                ['name' => 'Phillipsburg', 'state_id' => 25],
                ['name' => 'Alma', 'state_id' => 25],
                ['name' => 'Bates City', 'state_id' => 25],
                ['name' => 'Concordia', 'state_id' => 25],
                ['name' => 'Corder', 'state_id' => 25],
                ['name' => 'Dover', 'state_id' => 25],
                ['name' => 'Higginsville', 'state_id' => 25],
                ['name' => 'Lexington', 'state_id' => 25],
                ['name' => 'Mayview', 'state_id' => 25],
                ['name' => 'Napoleon', 'state_id' => 25],
                ['name' => 'Odessa', 'state_id' => 25],
                ['name' => 'Waverly', 'state_id' => 25],
                ['name' => 'Wellington', 'state_id' => 25],
                ['name' => 'Emma', 'state_id' => 25],
                ['name' => 'Aurora', 'state_id' => 25],
                ['name' => 'Freistatt', 'state_id' => 25],
                ['name' => 'Halltown', 'state_id' => 25],
                ['name' => 'Marionville', 'state_id' => 25],
                ['name' => 'Miller', 'state_id' => 25],
                ['name' => 'Mount Vernon', 'state_id' => 25],
                ['name' => 'Pierce City', 'state_id' => 25],
                ['name' => 'Stotts City', 'state_id' => 25],
                ['name' => 'Verona', 'state_id' => 25],
                ['name' => 'Canton', 'state_id' => 25],
                ['name' => 'Durham', 'state_id' => 25],
                ['name' => 'Ewing', 'state_id' => 25],
                ['name' => 'La Belle', 'state_id' => 25],
                ['name' => 'La Grange', 'state_id' => 25],
                ['name' => 'Lewistown', 'state_id' => 25],
                ['name' => 'Monticello', 'state_id' => 25],
                ['name' => 'Williamstown', 'state_id' => 25],
                ['name' => 'Elsberry', 'state_id' => 25],
                ['name' => 'Foley', 'state_id' => 25],
                ['name' => 'Hawk Point', 'state_id' => 25],
                ['name' => 'Moscow Mills', 'state_id' => 25],
                ['name' => 'Old Monroe', 'state_id' => 25],
                ['name' => 'Olney', 'state_id' => 25],
                ['name' => 'Silex', 'state_id' => 25],
                ['name' => 'Troy', 'state_id' => 25],
                ['name' => 'Truxton', 'state_id' => 25],
                ['name' => 'Whiteside', 'state_id' => 25],
                ['name' => 'Winfield', 'state_id' => 25],
                ['name' => 'New Boston', 'state_id' => 25],
                ['name' => 'Brookfield', 'state_id' => 25],
                ['name' => 'Browning', 'state_id' => 25],
                ['name' => 'Bucklin', 'state_id' => 25],
                ['name' => 'Laclede', 'state_id' => 25],
                ['name' => 'Linneus', 'state_id' => 25],
                ['name' => 'Marceline', 'state_id' => 25],
                ['name' => 'Meadville', 'state_id' => 25],
                ['name' => 'Purdin', 'state_id' => 25],
                ['name' => 'Chillicothe', 'state_id' => 25],
                ['name' => 'Chula', 'state_id' => 25],
                ['name' => 'Dawn', 'state_id' => 25],
                ['name' => 'Ludlow', 'state_id' => 25],
                ['name' => 'Mooresville', 'state_id' => 25],
                ['name' => 'Utica', 'state_id' => 25],
                ['name' => 'Wheeling', 'state_id' => 25],
                ['name' => 'Anderson', 'state_id' => 25],
                ['name' => 'Goodman', 'state_id' => 25],
                ['name' => 'Lanagan', 'state_id' => 25],
                ['name' => 'Noel', 'state_id' => 25],
                ['name' => 'Pineville', 'state_id' => 25],
                ['name' => 'Rocky Comfort', 'state_id' => 25],
                ['name' => 'South West City', 'state_id' => 25],
                ['name' => 'Tiff City', 'state_id' => 25],
                ['name' => 'Powell', 'state_id' => 25],
                ['name' => 'Anabel', 'state_id' => 25],
                ['name' => 'Atlanta', 'state_id' => 25],
                ['name' => 'Bevier', 'state_id' => 25],
                ['name' => 'Callao', 'state_id' => 25],
                ['name' => 'Elmer', 'state_id' => 25],
                ['name' => 'Ethel', 'state_id' => 25],
                ['name' => 'La Plata', 'state_id' => 25],
                ['name' => 'Macon', 'state_id' => 25],
                ['name' => 'New Cambria', 'state_id' => 25],
                ['name' => 'Excello', 'state_id' => 25],
                ['name' => 'Fredericktown', 'state_id' => 25],
                ['name' => 'Marquand', 'state_id' => 25],
                ['name' => 'Belle', 'state_id' => 25],
                ['name' => 'Brinktown', 'state_id' => 25],
                ['name' => 'Vichy', 'state_id' => 25],
                ['name' => 'Vienna', 'state_id' => 25],
                ['name' => 'Hannibal', 'state_id' => 25],
                ['name' => 'Maywood', 'state_id' => 25],
                ['name' => 'Palmyra', 'state_id' => 25],
                ['name' => 'Philadelphia', 'state_id' => 25],
                ['name' => 'Taylor', 'state_id' => 25],
                ['name' => 'Mercer', 'state_id' => 25],
                ['name' => 'Princeton', 'state_id' => 25],
                ['name' => 'Brumley', 'state_id' => 25],
                ['name' => 'Eldon', 'state_id' => 25],
                ['name' => 'Kaiser', 'state_id' => 25],
                ['name' => 'Olean', 'state_id' => 25],
                ['name' => 'Saint Elizabeth', 'state_id' => 25],
                ['name' => 'Tuscumbia', 'state_id' => 25],
                ['name' => 'Ulman', 'state_id' => 25],
                ['name' => 'Iberia', 'state_id' => 25],
                ['name' => 'Anniston', 'state_id' => 25],
                ['name' => 'Bertrand', 'state_id' => 25],
                ['name' => 'Charleston', 'state_id' => 25],
                ['name' => 'East Prairie', 'state_id' => 25],
                ['name' => 'Wolf Island', 'state_id' => 25],
                ['name' => 'Wyatt', 'state_id' => 25],
                ['name' => 'California', 'state_id' => 25],
                ['name' => 'Clarksburg', 'state_id' => 25],
                ['name' => 'Fortuna', 'state_id' => 25],
                ['name' => 'High Point', 'state_id' => 25],
                ['name' => 'Jamestown', 'state_id' => 25],
                ['name' => 'Latham', 'state_id' => 25],
                ['name' => 'Mc Girk', 'state_id' => 25],
                ['name' => 'Tipton', 'state_id' => 25],
                ['name' => 'Monroe City', 'state_id' => 25],
                ['name' => 'Holliday', 'state_id' => 25],
                ['name' => 'Madison', 'state_id' => 25],
                ['name' => 'Paris', 'state_id' => 25],
                ['name' => 'Santa Fe', 'state_id' => 25],
                ['name' => 'Stoutsville', 'state_id' => 25],
                ['name' => 'Bellflower', 'state_id' => 25],
                ['name' => 'High Hill', 'state_id' => 25],
                ['name' => 'Jonesburg', 'state_id' => 25],
                ['name' => 'Middletown', 'state_id' => 25],
                ['name' => 'Montgomery City', 'state_id' => 25],
                ['name' => 'New Florence', 'state_id' => 25],
                ['name' => 'Wellsville', 'state_id' => 25],
                ['name' => 'Rhineland', 'state_id' => 25],
                ['name' => 'Barnett', 'state_id' => 25],
                ['name' => 'Gravois Mills', 'state_id' => 25],
                ['name' => 'Laurie', 'state_id' => 25],
                ['name' => 'Rocky Mount', 'state_id' => 25],
                ['name' => 'Stover', 'state_id' => 25],
                ['name' => 'Versailles', 'state_id' => 25],
                ['name' => 'Florence', 'state_id' => 25],
                ['name' => 'Syracuse', 'state_id' => 25],
                ['name' => 'Canalou', 'state_id' => 25],
                ['name' => 'Catron', 'state_id' => 25],
                ['name' => 'Gideon', 'state_id' => 25],
                ['name' => 'Kewanee', 'state_id' => 25],
                ['name' => 'Lilbourn', 'state_id' => 25],
                ['name' => 'Marston', 'state_id' => 25],
                ['name' => 'Matthews', 'state_id' => 25],
                ['name' => 'Morehouse', 'state_id' => 25],
                ['name' => 'New Madrid', 'state_id' => 25],
                ['name' => 'Parma', 'state_id' => 25],
                ['name' => 'Portageville', 'state_id' => 25],
                ['name' => 'Risco', 'state_id' => 25],
                ['name' => 'Tallapoosa', 'state_id' => 25],
                ['name' => 'Diamond', 'state_id' => 25],
                ['name' => 'Fairview', 'state_id' => 25],
                ['name' => 'Granby', 'state_id' => 25],
                ['name' => 'Neosho', 'state_id' => 25],
                ['name' => 'Newtonia', 'state_id' => 25],
                ['name' => 'Racine', 'state_id' => 25],
                ['name' => 'Saginaw', 'state_id' => 25],
                ['name' => 'Seneca', 'state_id' => 25],
                ['name' => 'Stark City', 'state_id' => 25],
                ['name' => 'Stella', 'state_id' => 25],
                ['name' => 'Wentworth', 'state_id' => 25],
                ['name' => 'Barnard', 'state_id' => 25],
                ['name' => 'Burlington Junction', 'state_id' => 25],
                ['name' => 'Clearmont', 'state_id' => 25],
                ['name' => 'Clyde', 'state_id' => 25],
                ['name' => 'Conception', 'state_id' => 25],
                ['name' => 'Conception Junction', 'state_id' => 25],
                ['name' => 'Elmo', 'state_id' => 25],
                ['name' => 'Graham', 'state_id' => 25],
                ['name' => 'Guilford', 'state_id' => 25],
                ['name' => 'Hopkins', 'state_id' => 25],
                ['name' => 'Maryville', 'state_id' => 25],
                ['name' => 'Parnell', 'state_id' => 25],
                ['name' => 'Pickering', 'state_id' => 25],
                ['name' => 'Ravenwood', 'state_id' => 25],
                ['name' => 'Skidmore', 'state_id' => 25],
                ['name' => 'Alton', 'state_id' => 25],
                ['name' => 'Couch', 'state_id' => 25],
                ['name' => 'Koshkonong', 'state_id' => 25],
                ['name' => 'Myrtle', 'state_id' => 25],
                ['name' => 'Thayer', 'state_id' => 25],
                ['name' => 'Argyle', 'state_id' => 25],
                ['name' => 'Bonnots Mill', 'state_id' => 25],
                ['name' => 'Chamois', 'state_id' => 25],
                ['name' => 'Freeburg', 'state_id' => 25],
                ['name' => 'Koeltztown', 'state_id' => 25],
                ['name' => 'Linn', 'state_id' => 25],
                ['name' => 'Loose Creek', 'state_id' => 25],
                ['name' => 'Meta', 'state_id' => 25],
                ['name' => 'Westphalia', 'state_id' => 25],
                ['name' => 'Bakersfield', 'state_id' => 25],
                ['name' => 'Brixey', 'state_id' => 25],
                ['name' => 'Dora', 'state_id' => 25],
                ['name' => 'Gainesville', 'state_id' => 25],
                ['name' => 'Hardenville', 'state_id' => 25],
                ['name' => 'Isabella', 'state_id' => 25],
                ['name' => 'Noble', 'state_id' => 25],
                ['name' => 'Pontiac', 'state_id' => 25],
                ['name' => 'Rockbridge', 'state_id' => 25],
                ['name' => 'Tecumseh', 'state_id' => 25],
                ['name' => 'Theodosia', 'state_id' => 25],
                ['name' => 'Thornfield', 'state_id' => 25],
                ['name' => 'Udall', 'state_id' => 25],
                ['name' => 'Wasola', 'state_id' => 25],
                ['name' => 'Zanoni', 'state_id' => 25],
                ['name' => 'Braggadocio', 'state_id' => 25],
                ['name' => 'Bragg City', 'state_id' => 25],
                ['name' => 'Caruthersville', 'state_id' => 25],
                ['name' => 'Cooter', 'state_id' => 25],
                ['name' => 'Deering', 'state_id' => 25],
                ['name' => 'Gobler', 'state_id' => 25],
                ['name' => 'Hayti', 'state_id' => 25],
                ['name' => 'Holland', 'state_id' => 25],
                ['name' => 'Steele', 'state_id' => 25],
                ['name' => 'Wardell', 'state_id' => 25],
                ['name' => 'Altenburg', 'state_id' => 25],
                ['name' => 'Brazeau', 'state_id' => 25],
                ['name' => 'Farrar', 'state_id' => 25],
                ['name' => 'Frohna', 'state_id' => 25],
                ['name' => 'Perryville', 'state_id' => 25],
                ['name' => 'Mc Bride', 'state_id' => 25],
                ['name' => 'Uniontown', 'state_id' => 25],
                ['name' => 'Sedalia', 'state_id' => 25],
                ['name' => 'Green Ridge', 'state_id' => 25],
                ['name' => 'Houstonia', 'state_id' => 25],
                ['name' => 'Hughesville', 'state_id' => 25],
                ['name' => 'La Monte', 'state_id' => 25],
                ['name' => 'Mora', 'state_id' => 25],
                ['name' => 'Smithton', 'state_id' => 25],
                ['name' => 'Rolla', 'state_id' => 25],
                ['name' => 'Beulah', 'state_id' => 25],
                ['name' => 'Duke', 'state_id' => 25],
                ['name' => 'Edgar Springs', 'state_id' => 25],
                ['name' => 'Jerome', 'state_id' => 25],
                ['name' => 'Newburg', 'state_id' => 25],
                ['name' => 'Saint James', 'state_id' => 25],
                ['name' => 'Annada', 'state_id' => 25],
                ['name' => 'Bowling Green', 'state_id' => 25],
                ['name' => 'Clarksville', 'state_id' => 25],
                ['name' => 'Curryville', 'state_id' => 25],
                ['name' => 'Eolia', 'state_id' => 25],
                ['name' => 'Louisiana', 'state_id' => 25],
                ['name' => 'Ashburn', 'state_id' => 25],
                ['name' => 'Frankford', 'state_id' => 25],
                ['name' => 'Camden Point', 'state_id' => 25],
                ['name' => 'Farley', 'state_id' => 25],
                ['name' => 'Platte City', 'state_id' => 25],
                ['name' => 'Waldron', 'state_id' => 25],
                ['name' => 'Weston', 'state_id' => 25],
                ['name' => 'Riverside', 'state_id' => 25],
                ['name' => 'Dearborn', 'state_id' => 25],
                ['name' => 'Edgerton', 'state_id' => 25],
                ['name' => 'Aldrich', 'state_id' => 25],
                ['name' => 'Bolivar', 'state_id' => 25],
                ['name' => 'Brighton', 'state_id' => 25],
                ['name' => 'Dunnegan', 'state_id' => 25],
                ['name' => 'Eudora', 'state_id' => 25],
                ['name' => 'Fair Play', 'state_id' => 25],
                ['name' => 'Flemington', 'state_id' => 25],
                ['name' => 'Half Way', 'state_id' => 25],
                ['name' => 'Humansville', 'state_id' => 25],
                ['name' => 'Morrisville', 'state_id' => 25],
                ['name' => 'Pleasant Hope', 'state_id' => 25],
                ['name' => 'Polk', 'state_id' => 25],
                ['name' => 'Crocker', 'state_id' => 25],
                ['name' => 'Devils Elbow', 'state_id' => 25],
                ['name' => 'Dixon', 'state_id' => 25],
                ['name' => 'Fort Leonard Wood', 'state_id' => 25],
                ['name' => 'Laquey', 'state_id' => 25],
                ['name' => 'Richland', 'state_id' => 25],
                ['name' => 'Waynesville', 'state_id' => 25],
                ['name' => 'Saint Robert', 'state_id' => 25],
                ['name' => 'Livonia', 'state_id' => 25],
                ['name' => 'Unionville', 'state_id' => 25],
                ['name' => 'Worthington', 'state_id' => 25],
                ['name' => 'Lucerne', 'state_id' => 25],
                ['name' => 'Powersville', 'state_id' => 25],
                ['name' => 'Center', 'state_id' => 25],
                ['name' => 'New London', 'state_id' => 25],
                ['name' => 'Perry', 'state_id' => 25],
                ['name' => 'Saverton', 'state_id' => 25],
                ['name' => 'Cairo', 'state_id' => 25],
                ['name' => 'Clark', 'state_id' => 25],
                ['name' => 'Clifton Hill', 'state_id' => 25],
                ['name' => 'Higbee', 'state_id' => 25],
                ['name' => 'Huntsville', 'state_id' => 25],
                ['name' => 'Jacksonville', 'state_id' => 25],
                ['name' => 'Moberly', 'state_id' => 25],
                ['name' => 'Renick', 'state_id' => 25],
                ['name' => 'Camden', 'state_id' => 25],
                ['name' => 'Hardin', 'state_id' => 25],
                ['name' => 'Henrietta', 'state_id' => 25],
                ['name' => 'Lawson', 'state_id' => 25],
                ['name' => 'Orrick', 'state_id' => 25],
                ['name' => 'Rayville', 'state_id' => 25],
                ['name' => 'Richmond', 'state_id' => 25],
                ['name' => 'Black', 'state_id' => 25],
                ['name' => 'Bunker', 'state_id' => 25],
                ['name' => 'Centerville', 'state_id' => 25],
                ['name' => 'Ellington', 'state_id' => 25],
                ['name' => 'Lesterville', 'state_id' => 25],
                ['name' => 'Redford', 'state_id' => 25],
                ['name' => 'Reynolds', 'state_id' => 25],
                ['name' => 'Briar', 'state_id' => 25],
                ['name' => 'Doniphan', 'state_id' => 25],
                ['name' => 'Fairdealing', 'state_id' => 25],
                ['name' => 'Gatewood', 'state_id' => 25],
                ['name' => 'Naylor', 'state_id' => 25],
                ['name' => 'Oxly', 'state_id' => 25],
                ['name' => 'Saint Charles', 'state_id' => 25],
                ['name' => 'Augusta', 'state_id' => 25],
                ['name' => 'Cottleville', 'state_id' => 25],
                ['name' => 'Defiance', 'state_id' => 25],
                ['name' => 'Flinthill', 'state_id' => 25],
                ['name' => 'Foristell', 'state_id' => 25],
                ['name' => 'New Melle', 'state_id' => 25],
                ['name' => 'O Fallon', 'state_id' => 25],
                ['name' => 'Lake Saint Louis', 'state_id' => 25],
                ['name' => 'Portage Des Sioux', 'state_id' => 25],
                ['name' => 'Saint Peters', 'state_id' => 25],
                ['name' => 'Wentzville', 'state_id' => 25],
                ['name' => 'West Alton', 'state_id' => 25],
                ['name' => 'Appleton City', 'state_id' => 25],
                ['name' => 'Collins', 'state_id' => 25],
                ['name' => 'Lowry City', 'state_id' => 25],
                ['name' => 'Osceola', 'state_id' => 25],
                ['name' => 'Roscoe', 'state_id' => 25],
                ['name' => 'Bloomsdale', 'state_id' => 25],
                ['name' => 'Sainte Genevieve', 'state_id' => 25],
                ['name' => 'Saint Mary', 'state_id' => 25],
                ['name' => 'French Village', 'state_id' => 25],
                ['name' => 'Valles Mines', 'state_id' => 25],
                ['name' => 'Park Hills', 'state_id' => 25],
                ['name' => 'Bismarck', 'state_id' => 25],
                ['name' => 'Blackwell', 'state_id' => 25],
                ['name' => 'Bonne Terre', 'state_id' => 25],
                ['name' => 'Doe Run', 'state_id' => 25],
                ['name' => 'Farmington', 'state_id' => 25],
                ['name' => 'Knob Lick', 'state_id' => 25],
                ['name' => 'Leadwood', 'state_id' => 25],
                ['name' => 'Chesterfield', 'state_id' => 25],
                ['name' => 'Ballwin', 'state_id' => 25],
                ['name' => 'Eureka', 'state_id' => 25],
                ['name' => 'Fenton', 'state_id' => 25],
                ['name' => 'Florissant', 'state_id' => 25],
                ['name' => 'Glencoe', 'state_id' => 25],
                ['name' => 'Grover', 'state_id' => 25],
                ['name' => 'Hazelwood', 'state_id' => 25],
                ['name' => 'Maryland Heights', 'state_id' => 25],
                ['name' => 'Bridgeton', 'state_id' => 25],
                ['name' => 'Earth City', 'state_id' => 25],
                ['name' => 'Saint Ann', 'state_id' => 25],
                ['name' => 'Valley Park', 'state_id' => 25],
                ['name' => 'Saint Louis', 'state_id' => 25],
                ['name' => 'Arrow Rock', 'state_id' => 25],
                ['name' => 'Blackburn', 'state_id' => 25],
                ['name' => 'Gilliam', 'state_id' => 25],
                ['name' => 'Malta Bend', 'state_id' => 25],
                ['name' => 'Marshall', 'state_id' => 25],
                ['name' => 'Miami', 'state_id' => 25],
                ['name' => 'Nelson', 'state_id' => 25],
                ['name' => 'Slater', 'state_id' => 25],
                ['name' => 'Sweet Springs', 'state_id' => 25],
                ['name' => 'Coatsville', 'state_id' => 25],
                ['name' => 'Downing', 'state_id' => 25],
                ['name' => 'Glenwood', 'state_id' => 25],
                ['name' => 'Lancaster', 'state_id' => 25],
                ['name' => 'Queen City', 'state_id' => 25],
                ['name' => 'Arbela', 'state_id' => 25],
                ['name' => 'Granger', 'state_id' => 25],
                ['name' => 'Gorin', 'state_id' => 25],
                ['name' => 'Memphis', 'state_id' => 25],
                ['name' => 'Rutledge', 'state_id' => 25],
                ['name' => 'Benton', 'state_id' => 25],
                ['name' => 'Chaffee', 'state_id' => 25],
                ['name' => 'Commerce', 'state_id' => 25],
                ['name' => 'Kelso', 'state_id' => 25],
                ['name' => 'Morley', 'state_id' => 25],
                ['name' => 'Oran', 'state_id' => 25],
                ['name' => 'Perkins', 'state_id' => 25],
                ['name' => 'Scott City', 'state_id' => 25],
                ['name' => 'Vanduser', 'state_id' => 25],
                ['name' => 'Sikeston', 'state_id' => 25],
                ['name' => 'Blodgett', 'state_id' => 25],
                ['name' => 'Birch Tree', 'state_id' => 25],
                ['name' => 'Eminence', 'state_id' => 25],
                ['name' => 'Montier', 'state_id' => 25],
                ['name' => 'Winona', 'state_id' => 25],
                ['name' => 'Bethel', 'state_id' => 25],
                ['name' => 'Clarence', 'state_id' => 25],
                ['name' => 'Emden', 'state_id' => 25],
                ['name' => 'Hunnewell', 'state_id' => 25],
                ['name' => 'Lentner', 'state_id' => 25],
                ['name' => 'Leonard', 'state_id' => 25],
                ['name' => 'Shelbina', 'state_id' => 25],
                ['name' => 'Shelbyville', 'state_id' => 25],
                ['name' => 'Advance', 'state_id' => 25],
                ['name' => 'Bell City', 'state_id' => 25],
                ['name' => 'Brownwood', 'state_id' => 25],
                ['name' => 'Bernie', 'state_id' => 25],
                ['name' => 'Bloomfield', 'state_id' => 25],
                ['name' => 'Dexter', 'state_id' => 25],
                ['name' => 'Essex', 'state_id' => 25],
                ['name' => 'Grayridge', 'state_id' => 25],
                ['name' => 'Dudley', 'state_id' => 25],
                ['name' => 'Puxico', 'state_id' => 25],
                ['name' => 'Blue Eye', 'state_id' => 25],
                ['name' => 'Cape Fair', 'state_id' => 25],
                ['name' => 'Crane', 'state_id' => 25],
                ['name' => 'Galena', 'state_id' => 25],
                ['name' => 'Hurley', 'state_id' => 25],
                ['name' => 'Lampe', 'state_id' => 25],
                ['name' => 'Kimberling City', 'state_id' => 25],
                ['name' => 'Ponce De Leon', 'state_id' => 25],
                ['name' => 'Reeds Spring', 'state_id' => 25],
                ['name' => 'Green Castle', 'state_id' => 25],
                ['name' => 'Green City', 'state_id' => 25],
                ['name' => 'Milan', 'state_id' => 25],
                ['name' => 'Pollock', 'state_id' => 25],
                ['name' => 'Winigan', 'state_id' => 25],
                ['name' => 'Harris', 'state_id' => 25],
                ['name' => 'Humphreys', 'state_id' => 25],
                ['name' => 'Newtown', 'state_id' => 25],
                ['name' => 'Bradleyville', 'state_id' => 25],
                ['name' => 'Branson', 'state_id' => 25],
                ['name' => 'Cedarcreek', 'state_id' => 25],
                ['name' => 'Forsyth', 'state_id' => 25],
                ['name' => 'Hollister', 'state_id' => 25],
                ['name' => 'Kirbyville', 'state_id' => 25],
                ['name' => 'Kissee Mills', 'state_id' => 25],
                ['name' => 'Point Lookout', 'state_id' => 25],
                ['name' => 'Powersite', 'state_id' => 25],
                ['name' => 'Protem', 'state_id' => 25],
                ['name' => 'Ridgedale', 'state_id' => 25],
                ['name' => 'Rockaway Beach', 'state_id' => 25],
                ['name' => 'Rueter', 'state_id' => 25],
                ['name' => 'Taneyville', 'state_id' => 25],
                ['name' => 'Walnut Shade', 'state_id' => 25],
                ['name' => 'Bucyrus', 'state_id' => 25],
                ['name' => 'Elk Creek', 'state_id' => 25],
                ['name' => 'Eunice', 'state_id' => 25],
                ['name' => 'Hartshorn', 'state_id' => 25],
                ['name' => 'Houston', 'state_id' => 25],
                ['name' => 'Huggins', 'state_id' => 25],
                ['name' => 'Licking', 'state_id' => 25],
                ['name' => 'Plato', 'state_id' => 25],
                ['name' => 'Raymondville', 'state_id' => 25],
                ['name' => 'Roby', 'state_id' => 25],
                ['name' => 'Solo', 'state_id' => 25],
                ['name' => 'Success', 'state_id' => 25],
                ['name' => 'Summersville', 'state_id' => 25],
                ['name' => 'Yukon', 'state_id' => 25],
                ['name' => 'Cabool', 'state_id' => 25],
                ['name' => 'Bronaugh', 'state_id' => 25],
                ['name' => 'Deerfield', 'state_id' => 25],
                ['name' => 'Harwood', 'state_id' => 25],
                ['name' => 'Metz', 'state_id' => 25],
                ['name' => 'Milo', 'state_id' => 25],
                ['name' => 'Moundville', 'state_id' => 25],
                ['name' => 'Nevada', 'state_id' => 25],
                ['name' => 'Richards', 'state_id' => 25],
                ['name' => 'Schell City', 'state_id' => 25],
                ['name' => 'Sheldon', 'state_id' => 25],
                ['name' => 'Walker', 'state_id' => 25],
                ['name' => 'Dutzow', 'state_id' => 25],
                ['name' => 'Marthasville', 'state_id' => 25],
                ['name' => 'Treloar', 'state_id' => 25],
                ['name' => 'Truesdale', 'state_id' => 25],
                ['name' => 'Warrenton', 'state_id' => 25],
                ['name' => 'Wright City', 'state_id' => 25],
                ['name' => 'Richwoods', 'state_id' => 25],
                ['name' => 'Belgrade', 'state_id' => 25],
                ['name' => 'Cadet', 'state_id' => 25],
                ['name' => 'Caledonia', 'state_id' => 25],
                ['name' => 'Irondale', 'state_id' => 25],
                ['name' => 'Mineral Point', 'state_id' => 25],
                ['name' => 'Potosi', 'state_id' => 25],
                ['name' => 'Tiff', 'state_id' => 25],
                ['name' => 'Cascade', 'state_id' => 25],
                ['name' => 'Mc Gee', 'state_id' => 25],
                ['name' => 'Clubb', 'state_id' => 25],
                ['name' => 'Greenville', 'state_id' => 25],
                ['name' => 'Lodi', 'state_id' => 25],
                ['name' => 'Lowndes', 'state_id' => 25],
                ['name' => 'Mill Spring', 'state_id' => 25],
                ['name' => 'Patterson', 'state_id' => 25],
                ['name' => 'Piedmont', 'state_id' => 25],
                ['name' => 'Silva', 'state_id' => 25],
                ['name' => 'Wappapello', 'state_id' => 25],
                ['name' => 'Williamsville', 'state_id' => 25],
                ['name' => 'Diggins', 'state_id' => 25],
                ['name' => 'Elkland', 'state_id' => 25],
                ['name' => 'Fordland', 'state_id' => 25],
                ['name' => 'Marshfield', 'state_id' => 25],
                ['name' => 'Niangua', 'state_id' => 25],
                ['name' => 'Rogersville', 'state_id' => 25],
                ['name' => 'Seymour', 'state_id' => 25],
                ['name' => 'Allendale', 'state_id' => 25],
                ['name' => 'Denver', 'state_id' => 25],
                ['name' => 'Grant City', 'state_id' => 25],
                ['name' => 'Sheridan', 'state_id' => 25],
                ['name' => 'Worth', 'state_id' => 25],
                ['name' => 'Graff', 'state_id' => 25],
                ['name' => 'Grovespring', 'state_id' => 25],
                ['name' => 'Hartville', 'state_id' => 25],
                ['name' => 'Macomb', 'state_id' => 25],
                ['name' => 'Mansfield', 'state_id' => 25],
                ['name' => 'Mountain Grove', 'state_id' => 25],
                ['name' => 'Norwood', 'state_id' => 25]
            ]);
        }
    }
}
