<?php

use Illuminate\Database\Seeder;

class state18TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of KY - Kentucky.
        //If the table 'cities' exists, insert the data to the table.
        if (DB::table('cities')->get()->count() >= 0) {
            DB::table('cities')->insert([
                ['name' => 'Breeding', 'state_id' => 18],
                ['name' => 'Cane Valley', 'state_id' => 18],
                ['name' => 'Columbia', 'state_id' => 18],
                ['name' => 'Glens Fork', 'state_id' => 18],
                ['name' => 'Gradyville', 'state_id' => 18],
                ['name' => 'Knifley', 'state_id' => 18],
                ['name' => 'Adolphus', 'state_id' => 18],
                ['name' => 'Holland', 'state_id' => 18],
                ['name' => 'Scottsville', 'state_id' => 18],
                ['name' => 'Lawrenceburg', 'state_id' => 18],
                ['name' => 'Bandana', 'state_id' => 18],
                ['name' => 'Barlow', 'state_id' => 18],
                ['name' => 'La Center', 'state_id' => 18],
                ['name' => 'Lovelaceville', 'state_id' => 18],
                ['name' => 'Wickliffe', 'state_id' => 18],
                ['name' => 'Austin', 'state_id' => 18],
                ['name' => 'Cave City', 'state_id' => 18],
                ['name' => 'Eighty Eight', 'state_id' => 18],
                ['name' => 'Etoile', 'state_id' => 18],
                ['name' => 'Glasgow', 'state_id' => 18],
                ['name' => 'Hiseville', 'state_id' => 18],
                ['name' => 'Lucas', 'state_id' => 18],
                ['name' => 'Park City', 'state_id' => 18],
                ['name' => 'Olympia', 'state_id' => 18],
                ['name' => 'Owingsville', 'state_id' => 18],
                ['name' => 'Preston', 'state_id' => 18],
                ['name' => 'Salt Lick', 'state_id' => 18],
                ['name' => 'Sharpsburg', 'state_id' => 18],
                ['name' => 'Calvin', 'state_id' => 18],
                ['name' => 'Hulen', 'state_id' => 18],
                ['name' => 'Miracle', 'state_id' => 18],
                ['name' => 'Arjay', 'state_id' => 18],
                ['name' => 'Beverly', 'state_id' => 18],
                ['name' => 'Frakes', 'state_id' => 18],
                ['name' => 'Ingram', 'state_id' => 18],
                ['name' => 'Kettle Island', 'state_id' => 18],
                ['name' => 'Middlesboro', 'state_id' => 18],
                ['name' => 'Pineville', 'state_id' => 18],
                ['name' => 'Stoney Fork', 'state_id' => 18],
                ['name' => 'Burlington', 'state_id' => 18],
                ['name' => 'Hebron', 'state_id' => 18],
                ['name' => 'Florence', 'state_id' => 18],
                ['name' => 'Petersburg', 'state_id' => 18],
                ['name' => 'Union', 'state_id' => 18],
                ['name' => 'Verona', 'state_id' => 18],
                ['name' => 'Walton', 'state_id' => 18],
                ['name' => 'Millersburg', 'state_id' => 18],
                ['name' => 'North Middletown', 'state_id' => 18],
                ['name' => 'Paris', 'state_id' => 18],
                ['name' => 'Ashland', 'state_id' => 18],
                ['name' => 'Catlettsburg', 'state_id' => 18],
                ['name' => 'Rush', 'state_id' => 18],
                ['name' => 'Danville', 'state_id' => 18],
                ['name' => 'Junction City', 'state_id' => 18],
                ['name' => 'Mitchellsburg', 'state_id' => 18],
                ['name' => 'Parksville', 'state_id' => 18],
                ['name' => 'Perryville', 'state_id' => 18],
                ['name' => 'Augusta', 'state_id' => 18],
                ['name' => 'Brooksville', 'state_id' => 18],
                ['name' => 'Foster', 'state_id' => 18],
                ['name' => 'Germantown', 'state_id' => 18],
                ['name' => 'Milford', 'state_id' => 18],
                ['name' => 'Bays', 'state_id' => 18],
                ['name' => 'Clayhole', 'state_id' => 18],
                ['name' => 'Jackson', 'state_id' => 18],
                ['name' => 'Lost Creek', 'state_id' => 18],
                ['name' => 'Rousseau', 'state_id' => 18],
                ['name' => 'Vancleve', 'state_id' => 18],
                ['name' => 'Whick', 'state_id' => 18],
                ['name' => 'Cloverport', 'state_id' => 18],
                ['name' => 'Custer', 'state_id' => 18],
                ['name' => 'Garfield', 'state_id' => 18],
                ['name' => 'Hardinsburg', 'state_id' => 18],
                ['name' => 'Harned', 'state_id' => 18],
                ['name' => 'Hudson', 'state_id' => 18],
                ['name' => 'Irvington', 'state_id' => 18],
                ['name' => 'Mc Daniels', 'state_id' => 18],
                ['name' => 'Mc Quady', 'state_id' => 18],
                ['name' => 'Stephensport', 'state_id' => 18],
                ['name' => 'Union Star', 'state_id' => 18],
                ['name' => 'Webster', 'state_id' => 18],
                ['name' => 'Westview', 'state_id' => 18],
                ['name' => 'Mount Washington', 'state_id' => 18],
                ['name' => 'Brooks', 'state_id' => 18],
                ['name' => 'Clermont', 'state_id' => 18],
                ['name' => 'Hillview', 'state_id' => 18],
                ['name' => 'Lebanon Junction', 'state_id' => 18],
                ['name' => 'Shepherdsville', 'state_id' => 18],
                ['name' => 'Aberdeen', 'state_id' => 18],
                ['name' => 'Dunbar', 'state_id' => 18],
                ['name' => 'Jetson', 'state_id' => 18],
                ['name' => 'Morgantown', 'state_id' => 18],
                ['name' => 'Rochester', 'state_id' => 18],
                ['name' => 'Woodbury', 'state_id' => 18],
                ['name' => 'Fredonia', 'state_id' => 18],
                ['name' => 'Princeton', 'state_id' => 18],
                ['name' => 'Almo', 'state_id' => 18],
                ['name' => 'Dexter', 'state_id' => 18],
                ['name' => 'Hazel', 'state_id' => 18],
                ['name' => 'Kirksey', 'state_id' => 18],
                ['name' => 'Murray', 'state_id' => 18],
                ['name' => 'New Concord', 'state_id' => 18],
                ['name' => 'Alexandria', 'state_id' => 18],
                ['name' => 'California', 'state_id' => 18],
                ['name' => 'Melbourne', 'state_id' => 18],
                ['name' => 'Newport', 'state_id' => 18],
                ['name' => 'Bellevue', 'state_id' => 18],
                ['name' => 'Dayton', 'state_id' => 18],
                ['name' => 'Fort Thomas', 'state_id' => 18],
                ['name' => 'Silver Grove', 'state_id' => 18],
                ['name' => 'Arlington', 'state_id' => 18],
                ['name' => 'Bardwell', 'state_id' => 18],
                ['name' => 'Cunningham', 'state_id' => 18],
                ['name' => 'Milburn', 'state_id' => 18],
                ['name' => 'Carrollton', 'state_id' => 18],
                ['name' => 'Ghent', 'state_id' => 18],
                ['name' => 'Sanders', 'state_id' => 18],
                ['name' => 'Worthville', 'state_id' => 18],
                ['name' => 'Carter', 'state_id' => 18],
                ['name' => 'Denton', 'state_id' => 18],
                ['name' => 'Grahn', 'state_id' => 18],
                ['name' => 'Grayson', 'state_id' => 18],
                ['name' => 'Hitchins', 'state_id' => 18],
                ['name' => 'Olive Hill', 'state_id' => 18],
                ['name' => 'Soldier', 'state_id' => 18],
                ['name' => 'Willard', 'state_id' => 18],
                ['name' => 'Bethelridge', 'state_id' => 18],
                ['name' => 'Dunnville', 'state_id' => 18],
                ['name' => 'Liberty', 'state_id' => 18],
                ['name' => 'Middleburg', 'state_id' => 18],
                ['name' => 'Windsor', 'state_id' => 18],
                ['name' => 'Yosemite', 'state_id' => 18],
                ['name' => 'Crofton', 'state_id' => 18],
                ['name' => 'Fairview', 'state_id' => 18],
                ['name' => 'Fort Campbell', 'state_id' => 18],
                ['name' => 'Gracey', 'state_id' => 18],
                ['name' => 'Herndon', 'state_id' => 18],
                ['name' => 'Hopkinsville', 'state_id' => 18],
                ['name' => 'La Fayette', 'state_id' => 18],
                ['name' => 'Oak Grove', 'state_id' => 18],
                ['name' => 'Pembroke', 'state_id' => 18],
                ['name' => 'Winchester', 'state_id' => 18],
                ['name' => 'Big Creek', 'state_id' => 18],
                ['name' => 'Fall Rock', 'state_id' => 18],
                ['name' => 'Garrard', 'state_id' => 18],
                ['name' => 'Goose Rock', 'state_id' => 18],
                ['name' => 'Hima', 'state_id' => 18],
                ['name' => 'Manchester', 'state_id' => 18],
                ['name' => 'Oneida', 'state_id' => 18],
                ['name' => 'Sextons Creek', 'state_id' => 18],
                ['name' => 'Albany', 'state_id' => 18],
                ['name' => 'Alpha', 'state_id' => 18],
                ['name' => 'Crayne', 'state_id' => 18],
                ['name' => 'Dycusburg', 'state_id' => 18],
                ['name' => 'Marion', 'state_id' => 18],
                ['name' => 'Burkesville', 'state_id' => 18],
                ['name' => 'Marrowbone', 'state_id' => 18],
                ['name' => 'Owensboro', 'state_id' => 18],
                ['name' => 'Curdsville', 'state_id' => 18],
                ['name' => 'Maceo', 'state_id' => 18],
                ['name' => 'Maple Mount', 'state_id' => 18],
                ['name' => 'Philpot', 'state_id' => 18],
                ['name' => 'Utica', 'state_id' => 18],
                ['name' => 'West Louisville', 'state_id' => 18],
                ['name' => 'Whitesville', 'state_id' => 18],
                ['name' => 'Rocky Hill', 'state_id' => 18],
                ['name' => 'Bee Spring', 'state_id' => 18],
                ['name' => 'Brownsville', 'state_id' => 18],
                ['name' => 'Mammoth Cave', 'state_id' => 18],
                ['name' => 'Roundhill', 'state_id' => 18],
                ['name' => 'Sweeden', 'state_id' => 18],
                ['name' => 'Isonville', 'state_id' => 18],
                ['name' => 'Sandy Hook', 'state_id' => 18],
                ['name' => 'Irvine', 'state_id' => 18],
                ['name' => 'Ravenna', 'state_id' => 18],
                ['name' => 'Lexington', 'state_id' => 18],
                ['name' => 'Elizaville', 'state_id' => 18],
                ['name' => 'Ewing', 'state_id' => 18],
                ['name' => 'Flemingsburg', 'state_id' => 18],
                ['name' => 'Hillsboro', 'state_id' => 18],
                ['name' => 'Muses Mills', 'state_id' => 18],
                ['name' => 'Plummers Landing', 'state_id' => 18],
                ['name' => 'Wallingford', 'state_id' => 18],
                ['name' => 'Allen', 'state_id' => 18],
                ['name' => 'Auxier', 'state_id' => 18],
                ['name' => 'Banner', 'state_id' => 18],
                ['name' => 'Beaver', 'state_id' => 18],
                ['name' => 'Betsy Layne', 'state_id' => 18],
                ['name' => 'Bevinsville', 'state_id' => 18],
                ['name' => 'Blue River', 'state_id' => 18],
                ['name' => 'Bypro', 'state_id' => 18],
                ['name' => 'Dana', 'state_id' => 18],
                ['name' => 'David', 'state_id' => 18],
                ['name' => 'Drift', 'state_id' => 18],
                ['name' => 'Dwale', 'state_id' => 18],
                ['name' => 'Eastern', 'state_id' => 18],
                ['name' => 'Garrett', 'state_id' => 18],
                ['name' => 'Grethel', 'state_id' => 18],
                ['name' => 'Harold', 'state_id' => 18],
                ['name' => 'Hi Hat', 'state_id' => 18],
                ['name' => 'Hueysville', 'state_id' => 18],
                ['name' => 'Ivel', 'state_id' => 18],
                ['name' => 'Lackey', 'state_id' => 18],
                ['name' => 'Langley', 'state_id' => 18],
                ['name' => 'Mc Dowell', 'state_id' => 18],
                ['name' => 'Martin', 'state_id' => 18],
                ['name' => 'Melvin', 'state_id' => 18],
                ['name' => 'Minnie', 'state_id' => 18],
                ['name' => 'Prestonsburg', 'state_id' => 18],
                ['name' => 'Printer', 'state_id' => 18],
                ['name' => 'Stanville', 'state_id' => 18],
                ['name' => 'Teaberry', 'state_id' => 18],
                ['name' => 'Tram', 'state_id' => 18],
                ['name' => 'Wayland', 'state_id' => 18],
                ['name' => 'Weeksbury', 'state_id' => 18],
                ['name' => 'Wheelwright', 'state_id' => 18],
                ['name' => 'Frankfort', 'state_id' => 18],
                ['name' => 'Fulton', 'state_id' => 18],
                ['name' => 'Hickman', 'state_id' => 18],
                ['name' => 'Glencoe', 'state_id' => 18],
                ['name' => 'Sparta', 'state_id' => 18],
                ['name' => 'Warsaw', 'state_id' => 18],
                ['name' => 'Bryantsville', 'state_id' => 18],
                ['name' => 'Lancaster', 'state_id' => 18],
                ['name' => 'Paint Lick', 'state_id' => 18],
                ['name' => 'Corinth', 'state_id' => 18],
                ['name' => 'Crittenden', 'state_id' => 18],
                ['name' => 'Dry Ridge', 'state_id' => 18],
                ['name' => 'Jonesville', 'state_id' => 18],
                ['name' => 'Mason', 'state_id' => 18],
                ['name' => 'Williamstown', 'state_id' => 18],
                ['name' => 'Boaz', 'state_id' => 18],
                ['name' => 'Fancy Farm', 'state_id' => 18],
                ['name' => 'Farmington', 'state_id' => 18],
                ['name' => 'Hickory', 'state_id' => 18],
                ['name' => 'Lowes', 'state_id' => 18],
                ['name' => 'Lynnville', 'state_id' => 18],
                ['name' => 'Mayfield', 'state_id' => 18],
                ['name' => 'Melber', 'state_id' => 18],
                ['name' => 'Sedalia', 'state_id' => 18],
                ['name' => 'Symsonia', 'state_id' => 18],
                ['name' => 'Water Valley', 'state_id' => 18],
                ['name' => 'Wingo', 'state_id' => 18],
                ['name' => 'Falls Of Rough', 'state_id' => 18],
                ['name' => 'Big Clifty', 'state_id' => 18],
                ['name' => 'Caneyville', 'state_id' => 18],
                ['name' => 'Clarkson', 'state_id' => 18],
                ['name' => 'Leitchfield', 'state_id' => 18],
                ['name' => 'Millwood', 'state_id' => 18],
                ['name' => 'Greensburg', 'state_id' => 18],
                ['name' => 'Summersville', 'state_id' => 18],
                ['name' => 'Argillite', 'state_id' => 18],
                ['name' => 'Flatwoods', 'state_id' => 18],
                ['name' => 'Greenup', 'state_id' => 18],
                ['name' => 'Russell', 'state_id' => 18],
                ['name' => 'South Portsmouth', 'state_id' => 18],
                ['name' => 'South Shore', 'state_id' => 18],
                ['name' => 'Worthington', 'state_id' => 18],
                ['name' => 'Hawesville', 'state_id' => 18],
                ['name' => 'Lewisport', 'state_id' => 18],
                ['name' => 'Pellville', 'state_id' => 18],
                ['name' => 'Reynolds Station', 'state_id' => 18],
                ['name' => 'Fort Knox', 'state_id' => 18],
                ['name' => 'Radcliff', 'state_id' => 18],
                ['name' => 'Rineyville', 'state_id' => 18],
                ['name' => 'Vine Grove', 'state_id' => 18],
                ['name' => 'West Point', 'state_id' => 18],
                ['name' => 'Elizabethtown', 'state_id' => 18],
                ['name' => 'Cecilia', 'state_id' => 18],
                ['name' => 'Eastview', 'state_id' => 18],
                ['name' => 'Glendale', 'state_id' => 18],
                ['name' => 'Sonora', 'state_id' => 18],
                ['name' => 'Upton', 'state_id' => 18],
                ['name' => 'White Mills', 'state_id' => 18],
                ['name' => 'Ages Brookside', 'state_id' => 18],
                ['name' => 'Baxter', 'state_id' => 18],
                ['name' => 'Benham', 'state_id' => 18],
                ['name' => 'Big Laurel', 'state_id' => 18],
                ['name' => 'Bledsoe', 'state_id' => 18],
                ['name' => 'Cawood', 'state_id' => 18],
                ['name' => 'Coalgood', 'state_id' => 18],
                ['name' => 'Coldiron', 'state_id' => 18],
                ['name' => 'Cranks', 'state_id' => 18],
                ['name' => 'Cumberland', 'state_id' => 18],
                ['name' => 'Dayhoit', 'state_id' => 18],
                ['name' => 'Evarts', 'state_id' => 18],
                ['name' => 'Grays Knob', 'state_id' => 18],
                ['name' => 'Gulston', 'state_id' => 18],
                ['name' => 'Harlan', 'state_id' => 18],
                ['name' => 'Holmes Mill', 'state_id' => 18],
                ['name' => 'Kenvir', 'state_id' => 18],
                ['name' => 'Lejunior', 'state_id' => 18],
                ['name' => 'Loyall', 'state_id' => 18],
                ['name' => 'Lynch', 'state_id' => 18],
                ['name' => 'Pathfork', 'state_id' => 18],
                ['name' => 'Putney', 'state_id' => 18],
                ['name' => 'Totz', 'state_id' => 18],
                ['name' => 'Wallins Creek', 'state_id' => 18],
                ['name' => 'Closplint', 'state_id' => 18],
                ['name' => 'Mary Alice', 'state_id' => 18],
                ['name' => 'Berry', 'state_id' => 18],
                ['name' => 'Cynthiana', 'state_id' => 18],
                ['name' => 'Bonnieville', 'state_id' => 18],
                ['name' => 'Canmer', 'state_id' => 18],
                ['name' => 'Cub Run', 'state_id' => 18],
                ['name' => 'Hardyville', 'state_id' => 18],
                ['name' => 'Horse Cave', 'state_id' => 18],
                ['name' => 'Munfordville', 'state_id' => 18],
                ['name' => 'Baskett', 'state_id' => 18],
                ['name' => 'Corydon', 'state_id' => 18],
                ['name' => 'Henderson', 'state_id' => 18],
                ['name' => 'Reed', 'state_id' => 18],
                ['name' => 'Robards', 'state_id' => 18],
                ['name' => 'Smith Mills', 'state_id' => 18],
                ['name' => 'Spottsville', 'state_id' => 18],
                ['name' => 'Bethlehem', 'state_id' => 18],
                ['name' => 'Campbellsburg', 'state_id' => 18],
                ['name' => 'Eminence', 'state_id' => 18],
                ['name' => 'Lockport', 'state_id' => 18],
                ['name' => 'New Castle', 'state_id' => 18],
                ['name' => 'Pendleton', 'state_id' => 18],
                ['name' => 'Pleasureville', 'state_id' => 18],
                ['name' => 'Port Royal', 'state_id' => 18],
                ['name' => 'Smithfield', 'state_id' => 18],
                ['name' => 'Sulphur', 'state_id' => 18],
                ['name' => 'Turners Station', 'state_id' => 18],
                ['name' => 'Clinton', 'state_id' => 18],
                ['name' => 'Columbus', 'state_id' => 18],
                ['name' => 'Dawson Springs', 'state_id' => 18],
                ['name' => 'Earlington', 'state_id' => 18],
                ['name' => 'Hanson', 'state_id' => 18],
                ['name' => 'Madisonville', 'state_id' => 18],
                ['name' => 'Manitou', 'state_id' => 18],
                ['name' => 'Mortons Gap', 'state_id' => 18],
                ['name' => 'Nebo', 'state_id' => 18],
                ['name' => 'Nortonville', 'state_id' => 18],
                ['name' => 'Saint Charles', 'state_id' => 18],
                ['name' => 'White Plains', 'state_id' => 18],
                ['name' => 'Annville', 'state_id' => 18],
                ['name' => 'Gray Hawk', 'state_id' => 18],
                ['name' => 'Mc Kee', 'state_id' => 18],
                ['name' => 'Sandgap', 'state_id' => 18],
                ['name' => 'Tyner', 'state_id' => 18],
                ['name' => 'Waneta', 'state_id' => 18],
                ['name' => 'Eastwood', 'state_id' => 18],
                ['name' => 'Fisherville', 'state_id' => 18],
                ['name' => 'Glenview', 'state_id' => 18],
                ['name' => 'Harrods Creek', 'state_id' => 18],
                ['name' => 'Masonic Home', 'state_id' => 18],
                ['name' => 'Prospect', 'state_id' => 18],
                ['name' => 'Fairdale', 'state_id' => 18],
                ['name' => 'Louisville', 'state_id' => 18],
                ['name' => 'Keene', 'state_id' => 18],
                ['name' => 'Nicholasville', 'state_id' => 18],
                ['name' => 'Wilmore', 'state_id' => 18],
                ['name' => 'Boons Camp', 'state_id' => 18],
                ['name' => 'East Point', 'state_id' => 18],
                ['name' => 'Flatgap', 'state_id' => 18],
                ['name' => 'Hagerhill', 'state_id' => 18],
                ['name' => 'Keaton', 'state_id' => 18],
                ['name' => 'Meally', 'state_id' => 18],
                ['name' => 'Oil Springs', 'state_id' => 18],
                ['name' => 'Paintsville', 'state_id' => 18],
                ['name' => 'River', 'state_id' => 18],
                ['name' => 'Sitka', 'state_id' => 18],
                ['name' => 'Staffordsville', 'state_id' => 18],
                ['name' => 'Stambaugh', 'state_id' => 18],
                ['name' => 'Thelma', 'state_id' => 18],
                ['name' => 'Tutor Key', 'state_id' => 18],
                ['name' => 'Van Lear', 'state_id' => 18],
                ['name' => 'West Van Lear', 'state_id' => 18],
                ['name' => 'Williamsport', 'state_id' => 18],
                ['name' => 'Wittensville', 'state_id' => 18],
                ['name' => 'Covington', 'state_id' => 18],
                ['name' => 'Latonia', 'state_id' => 18],
                ['name' => 'Ft Mitchell', 'state_id' => 18],
                ['name' => 'Erlanger', 'state_id' => 18],
                ['name' => 'Independence', 'state_id' => 18],
                ['name' => 'Kenton', 'state_id' => 18],
                ['name' => 'Morning View', 'state_id' => 18],
                ['name' => 'Carrie', 'state_id' => 18],
                ['name' => 'Emmalena', 'state_id' => 18],
                ['name' => 'Fisty', 'state_id' => 18],
                ['name' => 'Sassafras', 'state_id' => 18],
                ['name' => 'Vest', 'state_id' => 18],
                ['name' => 'Garner', 'state_id' => 18],
                ['name' => 'Hindman', 'state_id' => 18],
                ['name' => 'Kite', 'state_id' => 18],
                ['name' => 'Leburn', 'state_id' => 18],
                ['name' => 'Littcarr', 'state_id' => 18],
                ['name' => 'Mallie', 'state_id' => 18],
                ['name' => 'Mousie', 'state_id' => 18],
                ['name' => 'Pine Top', 'state_id' => 18],
                ['name' => 'Pippa Passes', 'state_id' => 18],
                ['name' => 'Redfox', 'state_id' => 18],
                ['name' => 'Dema', 'state_id' => 18],
                ['name' => 'Raven', 'state_id' => 18],
                ['name' => 'Topmost', 'state_id' => 18],
                ['name' => 'Gray', 'state_id' => 18],
                ['name' => 'Woodbine', 'state_id' => 18],
                ['name' => 'Artemus', 'state_id' => 18],
                ['name' => 'Barbourville', 'state_id' => 18],
                ['name' => 'Bimble', 'state_id' => 18],
                ['name' => 'Bryants Store', 'state_id' => 18],
                ['name' => 'Cannon', 'state_id' => 18],
                ['name' => 'Dewitt', 'state_id' => 18],
                ['name' => 'Flat Lick', 'state_id' => 18],
                ['name' => 'Fourmile', 'state_id' => 18],
                ['name' => 'Girdler', 'state_id' => 18],
                ['name' => 'Green Road', 'state_id' => 18],
                ['name' => 'Heidrick', 'state_id' => 18],
                ['name' => 'Hinkle', 'state_id' => 18],
                ['name' => 'Scalf', 'state_id' => 18],
                ['name' => 'Trosper', 'state_id' => 18],
                ['name' => 'Walker', 'state_id' => 18],
                ['name' => 'Buffalo', 'state_id' => 18],
                ['name' => 'Hodgenville', 'state_id' => 18],
                ['name' => 'Magnolia', 'state_id' => 18],
                ['name' => 'Mount Sherman', 'state_id' => 18],
                ['name' => 'Bush', 'state_id' => 18],
                ['name' => 'East Bernstadt', 'state_id' => 18],
                ['name' => 'Keavy', 'state_id' => 18],
                ['name' => 'Lily', 'state_id' => 18],
                ['name' => 'London', 'state_id' => 18],
                ['name' => 'Pittsburg', 'state_id' => 18],
                ['name' => 'Blaine', 'state_id' => 18],
                ['name' => 'Martha', 'state_id' => 18],
                ['name' => 'Mazie', 'state_id' => 18],
                ['name' => 'Webbville', 'state_id' => 18],
                ['name' => 'Adams', 'state_id' => 18],
                ['name' => 'Louisa', 'state_id' => 18],
                ['name' => 'Lowmansville', 'state_id' => 18],
                ['name' => 'Ulysses', 'state_id' => 18],
                ['name' => 'Beattyville', 'state_id' => 18],
                ['name' => 'Lone', 'state_id' => 18],
                ['name' => 'Saint Helens', 'state_id' => 18],
                ['name' => 'Zoe', 'state_id' => 18],
                ['name' => 'Asher', 'state_id' => 18],
                ['name' => 'Chappell', 'state_id' => 18],
                ['name' => 'Essie', 'state_id' => 18],
                ['name' => 'Helton', 'state_id' => 18],
                ['name' => 'Hoskinston', 'state_id' => 18],
                ['name' => 'Mozelle', 'state_id' => 18],
                ['name' => 'Stinnett', 'state_id' => 18],
                ['name' => 'Warbranch', 'state_id' => 18],
                ['name' => 'Roark', 'state_id' => 18],
                ['name' => 'Bear Branch', 'state_id' => 18],
                ['name' => 'Hyden', 'state_id' => 18],
                ['name' => 'Sizerock', 'state_id' => 18],
                ['name' => 'Smilax', 'state_id' => 18],
                ['name' => 'Thousandsticks', 'state_id' => 18],
                ['name' => 'Wendover', 'state_id' => 18],
                ['name' => 'Wooton', 'state_id' => 18],
                ['name' => 'Yeaddiss', 'state_id' => 18],
                ['name' => 'Eolia', 'state_id' => 18],
                ['name' => 'Partridge', 'state_id' => 18],
                ['name' => 'Burdine', 'state_id' => 18],
                ['name' => 'Jenkins', 'state_id' => 18],
                ['name' => 'Blackey', 'state_id' => 18],
                ['name' => 'Cromona', 'state_id' => 18],
                ['name' => 'Deane', 'state_id' => 18],
                ['name' => 'Ermine', 'state_id' => 18],
                ['name' => 'Gordon', 'state_id' => 18],
                ['name' => 'Hallie', 'state_id' => 18],
                ['name' => 'Isom', 'state_id' => 18],
                ['name' => 'Jackhorn', 'state_id' => 18],
                ['name' => 'Jeremiah', 'state_id' => 18],
                ['name' => 'Letcher', 'state_id' => 18],
                ['name' => 'Linefork', 'state_id' => 18],
                ['name' => 'Mc Roberts', 'state_id' => 18],
                ['name' => 'Mayking', 'state_id' => 18],
                ['name' => 'Millstone', 'state_id' => 18],
                ['name' => 'Neon', 'state_id' => 18],
                ['name' => 'Premium', 'state_id' => 18],
                ['name' => 'Roxana', 'state_id' => 18],
                ['name' => 'Seco', 'state_id' => 18],
                ['name' => 'Thornton', 'state_id' => 18],
                ['name' => 'Whitesburg', 'state_id' => 18],
                ['name' => 'Emerson', 'state_id' => 18],
                ['name' => 'Garrison', 'state_id' => 18],
                ['name' => 'Quincy', 'state_id' => 18],
                ['name' => 'Vanceburg', 'state_id' => 18],
                ['name' => 'Tollesboro', 'state_id' => 18],
                ['name' => 'Crab Orchard', 'state_id' => 18],
                ['name' => 'Hustonville', 'state_id' => 18],
                ['name' => 'Kings Mountain', 'state_id' => 18],
                ['name' => 'Mc Kinney', 'state_id' => 18],
                ['name' => 'Stanford', 'state_id' => 18],
                ['name' => 'Waynesburg', 'state_id' => 18],
                ['name' => 'Burna', 'state_id' => 18],
                ['name' => 'Grand Rivers', 'state_id' => 18],
                ['name' => 'Hampton', 'state_id' => 18],
                ['name' => 'Ledbetter', 'state_id' => 18],
                ['name' => 'Salem', 'state_id' => 18],
                ['name' => 'Smithland', 'state_id' => 18],
                ['name' => 'Tiline', 'state_id' => 18],
                ['name' => 'Adairville', 'state_id' => 18],
                ['name' => 'Auburn', 'state_id' => 18],
                ['name' => 'Lewisburg', 'state_id' => 18],
                ['name' => 'Olmstead', 'state_id' => 18],
                ['name' => 'Russellville', 'state_id' => 18],
                ['name' => 'Eddyville', 'state_id' => 18],
                ['name' => 'Kuttawa', 'state_id' => 18],
                ['name' => 'Paducah', 'state_id' => 18],
                ['name' => 'Kevil', 'state_id' => 18],
                ['name' => 'West Paducah', 'state_id' => 18],
                ['name' => 'Marshes Siding', 'state_id' => 18],
                ['name' => 'Parkers Lake', 'state_id' => 18],
                ['name' => 'Pine Knot', 'state_id' => 18],
                ['name' => 'Revelo', 'state_id' => 18],
                ['name' => 'Stearns', 'state_id' => 18],
                ['name' => 'Strunk', 'state_id' => 18],
                ['name' => 'Whitley City', 'state_id' => 18],
                ['name' => 'Beech Grove', 'state_id' => 18],
                ['name' => 'Calhoun', 'state_id' => 18],
                ['name' => 'Island', 'state_id' => 18],
                ['name' => 'Livermore', 'state_id' => 18],
                ['name' => 'Rumsey', 'state_id' => 18],
                ['name' => 'Sacramento', 'state_id' => 18],
                ['name' => 'Waco', 'state_id' => 18],
                ['name' => 'Berea', 'state_id' => 18],
                ['name' => 'Bighill', 'state_id' => 18],
                ['name' => 'Richmond', 'state_id' => 18],
                ['name' => 'Falcon', 'state_id' => 18],
                ['name' => 'Royalton', 'state_id' => 18],
                ['name' => 'Salyersville', 'state_id' => 18],
                ['name' => 'Gunlock', 'state_id' => 18],
                ['name' => 'Bradfordsville', 'state_id' => 18],
                ['name' => 'Lebanon', 'state_id' => 18],
                ['name' => 'Loretto', 'state_id' => 18],
                ['name' => 'Nerinx', 'state_id' => 18],
                ['name' => 'Raywick', 'state_id' => 18],
                ['name' => 'Saint Francis', 'state_id' => 18],
                ['name' => 'Saint Mary', 'state_id' => 18],
                ['name' => 'Gravel Switch', 'state_id' => 18],
                ['name' => 'Benton', 'state_id' => 18],
                ['name' => 'Calvert City', 'state_id' => 18],
                ['name' => 'Gilbertsville', 'state_id' => 18],
                ['name' => 'Hardin', 'state_id' => 18],
                ['name' => 'Beauty', 'state_id' => 18],
                ['name' => 'Debord', 'state_id' => 18],
                ['name' => 'Inez', 'state_id' => 18],
                ['name' => 'Lovely', 'state_id' => 18],
                ['name' => 'Pilgrim', 'state_id' => 18],
                ['name' => 'Tomahawk', 'state_id' => 18],
                ['name' => 'Warfield', 'state_id' => 18],
                ['name' => 'Dover', 'state_id' => 18],
                ['name' => 'Mayslick', 'state_id' => 18],
                ['name' => 'Maysville', 'state_id' => 18],
                ['name' => 'Minerva', 'state_id' => 18],
                ['name' => 'Washington', 'state_id' => 18],
                ['name' => 'Battletown', 'state_id' => 18],
                ['name' => 'Brandenburg', 'state_id' => 18],
                ['name' => 'Ekron', 'state_id' => 18],
                ['name' => 'Guston', 'state_id' => 18],
                ['name' => 'Muldraugh', 'state_id' => 18],
                ['name' => 'Payneville', 'state_id' => 18],
                ['name' => 'Rhodelia', 'state_id' => 18],
                ['name' => 'Denniston', 'state_id' => 18],
                ['name' => 'Frenchburg', 'state_id' => 18],
                ['name' => 'Means', 'state_id' => 18],
                ['name' => 'Wellington', 'state_id' => 18],
                ['name' => 'Burgin', 'state_id' => 18],
                ['name' => 'Harrodsburg', 'state_id' => 18],
                ['name' => 'Salvisa', 'state_id' => 18],
                ['name' => 'Beaumont', 'state_id' => 18],
                ['name' => 'Edmonton', 'state_id' => 18],
                ['name' => 'Knob Lick', 'state_id' => 18],
                ['name' => 'Summer Shade', 'state_id' => 18],
                ['name' => 'Center', 'state_id' => 18],
                ['name' => 'Fountain Run', 'state_id' => 18],
                ['name' => 'Gamaliel', 'state_id' => 18],
                ['name' => 'Hestand', 'state_id' => 18],
                ['name' => 'Mount Hermon', 'state_id' => 18],
                ['name' => 'Tompkinsville', 'state_id' => 18],
                ['name' => 'Hope', 'state_id' => 18],
                ['name' => 'Jeffersonville', 'state_id' => 18],
                ['name' => 'Mount Sterling', 'state_id' => 18],
                ['name' => 'Mize', 'state_id' => 18],
                ['name' => 'Cannel City', 'state_id' => 18],
                ['name' => 'Crockett', 'state_id' => 18],
                ['name' => 'Elkfork', 'state_id' => 18],
                ['name' => 'Ezel', 'state_id' => 18],
                ['name' => 'Malone', 'state_id' => 18],
                ['name' => 'West Liberty', 'state_id' => 18],
                ['name' => 'Wrigley', 'state_id' => 18],
                ['name' => 'Beech Creek', 'state_id' => 18],
                ['name' => 'Beechmont', 'state_id' => 18],
                ['name' => 'Belton', 'state_id' => 18],
                ['name' => 'Bremen', 'state_id' => 18],
                ['name' => 'Browder', 'state_id' => 18],
                ['name' => 'Central City', 'state_id' => 18],
                ['name' => 'Cleaton', 'state_id' => 18],
                ['name' => 'Drakesboro', 'state_id' => 18],
                ['name' => 'Dunmor', 'state_id' => 18],
                ['name' => 'Graham', 'state_id' => 18],
                ['name' => 'Greenville', 'state_id' => 18],
                ['name' => 'Powderly', 'state_id' => 18],
                ['name' => 'South Carrollton', 'state_id' => 18],
                ['name' => 'Bardstown', 'state_id' => 18],
                ['name' => 'Bloomfield', 'state_id' => 18],
                ['name' => 'Chaplin', 'state_id' => 18],
                ['name' => 'Coxs Creek', 'state_id' => 18],
                ['name' => 'Fairfield', 'state_id' => 18],
                ['name' => 'Nazareth', 'state_id' => 18],
                ['name' => 'New Haven', 'state_id' => 18],
                ['name' => 'New Hope', 'state_id' => 18],
                ['name' => 'Boston', 'state_id' => 18],
                ['name' => 'Carlisle', 'state_id' => 18],
                ['name' => 'Moorefield', 'state_id' => 18],
                ['name' => 'Beaver Dam', 'state_id' => 18],
                ['name' => 'Centertown', 'state_id' => 18],
                ['name' => 'Cromwell', 'state_id' => 18],
                ['name' => 'Dundee', 'state_id' => 18],
                ['name' => 'Fordsville', 'state_id' => 18],
                ['name' => 'Hartford', 'state_id' => 18],
                ['name' => 'Horse Branch', 'state_id' => 18],
                ['name' => 'Mc Henry', 'state_id' => 18],
                ['name' => 'Olaton', 'state_id' => 18],
                ['name' => 'Rockport', 'state_id' => 18],
                ['name' => 'Rosine', 'state_id' => 18],
                ['name' => 'Buckner', 'state_id' => 18],
                ['name' => 'Crestwood', 'state_id' => 18],
                ['name' => 'Goshen', 'state_id' => 18],
                ['name' => 'La Grange', 'state_id' => 18],
                ['name' => 'Pewee Valley', 'state_id' => 18],
                ['name' => 'Westport', 'state_id' => 18],
                ['name' => 'New Liberty', 'state_id' => 18],
                ['name' => 'Owenton', 'state_id' => 18],
                ['name' => 'Perry Park', 'state_id' => 18],
                ['name' => 'Booneville', 'state_id' => 18],
                ['name' => 'Mistletoe', 'state_id' => 18],
                ['name' => 'Ricetown', 'state_id' => 18],
                ['name' => 'Vincent', 'state_id' => 18],
                ['name' => 'Butler', 'state_id' => 18],
                ['name' => 'De Mossville', 'state_id' => 18],
                ['name' => 'Falmouth', 'state_id' => 18],
                ['name' => 'Saul', 'state_id' => 18],
                ['name' => 'Rowdy', 'state_id' => 18],
                ['name' => 'Hazard', 'state_id' => 18],
                ['name' => 'Ary', 'state_id' => 18],
                ['name' => 'Avawam', 'state_id' => 18],
                ['name' => 'Bonnyman', 'state_id' => 18],
                ['name' => 'Buckhorn', 'state_id' => 18],
                ['name' => 'Bulan', 'state_id' => 18],
                ['name' => 'Busy', 'state_id' => 18],
                ['name' => 'Chavies', 'state_id' => 18],
                ['name' => 'Combs', 'state_id' => 18],
                ['name' => 'Cornettsville', 'state_id' => 18],
                ['name' => 'Delphia', 'state_id' => 18],
                ['name' => 'Dice', 'state_id' => 18],
                ['name' => 'Dwarf', 'state_id' => 18],
                ['name' => 'Gays Creek', 'state_id' => 18],
                ['name' => 'Happy', 'state_id' => 18],
                ['name' => 'Jeff', 'state_id' => 18],
                ['name' => 'Krypton', 'state_id' => 18],
                ['name' => 'Scuddy', 'state_id' => 18],
                ['name' => 'Slemp', 'state_id' => 18],
                ['name' => 'Vicco', 'state_id' => 18],
                ['name' => 'Viper', 'state_id' => 18],
                ['name' => 'Yerkes', 'state_id' => 18],
                ['name' => 'Pikeville', 'state_id' => 18],
                ['name' => 'South Williamson', 'state_id' => 18],
                ['name' => 'Ashcamp', 'state_id' => 18],
                ['name' => 'Belcher', 'state_id' => 18],
                ['name' => 'Belfry', 'state_id' => 18],
                ['name' => 'Canada', 'state_id' => 18],
                ['name' => 'Dorton', 'state_id' => 18],
                ['name' => 'Elkhorn City', 'state_id' => 18],
                ['name' => 'Fedscreek', 'state_id' => 18],
                ['name' => 'Fords Branch', 'state_id' => 18],
                ['name' => 'Forest Hills', 'state_id' => 18],
                ['name' => 'Freeburn', 'state_id' => 18],
                ['name' => 'Hardy', 'state_id' => 18],
                ['name' => 'Hellier', 'state_id' => 18],
                ['name' => 'Huddy', 'state_id' => 18],
                ['name' => 'Jonancy', 'state_id' => 18],
                ['name' => 'Kimper', 'state_id' => 18],
                ['name' => 'Lick Creek', 'state_id' => 18],
                ['name' => 'Lookout', 'state_id' => 18],
                ['name' => 'Mc Andrews', 'state_id' => 18],
                ['name' => 'Mc Carr', 'state_id' => 18],
                ['name' => 'Majestic', 'state_id' => 18],
                ['name' => 'Mouthcard', 'state_id' => 18],
                ['name' => 'Myra', 'state_id' => 18],
                ['name' => 'Phelps', 'state_id' => 18],
                ['name' => 'Phyllis', 'state_id' => 18],
                ['name' => 'Pinsonfork', 'state_id' => 18],
                ['name' => 'Raccoon', 'state_id' => 18],
                ['name' => 'Ransom', 'state_id' => 18],
                ['name' => 'Regina', 'state_id' => 18],
                ['name' => 'Robinson Creek', 'state_id' => 18],
                ['name' => 'Rockhouse', 'state_id' => 18],
                ['name' => 'Shelbiana', 'state_id' => 18],
                ['name' => 'Shelby Gap', 'state_id' => 18],
                ['name' => 'Sidney', 'state_id' => 18],
                ['name' => 'Steele', 'state_id' => 18],
                ['name' => 'Stone', 'state_id' => 18],
                ['name' => 'Stopover', 'state_id' => 18],
                ['name' => 'Varney', 'state_id' => 18],
                ['name' => 'Virgie', 'state_id' => 18],
                ['name' => 'Clay City', 'state_id' => 18],
                ['name' => 'Slade', 'state_id' => 18],
                ['name' => 'Stanton', 'state_id' => 18],
                ['name' => 'Somerset', 'state_id' => 18],
                ['name' => 'Bronston', 'state_id' => 18],
                ['name' => 'Burnside', 'state_id' => 18],
                ['name' => 'Ferguson', 'state_id' => 18],
                ['name' => 'Nancy', 'state_id' => 18],
                ['name' => 'Science Hill', 'state_id' => 18],
                ['name' => 'Tateville', 'state_id' => 18],
                ['name' => 'West Somerset', 'state_id' => 18],
                ['name' => 'Eubank', 'state_id' => 18],
                ['name' => 'Mount Olivet', 'state_id' => 18],
                ['name' => 'Brodhead', 'state_id' => 18],
                ['name' => 'Livingston', 'state_id' => 18],
                ['name' => 'Mount Vernon', 'state_id' => 18],
                ['name' => 'Orlando', 'state_id' => 18],
                ['name' => 'Renfro Valley', 'state_id' => 18],
                ['name' => 'Wildie', 'state_id' => 18],
                ['name' => 'Clearfield', 'state_id' => 18],
                ['name' => 'Elliottville', 'state_id' => 18],
                ['name' => 'Farmers', 'state_id' => 18],
                ['name' => 'Morehead', 'state_id' => 18],
                ['name' => 'Jamestown', 'state_id' => 18],
                ['name' => 'Russell Springs', 'state_id' => 18],
                ['name' => 'Georgetown', 'state_id' => 18],
                ['name' => 'Sadieville', 'state_id' => 18],
                ['name' => 'Stamping Ground', 'state_id' => 18],
                ['name' => 'Bagdad', 'state_id' => 18],
                ['name' => 'Finchville', 'state_id' => 18],
                ['name' => 'Shelbyville', 'state_id' => 18],
                ['name' => 'Simpsonville', 'state_id' => 18],
                ['name' => 'Waddy', 'state_id' => 18],
                ['name' => 'Franklin', 'state_id' => 18],
                ['name' => 'Mount Eden', 'state_id' => 18],
                ['name' => 'Taylorsville', 'state_id' => 18],
                ['name' => 'Campbellsville', 'state_id' => 18],
                ['name' => 'Elk Horn', 'state_id' => 18],
                ['name' => 'Mannsville', 'state_id' => 18],
                ['name' => 'Allensville', 'state_id' => 18],
                ['name' => 'Clifty', 'state_id' => 18],
                ['name' => 'Elkton', 'state_id' => 18],
                ['name' => 'Guthrie', 'state_id' => 18],
                ['name' => 'Sharon Grove', 'state_id' => 18],
                ['name' => 'Trenton', 'state_id' => 18],
                ['name' => 'Cadiz', 'state_id' => 18],
                ['name' => 'Cerulean', 'state_id' => 18],
                ['name' => 'Bedford', 'state_id' => 18],
                ['name' => 'Milton', 'state_id' => 18],
                ['name' => 'Morganfield', 'state_id' => 18],
                ['name' => 'Sturgis', 'state_id' => 18],
                ['name' => 'Sullivan', 'state_id' => 18],
                ['name' => 'Uniontown', 'state_id' => 18],
                ['name' => 'Waverly', 'state_id' => 18],
                ['name' => 'Bowling Green', 'state_id' => 18],
                ['name' => 'Alvaton', 'state_id' => 18],
                ['name' => 'Drake', 'state_id' => 18],
                ['name' => 'Oakland', 'state_id' => 18],
                ['name' => 'Woodburn', 'state_id' => 18],
                ['name' => 'Smiths Grove', 'state_id' => 18],
                ['name' => 'Rockfield', 'state_id' => 18],
                ['name' => 'Mackville', 'state_id' => 18],
                ['name' => 'Saint Catharine', 'state_id' => 18],
                ['name' => 'Springfield', 'state_id' => 18],
                ['name' => 'Willisburg', 'state_id' => 18],
                ['name' => 'Monticello', 'state_id' => 18],
                ['name' => 'Clay', 'state_id' => 18],
                ['name' => 'Dixon', 'state_id' => 18],
                ['name' => 'Poole', 'state_id' => 18],
                ['name' => 'Providence', 'state_id' => 18],
                ['name' => 'Sebree', 'state_id' => 18],
                ['name' => 'Slaughters', 'state_id' => 18],
                ['name' => 'Wheatcroft', 'state_id' => 18],
                ['name' => 'Corbin', 'state_id' => 18],
                ['name' => 'Emlyn', 'state_id' => 18],
                ['name' => 'Rockholds', 'state_id' => 18],
                ['name' => 'Siler', 'state_id' => 18],
                ['name' => 'Williamsburg', 'state_id' => 18],
                ['name' => 'Campton', 'state_id' => 18],
                ['name' => 'Hazel Green', 'state_id' => 18],
                ['name' => 'Pine Ridge', 'state_id' => 18],
                ['name' => 'Rogers', 'state_id' => 18],
                ['name' => 'Midway', 'state_id' => 18],
                ['name' => 'Versailles', 'state_id' => 18]
            ]);
        }
    }
}
