<?php

use Illuminate\Database\Seeder;

class state23TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of MI - Michigan.
        //If the table 'cities' exists, insert the data to the table.
        if (DB::table('cities')->get()->count() >= 0) {
            DB::table('cities')->insert([
                ['name' => 'Barton City', 'state_id' => 23],
                ['name' => 'Black River', 'state_id' => 23],
                ['name' => 'Curran', 'state_id' => 23],
                ['name' => 'Glennie', 'state_id' => 23],
                ['name' => 'Greenbush', 'state_id' => 23],
                ['name' => 'Harrisville', 'state_id' => 23],
                ['name' => 'Lincoln', 'state_id' => 23],
                ['name' => 'Mikado', 'state_id' => 23],
                ['name' => 'Spruce', 'state_id' => 23],
                ['name' => 'Au Train', 'state_id' => 23],
                ['name' => 'Chatham', 'state_id' => 23],
                ['name' => 'Deerton', 'state_id' => 23],
                ['name' => 'Eben Junction', 'state_id' => 23],
                ['name' => 'Rumely', 'state_id' => 23],
                ['name' => 'Grand Marais', 'state_id' => 23],
                ['name' => 'Munising', 'state_id' => 23],
                ['name' => 'Shingleton', 'state_id' => 23],
                ['name' => 'Trenary', 'state_id' => 23],
                ['name' => 'Wetmore', 'state_id' => 23],
                ['name' => 'Allegan', 'state_id' => 23],
                ['name' => 'Martin', 'state_id' => 23],
                ['name' => 'Otsego', 'state_id' => 23],
                ['name' => 'Plainwell', 'state_id' => 23],
                ['name' => 'Bradley', 'state_id' => 23],
                ['name' => 'Burnips', 'state_id' => 23],
                ['name' => 'Dorr', 'state_id' => 23],
                ['name' => 'Hopkins', 'state_id' => 23],
                ['name' => 'Moline', 'state_id' => 23],
                ['name' => 'Shelbyville', 'state_id' => 23],
                ['name' => 'Wayland', 'state_id' => 23],
                ['name' => 'Douglas', 'state_id' => 23],
                ['name' => 'Fennville', 'state_id' => 23],
                ['name' => 'Glenn', 'state_id' => 23],
                ['name' => 'Hamilton', 'state_id' => 23],
                ['name' => 'Pullman', 'state_id' => 23],
                ['name' => 'Saugatuck', 'state_id' => 23],
                ['name' => 'Alpena', 'state_id' => 23],
                ['name' => 'Herron', 'state_id' => 23],
                ['name' => 'Hubbard Lake', 'state_id' => 23],
                ['name' => 'Lachine', 'state_id' => 23],
                ['name' => 'Ossineke', 'state_id' => 23],
                ['name' => 'Alba', 'state_id' => 23],
                ['name' => 'Alden', 'state_id' => 23],
                ['name' => 'Bellaire', 'state_id' => 23],
                ['name' => 'Central Lake', 'state_id' => 23],
                ['name' => 'Eastport', 'state_id' => 23],
                ['name' => 'Elk Rapids', 'state_id' => 23],
                ['name' => 'Kewadin', 'state_id' => 23],
                ['name' => 'Mancelona', 'state_id' => 23],
                ['name' => 'Ellsworth', 'state_id' => 23],
                ['name' => 'Standish', 'state_id' => 23],
                ['name' => 'Sterling', 'state_id' => 23],
                ['name' => 'Au Gres', 'state_id' => 23],
                ['name' => 'Omer', 'state_id' => 23],
                ['name' => 'Turner', 'state_id' => 23],
                ['name' => 'Twining', 'state_id' => 23],
                ['name' => 'Baraga', 'state_id' => 23],
                ['name' => 'Covington', 'state_id' => 23],
                ['name' => 'Lanse', 'state_id' => 23],
                ['name' => 'Skanee', 'state_id' => 23],
                ['name' => 'Watton', 'state_id' => 23],
                ['name' => 'Woodland', 'state_id' => 23],
                ['name' => 'Cloverdale', 'state_id' => 23],
                ['name' => 'Delton', 'state_id' => 23],
                ['name' => 'Dowling', 'state_id' => 23],
                ['name' => 'Hastings', 'state_id' => 23],
                ['name' => 'Hickory Corners', 'state_id' => 23],
                ['name' => 'Nashville', 'state_id' => 23],
                ['name' => 'Freeport', 'state_id' => 23],
                ['name' => 'Middleville', 'state_id' => 23],
                ['name' => 'Auburn', 'state_id' => 23],
                ['name' => 'Bentley', 'state_id' => 23],
                ['name' => 'Kawkawlin', 'state_id' => 23],
                ['name' => 'Linwood', 'state_id' => 23],
                ['name' => 'Pinconning', 'state_id' => 23],
                ['name' => 'Bay City', 'state_id' => 23],
                ['name' => 'University Center', 'state_id' => 23],
                ['name' => 'Essexville', 'state_id' => 23],
                ['name' => 'Munger', 'state_id' => 23],
                ['name' => 'Benzonia', 'state_id' => 23],
                ['name' => 'Beulah', 'state_id' => 23],
                ['name' => 'Elberta', 'state_id' => 23],
                ['name' => 'Frankfort', 'state_id' => 23],
                ['name' => 'Honor', 'state_id' => 23],
                ['name' => 'Lake Ann', 'state_id' => 23],
                ['name' => 'Thompsonville', 'state_id' => 23],
                ['name' => 'Benton Harbor', 'state_id' => 23],
                ['name' => 'Coloma', 'state_id' => 23],
                ['name' => 'Hagar Shores', 'state_id' => 23],
                ['name' => 'Riverside', 'state_id' => 23],
                ['name' => 'Saint Joseph', 'state_id' => 23],
                ['name' => 'Watervliet', 'state_id' => 23],
                ['name' => 'Baroda', 'state_id' => 23],
                ['name' => 'Berrien Center', 'state_id' => 23],
                ['name' => 'Berrien Springs', 'state_id' => 23],
                ['name' => 'Bridgman', 'state_id' => 23],
                ['name' => 'Buchanan', 'state_id' => 23],
                ['name' => 'Eau Claire', 'state_id' => 23],
                ['name' => 'Galien', 'state_id' => 23],
                ['name' => 'Harbert', 'state_id' => 23],
                ['name' => 'Lakeside', 'state_id' => 23],
                ['name' => 'New Buffalo', 'state_id' => 23],
                ['name' => 'New Troy', 'state_id' => 23],
                ['name' => 'Niles', 'state_id' => 23],
                ['name' => 'Sawyer', 'state_id' => 23],
                ['name' => 'Sodus', 'state_id' => 23],
                ['name' => 'Stevensville', 'state_id' => 23],
                ['name' => 'Three Oaks', 'state_id' => 23],
                ['name' => 'Union Pier', 'state_id' => 23],
                ['name' => 'Bronson', 'state_id' => 23],
                ['name' => 'Coldwater', 'state_id' => 23],
                ['name' => 'Quincy', 'state_id' => 23],
                ['name' => 'Sherwood', 'state_id' => 23],
                ['name' => 'Union City', 'state_id' => 23],
                ['name' => 'Montgomery', 'state_id' => 23],
                ['name' => 'Athens', 'state_id' => 23],
                ['name' => 'Battle Creek', 'state_id' => 23],
                ['name' => 'Bedford', 'state_id' => 23],
                ['name' => 'Burlington', 'state_id' => 23],
                ['name' => 'Ceresco', 'state_id' => 23],
                ['name' => 'East Leroy', 'state_id' => 23],
                ['name' => 'Marshall', 'state_id' => 23],
                ['name' => 'Tekonsha', 'state_id' => 23],
                ['name' => 'Albion', 'state_id' => 23],
                ['name' => 'Homer', 'state_id' => 23],
                ['name' => 'Cassopolis', 'state_id' => 23],
                ['name' => 'Dowagiac', 'state_id' => 23],
                ['name' => 'Jones', 'state_id' => 23],
                ['name' => 'Marcellus', 'state_id' => 23],
                ['name' => 'Vandalia', 'state_id' => 23],
                ['name' => 'Edwardsburg', 'state_id' => 23],
                ['name' => 'Union', 'state_id' => 23],
                ['name' => 'Bay Shore', 'state_id' => 23],
                ['name' => 'Boyne City', 'state_id' => 23],
                ['name' => 'Boyne Falls', 'state_id' => 23],
                ['name' => 'Charlevoix', 'state_id' => 23],
                ['name' => 'East Jordan', 'state_id' => 23],
                ['name' => 'Beaver Island', 'state_id' => 23],
                ['name' => 'Walloon Lake', 'state_id' => 23],
                ['name' => 'Mackinaw City', 'state_id' => 23],
                ['name' => 'Afton', 'state_id' => 23],
                ['name' => 'Brutus', 'state_id' => 23],
                ['name' => 'Burt Lake', 'state_id' => 23],
                ['name' => 'Cheboygan', 'state_id' => 23],
                ['name' => 'Indian River', 'state_id' => 23],
                ['name' => 'Mullett Lake', 'state_id' => 23],
                ['name' => 'Topinabee', 'state_id' => 23],
                ['name' => 'Tower', 'state_id' => 23],
                ['name' => 'Wolverine', 'state_id' => 23],
                ['name' => 'Barbeau', 'state_id' => 23],
                ['name' => 'Brimley', 'state_id' => 23],
                ['name' => 'Dafter', 'state_id' => 23],
                ['name' => 'De Tour Village', 'state_id' => 23],
                ['name' => 'Drummond Island', 'state_id' => 23],
                ['name' => 'Eckerman', 'state_id' => 23],
                ['name' => 'Goetzville', 'state_id' => 23],
                ['name' => 'Hulbert', 'state_id' => 23],
                ['name' => 'Kinross', 'state_id' => 23],
                ['name' => 'Paradise', 'state_id' => 23],
                ['name' => 'Pickford', 'state_id' => 23],
                ['name' => 'Rudyard', 'state_id' => 23],
                ['name' => 'Sault Sainte Marie', 'state_id' => 23],
                ['name' => 'Kincheloe', 'state_id' => 23],
                ['name' => 'Trout Lake', 'state_id' => 23],
                ['name' => 'Clare', 'state_id' => 23],
                ['name' => 'Farwell', 'state_id' => 23],
                ['name' => 'Harrison', 'state_id' => 23],
                ['name' => 'Lake', 'state_id' => 23],
                ['name' => 'Lake George', 'state_id' => 23],
                ['name' => 'Bath', 'state_id' => 23],
                ['name' => 'Dewitt', 'state_id' => 23],
                ['name' => 'Eagle', 'state_id' => 23],
                ['name' => 'Elsie', 'state_id' => 23],
                ['name' => 'Eureka', 'state_id' => 23],
                ['name' => 'Fowler', 'state_id' => 23],
                ['name' => 'Maple Rapids', 'state_id' => 23],
                ['name' => 'Ovid', 'state_id' => 23],
                ['name' => 'Saint Johns', 'state_id' => 23],
                ['name' => 'Westphalia', 'state_id' => 23],
                ['name' => 'Frederic', 'state_id' => 23],
                ['name' => 'Grayling', 'state_id' => 23],
                ['name' => 'Bark River', 'state_id' => 23],
                ['name' => 'Cornell', 'state_id' => 23],
                ['name' => 'Escanaba', 'state_id' => 23],
                ['name' => 'Garden', 'state_id' => 23],
                ['name' => 'Gladstone', 'state_id' => 23],
                ['name' => 'Nahma', 'state_id' => 23],
                ['name' => 'Perkins', 'state_id' => 23],
                ['name' => 'Rapid River', 'state_id' => 23],
                ['name' => 'Rock', 'state_id' => 23],
                ['name' => 'Wells', 'state_id' => 23],
                ['name' => 'Iron Mountain', 'state_id' => 23],
                ['name' => 'Kingsford', 'state_id' => 23],
                ['name' => 'Channing', 'state_id' => 23],
                ['name' => 'Felch', 'state_id' => 23],
                ['name' => 'Foster City', 'state_id' => 23],
                ['name' => 'Loretto', 'state_id' => 23],
                ['name' => 'Norway', 'state_id' => 23],
                ['name' => 'Quinnesec', 'state_id' => 23],
                ['name' => 'Ralph', 'state_id' => 23],
                ['name' => 'Sagola', 'state_id' => 23],
                ['name' => 'Vulcan', 'state_id' => 23],
                ['name' => 'Charlotte', 'state_id' => 23],
                ['name' => 'Dimondale', 'state_id' => 23],
                ['name' => 'Eaton Rapids', 'state_id' => 23],
                ['name' => 'Grand Ledge', 'state_id' => 23],
                ['name' => 'Mulliken', 'state_id' => 23],
                ['name' => 'Potterville', 'state_id' => 23],
                ['name' => 'Sunfield', 'state_id' => 23],
                ['name' => 'Lansing', 'state_id' => 23],
                ['name' => 'Bellevue', 'state_id' => 23],
                ['name' => 'Olivet', 'state_id' => 23],
                ['name' => 'Vermontville', 'state_id' => 23],
                ['name' => 'Alanson', 'state_id' => 23],
                ['name' => 'Carp Lake', 'state_id' => 23],
                ['name' => 'Conway', 'state_id' => 23],
                ['name' => 'Cross Village', 'state_id' => 23],
                ['name' => 'Good Hart', 'state_id' => 23],
                ['name' => 'Harbor Springs', 'state_id' => 23],
                ['name' => 'Levering', 'state_id' => 23],
                ['name' => 'Oden', 'state_id' => 23],
                ['name' => 'Pellston', 'state_id' => 23],
                ['name' => 'Petoskey', 'state_id' => 23],
                ['name' => 'Atlas', 'state_id' => 23],
                ['name' => 'Clio', 'state_id' => 23],
                ['name' => 'Davison', 'state_id' => 23],
                ['name' => 'Fenton', 'state_id' => 23],
                ['name' => 'Flushing', 'state_id' => 23],
                ['name' => 'Gaines', 'state_id' => 23],
                ['name' => 'Genesee', 'state_id' => 23],
                ['name' => 'Goodrich', 'state_id' => 23],
                ['name' => 'Grand Blanc', 'state_id' => 23],
                ['name' => 'Lennon', 'state_id' => 23],
                ['name' => 'Linden', 'state_id' => 23],
                ['name' => 'Montrose', 'state_id' => 23],
                ['name' => 'Mount Morris', 'state_id' => 23],
                ['name' => 'Otisville', 'state_id' => 23],
                ['name' => 'Swartz Creek', 'state_id' => 23],
                ['name' => 'Flint', 'state_id' => 23],
                ['name' => 'Burton', 'state_id' => 23],
                ['name' => 'Beaverton', 'state_id' => 23],
                ['name' => 'Gladwin', 'state_id' => 23],
                ['name' => 'Saginaw', 'state_id' => 23],
                ['name' => 'Rhodes', 'state_id' => 23],
                ['name' => 'Bessemer', 'state_id' => 23],
                ['name' => 'Ironwood', 'state_id' => 23],
                ['name' => 'Marenisco', 'state_id' => 23],
                ['name' => 'Ramsay', 'state_id' => 23],
                ['name' => 'Wakefield', 'state_id' => 23],
                ['name' => 'Watersmeet', 'state_id' => 23],
                ['name' => 'Acme', 'state_id' => 23],
                ['name' => 'Fife Lake', 'state_id' => 23],
                ['name' => 'Grawn', 'state_id' => 23],
                ['name' => 'Interlochen', 'state_id' => 23],
                ['name' => 'Kingsley', 'state_id' => 23],
                ['name' => 'Mayfield', 'state_id' => 23],
                ['name' => 'Old Mission', 'state_id' => 23],
                ['name' => 'Traverse City', 'state_id' => 23],
                ['name' => 'Williamsburg', 'state_id' => 23],
                ['name' => 'Breckenridge', 'state_id' => 23],
                ['name' => 'Wheeler', 'state_id' => 23],
                ['name' => 'Alma', 'state_id' => 23],
                ['name' => 'Ashley', 'state_id' => 23],
                ['name' => 'Bannister', 'state_id' => 23],
                ['name' => 'Elm Hall', 'state_id' => 23],
                ['name' => 'Elwell', 'state_id' => 23],
                ['name' => 'Ithaca', 'state_id' => 23],
                ['name' => 'Middleton', 'state_id' => 23],
                ['name' => 'North Star', 'state_id' => 23],
                ['name' => 'Perrinton', 'state_id' => 23],
                ['name' => 'Pompeii', 'state_id' => 23],
                ['name' => 'Riverdale', 'state_id' => 23],
                ['name' => 'Saint Louis', 'state_id' => 23],
                ['name' => 'Sumner', 'state_id' => 23],
                ['name' => 'Allen', 'state_id' => 23],
                ['name' => 'Camden', 'state_id' => 23],
                ['name' => 'Frontier', 'state_id' => 23],
                ['name' => 'Hillsdale', 'state_id' => 23],
                ['name' => 'Jerome', 'state_id' => 23],
                ['name' => 'Jonesville', 'state_id' => 23],
                ['name' => 'Litchfield', 'state_id' => 23],
                ['name' => 'Moscow', 'state_id' => 23],
                ['name' => 'Mosherville', 'state_id' => 23],
                ['name' => 'North Adams', 'state_id' => 23],
                ['name' => 'Osseo', 'state_id' => 23],
                ['name' => 'Pittsford', 'state_id' => 23],
                ['name' => 'Reading', 'state_id' => 23],
                ['name' => 'Somerset', 'state_id' => 23],
                ['name' => 'Somerset Center', 'state_id' => 23],
                ['name' => 'Waldron', 'state_id' => 23],
                ['name' => 'Atlantic Mine', 'state_id' => 23],
                ['name' => 'Calumet', 'state_id' => 23],
                ['name' => 'Chassell', 'state_id' => 23],
                ['name' => 'Copper City', 'state_id' => 23],
                ['name' => 'Dodgeville', 'state_id' => 23],
                ['name' => 'Dollar Bay', 'state_id' => 23],
                ['name' => 'Hancock', 'state_id' => 23],
                ['name' => 'Houghton', 'state_id' => 23],
                ['name' => 'Hubbell', 'state_id' => 23],
                ['name' => 'Kearsarge', 'state_id' => 23],
                ['name' => 'Lake Linden', 'state_id' => 23],
                ['name' => 'Nisula', 'state_id' => 23],
                ['name' => 'Painesdale', 'state_id' => 23],
                ['name' => 'Pelkie', 'state_id' => 23],
                ['name' => 'Sidnaw', 'state_id' => 23],
                ['name' => 'South Range', 'state_id' => 23],
                ['name' => 'Toivola', 'state_id' => 23],
                ['name' => 'Bad Axe', 'state_id' => 23],
                ['name' => 'Filion', 'state_id' => 23],
                ['name' => 'Harbor Beach', 'state_id' => 23],
                ['name' => 'Kinde', 'state_id' => 23],
                ['name' => 'Port Austin', 'state_id' => 23],
                ['name' => 'Port Hope', 'state_id' => 23],
                ['name' => 'Ruth', 'state_id' => 23],
                ['name' => 'Ubly', 'state_id' => 23],
                ['name' => 'Bay Port', 'state_id' => 23],
                ['name' => 'Caseville', 'state_id' => 23],
                ['name' => 'Elkton', 'state_id' => 23],
                ['name' => 'Owendale', 'state_id' => 23],
                ['name' => 'Pigeon', 'state_id' => 23],
                ['name' => 'Sebewaing', 'state_id' => 23],
                ['name' => 'Okemos', 'state_id' => 23],
                ['name' => 'Dansville', 'state_id' => 23],
                ['name' => 'East Lansing', 'state_id' => 23],
                ['name' => 'Haslett', 'state_id' => 23],
                ['name' => 'Holt', 'state_id' => 23],
                ['name' => 'Mason', 'state_id' => 23],
                ['name' => 'Webberville', 'state_id' => 23],
                ['name' => 'Williamston', 'state_id' => 23],
                ['name' => 'Leslie', 'state_id' => 23],
                ['name' => 'Onondaga', 'state_id' => 23],
                ['name' => 'Stockbridge', 'state_id' => 23],
                ['name' => 'Belding', 'state_id' => 23],
                ['name' => 'Clarksville', 'state_id' => 23],
                ['name' => 'Hubbardston', 'state_id' => 23],
                ['name' => 'Ionia', 'state_id' => 23],
                ['name' => 'Lake Odessa', 'state_id' => 23],
                ['name' => 'Lyons', 'state_id' => 23],
                ['name' => 'Muir', 'state_id' => 23],
                ['name' => 'Orleans', 'state_id' => 23],
                ['name' => 'Palo', 'state_id' => 23],
                ['name' => 'Pewamo', 'state_id' => 23],
                ['name' => 'Portland', 'state_id' => 23],
                ['name' => 'Saranac', 'state_id' => 23],
                ['name' => 'Smyrna', 'state_id' => 23],
                ['name' => 'East Tawas', 'state_id' => 23],
                ['name' => 'Hale', 'state_id' => 23],
                ['name' => 'Long Lake', 'state_id' => 23],
                ['name' => 'National City', 'state_id' => 23],
                ['name' => 'Oscoda', 'state_id' => 23],
                ['name' => 'Tawas City', 'state_id' => 23],
                ['name' => 'Whittemore', 'state_id' => 23],
                ['name' => 'Alpha', 'state_id' => 23],
                ['name' => 'Amasa', 'state_id' => 23],
                ['name' => 'Caspian', 'state_id' => 23],
                ['name' => 'Crystal Falls', 'state_id' => 23],
                ['name' => 'Gaastra', 'state_id' => 23],
                ['name' => 'Iron River', 'state_id' => 23],
                ['name' => 'Stambaugh', 'state_id' => 23],
                ['name' => 'Mount Pleasant', 'state_id' => 23],
                ['name' => 'Rosebush', 'state_id' => 23],
                ['name' => 'Shepherd', 'state_id' => 23],
                ['name' => 'Weidman', 'state_id' => 23],
                ['name' => 'Winn', 'state_id' => 23],
                ['name' => 'Blanchard', 'state_id' => 23],
                ['name' => 'Jackson', 'state_id' => 23],
                ['name' => 'Brooklyn', 'state_id' => 23],
                ['name' => 'Clarklake', 'state_id' => 23],
                ['name' => 'Concord', 'state_id' => 23],
                ['name' => 'Grass Lake', 'state_id' => 23],
                ['name' => 'Hanover', 'state_id' => 23],
                ['name' => 'Horton', 'state_id' => 23],
                ['name' => 'Michigan Center', 'state_id' => 23],
                ['name' => 'Munith', 'state_id' => 23],
                ['name' => 'Napoleon', 'state_id' => 23],
                ['name' => 'Norvell', 'state_id' => 23],
                ['name' => 'Parma', 'state_id' => 23],
                ['name' => 'Pleasant Lake', 'state_id' => 23],
                ['name' => 'Rives Junction', 'state_id' => 23],
                ['name' => 'Spring Arbor', 'state_id' => 23],
                ['name' => 'Springport', 'state_id' => 23],
                ['name' => 'Kalamazoo', 'state_id' => 23],
                ['name' => 'Portage', 'state_id' => 23],
                ['name' => 'Augusta', 'state_id' => 23],
                ['name' => 'Climax', 'state_id' => 23],
                ['name' => 'Comstock', 'state_id' => 23],
                ['name' => 'Fulton', 'state_id' => 23],
                ['name' => 'Galesburg', 'state_id' => 23],
                ['name' => 'Nazareth', 'state_id' => 23],
                ['name' => 'Oshtemo', 'state_id' => 23],
                ['name' => 'Richland', 'state_id' => 23],
                ['name' => 'Schoolcraft', 'state_id' => 23],
                ['name' => 'Scotts', 'state_id' => 23],
                ['name' => 'Vicksburg', 'state_id' => 23],
                ['name' => 'Kalkaska', 'state_id' => 23],
                ['name' => 'Rapid City', 'state_id' => 23],
                ['name' => 'South Boardman', 'state_id' => 23],
                ['name' => 'Ada', 'state_id' => 23],
                ['name' => 'Alto', 'state_id' => 23],
                ['name' => 'Belmont', 'state_id' => 23],
                ['name' => 'Byron Center', 'state_id' => 23],
                ['name' => 'Caledonia', 'state_id' => 23],
                ['name' => 'Cannonsburg', 'state_id' => 23],
                ['name' => 'Cedar Springs', 'state_id' => 23],
                ['name' => 'Comstock Park', 'state_id' => 23],
                ['name' => 'Kent City', 'state_id' => 23],
                ['name' => 'Lowell', 'state_id' => 23],
                ['name' => 'Rockford', 'state_id' => 23],
                ['name' => 'Sand Lake', 'state_id' => 23],
                ['name' => 'Sparta', 'state_id' => 23],
                ['name' => 'Grandville', 'state_id' => 23],
                ['name' => 'Grand Rapids', 'state_id' => 23],
                ['name' => 'Wyoming', 'state_id' => 23],
                ['name' => 'Allouez', 'state_id' => 23],
                ['name' => 'Ahmeek', 'state_id' => 23],
                ['name' => 'Copper Harbor', 'state_id' => 23],
                ['name' => 'Mohawk', 'state_id' => 23],
                ['name' => 'Baldwin', 'state_id' => 23],
                ['name' => 'Branch', 'state_id' => 23],
                ['name' => 'Chase', 'state_id' => 23],
                ['name' => 'Idlewild', 'state_id' => 23],
                ['name' => 'Irons', 'state_id' => 23],
                ['name' => 'Luther', 'state_id' => 23],
                ['name' => 'Almont', 'state_id' => 23],
                ['name' => 'Attica', 'state_id' => 23],
                ['name' => 'Columbiaville', 'state_id' => 23],
                ['name' => 'Dryden', 'state_id' => 23],
                ['name' => 'Hadley', 'state_id' => 23],
                ['name' => 'Imlay City', 'state_id' => 23],
                ['name' => 'Lapeer', 'state_id' => 23],
                ['name' => 'Metamora', 'state_id' => 23],
                ['name' => 'North Branch', 'state_id' => 23],
                ['name' => 'Otter Lake', 'state_id' => 23],
                ['name' => 'Clifford', 'state_id' => 23],
                ['name' => 'Silverwood', 'state_id' => 23],
                ['name' => 'Cedar', 'state_id' => 23],
                ['name' => 'Empire', 'state_id' => 23],
                ['name' => 'Glen Arbor', 'state_id' => 23],
                ['name' => 'Lake Leelanau', 'state_id' => 23],
                ['name' => 'Leland', 'state_id' => 23],
                ['name' => 'Maple City', 'state_id' => 23],
                ['name' => 'Northport', 'state_id' => 23],
                ['name' => 'Omena', 'state_id' => 23],
                ['name' => 'Suttons Bay', 'state_id' => 23],
                ['name' => 'Addison', 'state_id' => 23],
                ['name' => 'Adrian', 'state_id' => 23],
                ['name' => 'Blissfield', 'state_id' => 23],
                ['name' => 'Britton', 'state_id' => 23],
                ['name' => 'Cement City', 'state_id' => 23],
                ['name' => 'Clayton', 'state_id' => 23],
                ['name' => 'Clinton', 'state_id' => 23],
                ['name' => 'Deerfield', 'state_id' => 23],
                ['name' => 'Hudson', 'state_id' => 23],
                ['name' => 'Jasper', 'state_id' => 23],
                ['name' => 'Manitou Beach', 'state_id' => 23],
                ['name' => 'Morenci', 'state_id' => 23],
                ['name' => 'Onsted', 'state_id' => 23],
                ['name' => 'Palmyra', 'state_id' => 23],
                ['name' => 'Riga', 'state_id' => 23],
                ['name' => 'Sand Creek', 'state_id' => 23],
                ['name' => 'Tecumseh', 'state_id' => 23],
                ['name' => 'Tipton', 'state_id' => 23],
                ['name' => 'Weston', 'state_id' => 23],
                ['name' => 'Brighton', 'state_id' => 23],
                ['name' => 'Gregory', 'state_id' => 23],
                ['name' => 'Hamburg', 'state_id' => 23],
                ['name' => 'Lakeland', 'state_id' => 23],
                ['name' => 'Pinckney', 'state_id' => 23],
                ['name' => 'Hartland', 'state_id' => 23],
                ['name' => 'Cohoctah', 'state_id' => 23],
                ['name' => 'Fowlerville', 'state_id' => 23],
                ['name' => 'Howell', 'state_id' => 23],
                ['name' => 'Mc Millan', 'state_id' => 23],
                ['name' => 'Newberry', 'state_id' => 23],
                ['name' => 'Cedarville', 'state_id' => 23],
                ['name' => 'Hessel', 'state_id' => 23],
                ['name' => 'Mackinac Island', 'state_id' => 23],
                ['name' => 'Moran', 'state_id' => 23],
                ['name' => 'Naubinway', 'state_id' => 23],
                ['name' => 'Pointe Aux Pins', 'state_id' => 23],
                ['name' => 'Saint Ignace', 'state_id' => 23],
                ['name' => 'Curtis', 'state_id' => 23],
                ['name' => 'Engadine', 'state_id' => 23],
                ['name' => 'Gould City', 'state_id' => 23],
                ['name' => 'Armada', 'state_id' => 23],
                ['name' => 'Center Line', 'state_id' => 23],
                ['name' => 'Eastpointe', 'state_id' => 23],
                ['name' => 'Fraser', 'state_id' => 23],
                ['name' => 'Clinton Township', 'state_id' => 23],
                ['name' => 'Macomb', 'state_id' => 23],
                ['name' => 'Mount Clemens', 'state_id' => 23],
                ['name' => 'Harrison Township', 'state_id' => 23],
                ['name' => 'New Baltimore', 'state_id' => 23],
                ['name' => 'New Haven', 'state_id' => 23],
                ['name' => 'Richmond', 'state_id' => 23],
                ['name' => 'Romeo', 'state_id' => 23],
                ['name' => 'Roseville', 'state_id' => 23],
                ['name' => 'Saint Clair Shores', 'state_id' => 23],
                ['name' => 'Warren', 'state_id' => 23],
                ['name' => 'Washington', 'state_id' => 23],
                ['name' => 'Ray', 'state_id' => 23],
                ['name' => 'Sterling Heights', 'state_id' => 23],
                ['name' => 'Utica', 'state_id' => 23],
                ['name' => 'Arcadia', 'state_id' => 23],
                ['name' => 'Bear Lake', 'state_id' => 23],
                ['name' => 'Brethren', 'state_id' => 23],
                ['name' => 'Copemish', 'state_id' => 23],
                ['name' => 'Eastlake', 'state_id' => 23],
                ['name' => 'Filer City', 'state_id' => 23],
                ['name' => 'Kaleva', 'state_id' => 23],
                ['name' => 'Manistee', 'state_id' => 23],
                ['name' => 'Onekama', 'state_id' => 23],
                ['name' => 'Wellston', 'state_id' => 23],
                ['name' => 'Big Bay', 'state_id' => 23],
                ['name' => 'Champion', 'state_id' => 23],
                ['name' => 'Arnold', 'state_id' => 23],
                ['name' => 'Little Lake', 'state_id' => 23],
                ['name' => 'Gwinn', 'state_id' => 23],
                ['name' => 'Ishpeming', 'state_id' => 23],
                ['name' => 'Marquette', 'state_id' => 23],
                ['name' => 'Michigamme', 'state_id' => 23],
                ['name' => 'National Mine', 'state_id' => 23],
                ['name' => 'Negaunee', 'state_id' => 23],
                ['name' => 'Palmer', 'state_id' => 23],
                ['name' => 'Republic', 'state_id' => 23],
                ['name' => 'Skandia', 'state_id' => 23],
                ['name' => 'Custer', 'state_id' => 23],
                ['name' => 'Fountain', 'state_id' => 23],
                ['name' => 'Free Soil', 'state_id' => 23],
                ['name' => 'Ludington', 'state_id' => 23],
                ['name' => 'Scottville', 'state_id' => 23],
                ['name' => 'Walhalla', 'state_id' => 23],
                ['name' => 'Barryton', 'state_id' => 23],
                ['name' => 'Big Rapids', 'state_id' => 23],
                ['name' => 'Chippewa Lake', 'state_id' => 23],
                ['name' => 'Mecosta', 'state_id' => 23],
                ['name' => 'Morley', 'state_id' => 23],
                ['name' => 'Paris', 'state_id' => 23],
                ['name' => 'Remus', 'state_id' => 23],
                ['name' => 'Rodney', 'state_id' => 23],
                ['name' => 'Stanwood', 'state_id' => 23],
                ['name' => 'Carney', 'state_id' => 23],
                ['name' => 'Daggett', 'state_id' => 23],
                ['name' => 'Harris', 'state_id' => 23],
                ['name' => 'Hermansville', 'state_id' => 23],
                ['name' => 'Ingalls', 'state_id' => 23],
                ['name' => 'Menominee', 'state_id' => 23],
                ['name' => 'Nadeau', 'state_id' => 23],
                ['name' => 'Perronville', 'state_id' => 23],
                ['name' => 'Powers', 'state_id' => 23],
                ['name' => 'Spalding', 'state_id' => 23],
                ['name' => 'Stephenson', 'state_id' => 23],
                ['name' => 'Wallace', 'state_id' => 23],
                ['name' => 'Wilson', 'state_id' => 23],
                ['name' => 'Coleman', 'state_id' => 23],
                ['name' => 'Edenville', 'state_id' => 23],
                ['name' => 'Hope', 'state_id' => 23],
                ['name' => 'Midland', 'state_id' => 23],
                ['name' => 'Sanford', 'state_id' => 23],
                ['name' => 'Falmouth', 'state_id' => 23],
                ['name' => 'Lake City', 'state_id' => 23],
                ['name' => 'Mc Bain', 'state_id' => 23],
                ['name' => 'Merritt', 'state_id' => 23],
                ['name' => 'Azalia', 'state_id' => 23],
                ['name' => 'Carleton', 'state_id' => 23],
                ['name' => 'Dundee', 'state_id' => 23],
                ['name' => 'Erie', 'state_id' => 23],
                ['name' => 'Ida', 'state_id' => 23],
                ['name' => 'Lambertville', 'state_id' => 23],
                ['name' => 'La Salle', 'state_id' => 23],
                ['name' => 'Luna Pier', 'state_id' => 23],
                ['name' => 'Maybee', 'state_id' => 23],
                ['name' => 'Milan', 'state_id' => 23],
                ['name' => 'Monroe', 'state_id' => 23],
                ['name' => 'Newport', 'state_id' => 23],
                ['name' => 'Samaria', 'state_id' => 23],
                ['name' => 'South Rockwood', 'state_id' => 23],
                ['name' => 'Temperance', 'state_id' => 23],
                ['name' => 'Ottawa Lake', 'state_id' => 23],
                ['name' => 'Petersburg', 'state_id' => 23],
                ['name' => 'Carson City', 'state_id' => 23],
                ['name' => 'Cedar Lake', 'state_id' => 23],
                ['name' => 'Crystal', 'state_id' => 23],
                ['name' => 'Edmore', 'state_id' => 23],
                ['name' => 'Fenwick', 'state_id' => 23],
                ['name' => 'Greenville', 'state_id' => 23],
                ['name' => 'Lakeview', 'state_id' => 23],
                ['name' => 'Mcbrides', 'state_id' => 23],
                ['name' => 'Sheridan', 'state_id' => 23],
                ['name' => 'Sidney', 'state_id' => 23],
                ['name' => 'Six Lakes', 'state_id' => 23],
                ['name' => 'Stanton', 'state_id' => 23],
                ['name' => 'Vestaburg', 'state_id' => 23],
                ['name' => 'Coral', 'state_id' => 23],
                ['name' => 'Gowen', 'state_id' => 23],
                ['name' => 'Howard City', 'state_id' => 23],
                ['name' => 'Pierson', 'state_id' => 23],
                ['name' => 'Trufant', 'state_id' => 23],
                ['name' => 'Atlanta', 'state_id' => 23],
                ['name' => 'Hillman', 'state_id' => 23],
                ['name' => 'Lewiston', 'state_id' => 23],
                ['name' => 'Bailey', 'state_id' => 23],
                ['name' => 'Casnovia', 'state_id' => 23],
                ['name' => 'Fruitport', 'state_id' => 23],
                ['name' => 'Holton', 'state_id' => 23],
                ['name' => 'Montague', 'state_id' => 23],
                ['name' => 'Muskegon', 'state_id' => 23],
                ['name' => 'Ravenna', 'state_id' => 23],
                ['name' => 'Twin Lake', 'state_id' => 23],
                ['name' => 'Whitehall', 'state_id' => 23],
                ['name' => 'Sylvan Beach', 'state_id' => 23],
                ['name' => 'Bitely', 'state_id' => 23],
                ['name' => 'Brohman', 'state_id' => 23],
                ['name' => 'Grant', 'state_id' => 23],
                ['name' => 'Newaygo', 'state_id' => 23],
                ['name' => 'White Cloud', 'state_id' => 23],
                ['name' => 'Fremont', 'state_id' => 23],
                ['name' => 'Troy', 'state_id' => 23],
                ['name' => 'Birmingham', 'state_id' => 23],
                ['name' => 'Clawson', 'state_id' => 23],
                ['name' => 'Franklin', 'state_id' => 23],
                ['name' => 'Hazel Park', 'state_id' => 23],
                ['name' => 'Southfield', 'state_id' => 23],
                ['name' => 'Royal Oak', 'state_id' => 23],
                ['name' => 'Pleasant Ridge', 'state_id' => 23],
                ['name' => 'Huntington Woods', 'state_id' => 23],
                ['name' => 'Madison Heights', 'state_id' => 23],
                ['name' => 'Berkley', 'state_id' => 23],
                ['name' => 'New Hudson', 'state_id' => 23],
                ['name' => 'South Lyon', 'state_id' => 23],
                ['name' => 'Ferndale', 'state_id' => 23],
                ['name' => 'Oak Park', 'state_id' => 23],
                ['name' => 'Bloomfield Hills', 'state_id' => 23],
                ['name' => 'Rochester', 'state_id' => 23],
                ['name' => 'Keego Harbor', 'state_id' => 23],
                ['name' => 'Auburn Hills', 'state_id' => 23],
                ['name' => 'West Bloomfield', 'state_id' => 23],
                ['name' => 'Waterford', 'state_id' => 23],
                ['name' => 'Drayton Plains', 'state_id' => 23],
                ['name' => 'Farmington', 'state_id' => 23],
                ['name' => 'Pontiac', 'state_id' => 23],
                ['name' => 'Clarkston', 'state_id' => 23],
                ['name' => 'Davisburg', 'state_id' => 23],
                ['name' => 'Highland', 'state_id' => 23],
                ['name' => 'Lake Orion', 'state_id' => 23],
                ['name' => 'Oakland', 'state_id' => 23],
                ['name' => 'Lakeville', 'state_id' => 23],
                ['name' => 'Leonard', 'state_id' => 23],
                ['name' => 'Oxford', 'state_id' => 23],
                ['name' => 'Novi', 'state_id' => 23],
                ['name' => 'Milford', 'state_id' => 23],
                ['name' => 'Commerce Township', 'state_id' => 23],
                ['name' => 'White Lake', 'state_id' => 23],
                ['name' => 'Union Lake', 'state_id' => 23],
                ['name' => 'Walled Lake', 'state_id' => 23],
                ['name' => 'Wixom', 'state_id' => 23],
                ['name' => 'Holly', 'state_id' => 23],
                ['name' => 'Ortonville', 'state_id' => 23],
                ['name' => 'Hart', 'state_id' => 23],
                ['name' => 'Hesperia', 'state_id' => 23],
                ['name' => 'Mears', 'state_id' => 23],
                ['name' => 'New Era', 'state_id' => 23],
                ['name' => 'Pentwater', 'state_id' => 23],
                ['name' => 'Rothbury', 'state_id' => 23],
                ['name' => 'Shelby', 'state_id' => 23],
                ['name' => 'Walkerville', 'state_id' => 23],
                ['name' => 'Alger', 'state_id' => 23],
                ['name' => 'Lupton', 'state_id' => 23],
                ['name' => 'Rose City', 'state_id' => 23],
                ['name' => 'West Branch', 'state_id' => 23],
                ['name' => 'Prescott', 'state_id' => 23],
                ['name' => 'South Branch', 'state_id' => 23],
                ['name' => 'Bergland', 'state_id' => 23],
                ['name' => 'Bruce Crossing', 'state_id' => 23],
                ['name' => 'Ewen', 'state_id' => 23],
                ['name' => 'Greenland', 'state_id' => 23],
                ['name' => 'Mass City', 'state_id' => 23],
                ['name' => 'Ontonagon', 'state_id' => 23],
                ['name' => 'Rockland', 'state_id' => 23],
                ['name' => 'Trout Creek', 'state_id' => 23],
                ['name' => 'White Pine', 'state_id' => 23],
                ['name' => 'Evart', 'state_id' => 23],
                ['name' => 'Hersey', 'state_id' => 23],
                ['name' => 'Leroy', 'state_id' => 23],
                ['name' => 'Marion', 'state_id' => 23],
                ['name' => 'Reed City', 'state_id' => 23],
                ['name' => 'Sears', 'state_id' => 23],
                ['name' => 'Tustin', 'state_id' => 23],
                ['name' => 'Comins', 'state_id' => 23],
                ['name' => 'Fairview', 'state_id' => 23],
                ['name' => 'Luzerne', 'state_id' => 23],
                ['name' => 'Mio', 'state_id' => 23],
                ['name' => 'Elmira', 'state_id' => 23],
                ['name' => 'Gaylord', 'state_id' => 23],
                ['name' => 'Johannesburg', 'state_id' => 23],
                ['name' => 'Vanderbilt', 'state_id' => 23],
                ['name' => 'Waters', 'state_id' => 23],
                ['name' => 'Allendale', 'state_id' => 23],
                ['name' => 'Conklin', 'state_id' => 23],
                ['name' => 'Coopersville', 'state_id' => 23],
                ['name' => 'Ferrysburg', 'state_id' => 23],
                ['name' => 'Grand Haven', 'state_id' => 23],
                ['name' => 'Holland', 'state_id' => 23],
                ['name' => 'Hudsonville', 'state_id' => 23],
                ['name' => 'Jamestown', 'state_id' => 23],
                ['name' => 'Jenison', 'state_id' => 23],
                ['name' => 'Lamont', 'state_id' => 23],
                ['name' => 'Macatawa', 'state_id' => 23],
                ['name' => 'Marne', 'state_id' => 23],
                ['name' => 'Nunica', 'state_id' => 23],
                ['name' => 'Spring Lake', 'state_id' => 23],
                ['name' => 'West Olive', 'state_id' => 23],
                ['name' => 'Zeeland', 'state_id' => 23],
                ['name' => 'Hawks', 'state_id' => 23],
                ['name' => 'Millersburg', 'state_id' => 23],
                ['name' => 'Onaway', 'state_id' => 23],
                ['name' => 'Posen', 'state_id' => 23],
                ['name' => 'Presque Isle', 'state_id' => 23],
                ['name' => 'Rogers City', 'state_id' => 23],
                ['name' => 'Higgins Lake', 'state_id' => 23],
                ['name' => 'Houghton Lake', 'state_id' => 23],
                ['name' => 'Houghton Lake Heights', 'state_id' => 23],
                ['name' => 'Prudenville', 'state_id' => 23],
                ['name' => 'Roscommon', 'state_id' => 23],
                ['name' => 'Saint Helen', 'state_id' => 23],
                ['name' => 'Birch Run', 'state_id' => 23],
                ['name' => 'Burt', 'state_id' => 23],
                ['name' => 'Brant', 'state_id' => 23],
                ['name' => 'Chesaning', 'state_id' => 23],
                ['name' => 'Freeland', 'state_id' => 23],
                ['name' => 'Hemlock', 'state_id' => 23],
                ['name' => 'Merrill', 'state_id' => 23],
                ['name' => 'Oakley', 'state_id' => 23],
                ['name' => 'Saint Charles', 'state_id' => 23],
                ['name' => 'Bridgeport', 'state_id' => 23],
                ['name' => 'Carrollton', 'state_id' => 23],
                ['name' => 'Frankenmuth', 'state_id' => 23],
                ['name' => 'Algonac', 'state_id' => 23],
                ['name' => 'Allenton', 'state_id' => 23],
                ['name' => 'Anchorville', 'state_id' => 23],
                ['name' => 'Avoca', 'state_id' => 23],
                ['name' => 'Capac', 'state_id' => 23],
                ['name' => 'Emmett', 'state_id' => 23],
                ['name' => 'Fair Haven', 'state_id' => 23],
                ['name' => 'Goodells', 'state_id' => 23],
                ['name' => 'Harsens Island', 'state_id' => 23],
                ['name' => 'Jeddo', 'state_id' => 23],
                ['name' => 'Marine City', 'state_id' => 23],
                ['name' => 'Marysville', 'state_id' => 23],
                ['name' => 'Memphis', 'state_id' => 23],
                ['name' => 'North Street', 'state_id' => 23],
                ['name' => 'East China', 'state_id' => 23],
                ['name' => 'Fort Gratiot', 'state_id' => 23],
                ['name' => 'Port Huron', 'state_id' => 23],
                ['name' => 'Columbus', 'state_id' => 23],
                ['name' => 'Casco', 'state_id' => 23],
                ['name' => 'Smiths Creek', 'state_id' => 23],
                ['name' => 'Saint Clair', 'state_id' => 23],
                ['name' => 'Yale', 'state_id' => 23],
                ['name' => 'Burr Oak', 'state_id' => 23],
                ['name' => 'Centreville', 'state_id' => 23],
                ['name' => 'Colon', 'state_id' => 23],
                ['name' => 'Constantine', 'state_id' => 23],
                ['name' => 'Leonidas', 'state_id' => 23],
                ['name' => 'Mendon', 'state_id' => 23],
                ['name' => 'Nottawa', 'state_id' => 23],
                ['name' => 'Sturgis', 'state_id' => 23],
                ['name' => 'Three Rivers', 'state_id' => 23],
                ['name' => 'White Pigeon', 'state_id' => 23],
                ['name' => 'Applegate', 'state_id' => 23],
                ['name' => 'Argyle', 'state_id' => 23],
                ['name' => 'Brown City', 'state_id' => 23],
                ['name' => 'Carsonville', 'state_id' => 23],
                ['name' => 'Croswell', 'state_id' => 23],
                ['name' => 'Decker', 'state_id' => 23],
                ['name' => 'Deckerville', 'state_id' => 23],
                ['name' => 'Forestville', 'state_id' => 23],
                ['name' => 'Lexington', 'state_id' => 23],
                ['name' => 'Marlette', 'state_id' => 23],
                ['name' => 'Melvin', 'state_id' => 23],
                ['name' => 'Minden City', 'state_id' => 23],
                ['name' => 'Palms', 'state_id' => 23],
                ['name' => 'Peck', 'state_id' => 23],
                ['name' => 'Port Sanilac', 'state_id' => 23],
                ['name' => 'Sandusky', 'state_id' => 23],
                ['name' => 'Snover', 'state_id' => 23],
                ['name' => 'Cooks', 'state_id' => 23],
                ['name' => 'Germfask', 'state_id' => 23],
                ['name' => 'Gulliver', 'state_id' => 23],
                ['name' => 'Manistique', 'state_id' => 23],
                ['name' => 'Seney', 'state_id' => 23],
                ['name' => 'Bancroft', 'state_id' => 23],
                ['name' => 'Byron', 'state_id' => 23],
                ['name' => 'Durand', 'state_id' => 23],
                ['name' => 'New Lothrop', 'state_id' => 23],
                ['name' => 'Vernon', 'state_id' => 23],
                ['name' => 'Corunna', 'state_id' => 23],
                ['name' => 'Henderson', 'state_id' => 23],
                ['name' => 'Laingsburg', 'state_id' => 23],
                ['name' => 'Morrice', 'state_id' => 23],
                ['name' => 'Owosso', 'state_id' => 23],
                ['name' => 'Perry', 'state_id' => 23],
                ['name' => 'Shaftsburg', 'state_id' => 23],
                ['name' => 'Fostoria', 'state_id' => 23],
                ['name' => 'Akron', 'state_id' => 23],
                ['name' => 'Caro', 'state_id' => 23],
                ['name' => 'Cass City', 'state_id' => 23],
                ['name' => 'Deford', 'state_id' => 23],
                ['name' => 'Fairgrove', 'state_id' => 23],
                ['name' => 'Gagetown', 'state_id' => 23],
                ['name' => 'Kingston', 'state_id' => 23],
                ['name' => 'Mayville', 'state_id' => 23],
                ['name' => 'Millington', 'state_id' => 23],
                ['name' => 'Reese', 'state_id' => 23],
                ['name' => 'Richville', 'state_id' => 23],
                ['name' => 'Unionville', 'state_id' => 23],
                ['name' => 'Vassar', 'state_id' => 23],
                ['name' => 'Bangor', 'state_id' => 23],
                ['name' => 'Bloomingdale', 'state_id' => 23],
                ['name' => 'Breedsville', 'state_id' => 23],
                ['name' => 'Covert', 'state_id' => 23],
                ['name' => 'Decatur', 'state_id' => 23],
                ['name' => 'Gobles', 'state_id' => 23],
                ['name' => 'Grand Junction', 'state_id' => 23],
                ['name' => 'Hartford', 'state_id' => 23],
                ['name' => 'Kendall', 'state_id' => 23],
                ['name' => 'Lacota', 'state_id' => 23],
                ['name' => 'Lawrence', 'state_id' => 23],
                ['name' => 'Lawton', 'state_id' => 23],
                ['name' => 'Mattawan', 'state_id' => 23],
                ['name' => 'Paw Paw', 'state_id' => 23],
                ['name' => 'South Haven', 'state_id' => 23],
                ['name' => 'Ann Arbor', 'state_id' => 23],
                ['name' => 'Bridgewater', 'state_id' => 23],
                ['name' => 'Chelsea', 'state_id' => 23],
                ['name' => 'Dexter', 'state_id' => 23],
                ['name' => 'Manchester', 'state_id' => 23],
                ['name' => 'Salem', 'state_id' => 23],
                ['name' => 'Saline', 'state_id' => 23],
                ['name' => 'Whitmore Lake', 'state_id' => 23],
                ['name' => 'Whittaker', 'state_id' => 23],
                ['name' => 'Willis', 'state_id' => 23],
                ['name' => 'Ypsilanti', 'state_id' => 23],
                ['name' => 'Allen Park', 'state_id' => 23],
                ['name' => 'Belleville', 'state_id' => 23],
                ['name' => 'Dearborn', 'state_id' => 23],
                ['name' => 'Melvindale', 'state_id' => 23],
                ['name' => 'Dearborn Heights', 'state_id' => 23],
                ['name' => 'Flat Rock', 'state_id' => 23],
                ['name' => 'Garden City', 'state_id' => 23],
                ['name' => 'Grosse Ile', 'state_id' => 23],
                ['name' => 'Inkster', 'state_id' => 23],
                ['name' => 'Lincoln Park', 'state_id' => 23],
                ['name' => 'Livonia', 'state_id' => 23],
                ['name' => 'New Boston', 'state_id' => 23],
                ['name' => 'Northville', 'state_id' => 23],
                ['name' => 'Plymouth', 'state_id' => 23],
                ['name' => 'Rockwood', 'state_id' => 23],
                ['name' => 'Romulus', 'state_id' => 23],
                ['name' => 'Taylor', 'state_id' => 23],
                ['name' => 'Trenton', 'state_id' => 23],
                ['name' => 'Wayne', 'state_id' => 23],
                ['name' => 'Westland', 'state_id' => 23],
                ['name' => 'Canton', 'state_id' => 23],
                ['name' => 'Wyandotte', 'state_id' => 23],
                ['name' => 'Riverview', 'state_id' => 23],
                ['name' => 'Southgate', 'state_id' => 23],
                ['name' => 'Detroit', 'state_id' => 23],
                ['name' => 'Highland Park', 'state_id' => 23],
                ['name' => 'Hamtramck', 'state_id' => 23],
                ['name' => 'River Rouge', 'state_id' => 23],
                ['name' => 'Harper Woods', 'state_id' => 23],
                ['name' => 'Ecorse', 'state_id' => 23],
                ['name' => 'Grosse Pointe', 'state_id' => 23],
                ['name' => 'Redford', 'state_id' => 23],
                ['name' => 'Cadillac', 'state_id' => 23],
                ['name' => 'Boon', 'state_id' => 23],
                ['name' => 'Buckley', 'state_id' => 23],
                ['name' => 'Harrietta', 'state_id' => 23],
                ['name' => 'Manton', 'state_id' => 23],
                ['name' => 'Mesick', 'state_id' => 23]
            ]);
        }
    }
}
