<?php

use Illuminate\Database\Seeder;

class state22TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of ME - Maine.
        //If the table 'cities' exists, insert the data to the table.
        if (DB::table('cities')->get()->count() >= 0) {
            DB::table('cities')->insert([
                ['name' => 'Auburn', 'state_id' => 22],
                ['name' => 'Durham', 'state_id' => 22],
                ['name' => 'Danville', 'state_id' => 22],
                ['name' => 'East Livermore', 'state_id' => 22],
                ['name' => 'East Poland', 'state_id' => 22],
                ['name' => 'Greene', 'state_id' => 22],
                ['name' => 'Lewiston', 'state_id' => 22],
                ['name' => 'Lisbon', 'state_id' => 22],
                ['name' => 'Lisbon Falls', 'state_id' => 22],
                ['name' => 'Livermore', 'state_id' => 22],
                ['name' => 'Livermore Falls', 'state_id' => 22],
                ['name' => 'Mechanic Falls', 'state_id' => 22],
                ['name' => 'Minot', 'state_id' => 22],
                ['name' => 'Leeds', 'state_id' => 22],
                ['name' => 'North Turner', 'state_id' => 22],
                ['name' => 'Poland', 'state_id' => 22],
                ['name' => 'Sabattus', 'state_id' => 22],
                ['name' => 'Turner', 'state_id' => 22],
                ['name' => 'West Minot', 'state_id' => 22],
                ['name' => 'West Poland', 'state_id' => 22],
                ['name' => 'Orient', 'state_id' => 22],
                ['name' => 'Wytopitlock', 'state_id' => 22],
                ['name' => 'Houlton', 'state_id' => 22],
                ['name' => 'Ashland', 'state_id' => 22],
                ['name' => 'Benedicta', 'state_id' => 22],
                ['name' => 'Blaine', 'state_id' => 22],
                ['name' => 'Bridgewater', 'state_id' => 22],
                ['name' => 'Caribou', 'state_id' => 22],
                ['name' => 'Clayton Lake', 'state_id' => 22],
                ['name' => 'Crouseville', 'state_id' => 22],
                ['name' => 'Eagle Lake', 'state_id' => 22],
                ['name' => 'Easton', 'state_id' => 22],
                ['name' => 'Estcourt Station', 'state_id' => 22],
                ['name' => 'Fort Fairfield', 'state_id' => 22],
                ['name' => 'Fort Kent', 'state_id' => 22],
                ['name' => 'Fort Kent Mills', 'state_id' => 22],
                ['name' => 'Frenchville', 'state_id' => 22],
                ['name' => 'Grand Isle', 'state_id' => 22],
                ['name' => 'Island Falls', 'state_id' => 22],
                ['name' => 'Limestone', 'state_id' => 22],
                ['name' => 'Madawaska', 'state_id' => 22],
                ['name' => 'Mapleton', 'state_id' => 22],
                ['name' => 'Mars Hill', 'state_id' => 22],
                ['name' => 'Monticello', 'state_id' => 22],
                ['name' => 'New Limerick', 'state_id' => 22],
                ['name' => 'New Sweden', 'state_id' => 22],
                ['name' => 'Oakfield', 'state_id' => 22],
                ['name' => 'Oxbow', 'state_id' => 22],
                ['name' => 'Perham', 'state_id' => 22],
                ['name' => 'Portage', 'state_id' => 22],
                ['name' => 'Presque Isle', 'state_id' => 22],
                ['name' => 'Saint Agatha', 'state_id' => 22],
                ['name' => 'Saint David', 'state_id' => 22],
                ['name' => 'Saint Francis', 'state_id' => 22],
                ['name' => 'Sheridan', 'state_id' => 22],
                ['name' => 'Sherman', 'state_id' => 22],
                ['name' => 'Sinclair', 'state_id' => 22],
                ['name' => 'Smyrna Mills', 'state_id' => 22],
                ['name' => 'Wallagrass', 'state_id' => 22],
                ['name' => 'Stockholm', 'state_id' => 22],
                ['name' => 'Van Buren', 'state_id' => 22],
                ['name' => 'Washburn', 'state_id' => 22],
                ['name' => 'Westfield', 'state_id' => 22],
                ['name' => 'Bailey Island', 'state_id' => 22],
                ['name' => 'Bridgton', 'state_id' => 22],
                ['name' => 'Brunswick', 'state_id' => 22],
                ['name' => 'Bustins Island', 'state_id' => 22],
                ['name' => 'Casco', 'state_id' => 22],
                ['name' => 'Chebeague Island', 'state_id' => 22],
                ['name' => 'Cliff Island', 'state_id' => 22],
                ['name' => 'Cumberland Center', 'state_id' => 22],
                ['name' => 'East Baldwin', 'state_id' => 22],
                ['name' => 'Sebago', 'state_id' => 22],
                ['name' => 'Freeport', 'state_id' => 22],
                ['name' => 'Gorham', 'state_id' => 22],
                ['name' => 'Gray', 'state_id' => 22],
                ['name' => 'Harrison', 'state_id' => 22],
                ['name' => 'Long Island', 'state_id' => 22],
                ['name' => 'Naples', 'state_id' => 22],
                ['name' => 'North Bridgton', 'state_id' => 22],
                ['name' => 'Windham', 'state_id' => 22],
                ['name' => 'Orrs Island', 'state_id' => 22],
                ['name' => 'Pownal', 'state_id' => 22],
                ['name' => 'Scarborough', 'state_id' => 22],
                ['name' => 'Raymond', 'state_id' => 22],
                ['name' => 'South Casco', 'state_id' => 22],
                ['name' => 'South Freeport', 'state_id' => 22],
                ['name' => 'Harpswell', 'state_id' => 22],
                ['name' => 'South Windham', 'state_id' => 22],
                ['name' => 'Standish', 'state_id' => 22],
                ['name' => 'Steep Falls', 'state_id' => 22],
                ['name' => 'West Baldwin', 'state_id' => 22],
                ['name' => 'Westbrook', 'state_id' => 22],
                ['name' => 'Yarmouth', 'state_id' => 22],
                ['name' => 'North Yarmouth', 'state_id' => 22],
                ['name' => 'Portland', 'state_id' => 22],
                ['name' => 'Falmouth', 'state_id' => 22],
                ['name' => 'South Portland', 'state_id' => 22],
                ['name' => 'Cape Elizabeth', 'state_id' => 22],
                ['name' => 'Peaks Island', 'state_id' => 22],
                ['name' => 'Cumberland Foreside', 'state_id' => 22],
                ['name' => 'New Gloucester', 'state_id' => 22],
                ['name' => 'Dryden', 'state_id' => 22],
                ['name' => 'East Dixfield', 'state_id' => 22],
                ['name' => 'East Wilton', 'state_id' => 22],
                ['name' => 'Jay', 'state_id' => 22],
                ['name' => 'North Jay', 'state_id' => 22],
                ['name' => 'Weld', 'state_id' => 22],
                ['name' => 'Wilton', 'state_id' => 22],
                ['name' => 'Eustis', 'state_id' => 22],
                ['name' => 'Farmington', 'state_id' => 22],
                ['name' => 'Farmington Falls', 'state_id' => 22],
                ['name' => 'Kingfield', 'state_id' => 22],
                ['name' => 'New Sharon', 'state_id' => 22],
                ['name' => 'New Vineyard', 'state_id' => 22],
                ['name' => 'Oquossoc', 'state_id' => 22],
                ['name' => 'Phillips', 'state_id' => 22],
                ['name' => 'Rangeley', 'state_id' => 22],
                ['name' => 'Stratton', 'state_id' => 22],
                ['name' => 'Strong', 'state_id' => 22],
                ['name' => 'Temple', 'state_id' => 22],
                ['name' => 'West Farmington', 'state_id' => 22],
                ['name' => 'Aurora', 'state_id' => 22],
                ['name' => 'Bucksport', 'state_id' => 22],
                ['name' => 'Castine', 'state_id' => 22],
                ['name' => 'East Orland', 'state_id' => 22],
                ['name' => 'Orland', 'state_id' => 22],
                ['name' => 'Penobscot', 'state_id' => 22],
                ['name' => 'Ellsworth', 'state_id' => 22],
                ['name' => 'Gouldsboro', 'state_id' => 22],
                ['name' => 'Bar Harbor', 'state_id' => 22],
                ['name' => 'Bernard', 'state_id' => 22],
                ['name' => 'Birch Harbor', 'state_id' => 22],
                ['name' => 'Blue Hill', 'state_id' => 22],
                ['name' => 'Brooklin', 'state_id' => 22],
                ['name' => 'Brooksville', 'state_id' => 22],
                ['name' => 'Corea', 'state_id' => 22],
                ['name' => 'Cranberry Isles', 'state_id' => 22],
                ['name' => 'Deer Isle', 'state_id' => 22],
                ['name' => 'East Blue Hill', 'state_id' => 22],
                ['name' => 'Franklin', 'state_id' => 22],
                ['name' => 'Frenchboro', 'state_id' => 22],
                ['name' => 'Hancock', 'state_id' => 22],
                ['name' => 'Harborside', 'state_id' => 22],
                ['name' => 'Hulls Cove', 'state_id' => 22],
                ['name' => 'Islesford', 'state_id' => 22],
                ['name' => 'Little Deer Isle', 'state_id' => 22],
                ['name' => 'Bass Harbor', 'state_id' => 22],
                ['name' => 'Mount Desert', 'state_id' => 22],
                ['name' => 'Northeast Harbor', 'state_id' => 22],
                ['name' => 'Sullivan', 'state_id' => 22],
                ['name' => 'Prospect Harbor', 'state_id' => 22],
                ['name' => 'Salsbury Cove', 'state_id' => 22],
                ['name' => 'Sargentville', 'state_id' => 22],
                ['name' => 'Seal Cove', 'state_id' => 22],
                ['name' => 'Seal Harbor', 'state_id' => 22],
                ['name' => 'Sedgwick', 'state_id' => 22],
                ['name' => 'Sorrento', 'state_id' => 22],
                ['name' => 'Southwest Harbor', 'state_id' => 22],
                ['name' => 'Stonington', 'state_id' => 22],
                ['name' => 'Sunset', 'state_id' => 22],
                ['name' => 'Surry', 'state_id' => 22],
                ['name' => 'Swans Island', 'state_id' => 22],
                ['name' => 'Winter Harbor', 'state_id' => 22],
                ['name' => 'Monmouth', 'state_id' => 22],
                ['name' => 'North Monmouth', 'state_id' => 22],
                ['name' => 'Wayne', 'state_id' => 22],
                ['name' => 'Augusta', 'state_id' => 22],
                ['name' => 'East Winthrop', 'state_id' => 22],
                ['name' => 'Farmingdale', 'state_id' => 22],
                ['name' => 'Gardiner', 'state_id' => 22],
                ['name' => 'Randolph', 'state_id' => 22],
                ['name' => 'Hallowell', 'state_id' => 22],
                ['name' => 'Kents Hill', 'state_id' => 22],
                ['name' => 'Litchfield', 'state_id' => 22],
                ['name' => 'Manchester', 'state_id' => 22],
                ['name' => 'Mount Vernon', 'state_id' => 22],
                ['name' => 'Readfield', 'state_id' => 22],
                ['name' => 'South China', 'state_id' => 22],
                ['name' => 'South Gardiner', 'state_id' => 22],
                ['name' => 'Vienna', 'state_id' => 22],
                ['name' => 'Windsor', 'state_id' => 22],
                ['name' => 'Winthrop', 'state_id' => 22],
                ['name' => 'Waterville', 'state_id' => 22],
                ['name' => 'Albion', 'state_id' => 22],
                ['name' => 'Belgrade', 'state_id' => 22],
                ['name' => 'Belgrade Lakes', 'state_id' => 22],
                ['name' => 'China Village', 'state_id' => 22],
                ['name' => 'Clinton', 'state_id' => 22],
                ['name' => 'East Vassalboro', 'state_id' => 22],
                ['name' => 'North Vassalboro', 'state_id' => 22],
                ['name' => 'Oakland', 'state_id' => 22],
                ['name' => 'Vassalboro', 'state_id' => 22],
                ['name' => 'Friendship', 'state_id' => 22],
                ['name' => 'Cushing', 'state_id' => 22],
                ['name' => 'Washington', 'state_id' => 22],
                ['name' => 'Isle Au Haut', 'state_id' => 22],
                ['name' => 'Rockland', 'state_id' => 22],
                ['name' => 'Camden', 'state_id' => 22],
                ['name' => 'Hope', 'state_id' => 22],
                ['name' => 'Matinicus', 'state_id' => 22],
                ['name' => 'North Haven', 'state_id' => 22],
                ['name' => 'Owls Head', 'state_id' => 22],
                ['name' => 'Port Clyde', 'state_id' => 22],
                ['name' => 'Rockport', 'state_id' => 22],
                ['name' => 'South Thomaston', 'state_id' => 22],
                ['name' => 'Spruce Head', 'state_id' => 22],
                ['name' => 'Tenants Harbor', 'state_id' => 22],
                ['name' => 'Thomaston', 'state_id' => 22],
                ['name' => 'Union', 'state_id' => 22],
                ['name' => 'Vinalhaven', 'state_id' => 22],
                ['name' => 'Warren', 'state_id' => 22],
                ['name' => 'West Rockport', 'state_id' => 22],
                ['name' => 'Coopers Mills', 'state_id' => 22],
                ['name' => 'Dresden', 'state_id' => 22],
                ['name' => 'Jefferson', 'state_id' => 22],
                ['name' => 'Whitefield', 'state_id' => 22],
                ['name' => 'Alna', 'state_id' => 22],
                ['name' => 'Boothbay', 'state_id' => 22],
                ['name' => 'Boothbay Harbor', 'state_id' => 22],
                ['name' => 'Bristol', 'state_id' => 22],
                ['name' => 'Chamberlain', 'state_id' => 22],
                ['name' => 'Damariscotta', 'state_id' => 22],
                ['name' => 'East Boothbay', 'state_id' => 22],
                ['name' => 'Isle Of Springs', 'state_id' => 22],
                ['name' => 'Bremen', 'state_id' => 22],
                ['name' => 'Newcastle', 'state_id' => 22],
                ['name' => 'New Harbor', 'state_id' => 22],
                ['name' => 'Nobleboro', 'state_id' => 22],
                ['name' => 'Edgecomb', 'state_id' => 22],
                ['name' => 'Pemaquid', 'state_id' => 22],
                ['name' => 'Round Pond', 'state_id' => 22],
                ['name' => 'South Bristol', 'state_id' => 22],
                ['name' => 'Squirrel Island', 'state_id' => 22],
                ['name' => 'Trevett', 'state_id' => 22],
                ['name' => 'Waldoboro', 'state_id' => 22],
                ['name' => 'Walpole', 'state_id' => 22],
                ['name' => 'West Boothbay Harbor', 'state_id' => 22],
                ['name' => 'Southport', 'state_id' => 22],
                ['name' => 'Wiscasset', 'state_id' => 22],
                ['name' => 'Monhegan', 'state_id' => 22],
                ['name' => 'Brownfield', 'state_id' => 22],
                ['name' => 'Center Lovell', 'state_id' => 22],
                ['name' => 'Denmark', 'state_id' => 22],
                ['name' => 'Fryeburg', 'state_id' => 22],
                ['name' => 'Hiram', 'state_id' => 22],
                ['name' => 'Lovell', 'state_id' => 22],
                ['name' => 'Porter', 'state_id' => 22],
                ['name' => 'Waterford', 'state_id' => 22],
                ['name' => 'Andover', 'state_id' => 22],
                ['name' => 'Bethel', 'state_id' => 22],
                ['name' => 'Bryant Pond', 'state_id' => 22],
                ['name' => 'Buckfield', 'state_id' => 22],
                ['name' => 'Canton', 'state_id' => 22],
                ['name' => 'Dixfield', 'state_id' => 22],
                ['name' => 'East Andover', 'state_id' => 22],
                ['name' => 'Stoneham', 'state_id' => 22],
                ['name' => 'Hanover', 'state_id' => 22],
                ['name' => 'Hebron', 'state_id' => 22],
                ['name' => 'Greenwood', 'state_id' => 22],
                ['name' => 'Mexico', 'state_id' => 22],
                ['name' => 'Newry', 'state_id' => 22],
                ['name' => 'North Waterford', 'state_id' => 22],
                ['name' => 'Norway', 'state_id' => 22],
                ['name' => 'Oxford', 'state_id' => 22],
                ['name' => 'Paris', 'state_id' => 22],
                ['name' => 'Roxbury', 'state_id' => 22],
                ['name' => 'Rumford', 'state_id' => 22],
                ['name' => 'South Paris', 'state_id' => 22],
                ['name' => 'West Bethel', 'state_id' => 22],
                ['name' => 'West Paris', 'state_id' => 22],
                ['name' => 'Peru', 'state_id' => 22],
                ['name' => 'Sumner', 'state_id' => 22],
                ['name' => 'Bangor', 'state_id' => 22],
                ['name' => 'Bradford', 'state_id' => 22],
                ['name' => 'Bradley', 'state_id' => 22],
                ['name' => 'Brewer', 'state_id' => 22],
                ['name' => 'Burlington', 'state_id' => 22],
                ['name' => 'Greenbush', 'state_id' => 22],
                ['name' => 'Carmel', 'state_id' => 22],
                ['name' => 'Charleston', 'state_id' => 22],
                ['name' => 'Corinth', 'state_id' => 22],
                ['name' => 'Eddington', 'state_id' => 22],
                ['name' => 'Holden', 'state_id' => 22],
                ['name' => 'East Millinocket', 'state_id' => 22],
                ['name' => 'Etna', 'state_id' => 22],
                ['name' => 'Exeter', 'state_id' => 22],
                ['name' => 'Hampden', 'state_id' => 22],
                ['name' => 'Howland', 'state_id' => 22],
                ['name' => 'Hudson', 'state_id' => 22],
                ['name' => 'Kenduskeag', 'state_id' => 22],
                ['name' => 'Kingman', 'state_id' => 22],
                ['name' => 'Lagrange', 'state_id' => 22],
                ['name' => 'Lee', 'state_id' => 22],
                ['name' => 'Levant', 'state_id' => 22],
                ['name' => 'Lincoln', 'state_id' => 22],
                ['name' => 'Mattawamkeag', 'state_id' => 22],
                ['name' => 'Medway', 'state_id' => 22],
                ['name' => 'Milford', 'state_id' => 22],
                ['name' => 'Millinocket', 'state_id' => 22],
                ['name' => 'Old Town', 'state_id' => 22],
                ['name' => 'Orono', 'state_id' => 22],
                ['name' => 'Orrington', 'state_id' => 22],
                ['name' => 'Passadumkeag', 'state_id' => 22],
                ['name' => 'Springfield', 'state_id' => 22],
                ['name' => 'Stetson', 'state_id' => 22],
                ['name' => 'Stillwater', 'state_id' => 22],
                ['name' => 'West Enfield', 'state_id' => 22],
                ['name' => 'Winn', 'state_id' => 22],
                ['name' => 'Patten', 'state_id' => 22],
                ['name' => 'Stacyville', 'state_id' => 22],
                ['name' => 'Corinna', 'state_id' => 22],
                ['name' => 'Dexter', 'state_id' => 22],
                ['name' => 'Dixmont', 'state_id' => 22],
                ['name' => 'East Newport', 'state_id' => 22],
                ['name' => 'Garland', 'state_id' => 22],
                ['name' => 'Newport', 'state_id' => 22],
                ['name' => 'Plymouth', 'state_id' => 22],
                ['name' => 'Abbot', 'state_id' => 22],
                ['name' => 'Brownville', 'state_id' => 22],
                ['name' => 'Brownville Junction', 'state_id' => 22],
                ['name' => 'Dover Foxcroft', 'state_id' => 22],
                ['name' => 'Greenville', 'state_id' => 22],
                ['name' => 'Greenville Junction', 'state_id' => 22],
                ['name' => 'Guilford', 'state_id' => 22],
                ['name' => 'Milo', 'state_id' => 22],
                ['name' => 'Monson', 'state_id' => 22],
                ['name' => 'Sangerville', 'state_id' => 22],
                ['name' => 'Sebec', 'state_id' => 22],
                ['name' => 'Shirley Mills', 'state_id' => 22],
                ['name' => 'Bowdoinham', 'state_id' => 22],
                ['name' => 'Topsham', 'state_id' => 22],
                ['name' => 'Bowdoin', 'state_id' => 22],
                ['name' => 'Richmond', 'state_id' => 22],
                ['name' => 'Bath', 'state_id' => 22],
                ['name' => 'Georgetown', 'state_id' => 22],
                ['name' => 'Phippsburg', 'state_id' => 22],
                ['name' => 'Sebasco Estates', 'state_id' => 22],
                ['name' => 'Woolwich', 'state_id' => 22],
                ['name' => 'Rockwood', 'state_id' => 22],
                ['name' => 'Anson', 'state_id' => 22],
                ['name' => 'Athens', 'state_id' => 22],
                ['name' => 'Bingham', 'state_id' => 22],
                ['name' => 'Cambridge', 'state_id' => 22],
                ['name' => 'Canaan', 'state_id' => 22],
                ['name' => 'Caratunk', 'state_id' => 22],
                ['name' => 'Detroit', 'state_id' => 22],
                ['name' => 'Fairfield', 'state_id' => 22],
                ['name' => 'Harmony', 'state_id' => 22],
                ['name' => 'Hartland', 'state_id' => 22],
                ['name' => 'Hinckley', 'state_id' => 22],
                ['name' => 'Jackman', 'state_id' => 22],
                ['name' => 'Madison', 'state_id' => 22],
                ['name' => 'New Portland', 'state_id' => 22],
                ['name' => 'Norridgewock', 'state_id' => 22],
                ['name' => 'North Anson', 'state_id' => 22],
                ['name' => 'Palmyra', 'state_id' => 22],
                ['name' => 'Pittsfield', 'state_id' => 22],
                ['name' => 'Saint Albans', 'state_id' => 22],
                ['name' => 'Shawmut', 'state_id' => 22],
                ['name' => 'Skowhegan', 'state_id' => 22],
                ['name' => 'Smithfield', 'state_id' => 22],
                ['name' => 'Solon', 'state_id' => 22],
                ['name' => 'West Forks', 'state_id' => 22],
                ['name' => 'Palermo', 'state_id' => 22],
                ['name' => 'Frankfort', 'state_id' => 22],
                ['name' => 'Winterport', 'state_id' => 22],
                ['name' => 'Islesboro', 'state_id' => 22],
                ['name' => 'Lincolnville', 'state_id' => 22],
                ['name' => 'Lincolnville Center', 'state_id' => 22],
                ['name' => 'Belfast', 'state_id' => 22],
                ['name' => 'Brooks', 'state_id' => 22],
                ['name' => 'Burnham', 'state_id' => 22],
                ['name' => 'Freedom', 'state_id' => 22],
                ['name' => 'Liberty', 'state_id' => 22],
                ['name' => 'Monroe', 'state_id' => 22],
                ['name' => 'Morrill', 'state_id' => 22],
                ['name' => 'Sandy Point', 'state_id' => 22],
                ['name' => 'Searsmont', 'state_id' => 22],
                ['name' => 'Searsport', 'state_id' => 22],
                ['name' => 'Stockton Springs', 'state_id' => 22],
                ['name' => 'Thorndike', 'state_id' => 22],
                ['name' => 'Troy', 'state_id' => 22],
                ['name' => 'Unity', 'state_id' => 22],
                ['name' => 'Brookton', 'state_id' => 22],
                ['name' => 'Danforth', 'state_id' => 22],
                ['name' => 'Lambert Lake', 'state_id' => 22],
                ['name' => 'Topsfield', 'state_id' => 22],
                ['name' => 'Vanceboro', 'state_id' => 22],
                ['name' => 'Waite', 'state_id' => 22],
                ['name' => 'Addison', 'state_id' => 22],
                ['name' => 'Beals', 'state_id' => 22],
                ['name' => 'Calais', 'state_id' => 22],
                ['name' => 'Cherryfield', 'state_id' => 22],
                ['name' => 'Columbia Falls', 'state_id' => 22],
                ['name' => 'Cutler', 'state_id' => 22],
                ['name' => 'Dennysville', 'state_id' => 22],
                ['name' => 'East Machias', 'state_id' => 22],
                ['name' => 'Eastport', 'state_id' => 22],
                ['name' => 'Grand Lake Stream', 'state_id' => 22],
                ['name' => 'Harrington', 'state_id' => 22],
                ['name' => 'Jonesboro', 'state_id' => 22],
                ['name' => 'Jonesport', 'state_id' => 22],
                ['name' => 'Lubec', 'state_id' => 22],
                ['name' => 'Machias', 'state_id' => 22],
                ['name' => 'Machiasport', 'state_id' => 22],
                ['name' => 'Meddybemps', 'state_id' => 22],
                ['name' => 'Milbridge', 'state_id' => 22],
                ['name' => 'Pembroke', 'state_id' => 22],
                ['name' => 'Perry', 'state_id' => 22],
                ['name' => 'Princeton', 'state_id' => 22],
                ['name' => 'Robbinston', 'state_id' => 22],
                ['name' => 'Steuben', 'state_id' => 22],
                ['name' => 'Wesley', 'state_id' => 22],
                ['name' => 'Whiting', 'state_id' => 22],
                ['name' => 'Baileyville', 'state_id' => 22],
                ['name' => 'Berwick', 'state_id' => 22],
                ['name' => 'Cape Neddick', 'state_id' => 22],
                ['name' => 'Eliot', 'state_id' => 22],
                ['name' => 'Kittery', 'state_id' => 22],
                ['name' => 'Kittery Point', 'state_id' => 22],
                ['name' => 'North Berwick', 'state_id' => 22],
                ['name' => 'Ogunquit', 'state_id' => 22],
                ['name' => 'South Berwick', 'state_id' => 22],
                ['name' => 'York', 'state_id' => 22],
                ['name' => 'York Beach', 'state_id' => 22],
                ['name' => 'York Harbor', 'state_id' => 22],
                ['name' => 'Acton', 'state_id' => 22],
                ['name' => 'Alfred', 'state_id' => 22],
                ['name' => 'Bar Mills', 'state_id' => 22],
                ['name' => 'Biddeford', 'state_id' => 22],
                ['name' => 'Biddeford Pool', 'state_id' => 22],
                ['name' => 'Cape Porpoise', 'state_id' => 22],
                ['name' => 'Cornish', 'state_id' => 22],
                ['name' => 'Lebanon', 'state_id' => 22],
                ['name' => 'East Parsonsfield', 'state_id' => 22],
                ['name' => 'East Waterboro', 'state_id' => 22],
                ['name' => 'Hollis Center', 'state_id' => 22],
                ['name' => 'Kennebunk', 'state_id' => 22],
                ['name' => 'Kennebunkport', 'state_id' => 22],
                ['name' => 'Parsonsfield', 'state_id' => 22],
                ['name' => 'Limerick', 'state_id' => 22],
                ['name' => 'Limington', 'state_id' => 22],
                ['name' => 'Moody', 'state_id' => 22],
                ['name' => 'Newfield', 'state_id' => 22],
                ['name' => 'North Waterboro', 'state_id' => 22],
                ['name' => 'Ocean Park', 'state_id' => 22],
                ['name' => 'Old Orchard Beach', 'state_id' => 22],
                ['name' => 'Saco', 'state_id' => 22],
                ['name' => 'Sanford', 'state_id' => 22],
                ['name' => 'Shapleigh', 'state_id' => 22],
                ['name' => 'Springvale', 'state_id' => 22],
                ['name' => 'Waterboro', 'state_id' => 22],
                ['name' => 'Wells', 'state_id' => 22],
                ['name' => 'Buxton', 'state_id' => 22],
                ['name' => 'West Kennebunk', 'state_id' => 22],
                ['name' => 'West Newfield', 'state_id' => 22]
            ]);
        }
    }
}
