<?php

use Illuminate\Database\Seeder;

class state24TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of MN - Minnesota.
        //If the table 'cities' exists, insert the data to the table.
        if (DB::table('cities')->get()->count() >= 0) {
            DB::table('cities')->insert([
                ['name' => 'Hill City', 'state_id' => 24],
                ['name' => 'Jacobson', 'state_id' => 24],
                ['name' => 'Mcgregor', 'state_id' => 24],
                ['name' => 'Swatara', 'state_id' => 24],
                ['name' => 'Tamarack', 'state_id' => 24],
                ['name' => 'Mc Grath', 'state_id' => 24],
                ['name' => 'Aitkin', 'state_id' => 24],
                ['name' => 'Palisade', 'state_id' => 24],
                ['name' => 'Bethel', 'state_id' => 24],
                ['name' => 'Cedar', 'state_id' => 24],
                ['name' => 'Circle Pines', 'state_id' => 24],
                ['name' => 'Saint Francis', 'state_id' => 24],
                ['name' => 'Anoka', 'state_id' => 24],
                ['name' => 'Andover', 'state_id' => 24],
                ['name' => 'Minneapolis', 'state_id' => 24],
                ['name' => 'Detroit Lakes', 'state_id' => 24],
                ['name' => 'Audubon', 'state_id' => 24],
                ['name' => 'Callaway', 'state_id' => 24],
                ['name' => 'Frazee', 'state_id' => 24],
                ['name' => 'Lake Park', 'state_id' => 24],
                ['name' => 'Ogema', 'state_id' => 24],
                ['name' => 'Osage', 'state_id' => 24],
                ['name' => 'Ponsford', 'state_id' => 24],
                ['name' => 'Richwood', 'state_id' => 24],
                ['name' => 'Rochert', 'state_id' => 24],
                ['name' => 'White Earth', 'state_id' => 24],
                ['name' => 'Wolf Lake', 'state_id' => 24],
                ['name' => 'Bemidji', 'state_id' => 24],
                ['name' => 'Blackduck', 'state_id' => 24],
                ['name' => 'Hines', 'state_id' => 24],
                ['name' => 'Kelliher', 'state_id' => 24],
                ['name' => 'Pennington', 'state_id' => 24],
                ['name' => 'Ponemah', 'state_id' => 24],
                ['name' => 'Puposky', 'state_id' => 24],
                ['name' => 'Redby', 'state_id' => 24],
                ['name' => 'Redlake', 'state_id' => 24],
                ['name' => 'Solway', 'state_id' => 24],
                ['name' => 'Tenstrike', 'state_id' => 24],
                ['name' => 'Waskish', 'state_id' => 24],
                ['name' => 'Wilton', 'state_id' => 24],
                ['name' => 'Foley', 'state_id' => 24],
                ['name' => 'Gilman', 'state_id' => 24],
                ['name' => 'Oak Park', 'state_id' => 24],
                ['name' => 'Rice', 'state_id' => 24],
                ['name' => 'Sauk Rapids', 'state_id' => 24],
                ['name' => 'Barry', 'state_id' => 24],
                ['name' => 'Beardsley', 'state_id' => 24],
                ['name' => 'Clinton', 'state_id' => 24],
                ['name' => 'Correll', 'state_id' => 24],
                ['name' => 'Graceville', 'state_id' => 24],
                ['name' => 'Odessa', 'state_id' => 24],
                ['name' => 'Ortonville', 'state_id' => 24],
                ['name' => 'Mankato', 'state_id' => 24],
                ['name' => 'Amboy', 'state_id' => 24],
                ['name' => 'Eagle Lake', 'state_id' => 24],
                ['name' => 'Garden City', 'state_id' => 24],
                ['name' => 'Good Thunder', 'state_id' => 24],
                ['name' => 'Lake Crystal', 'state_id' => 24],
                ['name' => 'Madison Lake', 'state_id' => 24],
                ['name' => 'Mapleton', 'state_id' => 24],
                ['name' => 'Pemberton', 'state_id' => 24],
                ['name' => 'Saint Clair', 'state_id' => 24],
                ['name' => 'Vernon Center', 'state_id' => 24],
                ['name' => 'Comfrey', 'state_id' => 24],
                ['name' => 'Essig', 'state_id' => 24],
                ['name' => 'Hanska', 'state_id' => 24],
                ['name' => 'New Ulm', 'state_id' => 24],
                ['name' => 'Searles', 'state_id' => 24],
                ['name' => 'Sleepy Eye', 'state_id' => 24],
                ['name' => 'Springfield', 'state_id' => 24],
                ['name' => 'Barnum', 'state_id' => 24],
                ['name' => 'Carlton', 'state_id' => 24],
                ['name' => 'Cloquet', 'state_id' => 24],
                ['name' => 'Cromwell', 'state_id' => 24],
                ['name' => 'Esko', 'state_id' => 24],
                ['name' => 'Holyoke', 'state_id' => 24],
                ['name' => 'Kettle River', 'state_id' => 24],
                ['name' => 'Moose Lake', 'state_id' => 24],
                ['name' => 'Sawyer', 'state_id' => 24],
                ['name' => 'Wrenshall', 'state_id' => 24],
                ['name' => 'Wright', 'state_id' => 24],
                ['name' => 'Carver', 'state_id' => 24],
                ['name' => 'Chanhassen', 'state_id' => 24],
                ['name' => 'Chaska', 'state_id' => 24],
                ['name' => 'Cologne', 'state_id' => 24],
                ['name' => 'Hamburg', 'state_id' => 24],
                ['name' => 'Mayer', 'state_id' => 24],
                ['name' => 'New Germany', 'state_id' => 24],
                ['name' => 'Norwood Young America', 'state_id' => 24],
                ['name' => 'Norwood', 'state_id' => 24],
                ['name' => 'Victoria', 'state_id' => 24],
                ['name' => 'Waconia', 'state_id' => 24],
                ['name' => 'Watertown', 'state_id' => 24],
                ['name' => 'Young America', 'state_id' => 24],
                ['name' => 'Ah Gwah Ching', 'state_id' => 24],
                ['name' => 'Backus', 'state_id' => 24],
                ['name' => 'Hackensack', 'state_id' => 24],
                ['name' => 'Pillager', 'state_id' => 24],
                ['name' => 'Pine River', 'state_id' => 24],
                ['name' => 'Walker', 'state_id' => 24],
                ['name' => 'Bena', 'state_id' => 24],
                ['name' => 'Cass Lake', 'state_id' => 24],
                ['name' => 'Federal Dam', 'state_id' => 24],
                ['name' => 'Longville', 'state_id' => 24],
                ['name' => 'Outing', 'state_id' => 24],
                ['name' => 'Remer', 'state_id' => 24],
                ['name' => 'Clara City', 'state_id' => 24],
                ['name' => 'Maynard', 'state_id' => 24],
                ['name' => 'Milan', 'state_id' => 24],
                ['name' => 'Montevideo', 'state_id' => 24],
                ['name' => 'Watson', 'state_id' => 24],
                ['name' => 'Almelund', 'state_id' => 24],
                ['name' => 'Center City', 'state_id' => 24],
                ['name' => 'Chisago City', 'state_id' => 24],
                ['name' => 'Harris', 'state_id' => 24],
                ['name' => 'Lindstrom', 'state_id' => 24],
                ['name' => 'North Branch', 'state_id' => 24],
                ['name' => 'Rush City', 'state_id' => 24],
                ['name' => 'Shafer', 'state_id' => 24],
                ['name' => 'Stacy', 'state_id' => 24],
                ['name' => 'Taylors Falls', 'state_id' => 24],
                ['name' => 'Wyoming', 'state_id' => 24],
                ['name' => 'Barnesville', 'state_id' => 24],
                ['name' => 'Comstock', 'state_id' => 24],
                ['name' => 'Dilworth', 'state_id' => 24],
                ['name' => 'Felton', 'state_id' => 24],
                ['name' => 'Georgetown', 'state_id' => 24],
                ['name' => 'Glyndon', 'state_id' => 24],
                ['name' => 'Hawley', 'state_id' => 24],
                ['name' => 'Hitterdal', 'state_id' => 24],
                ['name' => 'Moorhead', 'state_id' => 24],
                ['name' => 'Sabin', 'state_id' => 24],
                ['name' => 'Ulen', 'state_id' => 24],
                ['name' => 'Bagley', 'state_id' => 24],
                ['name' => 'Clearbrook', 'state_id' => 24],
                ['name' => 'Gonvick', 'state_id' => 24],
                ['name' => 'Leonard', 'state_id' => 24],
                ['name' => 'Shevlin', 'state_id' => 24],
                ['name' => 'Grand Marais', 'state_id' => 24],
                ['name' => 'Grand Portage', 'state_id' => 24],
                ['name' => 'Hovland', 'state_id' => 24],
                ['name' => 'Lutsen', 'state_id' => 24],
                ['name' => 'Schroeder', 'state_id' => 24],
                ['name' => 'Tofte', 'state_id' => 24],
                ['name' => 'Windom', 'state_id' => 24],
                ['name' => 'Bingham Lake', 'state_id' => 24],
                ['name' => 'Jeffers', 'state_id' => 24],
                ['name' => 'Mountain Lake', 'state_id' => 24],
                ['name' => 'Storden', 'state_id' => 24],
                ['name' => 'Westbrook', 'state_id' => 24],
                ['name' => 'Brainerd', 'state_id' => 24],
                ['name' => 'Baxter', 'state_id' => 24],
                ['name' => 'Crosby', 'state_id' => 24],
                ['name' => 'Crosslake', 'state_id' => 24],
                ['name' => 'Deerwood', 'state_id' => 24],
                ['name' => 'Emily', 'state_id' => 24],
                ['name' => 'Fifty Lakes', 'state_id' => 24],
                ['name' => 'Fort Ripley', 'state_id' => 24],
                ['name' => 'Garrison', 'state_id' => 24],
                ['name' => 'Ironton', 'state_id' => 24],
                ['name' => 'Jenkins', 'state_id' => 24],
                ['name' => 'Lake Hubert', 'state_id' => 24],
                ['name' => 'Merrifield', 'state_id' => 24],
                ['name' => 'Nisswa', 'state_id' => 24],
                ['name' => 'Pequot Lakes', 'state_id' => 24],
                ['name' => 'Castle Rock', 'state_id' => 24],
                ['name' => 'Farmington', 'state_id' => 24],
                ['name' => 'Hampton', 'state_id' => 24],
                ['name' => 'Hastings', 'state_id' => 24],
                ['name' => 'Lakeville', 'state_id' => 24],
                ['name' => 'Randolph', 'state_id' => 24],
                ['name' => 'Rosemount', 'state_id' => 24],
                ['name' => 'South Saint Paul', 'state_id' => 24],
                ['name' => 'Inver Grove Heights', 'state_id' => 24],
                ['name' => 'Vermillion', 'state_id' => 24],
                ['name' => 'Saint Paul', 'state_id' => 24],
                ['name' => 'Mendota', 'state_id' => 24],
                ['name' => 'Burnsville', 'state_id' => 24],
                ['name' => 'Claremont', 'state_id' => 24],
                ['name' => 'Dodge Center', 'state_id' => 24],
                ['name' => 'Hayfield', 'state_id' => 24],
                ['name' => 'Kasson', 'state_id' => 24],
                ['name' => 'Mantorville', 'state_id' => 24],
                ['name' => 'West Concord', 'state_id' => 24],
                ['name' => 'Alexandria', 'state_id' => 24],
                ['name' => 'Brandon', 'state_id' => 24],
                ['name' => 'Carlos', 'state_id' => 24],
                ['name' => 'Evansville', 'state_id' => 24],
                ['name' => 'Garfield', 'state_id' => 24],
                ['name' => 'Holmes City', 'state_id' => 24],
                ['name' => 'Kensington', 'state_id' => 24],
                ['name' => 'Miltona', 'state_id' => 24],
                ['name' => 'Nelson', 'state_id' => 24],
                ['name' => 'Osakis', 'state_id' => 24],
                ['name' => 'Blue Earth', 'state_id' => 24],
                ['name' => 'Bricelyn', 'state_id' => 24],
                ['name' => 'Delavan', 'state_id' => 24],
                ['name' => 'Easton', 'state_id' => 24],
                ['name' => 'Elmore', 'state_id' => 24],
                ['name' => 'Frost', 'state_id' => 24],
                ['name' => 'Huntley', 'state_id' => 24],
                ['name' => 'Kiester', 'state_id' => 24],
                ['name' => 'Minnesota Lake', 'state_id' => 24],
                ['name' => 'Wells', 'state_id' => 24],
                ['name' => 'Winnebago', 'state_id' => 24],
                ['name' => 'Canton', 'state_id' => 24],
                ['name' => 'Chatfield', 'state_id' => 24],
                ['name' => 'Fountain', 'state_id' => 24],
                ['name' => 'Harmony', 'state_id' => 24],
                ['name' => 'Lanesboro', 'state_id' => 24],
                ['name' => 'Mabel', 'state_id' => 24],
                ['name' => 'Ostrander', 'state_id' => 24],
                ['name' => 'Peterson', 'state_id' => 24],
                ['name' => 'Preston', 'state_id' => 24],
                ['name' => 'Rushford', 'state_id' => 24],
                ['name' => 'Spring Valley', 'state_id' => 24],
                ['name' => 'Wykoff', 'state_id' => 24],
                ['name' => 'Albert Lea', 'state_id' => 24],
                ['name' => 'Alden', 'state_id' => 24],
                ['name' => 'Clarks Grove', 'state_id' => 24],
                ['name' => 'Conger', 'state_id' => 24],
                ['name' => 'Emmons', 'state_id' => 24],
                ['name' => 'Freeborn', 'state_id' => 24],
                ['name' => 'Geneva', 'state_id' => 24],
                ['name' => 'Glenville', 'state_id' => 24],
                ['name' => 'Hartland', 'state_id' => 24],
                ['name' => 'Hayward', 'state_id' => 24],
                ['name' => 'Hollandale', 'state_id' => 24],
                ['name' => 'Twin Lakes', 'state_id' => 24],
                ['name' => 'Cannon Falls', 'state_id' => 24],
                ['name' => 'Dennison', 'state_id' => 24],
                ['name' => 'Frontenac', 'state_id' => 24],
                ['name' => 'Goodhue', 'state_id' => 24],
                ['name' => 'Red Wing', 'state_id' => 24],
                ['name' => 'Welch', 'state_id' => 24],
                ['name' => 'Kenyon', 'state_id' => 24],
                ['name' => 'Pine Island', 'state_id' => 24],
                ['name' => 'Wanamingo', 'state_id' => 24],
                ['name' => 'Zumbrota', 'state_id' => 24],
                ['name' => 'Herman', 'state_id' => 24],
                ['name' => 'Norcross', 'state_id' => 24],
                ['name' => 'Ashby', 'state_id' => 24],
                ['name' => 'Barrett', 'state_id' => 24],
                ['name' => 'Hoffman', 'state_id' => 24],
                ['name' => 'Elbow Lake', 'state_id' => 24],
                ['name' => 'Wendell', 'state_id' => 24],
                ['name' => 'Hopkins', 'state_id' => 24],
                ['name' => 'Maple Grove', 'state_id' => 24],
                ['name' => 'Champlin', 'state_id' => 24],
                ['name' => 'Crystal Bay', 'state_id' => 24],
                ['name' => 'Dayton', 'state_id' => 24],
                ['name' => 'Excelsior', 'state_id' => 24],
                ['name' => 'Hamel', 'state_id' => 24],
                ['name' => 'Eden Prairie', 'state_id' => 24],
                ['name' => 'Minnetonka', 'state_id' => 24],
                ['name' => 'Maple Plain', 'state_id' => 24],
                ['name' => 'Long Lake', 'state_id' => 24],
                ['name' => 'Loretto', 'state_id' => 24],
                ['name' => 'Minnetonka Beach', 'state_id' => 24],
                ['name' => 'Mound', 'state_id' => 24],
                ['name' => 'Osseo', 'state_id' => 24],
                ['name' => 'Rogers', 'state_id' => 24],
                ['name' => 'Saint Bonifacius', 'state_id' => 24],
                ['name' => 'Spring Park', 'state_id' => 24],
                ['name' => 'Wayzata', 'state_id' => 24],
                ['name' => 'Navarre', 'state_id' => 24],
                ['name' => 'Rockford', 'state_id' => 24],
                ['name' => 'Howard Lake', 'state_id' => 24],
                ['name' => 'Brownsville', 'state_id' => 24],
                ['name' => 'Caledonia', 'state_id' => 24],
                ['name' => 'Eitzen', 'state_id' => 24],
                ['name' => 'Hokah', 'state_id' => 24],
                ['name' => 'Houston', 'state_id' => 24],
                ['name' => 'La Crescent', 'state_id' => 24],
                ['name' => 'Spring Grove', 'state_id' => 24],
                ['name' => 'Akeley', 'state_id' => 24],
                ['name' => 'Benedict', 'state_id' => 24],
                ['name' => 'Lake George', 'state_id' => 24],
                ['name' => 'Laporte', 'state_id' => 24],
                ['name' => 'Nevis', 'state_id' => 24],
                ['name' => 'Park Rapids', 'state_id' => 24],
                ['name' => 'Braham', 'state_id' => 24],
                ['name' => 'Cambridge', 'state_id' => 24],
                ['name' => 'Dalbo', 'state_id' => 24],
                ['name' => 'Grandy', 'state_id' => 24],
                ['name' => 'Isanti', 'state_id' => 24],
                ['name' => 'Stanchfield', 'state_id' => 24],
                ['name' => 'Bovey', 'state_id' => 24],
                ['name' => 'Calumet', 'state_id' => 24],
                ['name' => 'Cohasset', 'state_id' => 24],
                ['name' => 'Coleraine', 'state_id' => 24],
                ['name' => 'Grand Rapids', 'state_id' => 24],
                ['name' => 'Goodland', 'state_id' => 24],
                ['name' => 'Keewatin', 'state_id' => 24],
                ['name' => 'Marble', 'state_id' => 24],
                ['name' => 'Nashwauk', 'state_id' => 24],
                ['name' => 'Pengilly', 'state_id' => 24],
                ['name' => 'Swan River', 'state_id' => 24],
                ['name' => 'Taconite', 'state_id' => 24],
                ['name' => 'Warba', 'state_id' => 24],
                ['name' => 'Bigfork', 'state_id' => 24],
                ['name' => 'Bowstring', 'state_id' => 24],
                ['name' => 'Deer River', 'state_id' => 24],
                ['name' => 'Talmoon', 'state_id' => 24],
                ['name' => 'Effie', 'state_id' => 24],
                ['name' => 'Marcell', 'state_id' => 24],
                ['name' => 'Max', 'state_id' => 24],
                ['name' => 'Spring Lake', 'state_id' => 24],
                ['name' => 'Squaw Lake', 'state_id' => 24],
                ['name' => 'Wirt', 'state_id' => 24],
                ['name' => 'Alpha', 'state_id' => 24],
                ['name' => 'Heron Lake', 'state_id' => 24],
                ['name' => 'Jackson', 'state_id' => 24],
                ['name' => 'Lakefield', 'state_id' => 24],
                ['name' => 'Okabena', 'state_id' => 24],
                ['name' => 'Mora', 'state_id' => 24],
                ['name' => 'Ogilvie', 'state_id' => 24],
                ['name' => 'Willmar', 'state_id' => 24],
                ['name' => 'Atwater', 'state_id' => 24],
                ['name' => 'Blomkest', 'state_id' => 24],
                ['name' => 'Kandiyohi', 'state_id' => 24],
                ['name' => 'Lake Lillian', 'state_id' => 24],
                ['name' => 'New London', 'state_id' => 24],
                ['name' => 'Pennock', 'state_id' => 24],
                ['name' => 'Prinsburg', 'state_id' => 24],
                ['name' => 'Raymond', 'state_id' => 24],
                ['name' => 'Spicer', 'state_id' => 24],
                ['name' => 'Sunburg', 'state_id' => 24],
                ['name' => 'Donaldson', 'state_id' => 24],
                ['name' => 'Hallock', 'state_id' => 24],
                ['name' => 'Halma', 'state_id' => 24],
                ['name' => 'Humboldt', 'state_id' => 24],
                ['name' => 'Karlstad', 'state_id' => 24],
                ['name' => 'Kennedy', 'state_id' => 24],
                ['name' => 'Lake Bronson', 'state_id' => 24],
                ['name' => 'Lancaster', 'state_id' => 24],
                ['name' => 'Noyes', 'state_id' => 24],
                ['name' => 'Saint Vincent', 'state_id' => 24],
                ['name' => 'Big Falls', 'state_id' => 24],
                ['name' => 'Birchdale', 'state_id' => 24],
                ['name' => 'International Falls', 'state_id' => 24],
                ['name' => 'Littlefork', 'state_id' => 24],
                ['name' => 'Loman', 'state_id' => 24],
                ['name' => 'Margie', 'state_id' => 24],
                ['name' => 'Mizpah', 'state_id' => 24],
                ['name' => 'Northome', 'state_id' => 24],
                ['name' => 'Ranier', 'state_id' => 24],
                ['name' => 'Kabetogama', 'state_id' => 24],
                ['name' => 'South International Falls', 'state_id' => 24],
                ['name' => 'Bellingham', 'state_id' => 24],
                ['name' => 'Boyd', 'state_id' => 24],
                ['name' => 'Dawson', 'state_id' => 24],
                ['name' => 'Madison', 'state_id' => 24],
                ['name' => 'Marietta', 'state_id' => 24],
                ['name' => 'Beaver Bay', 'state_id' => 24],
                ['name' => 'Finland', 'state_id' => 24],
                ['name' => 'Isabella', 'state_id' => 24],
                ['name' => 'Knife River', 'state_id' => 24],
                ['name' => 'Silver Bay', 'state_id' => 24],
                ['name' => 'Two Harbors', 'state_id' => 24],
                ['name' => 'Baudette', 'state_id' => 24],
                ['name' => 'Williams', 'state_id' => 24],
                ['name' => 'Angle Inlet', 'state_id' => 24],
                ['name' => 'Oak Island', 'state_id' => 24],
                ['name' => 'Cleveland', 'state_id' => 24],
                ['name' => 'Elysian', 'state_id' => 24],
                ['name' => 'Kasota', 'state_id' => 24],
                ['name' => 'Kilkenny', 'state_id' => 24],
                ['name' => 'Le Center', 'state_id' => 24],
                ['name' => 'Le Sueur', 'state_id' => 24],
                ['name' => 'Montgomery', 'state_id' => 24],
                ['name' => 'New Prague', 'state_id' => 24],
                ['name' => 'Waterville', 'state_id' => 24],
                ['name' => 'Arco', 'state_id' => 24],
                ['name' => 'Hendricks', 'state_id' => 24],
                ['name' => 'Ivanhoe', 'state_id' => 24],
                ['name' => 'Lake Benton', 'state_id' => 24],
                ['name' => 'Tyler', 'state_id' => 24],
                ['name' => 'Balaton', 'state_id' => 24],
                ['name' => 'Garvin', 'state_id' => 24],
                ['name' => 'Lynd', 'state_id' => 24],
                ['name' => 'Russell', 'state_id' => 24],
                ['name' => 'Tracy', 'state_id' => 24],
                ['name' => 'Cottonwood', 'state_id' => 24],
                ['name' => 'Ghent', 'state_id' => 24],
                ['name' => 'Marshall', 'state_id' => 24],
                ['name' => 'Minneota', 'state_id' => 24],
                ['name' => 'Taunton', 'state_id' => 24],
                ['name' => 'Brownton', 'state_id' => 24],
                ['name' => 'Glencoe', 'state_id' => 24],
                ['name' => 'Hutchinson', 'state_id' => 24],
                ['name' => 'Lester Prairie', 'state_id' => 24],
                ['name' => 'Plato', 'state_id' => 24],
                ['name' => 'Silver Lake', 'state_id' => 24],
                ['name' => 'Stewart', 'state_id' => 24],
                ['name' => 'Winsted', 'state_id' => 24],
                ['name' => 'Bejou', 'state_id' => 24],
                ['name' => 'Mahnomen', 'state_id' => 24],
                ['name' => 'Naytahwaush', 'state_id' => 24],
                ['name' => 'Waubun', 'state_id' => 24],
                ['name' => 'Alvarado', 'state_id' => 24],
                ['name' => 'Argyle', 'state_id' => 24],
                ['name' => 'Gatzke', 'state_id' => 24],
                ['name' => 'Grygla', 'state_id' => 24],
                ['name' => 'Middle River', 'state_id' => 24],
                ['name' => 'Newfolden', 'state_id' => 24],
                ['name' => 'Oslo', 'state_id' => 24],
                ['name' => 'Stephen', 'state_id' => 24],
                ['name' => 'Strandquist', 'state_id' => 24],
                ['name' => 'Viking', 'state_id' => 24],
                ['name' => 'Warren', 'state_id' => 24],
                ['name' => 'Fairmont', 'state_id' => 24],
                ['name' => 'Granada', 'state_id' => 24],
                ['name' => 'Northrop', 'state_id' => 24],
                ['name' => 'Truman', 'state_id' => 24],
                ['name' => 'Ceylon', 'state_id' => 24],
                ['name' => 'Dunnell', 'state_id' => 24],
                ['name' => 'Ormsby', 'state_id' => 24],
                ['name' => 'Sherburn', 'state_id' => 24],
                ['name' => 'Trimont', 'state_id' => 24],
                ['name' => 'Welcome', 'state_id' => 24],
                ['name' => 'Darwin', 'state_id' => 24],
                ['name' => 'Dassel', 'state_id' => 24],
                ['name' => 'Eden Valley', 'state_id' => 24],
                ['name' => 'Litchfield', 'state_id' => 24],
                ['name' => 'Watkins', 'state_id' => 24],
                ['name' => 'Cosmos', 'state_id' => 24],
                ['name' => 'Grove City', 'state_id' => 24],
                ['name' => 'Princeton', 'state_id' => 24],
                ['name' => 'Bock', 'state_id' => 24],
                ['name' => 'Foreston', 'state_id' => 24],
                ['name' => 'Isle', 'state_id' => 24],
                ['name' => 'Milaca', 'state_id' => 24],
                ['name' => 'Onamia', 'state_id' => 24],
                ['name' => 'Pease', 'state_id' => 24],
                ['name' => 'Wahkon', 'state_id' => 24],
                ['name' => 'Bowlus', 'state_id' => 24],
                ['name' => 'Buckman', 'state_id' => 24],
                ['name' => 'Flensburg', 'state_id' => 24],
                ['name' => 'Hillman', 'state_id' => 24],
                ['name' => 'Lastrup', 'state_id' => 24],
                ['name' => 'Little Falls', 'state_id' => 24],
                ['name' => 'Pierz', 'state_id' => 24],
                ['name' => 'Royalton', 'state_id' => 24],
                ['name' => 'Swanville', 'state_id' => 24],
                ['name' => 'Upsala', 'state_id' => 24],
                ['name' => 'Waite Park', 'state_id' => 24],
                ['name' => 'Cushing', 'state_id' => 24],
                ['name' => 'Motley', 'state_id' => 24],
                ['name' => 'Randall', 'state_id' => 24],
                ['name' => 'Adams', 'state_id' => 24],
                ['name' => 'Austin', 'state_id' => 24],
                ['name' => 'Brownsdale', 'state_id' => 24],
                ['name' => 'Dexter', 'state_id' => 24],
                ['name' => 'Elkton', 'state_id' => 24],
                ['name' => 'Grand Meadow', 'state_id' => 24],
                ['name' => 'Lansing', 'state_id' => 24],
                ['name' => 'Le Roy', 'state_id' => 24],
                ['name' => 'Lyle', 'state_id' => 24],
                ['name' => 'Racine', 'state_id' => 24],
                ['name' => 'Rose Creek', 'state_id' => 24],
                ['name' => 'Sargeant', 'state_id' => 24],
                ['name' => 'Taopi', 'state_id' => 24],
                ['name' => 'Waltham', 'state_id' => 24],
                ['name' => 'Avoca', 'state_id' => 24],
                ['name' => 'Chandler', 'state_id' => 24],
                ['name' => 'Currie', 'state_id' => 24],
                ['name' => 'Dovray', 'state_id' => 24],
                ['name' => 'Fulda', 'state_id' => 24],
                ['name' => 'Iona', 'state_id' => 24],
                ['name' => 'Lake Wilson', 'state_id' => 24],
                ['name' => 'Slayton', 'state_id' => 24],
                ['name' => 'Courtland', 'state_id' => 24],
                ['name' => 'Lafayette', 'state_id' => 24],
                ['name' => 'Nicollet', 'state_id' => 24],
                ['name' => 'Saint Peter', 'state_id' => 24],
                ['name' => 'Adrian', 'state_id' => 24],
                ['name' => 'Bigelow', 'state_id' => 24],
                ['name' => 'Brewster', 'state_id' => 24],
                ['name' => 'Ellsworth', 'state_id' => 24],
                ['name' => 'Leota', 'state_id' => 24],
                ['name' => 'Lismore', 'state_id' => 24],
                ['name' => 'Reading', 'state_id' => 24],
                ['name' => 'Round Lake', 'state_id' => 24],
                ['name' => 'Rushmore', 'state_id' => 24],
                ['name' => 'Wilmont', 'state_id' => 24],
                ['name' => 'Worthington', 'state_id' => 24],
                ['name' => 'Ada', 'state_id' => 24],
                ['name' => 'Borup', 'state_id' => 24],
                ['name' => 'Flom', 'state_id' => 24],
                ['name' => 'Gary', 'state_id' => 24],
                ['name' => 'Halstad', 'state_id' => 24],
                ['name' => 'Hendrum', 'state_id' => 24],
                ['name' => 'Perley', 'state_id' => 24],
                ['name' => 'Shelly', 'state_id' => 24],
                ['name' => 'Twin Valley', 'state_id' => 24],
                ['name' => 'Rochester', 'state_id' => 24],
                ['name' => 'Byron', 'state_id' => 24],
                ['name' => 'Dover', 'state_id' => 24],
                ['name' => 'Eyota', 'state_id' => 24],
                ['name' => 'Oronoco', 'state_id' => 24],
                ['name' => 'Stewartville', 'state_id' => 24],
                ['name' => 'Dalton', 'state_id' => 24],
                ['name' => 'Parkers Prairie', 'state_id' => 24],
                ['name' => 'Battle Lake', 'state_id' => 24],
                ['name' => 'Bluffton', 'state_id' => 24],
                ['name' => 'Clitherall', 'state_id' => 24],
                ['name' => 'Deer Creek', 'state_id' => 24],
                ['name' => 'Dent', 'state_id' => 24],
                ['name' => 'Elizabeth', 'state_id' => 24],
                ['name' => 'Erhard', 'state_id' => 24],
                ['name' => 'Fergus Falls', 'state_id' => 24],
                ['name' => 'Henning', 'state_id' => 24],
                ['name' => 'New York Mills', 'state_id' => 24],
                ['name' => 'Ottertail', 'state_id' => 24],
                ['name' => 'Pelican Rapids', 'state_id' => 24],
                ['name' => 'Perham', 'state_id' => 24],
                ['name' => 'Richville', 'state_id' => 24],
                ['name' => 'Underwood', 'state_id' => 24],
                ['name' => 'Vergas', 'state_id' => 24],
                ['name' => 'Vining', 'state_id' => 24],
                ['name' => 'Thief River Falls', 'state_id' => 24],
                ['name' => 'Goodridge', 'state_id' => 24],
                ['name' => 'Saint Hilaire', 'state_id' => 24],
                ['name' => 'Brook Park', 'state_id' => 24],
                ['name' => 'Grasston', 'state_id' => 24],
                ['name' => 'Henriette', 'state_id' => 24],
                ['name' => 'Hinckley', 'state_id' => 24],
                ['name' => 'Pine City', 'state_id' => 24],
                ['name' => 'Rock Creek', 'state_id' => 24],
                ['name' => 'Sandstone', 'state_id' => 24],
                ['name' => 'Askov', 'state_id' => 24],
                ['name' => 'Bruno', 'state_id' => 24],
                ['name' => 'Finlayson', 'state_id' => 24],
                ['name' => 'Kerrick', 'state_id' => 24],
                ['name' => 'Sturgeon Lake', 'state_id' => 24],
                ['name' => 'Willow River', 'state_id' => 24],
                ['name' => 'Edgerton', 'state_id' => 24],
                ['name' => 'Holland', 'state_id' => 24],
                ['name' => 'Ihlen', 'state_id' => 24],
                ['name' => 'Jasper', 'state_id' => 24],
                ['name' => 'Pipestone', 'state_id' => 24],
                ['name' => 'Ruthton', 'state_id' => 24],
                ['name' => 'Woodstock', 'state_id' => 24],
                ['name' => 'Beltrami', 'state_id' => 24],
                ['name' => 'Climax', 'state_id' => 24],
                ['name' => 'Erskine', 'state_id' => 24],
                ['name' => 'Fertile', 'state_id' => 24],
                ['name' => 'Fosston', 'state_id' => 24],
                ['name' => 'Mcintosh', 'state_id' => 24],
                ['name' => 'Nielsville', 'state_id' => 24],
                ['name' => 'Winger', 'state_id' => 24],
                ['name' => 'Gully', 'state_id' => 24],
                ['name' => 'Lengby', 'state_id' => 24],
                ['name' => 'Trail', 'state_id' => 24],
                ['name' => 'Crookston', 'state_id' => 24],
                ['name' => 'East Grand Forks', 'state_id' => 24],
                ['name' => 'Euclid', 'state_id' => 24],
                ['name' => 'Fisher', 'state_id' => 24],
                ['name' => 'Mentor', 'state_id' => 24],
                ['name' => 'Cyrus', 'state_id' => 24],
                ['name' => 'Farwell', 'state_id' => 24],
                ['name' => 'Glenwood', 'state_id' => 24],
                ['name' => 'Lowry', 'state_id' => 24],
                ['name' => 'Starbuck', 'state_id' => 24],
                ['name' => 'Villard', 'state_id' => 24],
                ['name' => 'Brooks', 'state_id' => 24],
                ['name' => 'Oklee', 'state_id' => 24],
                ['name' => 'Plummer', 'state_id' => 24],
                ['name' => 'Red Lake Falls', 'state_id' => 24],
                ['name' => 'Sanborn', 'state_id' => 24],
                ['name' => 'Lamberton', 'state_id' => 24],
                ['name' => 'Revere', 'state_id' => 24],
                ['name' => 'Walnut Grove', 'state_id' => 24],
                ['name' => 'Belview', 'state_id' => 24],
                ['name' => 'Clements', 'state_id' => 24],
                ['name' => 'Lucan', 'state_id' => 24],
                ['name' => 'Milroy', 'state_id' => 24],
                ['name' => 'Morgan', 'state_id' => 24],
                ['name' => 'Redwood Falls', 'state_id' => 24],
                ['name' => 'Seaforth', 'state_id' => 24],
                ['name' => 'Vesta', 'state_id' => 24],
                ['name' => 'Wabasso', 'state_id' => 24],
                ['name' => 'Wanda', 'state_id' => 24],
                ['name' => 'Bird Island', 'state_id' => 24],
                ['name' => 'Buffalo Lake', 'state_id' => 24],
                ['name' => 'Fairfax', 'state_id' => 24],
                ['name' => 'Franklin', 'state_id' => 24],
                ['name' => 'Hector', 'state_id' => 24],
                ['name' => 'Danube', 'state_id' => 24],
                ['name' => 'Morton', 'state_id' => 24],
                ['name' => 'Olivia', 'state_id' => 24],
                ['name' => 'Renville', 'state_id' => 24],
                ['name' => 'Sacred Heart', 'state_id' => 24],
                ['name' => 'Dundas', 'state_id' => 24],
                ['name' => 'Faribault', 'state_id' => 24],
                ['name' => 'Lonsdale', 'state_id' => 24],
                ['name' => 'Morristown', 'state_id' => 24],
                ['name' => 'Nerstrand', 'state_id' => 24],
                ['name' => 'Northfield', 'state_id' => 24],
                ['name' => 'Warsaw', 'state_id' => 24],
                ['name' => 'Webster', 'state_id' => 24],
                ['name' => 'Beaver Creek', 'state_id' => 24],
                ['name' => 'Hardwick', 'state_id' => 24],
                ['name' => 'Hills', 'state_id' => 24],
                ['name' => 'Kanaranzi', 'state_id' => 24],
                ['name' => 'Kenneth', 'state_id' => 24],
                ['name' => 'Luverne', 'state_id' => 24],
                ['name' => 'Magnolia', 'state_id' => 24],
                ['name' => 'Steen', 'state_id' => 24],
                ['name' => 'Roosevelt', 'state_id' => 24],
                ['name' => 'Swift', 'state_id' => 24],
                ['name' => 'Badger', 'state_id' => 24],
                ['name' => 'Greenbush', 'state_id' => 24],
                ['name' => 'Roseau', 'state_id' => 24],
                ['name' => 'Salol', 'state_id' => 24],
                ['name' => 'Strathcona', 'state_id' => 24],
                ['name' => 'Wannaska', 'state_id' => 24],
                ['name' => 'Warroad', 'state_id' => 24],
                ['name' => 'Brimson', 'state_id' => 24],
                ['name' => 'Alborn', 'state_id' => 24],
                ['name' => 'Angora', 'state_id' => 24],
                ['name' => 'Aurora', 'state_id' => 24],
                ['name' => 'Babbitt', 'state_id' => 24],
                ['name' => 'Biwabik', 'state_id' => 24],
                ['name' => 'Britt', 'state_id' => 24],
                ['name' => 'Brookston', 'state_id' => 24],
                ['name' => 'Buhl', 'state_id' => 24],
                ['name' => 'Canyon', 'state_id' => 24],
                ['name' => 'Chisholm', 'state_id' => 24],
                ['name' => 'Cook', 'state_id' => 24],
                ['name' => 'Cotton', 'state_id' => 24],
                ['name' => 'Crane Lake', 'state_id' => 24],
                ['name' => 'Ely', 'state_id' => 24],
                ['name' => 'Embarrass', 'state_id' => 24],
                ['name' => 'Eveleth', 'state_id' => 24],
                ['name' => 'Floodwood', 'state_id' => 24],
                ['name' => 'Forbes', 'state_id' => 24],
                ['name' => 'Gilbert', 'state_id' => 24],
                ['name' => 'Hibbing', 'state_id' => 24],
                ['name' => 'Hoyt Lakes', 'state_id' => 24],
                ['name' => 'Iron', 'state_id' => 24],
                ['name' => 'Kinney', 'state_id' => 24],
                ['name' => 'Makinen', 'state_id' => 24],
                ['name' => 'Meadowlands', 'state_id' => 24],
                ['name' => 'Melrude', 'state_id' => 24],
                ['name' => 'Mountain Iron', 'state_id' => 24],
                ['name' => 'Orr', 'state_id' => 24],
                ['name' => 'Nett Lake', 'state_id' => 24],
                ['name' => 'Virginia', 'state_id' => 24],
                ['name' => 'Saginaw', 'state_id' => 24],
                ['name' => 'Side Lake', 'state_id' => 24],
                ['name' => 'Soudan', 'state_id' => 24],
                ['name' => 'Tower', 'state_id' => 24],
                ['name' => 'Twig', 'state_id' => 24],
                ['name' => 'Winton', 'state_id' => 24],
                ['name' => 'Duluth', 'state_id' => 24],
                ['name' => 'Elko New Market', 'state_id' => 24],
                ['name' => 'Jordan', 'state_id' => 24],
                ['name' => 'Prior Lake', 'state_id' => 24],
                ['name' => 'Savage', 'state_id' => 24],
                ['name' => 'Shakopee', 'state_id' => 24],
                ['name' => 'Belle Plaine', 'state_id' => 24],
                ['name' => 'Becker', 'state_id' => 24],
                ['name' => 'Big Lake', 'state_id' => 24],
                ['name' => 'Clear Lake', 'state_id' => 24],
                ['name' => 'Elk River', 'state_id' => 24],
                ['name' => 'Santiago', 'state_id' => 24],
                ['name' => 'Zimmerman', 'state_id' => 24],
                ['name' => 'Arlington', 'state_id' => 24],
                ['name' => 'Gaylord', 'state_id' => 24],
                ['name' => 'Gibbon', 'state_id' => 24],
                ['name' => 'Green Isle', 'state_id' => 24],
                ['name' => 'New Auburn', 'state_id' => 24],
                ['name' => 'Winthrop', 'state_id' => 24],
                ['name' => 'Henderson', 'state_id' => 24],
                ['name' => 'Kimball', 'state_id' => 24],
                ['name' => 'Saint Cloud', 'state_id' => 24],
                ['name' => 'Albany', 'state_id' => 24],
                ['name' => 'Avon', 'state_id' => 24],
                ['name' => 'Belgrade', 'state_id' => 24],
                ['name' => 'Brooten', 'state_id' => 24],
                ['name' => 'Cold Spring', 'state_id' => 24],
                ['name' => 'Collegeville', 'state_id' => 24],
                ['name' => 'Elrosa', 'state_id' => 24],
                ['name' => 'Freeport', 'state_id' => 24],
                ['name' => 'Greenwald', 'state_id' => 24],
                ['name' => 'Holdingford', 'state_id' => 24],
                ['name' => 'Melrose', 'state_id' => 24],
                ['name' => 'New Munich', 'state_id' => 24],
                ['name' => 'Paynesville', 'state_id' => 24],
                ['name' => 'Richmond', 'state_id' => 24],
                ['name' => 'Rockville', 'state_id' => 24],
                ['name' => 'Roscoe', 'state_id' => 24],
                ['name' => 'Saint Joseph', 'state_id' => 24],
                ['name' => 'Saint Stephen', 'state_id' => 24],
                ['name' => 'Saint Martin', 'state_id' => 24],
                ['name' => 'Sartell', 'state_id' => 24],
                ['name' => 'Sauk Centre', 'state_id' => 24],
                ['name' => 'Medford', 'state_id' => 24],
                ['name' => 'Owatonna', 'state_id' => 24],
                ['name' => 'Blooming Prairie', 'state_id' => 24],
                ['name' => 'Ellendale', 'state_id' => 24],
                ['name' => 'Hope', 'state_id' => 24],
                ['name' => 'Alberta', 'state_id' => 24],
                ['name' => 'Chokio', 'state_id' => 24],
                ['name' => 'Donnelly', 'state_id' => 24],
                ['name' => 'Hancock', 'state_id' => 24],
                ['name' => 'Morris', 'state_id' => 24],
                ['name' => 'Appleton', 'state_id' => 24],
                ['name' => 'Benson', 'state_id' => 24],
                ['name' => 'Clontarf', 'state_id' => 24],
                ['name' => 'Danvers', 'state_id' => 24],
                ['name' => 'Holloway', 'state_id' => 24],
                ['name' => 'Kerkhoven', 'state_id' => 24],
                ['name' => 'Murdock', 'state_id' => 24],
                ['name' => 'Burtrum', 'state_id' => 24],
                ['name' => 'Grey Eagle', 'state_id' => 24],
                ['name' => 'Long Prairie', 'state_id' => 24],
                ['name' => 'West Union', 'state_id' => 24],
                ['name' => 'Bertha', 'state_id' => 24],
                ['name' => 'Browerville', 'state_id' => 24],
                ['name' => 'Clarissa', 'state_id' => 24],
                ['name' => 'Eagle Bend', 'state_id' => 24],
                ['name' => 'Hewitt', 'state_id' => 24],
                ['name' => 'Staples', 'state_id' => 24],
                ['name' => 'Browns Valley', 'state_id' => 24],
                ['name' => 'Dumont', 'state_id' => 24],
                ['name' => 'Wheaton', 'state_id' => 24],
                ['name' => 'Tintah', 'state_id' => 24],
                ['name' => 'Lake City', 'state_id' => 24],
                ['name' => 'Elgin', 'state_id' => 24],
                ['name' => 'Kellogg', 'state_id' => 24],
                ['name' => 'Mazeppa', 'state_id' => 24],
                ['name' => 'Millville', 'state_id' => 24],
                ['name' => 'Plainview', 'state_id' => 24],
                ['name' => 'Reads Landing', 'state_id' => 24],
                ['name' => 'Wabasha', 'state_id' => 24],
                ['name' => 'Zumbro Falls', 'state_id' => 24],
                ['name' => 'Aldrich', 'state_id' => 24],
                ['name' => 'Menahga', 'state_id' => 24],
                ['name' => 'Sebeka', 'state_id' => 24],
                ['name' => 'Verndale', 'state_id' => 24],
                ['name' => 'Wadena', 'state_id' => 24],
                ['name' => 'Janesville', 'state_id' => 24],
                ['name' => 'New Richland', 'state_id' => 24],
                ['name' => 'Waldorf', 'state_id' => 24],
                ['name' => 'Waseca', 'state_id' => 24],
                ['name' => 'Afton', 'state_id' => 24],
                ['name' => 'Bayport', 'state_id' => 24],
                ['name' => 'Cottage Grove', 'state_id' => 24],
                ['name' => 'Forest Lake', 'state_id' => 24],
                ['name' => 'Hugo', 'state_id' => 24],
                ['name' => 'Lake Elmo', 'state_id' => 24],
                ['name' => 'Lakeland', 'state_id' => 24],
                ['name' => 'Marine On Saint Croix', 'state_id' => 24],
                ['name' => 'Newport', 'state_id' => 24],
                ['name' => 'Saint Paul Park', 'state_id' => 24],
                ['name' => 'Scandia', 'state_id' => 24],
                ['name' => 'Stillwater', 'state_id' => 24],
                ['name' => 'Willernie', 'state_id' => 24],
                ['name' => 'Darfur', 'state_id' => 24],
                ['name' => 'La Salle', 'state_id' => 24],
                ['name' => 'Lewisville', 'state_id' => 24],
                ['name' => 'Madelia', 'state_id' => 24],
                ['name' => 'Saint James', 'state_id' => 24],
                ['name' => 'Butterfield', 'state_id' => 24],
                ['name' => 'Odin', 'state_id' => 24],
                ['name' => 'Breckenridge', 'state_id' => 24],
                ['name' => 'Campbell', 'state_id' => 24],
                ['name' => 'Foxhome', 'state_id' => 24],
                ['name' => 'Kent', 'state_id' => 24],
                ['name' => 'Nashua', 'state_id' => 24],
                ['name' => 'Rothsay', 'state_id' => 24],
                ['name' => 'Wolverton', 'state_id' => 24],
                ['name' => 'Altura', 'state_id' => 24],
                ['name' => 'Dakota', 'state_id' => 24],
                ['name' => 'Homer', 'state_id' => 24],
                ['name' => 'Lewiston', 'state_id' => 24],
                ['name' => 'Minnesota City', 'state_id' => 24],
                ['name' => 'Rollingstone', 'state_id' => 24],
                ['name' => 'Saint Charles', 'state_id' => 24],
                ['name' => 'Utica', 'state_id' => 24],
                ['name' => 'Winona', 'state_id' => 24],
                ['name' => 'Stockton', 'state_id' => 24],
                ['name' => 'Albertville', 'state_id' => 24],
                ['name' => 'Annandale', 'state_id' => 24],
                ['name' => 'Buffalo', 'state_id' => 24],
                ['name' => 'Clearwater', 'state_id' => 24],
                ['name' => 'Cokato', 'state_id' => 24],
                ['name' => 'Delano', 'state_id' => 24],
                ['name' => 'Hanover', 'state_id' => 24],
                ['name' => 'Maple Lake', 'state_id' => 24],
                ['name' => 'Monticello', 'state_id' => 24],
                ['name' => 'Montrose', 'state_id' => 24],
                ['name' => 'Saint Michael', 'state_id' => 24],
                ['name' => 'Silver Creek', 'state_id' => 24],
                ['name' => 'South Haven', 'state_id' => 24],
                ['name' => 'Waverly', 'state_id' => 24],
                ['name' => 'Canby', 'state_id' => 24],
                ['name' => 'Clarkfield', 'state_id' => 24],
                ['name' => 'Echo', 'state_id' => 24],
                ['name' => 'Granite Falls', 'state_id' => 24],
                ['name' => 'Hanley Falls', 'state_id' => 24],
                ['name' => 'Porter', 'state_id' => 24],
                ['name' => 'Wood Lake', 'state_id' => 24]
            ]);
        }
    }
}
