<?php

use Illuminate\Database\Seeder;

class state6TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of CO - Colorado.
        //If the table 'cities' exists, insert the data to the table.
        if (DB::table('cities')->get()->count() >= 0) {
            DB::table('cities')->insert([
                ['name' => 'Aurora', 'state_id' => 6],
                ['name' => 'Commerce City', 'state_id' => 6],
                ['name' => 'Dupont', 'state_id' => 6],
                ['name' => 'Westminster', 'state_id' => 6],
                ['name' => 'Bennett', 'state_id' => 6],
                ['name' => 'Strasburg', 'state_id' => 6],
                ['name' => 'Watkins', 'state_id' => 6],
                ['name' => 'Denver', 'state_id' => 6],
                ['name' => 'Thornton', 'state_id' => 6],
                ['name' => 'Brighton', 'state_id' => 6],
                ['name' => 'Eastlake', 'state_id' => 6],
                ['name' => 'Henderson', 'state_id' => 6],
                ['name' => 'Alamosa', 'state_id' => 6],
                ['name' => 'Hooper', 'state_id' => 6],
                ['name' => 'Mosca', 'state_id' => 6],
                ['name' => 'Byers', 'state_id' => 6],
                ['name' => 'Deer Trail', 'state_id' => 6],
                ['name' => 'Englewood', 'state_id' => 6],
                ['name' => 'Littleton', 'state_id' => 6],
                ['name' => 'Arboles', 'state_id' => 6],
                ['name' => 'Chromo', 'state_id' => 6],
                ['name' => 'Pagosa Springs', 'state_id' => 6],
                ['name' => 'Campo', 'state_id' => 6],
                ['name' => 'Pritchett', 'state_id' => 6],
                ['name' => 'Springfield', 'state_id' => 6],
                ['name' => 'Two Buttes', 'state_id' => 6],
                ['name' => 'Vilas', 'state_id' => 6],
                ['name' => 'Walsh', 'state_id' => 6],
                ['name' => 'Fort Lyon', 'state_id' => 6],
                ['name' => 'Hasty', 'state_id' => 6],
                ['name' => 'Las Animas', 'state_id' => 6],
                ['name' => 'Mc Clave', 'state_id' => 6],
                ['name' => 'Broomfield', 'state_id' => 6],
                ['name' => 'Eldorado Springs', 'state_id' => 6],
                ['name' => 'Lafayette', 'state_id' => 6],
                ['name' => 'Louisville', 'state_id' => 6],
                ['name' => 'Boulder', 'state_id' => 6],
                ['name' => 'Jamestown', 'state_id' => 6],
                ['name' => 'Nederland', 'state_id' => 6],
                ['name' => 'Pinecliffe', 'state_id' => 6],
                ['name' => 'Ward', 'state_id' => 6],
                ['name' => 'Longmont', 'state_id' => 6],
                ['name' => 'Allenspark', 'state_id' => 6],
                ['name' => 'Hygiene', 'state_id' => 6],
                ['name' => 'Lyons', 'state_id' => 6],
                ['name' => 'Niwot', 'state_id' => 6],
                ['name' => 'Salida', 'state_id' => 6],
                ['name' => 'Buena Vista', 'state_id' => 6],
                ['name' => 'Monarch', 'state_id' => 6],
                ['name' => 'Granite', 'state_id' => 6],
                ['name' => 'Nathrop', 'state_id' => 6],
                ['name' => 'Poncha Springs', 'state_id' => 6],
                ['name' => 'Arapahoe', 'state_id' => 6],
                ['name' => 'Cheyenne Wells', 'state_id' => 6],
                ['name' => 'Kit Carson', 'state_id' => 6],
                ['name' => 'Wild Horse', 'state_id' => 6],
                ['name' => 'Dumont', 'state_id' => 6],
                ['name' => 'Empire', 'state_id' => 6],
                ['name' => 'Georgetown', 'state_id' => 6],
                ['name' => 'Idaho Springs', 'state_id' => 6],
                ['name' => 'Silver Plume', 'state_id' => 6],
                ['name' => 'Antonito', 'state_id' => 6],
                ['name' => 'Capulin', 'state_id' => 6],
                ['name' => 'Conejos', 'state_id' => 6],
                ['name' => 'La Jara', 'state_id' => 6],
                ['name' => 'Manassa', 'state_id' => 6],
                ['name' => 'Romeo', 'state_id' => 6],
                ['name' => 'Sanford', 'state_id' => 6],
                ['name' => 'Blanca', 'state_id' => 6],
                ['name' => 'Chama', 'state_id' => 6],
                ['name' => 'Fort Garland', 'state_id' => 6],
                ['name' => 'Jaroso', 'state_id' => 6],
                ['name' => 'San Luis', 'state_id' => 6],
                ['name' => 'Crowley', 'state_id' => 6],
                ['name' => 'Olney Springs', 'state_id' => 6],
                ['name' => 'Ordway', 'state_id' => 6],
                ['name' => 'Sugar City', 'state_id' => 6],
                ['name' => 'Westcliffe', 'state_id' => 6],
                ['name' => 'Wetmore', 'state_id' => 6],
                ['name' => 'Austin', 'state_id' => 6],
                ['name' => 'Cedaredge', 'state_id' => 6],
                ['name' => 'Cory', 'state_id' => 6],
                ['name' => 'Crawford', 'state_id' => 6],
                ['name' => 'Delta', 'state_id' => 6],
                ['name' => 'Eckert', 'state_id' => 6],
                ['name' => 'Hotchkiss', 'state_id' => 6],
                ['name' => 'Lazear', 'state_id' => 6],
                ['name' => 'Paonia', 'state_id' => 6],
                ['name' => 'Cahone', 'state_id' => 6],
                ['name' => 'Dove Creek', 'state_id' => 6],
                ['name' => 'Rico', 'state_id' => 6],
                ['name' => 'Castle Rock', 'state_id' => 6],
                ['name' => 'Franktown', 'state_id' => 6],
                ['name' => 'Larkspur', 'state_id' => 6],
                ['name' => 'Lone Tree', 'state_id' => 6],
                ['name' => 'Louviers', 'state_id' => 6],
                ['name' => 'Parker', 'state_id' => 6],
                ['name' => 'Sedalia', 'state_id' => 6],
                ['name' => 'Bond', 'state_id' => 6],
                ['name' => 'Burns', 'state_id' => 6],
                ['name' => 'Mc Coy', 'state_id' => 6],
                ['name' => 'Avon', 'state_id' => 6],
                ['name' => 'Basalt', 'state_id' => 6],
                ['name' => 'Eagle', 'state_id' => 6],
                ['name' => 'Edwards', 'state_id' => 6],
                ['name' => 'Gypsum', 'state_id' => 6],
                ['name' => 'Minturn', 'state_id' => 6],
                ['name' => 'Red Cliff', 'state_id' => 6],
                ['name' => 'Wolcott', 'state_id' => 6],
                ['name' => 'Vail', 'state_id' => 6],
                ['name' => 'Agate', 'state_id' => 6],
                ['name' => 'Elbert', 'state_id' => 6],
                ['name' => 'Elizabeth', 'state_id' => 6],
                ['name' => 'Kiowa', 'state_id' => 6],
                ['name' => 'Matheson', 'state_id' => 6],
                ['name' => 'Simla', 'state_id' => 6],
                ['name' => 'Monument', 'state_id' => 6],
                ['name' => 'Palmer Lake', 'state_id' => 6],
                ['name' => 'Calhan', 'state_id' => 6],
                ['name' => 'Cascade', 'state_id' => 6],
                ['name' => 'Fountain', 'state_id' => 6],
                ['name' => 'Green Mountain Falls', 'state_id' => 6],
                ['name' => 'Manitou Springs', 'state_id' => 6],
                ['name' => 'Peyton', 'state_id' => 6],
                ['name' => 'Ramah', 'state_id' => 6],
                ['name' => 'Rush', 'state_id' => 6],
                ['name' => 'Usaf Academy', 'state_id' => 6],
                ['name' => 'Yoder', 'state_id' => 6],
                ['name' => 'Colorado Springs', 'state_id' => 6],
                ['name' => 'Canon City', 'state_id' => 6],
                ['name' => 'Coal Creek', 'state_id' => 6],
                ['name' => 'Coaldale', 'state_id' => 6],
                ['name' => 'Cotopaxi', 'state_id' => 6],
                ['name' => 'Florence', 'state_id' => 6],
                ['name' => 'Hillside', 'state_id' => 6],
                ['name' => 'Howard', 'state_id' => 6],
                ['name' => 'Penrose', 'state_id' => 6],
                ['name' => 'Rockvale', 'state_id' => 6],
                ['name' => 'Glenwood Springs', 'state_id' => 6],
                ['name' => 'Carbondale', 'state_id' => 6],
                ['name' => 'Parachute', 'state_id' => 6],
                ['name' => 'Battlement Mesa', 'state_id' => 6],
                ['name' => 'New Castle', 'state_id' => 6],
                ['name' => 'Rifle', 'state_id' => 6],
                ['name' => 'Silt', 'state_id' => 6],
                ['name' => 'Black Hawk', 'state_id' => 6],
                ['name' => 'Central City', 'state_id' => 6],
                ['name' => 'Rollinsville', 'state_id' => 6],
                ['name' => 'Fraser', 'state_id' => 6],
                ['name' => 'Granby', 'state_id' => 6],
                ['name' => 'Grand Lake', 'state_id' => 6],
                ['name' => 'Hot Sulphur Springs', 'state_id' => 6],
                ['name' => 'Kremmling', 'state_id' => 6],
                ['name' => 'Parshall', 'state_id' => 6],
                ['name' => 'Tabernash', 'state_id' => 6],
                ['name' => 'Winter Park', 'state_id' => 6],
                ['name' => 'Almont', 'state_id' => 6],
                ['name' => 'Crested Butte', 'state_id' => 6],
                ['name' => 'Gunnison', 'state_id' => 6],
                ['name' => 'Ohio City', 'state_id' => 6],
                ['name' => 'Parlin', 'state_id' => 6],
                ['name' => 'Pitkin', 'state_id' => 6],
                ['name' => 'Powderhorn', 'state_id' => 6],
                ['name' => 'Somerset', 'state_id' => 6],
                ['name' => 'Lake City', 'state_id' => 6],
                ['name' => 'Gardner', 'state_id' => 6],
                ['name' => 'La Veta', 'state_id' => 6],
                ['name' => 'Walsenburg', 'state_id' => 6],
                ['name' => 'Coalmont', 'state_id' => 6],
                ['name' => 'Cowdrey', 'state_id' => 6],
                ['name' => 'Rand', 'state_id' => 6],
                ['name' => 'Walden', 'state_id' => 6],
                ['name' => 'Arvada', 'state_id' => 6],
                ['name' => 'Wheat Ridge', 'state_id' => 6],
                ['name' => 'Golden', 'state_id' => 6],
                ['name' => 'Buffalo Creek', 'state_id' => 6],
                ['name' => 'Conifer', 'state_id' => 6],
                ['name' => 'Evergreen', 'state_id' => 6],
                ['name' => 'Idledale', 'state_id' => 6],
                ['name' => 'Indian Hills', 'state_id' => 6],
                ['name' => 'Kittredge', 'state_id' => 6],
                ['name' => 'Morrison', 'state_id' => 6],
                ['name' => 'Pine', 'state_id' => 6],
                ['name' => 'Arlington', 'state_id' => 6],
                ['name' => 'Eads', 'state_id' => 6],
                ['name' => 'Haswell', 'state_id' => 6],
                ['name' => 'Sheridan Lake', 'state_id' => 6],
                ['name' => 'Bethune', 'state_id' => 6],
                ['name' => 'Burlington', 'state_id' => 6],
                ['name' => 'Flagler', 'state_id' => 6],
                ['name' => 'Seibert', 'state_id' => 6],
                ['name' => 'Stratton', 'state_id' => 6],
                ['name' => 'Vona', 'state_id' => 6],
                ['name' => 'Climax', 'state_id' => 6],
                ['name' => 'Leadville', 'state_id' => 6],
                ['name' => 'Twin Lakes', 'state_id' => 6],
                ['name' => 'Bayfield', 'state_id' => 6],
                ['name' => 'Ignacio', 'state_id' => 6],
                ['name' => 'Durango', 'state_id' => 6],
                ['name' => 'Hesperus', 'state_id' => 6],
                ['name' => 'Marvel', 'state_id' => 6],
                ['name' => 'Estes Park', 'state_id' => 6],
                ['name' => 'Bellvue', 'state_id' => 6],
                ['name' => 'Berthoud', 'state_id' => 6],
                ['name' => 'Drake', 'state_id' => 6],
                ['name' => 'Fort Collins', 'state_id' => 6],
                ['name' => 'Glen Haven', 'state_id' => 6],
                ['name' => 'Laporte', 'state_id' => 6],
                ['name' => 'Livermore', 'state_id' => 6],
                ['name' => 'Loveland', 'state_id' => 6],
                ['name' => 'Masonville', 'state_id' => 6],
                ['name' => 'Red Feather Lakes', 'state_id' => 6],
                ['name' => 'Timnath', 'state_id' => 6],
                ['name' => 'Wellington', 'state_id' => 6],
                ['name' => 'Aguilar', 'state_id' => 6],
                ['name' => 'Boncarbo', 'state_id' => 6],
                ['name' => 'Branson', 'state_id' => 6],
                ['name' => 'Hoehne', 'state_id' => 6],
                ['name' => 'Kim', 'state_id' => 6],
                ['name' => 'Model', 'state_id' => 6],
                ['name' => 'Trinchera', 'state_id' => 6],
                ['name' => 'Trinidad', 'state_id' => 6],
                ['name' => 'Weston', 'state_id' => 6],
                ['name' => 'Arriba', 'state_id' => 6],
                ['name' => 'Genoa', 'state_id' => 6],
                ['name' => 'Hugo', 'state_id' => 6],
                ['name' => 'Karval', 'state_id' => 6],
                ['name' => 'Limon', 'state_id' => 6],
                ['name' => 'Atwood', 'state_id' => 6],
                ['name' => 'Crook', 'state_id' => 6],
                ['name' => 'Fleming', 'state_id' => 6],
                ['name' => 'Iliff', 'state_id' => 6],
                ['name' => 'Merino', 'state_id' => 6],
                ['name' => 'Padroni', 'state_id' => 6],
                ['name' => 'Peetz', 'state_id' => 6],
                ['name' => 'Sterling', 'state_id' => 6],
                ['name' => 'Grand Junction', 'state_id' => 6],
                ['name' => 'Clifton', 'state_id' => 6],
                ['name' => 'Fruita', 'state_id' => 6],
                ['name' => 'Gateway', 'state_id' => 6],
                ['name' => 'Glade Park', 'state_id' => 6],
                ['name' => 'Loma', 'state_id' => 6],
                ['name' => 'Mack', 'state_id' => 6],
                ['name' => 'Palisade', 'state_id' => 6],
                ['name' => 'Whitewater', 'state_id' => 6],
                ['name' => 'Collbran', 'state_id' => 6],
                ['name' => 'De Beque', 'state_id' => 6],
                ['name' => 'Mesa', 'state_id' => 6],
                ['name' => 'Molina', 'state_id' => 6],
                ['name' => 'Creede', 'state_id' => 6],
                ['name' => 'Dinosaur', 'state_id' => 6],
                ['name' => 'Craig', 'state_id' => 6],
                ['name' => 'Hamilton', 'state_id' => 6],
                ['name' => 'Maybell', 'state_id' => 6],
                ['name' => 'Slater', 'state_id' => 6],
                ['name' => 'Cortez', 'state_id' => 6],
                ['name' => 'Dolores', 'state_id' => 6],
                ['name' => 'Lewis', 'state_id' => 6],
                ['name' => 'Mancos', 'state_id' => 6],
                ['name' => 'Mesa Verde National Park', 'state_id' => 6],
                ['name' => 'Pleasant View', 'state_id' => 6],
                ['name' => 'Towaoc', 'state_id' => 6],
                ['name' => 'Yellow Jacket', 'state_id' => 6],
                ['name' => 'Cimarron', 'state_id' => 6],
                ['name' => 'Montrose', 'state_id' => 6],
                ['name' => 'Bedrock', 'state_id' => 6],
                ['name' => 'Naturita', 'state_id' => 6],
                ['name' => 'Nucla', 'state_id' => 6],
                ['name' => 'Olathe', 'state_id' => 6],
                ['name' => 'Paradox', 'state_id' => 6],
                ['name' => 'Redvale', 'state_id' => 6],
                ['name' => 'Orchard', 'state_id' => 6],
                ['name' => 'Weldona', 'state_id' => 6],
                ['name' => 'Wiggins', 'state_id' => 6],
                ['name' => 'Fort Morgan', 'state_id' => 6],
                ['name' => 'Log Lane Village', 'state_id' => 6],
                ['name' => 'Brush', 'state_id' => 6],
                ['name' => 'Hillrose', 'state_id' => 6],
                ['name' => 'Snyder', 'state_id' => 6],
                ['name' => 'Cheraw', 'state_id' => 6],
                ['name' => 'Fowler', 'state_id' => 6],
                ['name' => 'La Junta', 'state_id' => 6],
                ['name' => 'Manzanola', 'state_id' => 6],
                ['name' => 'Rocky Ford', 'state_id' => 6],
                ['name' => 'Swink', 'state_id' => 6],
                ['name' => 'Ouray', 'state_id' => 6],
                ['name' => 'Ridgway', 'state_id' => 6],
                ['name' => 'Alma', 'state_id' => 6],
                ['name' => 'Bailey', 'state_id' => 6],
                ['name' => 'Como', 'state_id' => 6],
                ['name' => 'Fairplay', 'state_id' => 6],
                ['name' => 'Grant', 'state_id' => 6],
                ['name' => 'Hartsel', 'state_id' => 6],
                ['name' => 'Jefferson', 'state_id' => 6],
                ['name' => 'Shawnee', 'state_id' => 6],
                ['name' => 'Guffey', 'state_id' => 6],
                ['name' => 'Lake George', 'state_id' => 6],
                ['name' => 'Amherst', 'state_id' => 6],
                ['name' => 'Haxtun', 'state_id' => 6],
                ['name' => 'Holyoke', 'state_id' => 6],
                ['name' => 'Paoli', 'state_id' => 6],
                ['name' => 'Aspen', 'state_id' => 6],
                ['name' => 'Snowmass Village', 'state_id' => 6],
                ['name' => 'Meredith', 'state_id' => 6],
                ['name' => 'Snowmass', 'state_id' => 6],
                ['name' => 'Woody Creek', 'state_id' => 6],
                ['name' => 'Granada', 'state_id' => 6],
                ['name' => 'Hartman', 'state_id' => 6],
                ['name' => 'Holly', 'state_id' => 6],
                ['name' => 'Lamar', 'state_id' => 6],
                ['name' => 'Wiley', 'state_id' => 6],
                ['name' => 'Pueblo', 'state_id' => 6],
                ['name' => 'Colorado City', 'state_id' => 6],
                ['name' => 'Avondale', 'state_id' => 6],
                ['name' => 'Beulah', 'state_id' => 6],
                ['name' => 'Boone', 'state_id' => 6],
                ['name' => 'Rye', 'state_id' => 6],
                ['name' => 'Meeker', 'state_id' => 6],
                ['name' => 'Rangely', 'state_id' => 6],
                ['name' => 'Del Norte', 'state_id' => 6],
                ['name' => 'Homelake', 'state_id' => 6],
                ['name' => 'Monte Vista', 'state_id' => 6],
                ['name' => 'South Fork', 'state_id' => 6],
                ['name' => 'Clark', 'state_id' => 6],
                ['name' => 'Oak Creek', 'state_id' => 6],
                ['name' => 'Phippsburg', 'state_id' => 6],
                ['name' => 'Steamboat Springs', 'state_id' => 6],
                ['name' => 'Toponas', 'state_id' => 6],
                ['name' => 'Yampa', 'state_id' => 6],
                ['name' => 'Hayden', 'state_id' => 6],
                ['name' => 'Center', 'state_id' => 6],
                ['name' => 'Crestone', 'state_id' => 6],
                ['name' => 'Moffat', 'state_id' => 6],
                ['name' => 'Saguache', 'state_id' => 6],
                ['name' => 'Villa Grove', 'state_id' => 6],
                ['name' => 'Sargents', 'state_id' => 6],
                ['name' => 'Silverton', 'state_id' => 6],
                ['name' => 'Egnar', 'state_id' => 6],
                ['name' => 'Norwood', 'state_id' => 6],
                ['name' => 'Ophir', 'state_id' => 6],
                ['name' => 'Placerville', 'state_id' => 6],
                ['name' => 'Telluride', 'state_id' => 6],
                ['name' => 'Julesburg', 'state_id' => 6],
                ['name' => 'Ovid', 'state_id' => 6],
                ['name' => 'Sedgwick', 'state_id' => 6],
                ['name' => 'Breckenridge', 'state_id' => 6],
                ['name' => 'Dillon', 'state_id' => 6],
                ['name' => 'Frisco', 'state_id' => 6],
                ['name' => 'Silverthorne', 'state_id' => 6],
                ['name' => 'Cripple Creek', 'state_id' => 6],
                ['name' => 'Divide', 'state_id' => 6],
                ['name' => 'Florissant', 'state_id' => 6],
                ['name' => 'Victor', 'state_id' => 6],
                ['name' => 'Woodland Park', 'state_id' => 6],
                ['name' => 'Akron', 'state_id' => 6],
                ['name' => 'Lindon', 'state_id' => 6],
                ['name' => 'Otis', 'state_id' => 6],
                ['name' => 'Woodrow', 'state_id' => 6],
                ['name' => 'Anton', 'state_id' => 6],
                ['name' => 'Cope', 'state_id' => 6],
                ['name' => 'Dacono', 'state_id' => 6],
                ['name' => 'Erie', 'state_id' => 6],
                ['name' => 'Firestone', 'state_id' => 6],
                ['name' => 'Frederick', 'state_id' => 6],
                ['name' => 'Johnstown', 'state_id' => 6],
                ['name' => 'Mead', 'state_id' => 6],
                ['name' => 'Milliken', 'state_id' => 6],
                ['name' => 'Severance', 'state_id' => 6],
                ['name' => 'Windsor', 'state_id' => 6],
                ['name' => 'Ault', 'state_id' => 6],
                ['name' => 'Briggsdale', 'state_id' => 6],
                ['name' => 'Carr', 'state_id' => 6],
                ['name' => 'Eaton', 'state_id' => 6],
                ['name' => 'Evans', 'state_id' => 6],
                ['name' => 'Fort Lupton', 'state_id' => 6],
                ['name' => 'Galeton', 'state_id' => 6],
                ['name' => 'Gilcrest', 'state_id' => 6],
                ['name' => 'Gill', 'state_id' => 6],
                ['name' => 'Greeley', 'state_id' => 6],
                ['name' => 'Hudson', 'state_id' => 6],
                ['name' => 'Keenesburg', 'state_id' => 6],
                ['name' => 'Kersey', 'state_id' => 6],
                ['name' => 'La Salle', 'state_id' => 6],
                ['name' => 'Lucerne', 'state_id' => 6],
                ['name' => 'Nunn', 'state_id' => 6],
                ['name' => 'Pierce', 'state_id' => 6],
                ['name' => 'Platteville', 'state_id' => 6],
                ['name' => 'Roggen', 'state_id' => 6],
                ['name' => 'Grover', 'state_id' => 6],
                ['name' => 'Hereford', 'state_id' => 6],
                ['name' => 'New Raymer', 'state_id' => 6],
                ['name' => 'Stoneham', 'state_id' => 6],
                ['name' => 'Eckley', 'state_id' => 6],
                ['name' => 'Idalia', 'state_id' => 6],
                ['name' => 'Vernon', 'state_id' => 6],
                ['name' => 'Wray', 'state_id' => 6],
                ['name' => 'Yuma', 'state_id' => 6],
                ['name' => 'Joes', 'state_id' => 6],
                ['name' => 'Kirk', 'state_id' => 6]
            ]);
        }
    }
}
