<?php

use Illuminate\Database\Seeder;

class state19TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of LA - Louisiana.
        //If the table 'cities' exists, insert the data to the table.
        if (DB::table('cities')->get()->count() >= 0) {
            DB::table('cities')->insert([
                ['name' => 'Branch', 'state_id' => 19],
                ['name' => 'Church Point', 'state_id' => 19],
                ['name' => 'Crowley', 'state_id' => 19],
                ['name' => 'Egan', 'state_id' => 19],
                ['name' => 'Estherwood', 'state_id' => 19],
                ['name' => 'Evangeline', 'state_id' => 19],
                ['name' => 'Iota', 'state_id' => 19],
                ['name' => 'Mermentau', 'state_id' => 19],
                ['name' => 'Morse', 'state_id' => 19],
                ['name' => 'Rayne', 'state_id' => 19],
                ['name' => 'Elizabeth', 'state_id' => 19],
                ['name' => 'Grant', 'state_id' => 19],
                ['name' => 'Kinder', 'state_id' => 19],
                ['name' => 'Leblanc', 'state_id' => 19],
                ['name' => 'Mittie', 'state_id' => 19],
                ['name' => 'Oberlin', 'state_id' => 19],
                ['name' => 'Reeves', 'state_id' => 19],
                ['name' => 'Oakdale', 'state_id' => 19],
                ['name' => 'Donaldsonville', 'state_id' => 19],
                ['name' => 'Gonzales', 'state_id' => 19],
                ['name' => 'Brittany', 'state_id' => 19],
                ['name' => 'Darrow', 'state_id' => 19],
                ['name' => 'Duplessis', 'state_id' => 19],
                ['name' => 'Geismar', 'state_id' => 19],
                ['name' => 'Burnside', 'state_id' => 19],
                ['name' => 'Prairieville', 'state_id' => 19],
                ['name' => 'Saint Amant', 'state_id' => 19],
                ['name' => 'Sorrento', 'state_id' => 19],
                ['name' => 'Pierre Part', 'state_id' => 19],
                ['name' => 'Belle Rose', 'state_id' => 19],
                ['name' => 'Labadieville', 'state_id' => 19],
                ['name' => 'Napoleonville', 'state_id' => 19],
                ['name' => 'Paincourtville', 'state_id' => 19],
                ['name' => 'Plattenville', 'state_id' => 19],
                ['name' => 'Bordelonville', 'state_id' => 19],
                ['name' => 'Bunkie', 'state_id' => 19],
                ['name' => 'Center Point', 'state_id' => 19],
                ['name' => 'Cottonport', 'state_id' => 19],
                ['name' => 'Dupont', 'state_id' => 19],
                ['name' => 'Effie', 'state_id' => 19],
                ['name' => 'Evergreen', 'state_id' => 19],
                ['name' => 'Hamburg', 'state_id' => 19],
                ['name' => 'Hessmer', 'state_id' => 19],
                ['name' => 'Mansura', 'state_id' => 19],
                ['name' => 'Marksville', 'state_id' => 19],
                ['name' => 'Moreauville', 'state_id' => 19],
                ['name' => 'Plaucheville', 'state_id' => 19],
                ['name' => 'Simmesport', 'state_id' => 19],
                ['name' => 'Deridder', 'state_id' => 19],
                ['name' => 'Dry Creek', 'state_id' => 19],
                ['name' => 'Longville', 'state_id' => 19],
                ['name' => 'Merryville', 'state_id' => 19],
                ['name' => 'Ragley', 'state_id' => 19],
                ['name' => 'Singer', 'state_id' => 19],
                ['name' => 'Sugartown', 'state_id' => 19],
                ['name' => 'Arcadia', 'state_id' => 19],
                ['name' => 'Bienville', 'state_id' => 19],
                ['name' => 'Castor', 'state_id' => 19],
                ['name' => 'Gibsland', 'state_id' => 19],
                ['name' => 'Jamestown', 'state_id' => 19],
                ['name' => 'Ringgold', 'state_id' => 19],
                ['name' => 'Saline', 'state_id' => 19],
                ['name' => 'Taylor', 'state_id' => 19],
                ['name' => 'Benton', 'state_id' => 19],
                ['name' => 'Haughton', 'state_id' => 19],
                ['name' => 'Elm Grove', 'state_id' => 19],
                ['name' => 'Plain Dealing', 'state_id' => 19],
                ['name' => 'Princeton', 'state_id' => 19],
                ['name' => 'Barksdale Afb', 'state_id' => 19],
                ['name' => 'Bossier City', 'state_id' => 19],
                ['name' => 'Belcher', 'state_id' => 19],
                ['name' => 'Bethany', 'state_id' => 19],
                ['name' => 'Blanchard', 'state_id' => 19],
                ['name' => 'Gilliam', 'state_id' => 19],
                ['name' => 'Greenwood', 'state_id' => 19],
                ['name' => 'Hosston', 'state_id' => 19],
                ['name' => 'Ida', 'state_id' => 19],
                ['name' => 'Keithville', 'state_id' => 19],
                ['name' => 'Mooringsport', 'state_id' => 19],
                ['name' => 'Oil City', 'state_id' => 19],
                ['name' => 'Rodessa', 'state_id' => 19],
                ['name' => 'Vivian', 'state_id' => 19],
                ['name' => 'Shreveport', 'state_id' => 19],
                ['name' => 'Lake Charles', 'state_id' => 19],
                ['name' => 'Bell City', 'state_id' => 19],
                ['name' => 'Dequincy', 'state_id' => 19],
                ['name' => 'Hayes', 'state_id' => 19],
                ['name' => 'Iowa', 'state_id' => 19],
                ['name' => 'Starks', 'state_id' => 19],
                ['name' => 'Sulphur', 'state_id' => 19],
                ['name' => 'Vinton', 'state_id' => 19],
                ['name' => 'Westlake', 'state_id' => 19],
                ['name' => 'Clarks', 'state_id' => 19],
                ['name' => 'Columbia', 'state_id' => 19],
                ['name' => 'Grayson', 'state_id' => 19],
                ['name' => 'Kelly', 'state_id' => 19],
                ['name' => 'Cameron', 'state_id' => 19],
                ['name' => 'Creole', 'state_id' => 19],
                ['name' => 'Grand Chenier', 'state_id' => 19],
                ['name' => 'Hackberry', 'state_id' => 19],
                ['name' => 'Harrisonburg', 'state_id' => 19],
                ['name' => 'Jonesville', 'state_id' => 19],
                ['name' => 'Rhinehart', 'state_id' => 19],
                ['name' => 'Sicily Island', 'state_id' => 19],
                ['name' => 'Aimwell', 'state_id' => 19],
                ['name' => 'Enterprise', 'state_id' => 19],
                ['name' => 'Athens', 'state_id' => 19],
                ['name' => 'Haynesville', 'state_id' => 19],
                ['name' => 'Homer', 'state_id' => 19],
                ['name' => 'Lisbon', 'state_id' => 19],
                ['name' => 'Summerfield', 'state_id' => 19],
                ['name' => 'Acme', 'state_id' => 19],
                ['name' => 'Clayton', 'state_id' => 19],
                ['name' => 'Ferriday', 'state_id' => 19],
                ['name' => 'Monterey', 'state_id' => 19],
                ['name' => 'Vidalia', 'state_id' => 19],
                ['name' => 'Wildsville', 'state_id' => 19],
                ['name' => 'Frierson', 'state_id' => 19],
                ['name' => 'Gloster', 'state_id' => 19],
                ['name' => 'Grand Cane', 'state_id' => 19],
                ['name' => 'Keatchie', 'state_id' => 19],
                ['name' => 'Logansport', 'state_id' => 19],
                ['name' => 'Longstreet', 'state_id' => 19],
                ['name' => 'Mansfield', 'state_id' => 19],
                ['name' => 'Pelican', 'state_id' => 19],
                ['name' => 'Stonewall', 'state_id' => 19],
                ['name' => 'Baker', 'state_id' => 19],
                ['name' => 'Greenwell Springs', 'state_id' => 19],
                ['name' => 'Pride', 'state_id' => 19],
                ['name' => 'Zachary', 'state_id' => 19],
                ['name' => 'Baton Rouge', 'state_id' => 19],
                ['name' => 'Lake Providence', 'state_id' => 19],
                ['name' => 'Sondheimer', 'state_id' => 19],
                ['name' => 'Transylvania', 'state_id' => 19],
                ['name' => 'Clinton', 'state_id' => 19],
                ['name' => 'Ethel', 'state_id' => 19],
                ['name' => 'Jackson', 'state_id' => 19],
                ['name' => 'Norwood', 'state_id' => 19],
                ['name' => 'Slaughter', 'state_id' => 19],
                ['name' => 'Wilson', 'state_id' => 19],
                ['name' => 'Basile', 'state_id' => 19],
                ['name' => 'Chataignier', 'state_id' => 19],
                ['name' => 'Mamou', 'state_id' => 19],
                ['name' => 'Pine Prairie', 'state_id' => 19],
                ['name' => 'Reddell', 'state_id' => 19],
                ['name' => 'Turkey Creek', 'state_id' => 19],
                ['name' => 'Ville Platte', 'state_id' => 19],
                ['name' => 'Saint Landry', 'state_id' => 19],
                ['name' => 'Baskin', 'state_id' => 19],
                ['name' => 'Crowville', 'state_id' => 19],
                ['name' => 'Fort Necessity', 'state_id' => 19],
                ['name' => 'Jigger', 'state_id' => 19],
                ['name' => 'Winnsboro', 'state_id' => 19],
                ['name' => 'Chase', 'state_id' => 19],
                ['name' => 'Gilbert', 'state_id' => 19],
                ['name' => 'Wisner', 'state_id' => 19],
                ['name' => 'Bentley', 'state_id' => 19],
                ['name' => 'Colfax', 'state_id' => 19],
                ['name' => 'Dry Prong', 'state_id' => 19],
                ['name' => 'Georgetown', 'state_id' => 19],
                ['name' => 'Montgomery', 'state_id' => 19],
                ['name' => 'Pollock', 'state_id' => 19],
                ['name' => 'Avery Island', 'state_id' => 19],
                ['name' => 'Jeanerette', 'state_id' => 19],
                ['name' => 'Loreauville', 'state_id' => 19],
                ['name' => 'New Iberia', 'state_id' => 19],
                ['name' => 'Lydia', 'state_id' => 19],
                ['name' => 'Carville', 'state_id' => 19],
                ['name' => 'Grosse Tete', 'state_id' => 19],
                ['name' => 'Maringouin', 'state_id' => 19],
                ['name' => 'Plaquemine', 'state_id' => 19],
                ['name' => 'Rosedale', 'state_id' => 19],
                ['name' => 'Saint Gabriel', 'state_id' => 19],
                ['name' => 'Sunshine', 'state_id' => 19],
                ['name' => 'White Castle', 'state_id' => 19],
                ['name' => 'Chatham', 'state_id' => 19],
                ['name' => 'Eros', 'state_id' => 19],
                ['name' => 'Hodge', 'state_id' => 19],
                ['name' => 'Jonesboro', 'state_id' => 19],
                ['name' => 'Quitman', 'state_id' => 19],
                ['name' => 'Metairie', 'state_id' => 19],
                ['name' => 'Barataria', 'state_id' => 19],
                ['name' => 'Gretna', 'state_id' => 19],
                ['name' => 'Harvey', 'state_id' => 19],
                ['name' => 'Kenner', 'state_id' => 19],
                ['name' => 'Lafitte', 'state_id' => 19],
                ['name' => 'Marrero', 'state_id' => 19],
                ['name' => 'Westwego', 'state_id' => 19],
                ['name' => 'New Orleans', 'state_id' => 19],
                ['name' => 'Grand Isle', 'state_id' => 19],
                ['name' => 'Elton', 'state_id' => 19],
                ['name' => 'Jennings', 'state_id' => 19],
                ['name' => 'Lake Arthur', 'state_id' => 19],
                ['name' => 'Roanoke', 'state_id' => 19],
                ['name' => 'Welsh', 'state_id' => 19],
                ['name' => 'Fenton', 'state_id' => 19],
                ['name' => 'Lacassine', 'state_id' => 19],
                ['name' => 'Lafayette', 'state_id' => 19],
                ['name' => 'Broussard', 'state_id' => 19],
                ['name' => 'Carencro', 'state_id' => 19],
                ['name' => 'Duson', 'state_id' => 19],
                ['name' => 'Milton', 'state_id' => 19],
                ['name' => 'Scott', 'state_id' => 19],
                ['name' => 'Youngsville', 'state_id' => 19],
                ['name' => 'Thibodaux', 'state_id' => 19],
                ['name' => 'Cut Off', 'state_id' => 19],
                ['name' => 'Galliano', 'state_id' => 19],
                ['name' => 'Gheens', 'state_id' => 19],
                ['name' => 'Golden Meadow', 'state_id' => 19],
                ['name' => 'Kraemer', 'state_id' => 19],
                ['name' => 'Larose', 'state_id' => 19],
                ['name' => 'Lockport', 'state_id' => 19],
                ['name' => 'Mathews', 'state_id' => 19],
                ['name' => 'Raceland', 'state_id' => 19],
                ['name' => 'Jena', 'state_id' => 19],
                ['name' => 'Trout', 'state_id' => 19],
                ['name' => 'Olla', 'state_id' => 19],
                ['name' => 'Tullos', 'state_id' => 19],
                ['name' => 'Urania', 'state_id' => 19],
                ['name' => 'Choudrant', 'state_id' => 19],
                ['name' => 'Dubach', 'state_id' => 19],
                ['name' => 'Grambling', 'state_id' => 19],
                ['name' => 'Ruston', 'state_id' => 19],
                ['name' => 'Simsboro', 'state_id' => 19],
                ['name' => 'Maurepas', 'state_id' => 19],
                ['name' => 'Springfield', 'state_id' => 19],
                ['name' => 'Denham Springs', 'state_id' => 19],
                ['name' => 'Albany', 'state_id' => 19],
                ['name' => 'French Settlement', 'state_id' => 19],
                ['name' => 'Holden', 'state_id' => 19],
                ['name' => 'Livingston', 'state_id' => 19],
                ['name' => 'Walker', 'state_id' => 19],
                ['name' => 'Watson', 'state_id' => 19],
                ['name' => 'Delta', 'state_id' => 19],
                ['name' => 'Tallulah', 'state_id' => 19],
                ['name' => 'Bastrop', 'state_id' => 19],
                ['name' => 'Bonita', 'state_id' => 19],
                ['name' => 'Collinston', 'state_id' => 19],
                ['name' => 'Jones', 'state_id' => 19],
                ['name' => 'Mer Rouge', 'state_id' => 19],
                ['name' => 'Oak Ridge', 'state_id' => 19],
                ['name' => 'Ashland', 'state_id' => 19],
                ['name' => 'Goldonna', 'state_id' => 19],
                ['name' => 'Powhatan', 'state_id' => 19],
                ['name' => 'Campti', 'state_id' => 19],
                ['name' => 'Clarence', 'state_id' => 19],
                ['name' => 'Cloutierville', 'state_id' => 19],
                ['name' => 'Flora', 'state_id' => 19],
                ['name' => 'Gorum', 'state_id' => 19],
                ['name' => 'Marthaville', 'state_id' => 19],
                ['name' => 'Melrose', 'state_id' => 19],
                ['name' => 'Mora', 'state_id' => 19],
                ['name' => 'Natchez', 'state_id' => 19],
                ['name' => 'Natchitoches', 'state_id' => 19],
                ['name' => 'Provencal', 'state_id' => 19],
                ['name' => 'Robeline', 'state_id' => 19],
                ['name' => 'Monroe', 'state_id' => 19],
                ['name' => 'Calhoun', 'state_id' => 19],
                ['name' => 'Fairbanks', 'state_id' => 19],
                ['name' => 'Sterlington', 'state_id' => 19],
                ['name' => 'Swartz', 'state_id' => 19],
                ['name' => 'West Monroe', 'state_id' => 19],
                ['name' => 'Belle Chasse', 'state_id' => 19],
                ['name' => 'Boothville', 'state_id' => 19],
                ['name' => 'Braithwaite', 'state_id' => 19],
                ['name' => 'Buras', 'state_id' => 19],
                ['name' => 'Empire', 'state_id' => 19],
                ['name' => 'Pilottown', 'state_id' => 19],
                ['name' => 'Pointe A La Hache', 'state_id' => 19],
                ['name' => 'Port Sulphur', 'state_id' => 19],
                ['name' => 'Venice', 'state_id' => 19],
                ['name' => 'Batchelor', 'state_id' => 19],
                ['name' => 'Fordoche', 'state_id' => 19],
                ['name' => 'Glynn', 'state_id' => 19],
                ['name' => 'Innis', 'state_id' => 19],
                ['name' => 'Jarreau', 'state_id' => 19],
                ['name' => 'Lakeland', 'state_id' => 19],
                ['name' => 'Lettsworth', 'state_id' => 19],
                ['name' => 'Livonia', 'state_id' => 19],
                ['name' => 'Lottie', 'state_id' => 19],
                ['name' => 'Morganza', 'state_id' => 19],
                ['name' => 'New Roads', 'state_id' => 19],
                ['name' => 'Oscar', 'state_id' => 19],
                ['name' => 'Rougon', 'state_id' => 19],
                ['name' => 'Ventress', 'state_id' => 19],
                ['name' => 'Alexandria', 'state_id' => 19],
                ['name' => 'Cheneyville', 'state_id' => 19],
                ['name' => 'Deville', 'state_id' => 19],
                ['name' => 'Echo', 'state_id' => 19],
                ['name' => 'Lecompte', 'state_id' => 19],
                ['name' => 'Libuse', 'state_id' => 19],
                ['name' => 'Pineville', 'state_id' => 19],
                ['name' => 'Ruby', 'state_id' => 19],
                ['name' => 'Ball', 'state_id' => 19],
                ['name' => 'Boyce', 'state_id' => 19],
                ['name' => 'Elmer', 'state_id' => 19],
                ['name' => 'Flatwoods', 'state_id' => 19],
                ['name' => 'Forest Hill', 'state_id' => 19],
                ['name' => 'Gardner', 'state_id' => 19],
                ['name' => 'Glenmora', 'state_id' => 19],
                ['name' => 'Hineston', 'state_id' => 19],
                ['name' => 'Lena', 'state_id' => 19],
                ['name' => 'Longleaf', 'state_id' => 19],
                ['name' => 'Otis', 'state_id' => 19],
                ['name' => 'Sieper', 'state_id' => 19],
                ['name' => 'Tioga', 'state_id' => 19],
                ['name' => 'Woodworth', 'state_id' => 19],
                ['name' => 'Coushatta', 'state_id' => 19],
                ['name' => 'Hall Summit', 'state_id' => 19],
                ['name' => 'Archibald', 'state_id' => 19],
                ['name' => 'Delhi', 'state_id' => 19],
                ['name' => 'Mangham', 'state_id' => 19],
                ['name' => 'Rayville', 'state_id' => 19],
                ['name' => 'Start', 'state_id' => 19],
                ['name' => 'Pleasant Hill', 'state_id' => 19],
                ['name' => 'Belmont', 'state_id' => 19],
                ['name' => 'Converse', 'state_id' => 19],
                ['name' => 'Fisher', 'state_id' => 19],
                ['name' => 'Florien', 'state_id' => 19],
                ['name' => 'Many', 'state_id' => 19],
                ['name' => 'Negreet', 'state_id' => 19],
                ['name' => 'Noble', 'state_id' => 19],
                ['name' => 'Zwolle', 'state_id' => 19],
                ['name' => 'Arabi', 'state_id' => 19],
                ['name' => 'Chalmette', 'state_id' => 19],
                ['name' => 'Meraux', 'state_id' => 19],
                ['name' => 'Saint Bernard', 'state_id' => 19],
                ['name' => 'Violet', 'state_id' => 19],
                ['name' => 'Des Allemands', 'state_id' => 19],
                ['name' => 'Ama', 'state_id' => 19],
                ['name' => 'Boutte', 'state_id' => 19],
                ['name' => 'Destrehan', 'state_id' => 19],
                ['name' => 'Hahnville', 'state_id' => 19],
                ['name' => 'Luling', 'state_id' => 19],
                ['name' => 'New Sarpy', 'state_id' => 19],
                ['name' => 'Norco', 'state_id' => 19],
                ['name' => 'Paradis', 'state_id' => 19],
                ['name' => 'Saint Rose', 'state_id' => 19],
                ['name' => 'Greensburg', 'state_id' => 19],
                ['name' => 'Pine Grove', 'state_id' => 19],
                ['name' => 'Gramercy', 'state_id' => 19],
                ['name' => 'Lutcher', 'state_id' => 19],
                ['name' => 'Saint James', 'state_id' => 19],
                ['name' => 'Vacherie', 'state_id' => 19],
                ['name' => 'Convent', 'state_id' => 19],
                ['name' => 'Hester', 'state_id' => 19],
                ['name' => 'Paulina', 'state_id' => 19],
                ['name' => 'Uncle Sam', 'state_id' => 19],
                ['name' => 'Edgard', 'state_id' => 19],
                ['name' => 'Garyville', 'state_id' => 19],
                ['name' => 'La Place', 'state_id' => 19],
                ['name' => 'Mount Airy', 'state_id' => 19],
                ['name' => 'Reserve', 'state_id' => 19],
                ['name' => 'Arnaudville', 'state_id' => 19],
                ['name' => 'Eunice', 'state_id' => 19],
                ['name' => 'Grand Coteau', 'state_id' => 19],
                ['name' => 'Lawtell', 'state_id' => 19],
                ['name' => 'Leonville', 'state_id' => 19],
                ['name' => 'Opelousas', 'state_id' => 19],
                ['name' => 'Port Barre', 'state_id' => 19],
                ['name' => 'Sunset', 'state_id' => 19],
                ['name' => 'Washington', 'state_id' => 19],
                ['name' => 'Krotz Springs', 'state_id' => 19],
                ['name' => 'Lebeau', 'state_id' => 19],
                ['name' => 'Melville', 'state_id' => 19],
                ['name' => 'Morrow', 'state_id' => 19],
                ['name' => 'Palmetto', 'state_id' => 19],
                ['name' => 'Breaux Bridge', 'state_id' => 19],
                ['name' => 'Cade', 'state_id' => 19],
                ['name' => 'Cecilia', 'state_id' => 19],
                ['name' => 'Saint Martinville', 'state_id' => 19],
                ['name' => 'Amelia', 'state_id' => 19],
                ['name' => 'Berwick', 'state_id' => 19],
                ['name' => 'Morgan City', 'state_id' => 19],
                ['name' => 'Patterson', 'state_id' => 19],
                ['name' => 'Baldwin', 'state_id' => 19],
                ['name' => 'Centerville', 'state_id' => 19],
                ['name' => 'Charenton', 'state_id' => 19],
                ['name' => 'Franklin', 'state_id' => 19],
                ['name' => 'Garden City', 'state_id' => 19],
                ['name' => 'Abita Springs', 'state_id' => 19],
                ['name' => 'Bush', 'state_id' => 19],
                ['name' => 'Covington', 'state_id' => 19],
                ['name' => 'Folsom', 'state_id' => 19],
                ['name' => 'Lacombe', 'state_id' => 19],
                ['name' => 'Madisonville', 'state_id' => 19],
                ['name' => 'Mandeville', 'state_id' => 19],
                ['name' => 'Pearl River', 'state_id' => 19],
                ['name' => 'Saint Benedict', 'state_id' => 19],
                ['name' => 'Slidell', 'state_id' => 19],
                ['name' => 'Sun', 'state_id' => 19],
                ['name' => 'Talisheek', 'state_id' => 19],
                ['name' => 'Hammond', 'state_id' => 19],
                ['name' => 'Akers', 'state_id' => 19],
                ['name' => 'Amite', 'state_id' => 19],
                ['name' => 'Fluker', 'state_id' => 19],
                ['name' => 'Husser', 'state_id' => 19],
                ['name' => 'Independence', 'state_id' => 19],
                ['name' => 'Kentwood', 'state_id' => 19],
                ['name' => 'Loranger', 'state_id' => 19],
                ['name' => 'Natalbany', 'state_id' => 19],
                ['name' => 'Ponchatoula', 'state_id' => 19],
                ['name' => 'Robert', 'state_id' => 19],
                ['name' => 'Roseland', 'state_id' => 19],
                ['name' => 'Tangipahoa', 'state_id' => 19],
                ['name' => 'Tickfaw', 'state_id' => 19],
                ['name' => 'Newellton', 'state_id' => 19],
                ['name' => 'Saint Joseph', 'state_id' => 19],
                ['name' => 'Waterproof', 'state_id' => 19],
                ['name' => 'Bourg', 'state_id' => 19],
                ['name' => 'Chauvin', 'state_id' => 19],
                ['name' => 'Donner', 'state_id' => 19],
                ['name' => 'Dulac', 'state_id' => 19],
                ['name' => 'Gibson', 'state_id' => 19],
                ['name' => 'Gray', 'state_id' => 19],
                ['name' => 'Houma', 'state_id' => 19],
                ['name' => 'Montegut', 'state_id' => 19],
                ['name' => 'Schriever', 'state_id' => 19],
                ['name' => 'Theriot', 'state_id' => 19],
                ['name' => 'Bernice', 'state_id' => 19],
                ['name' => 'Downsville', 'state_id' => 19],
                ['name' => 'Farmerville', 'state_id' => 19],
                ['name' => 'Lillie', 'state_id' => 19],
                ['name' => 'Marion', 'state_id' => 19],
                ['name' => 'Spearsville', 'state_id' => 19],
                ['name' => 'Abbeville', 'state_id' => 19],
                ['name' => 'Delcambre', 'state_id' => 19],
                ['name' => 'Erath', 'state_id' => 19],
                ['name' => 'Gueydan', 'state_id' => 19],
                ['name' => 'Kaplan', 'state_id' => 19],
                ['name' => 'Maurice', 'state_id' => 19],
                ['name' => 'Perry', 'state_id' => 19],
                ['name' => 'Evans', 'state_id' => 19],
                ['name' => 'Pitkin', 'state_id' => 19],
                ['name' => 'Rosepine', 'state_id' => 19],
                ['name' => 'Anacoco', 'state_id' => 19],
                ['name' => 'Hornbeck', 'state_id' => 19],
                ['name' => 'Kurthwood', 'state_id' => 19],
                ['name' => 'Leesville', 'state_id' => 19],
                ['name' => 'Fort Polk', 'state_id' => 19],
                ['name' => 'New Llano', 'state_id' => 19],
                ['name' => 'Simpson', 'state_id' => 19],
                ['name' => 'Slagle', 'state_id' => 19],
                ['name' => 'Angie', 'state_id' => 19],
                ['name' => 'Bogalusa', 'state_id' => 19],
                ['name' => 'Franklinton', 'state_id' => 19],
                ['name' => 'Mount Hermon', 'state_id' => 19],
                ['name' => 'Varnado', 'state_id' => 19],
                ['name' => 'Cotton Valley', 'state_id' => 19],
                ['name' => 'Cullen', 'state_id' => 19],
                ['name' => 'Doyline', 'state_id' => 19],
                ['name' => 'Dubberly', 'state_id' => 19],
                ['name' => 'Heflin', 'state_id' => 19],
                ['name' => 'Minden', 'state_id' => 19],
                ['name' => 'Sarepta', 'state_id' => 19],
                ['name' => 'Shongaloo', 'state_id' => 19],
                ['name' => 'Sibley', 'state_id' => 19],
                ['name' => 'Springhill', 'state_id' => 19],
                ['name' => 'Addis', 'state_id' => 19],
                ['name' => 'Brusly', 'state_id' => 19],
                ['name' => 'Erwinville', 'state_id' => 19],
                ['name' => 'Port Allen', 'state_id' => 19],
                ['name' => 'Epps', 'state_id' => 19],
                ['name' => 'Forest', 'state_id' => 19],
                ['name' => 'Kilbourne', 'state_id' => 19],
                ['name' => 'Oak Grove', 'state_id' => 19],
                ['name' => 'Pioneer', 'state_id' => 19],
                ['name' => 'Angola', 'state_id' => 19],
                ['name' => 'Saint Francisville', 'state_id' => 19],
                ['name' => 'Tunica', 'state_id' => 19],
                ['name' => 'Wakefield', 'state_id' => 19],
                ['name' => 'Weyanoke', 'state_id' => 19],
                ['name' => 'Atlanta', 'state_id' => 19],
                ['name' => 'Calvin', 'state_id' => 19],
                ['name' => 'Dodson', 'state_id' => 19],
                ['name' => 'Joyce', 'state_id' => 19],
                ['name' => 'Saint Maurice', 'state_id' => 19],
                ['name' => 'Sikes', 'state_id' => 19],
                ['name' => 'Winnfield', 'state_id' => 19]
            ]);
        }
    }
}
