<?php

use Illuminate\Database\Seeder;

class state51TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of WY - Wyoming.
        //If the table 'cities' exists, insert the data to the table.
        if (DB::table('cities')->get()->count() >= 0) {
            DB::table('cities')->insert([
                ['name' => 'Bosler', 'state_id' => 51],
                ['name' => 'Buford', 'state_id' => 51],
                ['name' => 'Centennial', 'state_id' => 51],
                ['name' => 'Garrett', 'state_id' => 51],
                ['name' => 'Jelm', 'state_id' => 51],
                ['name' => 'Laramie', 'state_id' => 51],
                ['name' => 'Rock River', 'state_id' => 51],
                ['name' => 'Tie Siding', 'state_id' => 51],
                ['name' => 'Basin', 'state_id' => 51],
                ['name' => 'Burlington', 'state_id' => 51],
                ['name' => 'Byron', 'state_id' => 51],
                ['name' => 'Cowley', 'state_id' => 51],
                ['name' => 'Deaver', 'state_id' => 51],
                ['name' => 'Emblem', 'state_id' => 51],
                ['name' => 'Greybull', 'state_id' => 51],
                ['name' => 'Hyattville', 'state_id' => 51],
                ['name' => 'Lovell', 'state_id' => 51],
                ['name' => 'Manderson', 'state_id' => 51],
                ['name' => 'Otto', 'state_id' => 51],
                ['name' => 'Shell', 'state_id' => 51],
                ['name' => 'Gillette', 'state_id' => 51],
                ['name' => 'Recluse', 'state_id' => 51],
                ['name' => 'Rozet', 'state_id' => 51],
                ['name' => 'Weston', 'state_id' => 51],
                ['name' => 'Wright', 'state_id' => 51],
                ['name' => 'Rawlins', 'state_id' => 51],
                ['name' => 'Baggs', 'state_id' => 51],
                ['name' => 'Dixon', 'state_id' => 51],
                ['name' => 'Elk Mountain', 'state_id' => 51],
                ['name' => 'Encampment', 'state_id' => 51],
                ['name' => 'Hanna', 'state_id' => 51],
                ['name' => 'Medicine Bow', 'state_id' => 51],
                ['name' => 'Saratoga', 'state_id' => 51],
                ['name' => 'Savery', 'state_id' => 51],
                ['name' => 'Sinclair', 'state_id' => 51],
                ['name' => 'Walcott', 'state_id' => 51],
                ['name' => 'Shirley Basin', 'state_id' => 51],
                ['name' => 'Lost Springs', 'state_id' => 51],
                ['name' => 'Shawnee', 'state_id' => 51],
                ['name' => 'Douglas', 'state_id' => 51],
                ['name' => 'Glenrock', 'state_id' => 51],
                ['name' => 'Aladdin', 'state_id' => 51],
                ['name' => 'Alva', 'state_id' => 51],
                ['name' => 'Beulah', 'state_id' => 51],
                ['name' => 'Devils Tower', 'state_id' => 51],
                ['name' => 'Hulett', 'state_id' => 51],
                ['name' => 'Moorcroft', 'state_id' => 51],
                ['name' => 'Sundance', 'state_id' => 51],
                ['name' => 'Jeffrey City', 'state_id' => 51],
                ['name' => 'Riverton', 'state_id' => 51],
                ['name' => 'Arapahoe', 'state_id' => 51],
                ['name' => 'Crowheart', 'state_id' => 51],
                ['name' => 'Dubois', 'state_id' => 51],
                ['name' => 'Fort Washakie', 'state_id' => 51],
                ['name' => 'Hudson', 'state_id' => 51],
                ['name' => 'Kinnear', 'state_id' => 51],
                ['name' => 'Lander', 'state_id' => 51],
                ['name' => 'Pavillion', 'state_id' => 51],
                ['name' => 'Saint Stephens', 'state_id' => 51],
                ['name' => 'Lysite', 'state_id' => 51],
                ['name' => 'Shoshoni', 'state_id' => 51],
                ['name' => 'Fort Laramie', 'state_id' => 51],
                ['name' => 'Hawk Springs', 'state_id' => 51],
                ['name' => 'Huntley', 'state_id' => 51],
                ['name' => 'Jay Em', 'state_id' => 51],
                ['name' => 'Lagrange', 'state_id' => 51],
                ['name' => 'Lingle', 'state_id' => 51],
                ['name' => 'Torrington', 'state_id' => 51],
                ['name' => 'Veteran', 'state_id' => 51],
                ['name' => 'Yoder', 'state_id' => 51],
                ['name' => 'Kirby', 'state_id' => 51],
                ['name' => 'Thermopolis', 'state_id' => 51],
                ['name' => 'Kaycee', 'state_id' => 51],
                ['name' => 'Linch', 'state_id' => 51],
                ['name' => 'Buffalo', 'state_id' => 51],
                ['name' => 'Saddlestring', 'state_id' => 51],
                ['name' => 'Cheyenne', 'state_id' => 51],
                ['name' => 'Fe Warren Afb', 'state_id' => 51],
                ['name' => 'Albin', 'state_id' => 51],
                ['name' => 'Burns', 'state_id' => 51],
                ['name' => 'Carpenter', 'state_id' => 51],
                ['name' => 'Granite Canon', 'state_id' => 51],
                ['name' => 'Hillsdale', 'state_id' => 51],
                ['name' => 'Horse Creek', 'state_id' => 51],
                ['name' => 'Meriden', 'state_id' => 51],
                ['name' => 'Pine Bluffs', 'state_id' => 51],
                ['name' => 'Kemmerer', 'state_id' => 51],
                ['name' => 'Afton', 'state_id' => 51],
                ['name' => 'Auburn', 'state_id' => 51],
                ['name' => 'Bedford', 'state_id' => 51],
                ['name' => 'Cokeville', 'state_id' => 51],
                ['name' => 'Diamondville', 'state_id' => 51],
                ['name' => 'Etna', 'state_id' => 51],
                ['name' => 'Fairview', 'state_id' => 51],
                ['name' => 'Freedom', 'state_id' => 51],
                ['name' => 'Frontier', 'state_id' => 51],
                ['name' => 'Grover', 'state_id' => 51],
                ['name' => 'La Barge', 'state_id' => 51],
                ['name' => 'Opal', 'state_id' => 51],
                ['name' => 'Smoot', 'state_id' => 51],
                ['name' => 'Thayne', 'state_id' => 51],
                ['name' => 'Alpine', 'state_id' => 51],
                ['name' => 'Casper', 'state_id' => 51],
                ['name' => 'Alcova', 'state_id' => 51],
                ['name' => 'Arminto', 'state_id' => 51],
                ['name' => 'Edgerton', 'state_id' => 51],
                ['name' => 'Evansville', 'state_id' => 51],
                ['name' => 'Hiland', 'state_id' => 51],
                ['name' => 'Midwest', 'state_id' => 51],
                ['name' => 'Mills', 'state_id' => 51],
                ['name' => 'Natrona', 'state_id' => 51],
                ['name' => 'Powder River', 'state_id' => 51],
                ['name' => 'Lance Creek', 'state_id' => 51],
                ['name' => 'Lusk', 'state_id' => 51],
                ['name' => 'Manville', 'state_id' => 51],
                ['name' => 'Van Tassell', 'state_id' => 51],
                ['name' => 'Yellowstone National Park', 'state_id' => 51],
                ['name' => 'Cody', 'state_id' => 51],
                ['name' => 'Frannie', 'state_id' => 51],
                ['name' => 'Meeteetse', 'state_id' => 51],
                ['name' => 'Powell', 'state_id' => 51],
                ['name' => 'Ralston', 'state_id' => 51],
                ['name' => 'Wapiti', 'state_id' => 51],
                ['name' => 'Wheatland', 'state_id' => 51],
                ['name' => 'Chugwater', 'state_id' => 51],
                ['name' => 'Glendo', 'state_id' => 51],
                ['name' => 'Guernsey', 'state_id' => 51],
                ['name' => 'Hartville', 'state_id' => 51],
                ['name' => 'Sheridan', 'state_id' => 51],
                ['name' => 'Arvada', 'state_id' => 51],
                ['name' => 'Banner', 'state_id' => 51],
                ['name' => 'Big Horn', 'state_id' => 51],
                ['name' => 'Clearmont', 'state_id' => 51],
                ['name' => 'Dayton', 'state_id' => 51],
                ['name' => 'Leiter', 'state_id' => 51],
                ['name' => 'Parkman', 'state_id' => 51],
                ['name' => 'Ranchester', 'state_id' => 51],
                ['name' => 'Story', 'state_id' => 51],
                ['name' => 'Wolf', 'state_id' => 51],
                ['name' => 'Wyarno', 'state_id' => 51],
                ['name' => 'Bondurant', 'state_id' => 51],
                ['name' => 'Boulder', 'state_id' => 51],
                ['name' => 'Cora', 'state_id' => 51],
                ['name' => 'Pinedale', 'state_id' => 51],
                ['name' => 'Big Piney', 'state_id' => 51],
                ['name' => 'Daniel', 'state_id' => 51],
                ['name' => 'Bairoil', 'state_id' => 51],
                ['name' => 'Wamsutter', 'state_id' => 51],
                ['name' => 'Rock Springs', 'state_id' => 51],
                ['name' => 'Little America', 'state_id' => 51],
                ['name' => 'Farson', 'state_id' => 51],
                ['name' => 'Granger', 'state_id' => 51],
                ['name' => 'Green River', 'state_id' => 51],
                ['name' => 'Mc Kinnon', 'state_id' => 51],
                ['name' => 'Point Of Rocks', 'state_id' => 51],
                ['name' => 'Reliance', 'state_id' => 51],
                ['name' => 'Superior', 'state_id' => 51],
                ['name' => 'Jackson', 'state_id' => 51],
                ['name' => 'Kelly', 'state_id' => 51],
                ['name' => 'Moose', 'state_id' => 51],
                ['name' => 'Moran', 'state_id' => 51],
                ['name' => 'Wilson', 'state_id' => 51],
                ['name' => 'Teton Village', 'state_id' => 51],
                ['name' => 'Alta', 'state_id' => 51],
                ['name' => 'Evanston', 'state_id' => 51],
                ['name' => 'Fort Bridger', 'state_id' => 51],
                ['name' => 'Lonetree', 'state_id' => 51],
                ['name' => 'Lyman', 'state_id' => 51],
                ['name' => 'Mountain View', 'state_id' => 51],
                ['name' => 'Robertson', 'state_id' => 51],
                ['name' => 'Worland', 'state_id' => 51],
                ['name' => 'Ten Sleep', 'state_id' => 51],
                ['name' => 'Newcastle', 'state_id' => 51],
                ['name' => 'Four Corners', 'state_id' => 51],
                ['name' => 'Osage', 'state_id' => 51],
                ['name' => 'Upton', 'state_id' => 51]
            ]);
        }
    }
}
