<?php

use Illuminate\Database\Seeder;

class state35TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of NY - New York.
        //If the table 'cities' exists, insert the data to the table.
        if (DB::table('cities')->get()->count() >= 0) {
            DB::table('cities')->insert([
                ['name' => 'Alcove', 'state_id' => 35],
                ['name' => 'Altamont', 'state_id' => 35],
                ['name' => 'Berne', 'state_id' => 35],
                ['name' => 'Clarksville', 'state_id' => 35],
                ['name' => 'Coeymans', 'state_id' => 35],
                ['name' => 'Coeymans Hollow', 'state_id' => 35],
                ['name' => 'Cohoes', 'state_id' => 35],
                ['name' => 'Delmar', 'state_id' => 35],
                ['name' => 'Dormansville', 'state_id' => 35],
                ['name' => 'East Berne', 'state_id' => 35],
                ['name' => 'Feura Bush', 'state_id' => 35],
                ['name' => 'Glenmont', 'state_id' => 35],
                ['name' => 'Guilderland', 'state_id' => 35],
                ['name' => 'Guilderland Center', 'state_id' => 35],
                ['name' => 'Knox', 'state_id' => 35],
                ['name' => 'Latham', 'state_id' => 35],
                ['name' => 'Medusa', 'state_id' => 35],
                ['name' => 'Newtonville', 'state_id' => 35],
                ['name' => 'Ravena', 'state_id' => 35],
                ['name' => 'Rensselaerville', 'state_id' => 35],
                ['name' => 'Selkirk', 'state_id' => 35],
                ['name' => 'Slingerlands', 'state_id' => 35],
                ['name' => 'South Bethlehem', 'state_id' => 35],
                ['name' => 'Troy', 'state_id' => 35],
                ['name' => 'Voorheesville', 'state_id' => 35],
                ['name' => 'Watervliet', 'state_id' => 35],
                ['name' => 'Westerlo', 'state_id' => 35],
                ['name' => 'Albany', 'state_id' => 35],
                ['name' => 'Preston Hollow', 'state_id' => 35],
                ['name' => 'Centerville', 'state_id' => 35],
                ['name' => 'Allentown', 'state_id' => 35],
                ['name' => 'Alma', 'state_id' => 35],
                ['name' => 'Angelica', 'state_id' => 35],
                ['name' => 'Belfast', 'state_id' => 35],
                ['name' => 'Black Creek', 'state_id' => 35],
                ['name' => 'Bolivar', 'state_id' => 35],
                ['name' => 'Caneadea', 'state_id' => 35],
                ['name' => 'Ceres', 'state_id' => 35],
                ['name' => 'Cuba', 'state_id' => 35],
                ['name' => 'Fillmore', 'state_id' => 35],
                ['name' => 'Friendship', 'state_id' => 35],
                ['name' => 'Houghton', 'state_id' => 35],
                ['name' => 'Hume', 'state_id' => 35],
                ['name' => 'Little Genesee', 'state_id' => 35],
                ['name' => 'Richburg', 'state_id' => 35],
                ['name' => 'Rushford', 'state_id' => 35],
                ['name' => 'West Clarksville', 'state_id' => 35],
                ['name' => 'Alfred', 'state_id' => 35],
                ['name' => 'Alfred Station', 'state_id' => 35],
                ['name' => 'Almond', 'state_id' => 35],
                ['name' => 'Andover', 'state_id' => 35],
                ['name' => 'Belmont', 'state_id' => 35],
                ['name' => 'Canaseraga', 'state_id' => 35],
                ['name' => 'Scio', 'state_id' => 35],
                ['name' => 'Swain', 'state_id' => 35],
                ['name' => 'Wellsville', 'state_id' => 35],
                ['name' => 'Whitesville', 'state_id' => 35],
                ['name' => 'Bronx', 'state_id' => 35],
                ['name' => 'Bible School Park', 'state_id' => 35],
                ['name' => 'Castle Creek', 'state_id' => 35],
                ['name' => 'Chenango Bridge', 'state_id' => 35],
                ['name' => 'Chenango Forks', 'state_id' => 35],
                ['name' => 'Conklin', 'state_id' => 35],
                ['name' => 'Corbettsville', 'state_id' => 35],
                ['name' => 'Deposit', 'state_id' => 35],
                ['name' => 'Endicott', 'state_id' => 35],
                ['name' => 'Endwell', 'state_id' => 35],
                ['name' => 'Glen Aubrey', 'state_id' => 35],
                ['name' => 'Harpursville', 'state_id' => 35],
                ['name' => 'Johnson City', 'state_id' => 35],
                ['name' => 'Killawog', 'state_id' => 35],
                ['name' => 'Kirkwood', 'state_id' => 35],
                ['name' => 'Lisle', 'state_id' => 35],
                ['name' => 'Maine', 'state_id' => 35],
                ['name' => 'Nineveh', 'state_id' => 35],
                ['name' => 'Ouaquaga', 'state_id' => 35],
                ['name' => 'Port Crane', 'state_id' => 35],
                ['name' => 'Tunnel', 'state_id' => 35],
                ['name' => 'Vestal', 'state_id' => 35],
                ['name' => 'Whitney Point', 'state_id' => 35],
                ['name' => 'Windsor', 'state_id' => 35],
                ['name' => 'Binghamton', 'state_id' => 35],
                ['name' => 'Dayton', 'state_id' => 35],
                ['name' => 'Delevan', 'state_id' => 35],
                ['name' => 'Farmersville Station', 'state_id' => 35],
                ['name' => 'Freedom', 'state_id' => 35],
                ['name' => 'Gowanda', 'state_id' => 35],
                ['name' => 'Machias', 'state_id' => 35],
                ['name' => 'Perrysburg', 'state_id' => 35],
                ['name' => 'Sandusky', 'state_id' => 35],
                ['name' => 'South Dayton', 'state_id' => 35],
                ['name' => 'Versailles', 'state_id' => 35],
                ['name' => 'West Valley', 'state_id' => 35],
                ['name' => 'Yorkshire', 'state_id' => 35],
                ['name' => 'Allegany', 'state_id' => 35],
                ['name' => 'Cattaraugus', 'state_id' => 35],
                ['name' => 'Conewango Valley', 'state_id' => 35],
                ['name' => 'East Otto', 'state_id' => 35],
                ['name' => 'East Randolph', 'state_id' => 35],
                ['name' => 'Ellicottville', 'state_id' => 35],
                ['name' => 'Franklinville', 'state_id' => 35],
                ['name' => 'Great Valley', 'state_id' => 35],
                ['name' => 'Hinsdale', 'state_id' => 35],
                ['name' => 'Kill Buck', 'state_id' => 35],
                ['name' => 'Leon', 'state_id' => 35],
                ['name' => 'Limestone', 'state_id' => 35],
                ['name' => 'Little Valley', 'state_id' => 35],
                ['name' => 'Olean', 'state_id' => 35],
                ['name' => 'Otto', 'state_id' => 35],
                ['name' => 'Portville', 'state_id' => 35],
                ['name' => 'Randolph', 'state_id' => 35],
                ['name' => 'Saint Bonaventure', 'state_id' => 35],
                ['name' => 'Salamanca', 'state_id' => 35],
                ['name' => 'Steamburg', 'state_id' => 35],
                ['name' => 'Westons Mills', 'state_id' => 35],
                ['name' => 'Auburn', 'state_id' => 35],
                ['name' => 'Aurora', 'state_id' => 35],
                ['name' => 'Cato', 'state_id' => 35],
                ['name' => 'Cayuga', 'state_id' => 35],
                ['name' => 'Genoa', 'state_id' => 35],
                ['name' => 'King Ferry', 'state_id' => 35],
                ['name' => 'Locke', 'state_id' => 35],
                ['name' => 'Martville', 'state_id' => 35],
                ['name' => 'Meridian', 'state_id' => 35],
                ['name' => 'Montezuma', 'state_id' => 35],
                ['name' => 'Moravia', 'state_id' => 35],
                ['name' => 'Poplar Ridge', 'state_id' => 35],
                ['name' => 'Port Byron', 'state_id' => 35],
                ['name' => 'Scipio Center', 'state_id' => 35],
                ['name' => 'Sterling', 'state_id' => 35],
                ['name' => 'Union Springs', 'state_id' => 35],
                ['name' => 'Weedsport', 'state_id' => 35],
                ['name' => 'Dunkirk', 'state_id' => 35],
                ['name' => 'Forestville', 'state_id' => 35],
                ['name' => 'Fredonia', 'state_id' => 35],
                ['name' => 'Irving', 'state_id' => 35],
                ['name' => 'Sheridan', 'state_id' => 35],
                ['name' => 'Silver Creek', 'state_id' => 35],
                ['name' => 'Van Buren Point', 'state_id' => 35],
                ['name' => 'Jamestown', 'state_id' => 35],
                ['name' => 'Ashville', 'state_id' => 35],
                ['name' => 'Bemus Point', 'state_id' => 35],
                ['name' => 'Brocton', 'state_id' => 35],
                ['name' => 'Cassadaga', 'state_id' => 35],
                ['name' => 'Celoron', 'state_id' => 35],
                ['name' => 'Chautauqua', 'state_id' => 35],
                ['name' => 'Cherry Creek', 'state_id' => 35],
                ['name' => 'Clymer', 'state_id' => 35],
                ['name' => 'Dewittville', 'state_id' => 35],
                ['name' => 'Ellington', 'state_id' => 35],
                ['name' => 'Falconer', 'state_id' => 35],
                ['name' => 'Findley Lake', 'state_id' => 35],
                ['name' => 'Frewsburg', 'state_id' => 35],
                ['name' => 'Gerry', 'state_id' => 35],
                ['name' => 'Greenhurst', 'state_id' => 35],
                ['name' => 'Kennedy', 'state_id' => 35],
                ['name' => 'Lakewood', 'state_id' => 35],
                ['name' => 'Lily Dale', 'state_id' => 35],
                ['name' => 'Maple Springs', 'state_id' => 35],
                ['name' => 'Mayville', 'state_id' => 35],
                ['name' => 'Niobe', 'state_id' => 35],
                ['name' => 'Panama', 'state_id' => 35],
                ['name' => 'Portland', 'state_id' => 35],
                ['name' => 'Ripley', 'state_id' => 35],
                ['name' => 'Sherman', 'state_id' => 35],
                ['name' => 'Sinclairville', 'state_id' => 35],
                ['name' => 'Stockton', 'state_id' => 35],
                ['name' => 'Stow', 'state_id' => 35],
                ['name' => 'Westfield', 'state_id' => 35],
                ['name' => 'Big Flats', 'state_id' => 35],
                ['name' => 'Breesport', 'state_id' => 35],
                ['name' => 'Chemung', 'state_id' => 35],
                ['name' => 'Erin', 'state_id' => 35],
                ['name' => 'Horseheads', 'state_id' => 35],
                ['name' => 'Lowman', 'state_id' => 35],
                ['name' => 'Millport', 'state_id' => 35],
                ['name' => 'Pine City', 'state_id' => 35],
                ['name' => 'Pine Valley', 'state_id' => 35],
                ['name' => 'Van Etten', 'state_id' => 35],
                ['name' => 'Wellsburg', 'state_id' => 35],
                ['name' => 'Elmira', 'state_id' => 35],
                ['name' => 'North Pitcher', 'state_id' => 35],
                ['name' => 'Pitcher', 'state_id' => 35],
                ['name' => 'South Otselic', 'state_id' => 35],
                ['name' => 'Earlville', 'state_id' => 35],
                ['name' => 'New Berlin', 'state_id' => 35],
                ['name' => 'Sherburne', 'state_id' => 35],
                ['name' => 'Smyrna', 'state_id' => 35],
                ['name' => 'Afton', 'state_id' => 35],
                ['name' => 'Bainbridge', 'state_id' => 35],
                ['name' => 'East Pharsalia', 'state_id' => 35],
                ['name' => 'Greene', 'state_id' => 35],
                ['name' => 'Guilford', 'state_id' => 35],
                ['name' => 'Mc Donough', 'state_id' => 35],
                ['name' => 'Mount Upton', 'state_id' => 35],
                ['name' => 'North Norwich', 'state_id' => 35],
                ['name' => 'Norwich', 'state_id' => 35],
                ['name' => 'Oxford', 'state_id' => 35],
                ['name' => 'Plymouth', 'state_id' => 35],
                ['name' => 'Smithville Flats', 'state_id' => 35],
                ['name' => 'South New Berlin', 'state_id' => 35],
                ['name' => 'South Plymouth', 'state_id' => 35],
                ['name' => 'Plattsburgh', 'state_id' => 35],
                ['name' => 'Altona', 'state_id' => 35],
                ['name' => 'Keeseville', 'state_id' => 35],
                ['name' => 'Au Sable Forks', 'state_id' => 35],
                ['name' => 'Cadyville', 'state_id' => 35],
                ['name' => 'Champlain', 'state_id' => 35],
                ['name' => 'Chazy', 'state_id' => 35],
                ['name' => 'Churubusco', 'state_id' => 35],
                ['name' => 'Dannemora', 'state_id' => 35],
                ['name' => 'Ellenburg', 'state_id' => 35],
                ['name' => 'Ellenburg Center', 'state_id' => 35],
                ['name' => 'Ellenburg Depot', 'state_id' => 35],
                ['name' => 'Lyon Mountain', 'state_id' => 35],
                ['name' => 'Mooers', 'state_id' => 35],
                ['name' => 'Mooers Forks', 'state_id' => 35],
                ['name' => 'Morrisonville', 'state_id' => 35],
                ['name' => 'Peru', 'state_id' => 35],
                ['name' => 'Redford', 'state_id' => 35],
                ['name' => 'Rouses Point', 'state_id' => 35],
                ['name' => 'Saranac', 'state_id' => 35],
                ['name' => 'Schuyler Falls', 'state_id' => 35],
                ['name' => 'West Chazy', 'state_id' => 35],
                ['name' => 'Austerlitz', 'state_id' => 35],
                ['name' => 'Canaan', 'state_id' => 35],
                ['name' => 'Chatham', 'state_id' => 35],
                ['name' => 'Columbiaville', 'state_id' => 35],
                ['name' => 'East Chatham', 'state_id' => 35],
                ['name' => 'Ghent', 'state_id' => 35],
                ['name' => 'Kinderhook', 'state_id' => 35],
                ['name' => 'Malden Bridge', 'state_id' => 35],
                ['name' => 'New Lebanon', 'state_id' => 35],
                ['name' => 'Niverville', 'state_id' => 35],
                ['name' => 'North Chatham', 'state_id' => 35],
                ['name' => 'Old Chatham', 'state_id' => 35],
                ['name' => 'Spencertown', 'state_id' => 35],
                ['name' => 'Stottville', 'state_id' => 35],
                ['name' => 'Stuyvesant', 'state_id' => 35],
                ['name' => 'Stuyvesant Falls', 'state_id' => 35],
                ['name' => 'Valatie', 'state_id' => 35],
                ['name' => 'West Lebanon', 'state_id' => 35],
                ['name' => 'Ancram', 'state_id' => 35],
                ['name' => 'Ancramdale', 'state_id' => 35],
                ['name' => 'Claverack', 'state_id' => 35],
                ['name' => 'Copake', 'state_id' => 35],
                ['name' => 'Copake Falls', 'state_id' => 35],
                ['name' => 'Craryville', 'state_id' => 35],
                ['name' => 'Elizaville', 'state_id' => 35],
                ['name' => 'Germantown', 'state_id' => 35],
                ['name' => 'Hillsdale', 'state_id' => 35],
                ['name' => 'Hollowville', 'state_id' => 35],
                ['name' => 'Hudson', 'state_id' => 35],
                ['name' => 'Livingston', 'state_id' => 35],
                ['name' => 'Mellenville', 'state_id' => 35],
                ['name' => 'Philmont', 'state_id' => 35],
                ['name' => 'Cincinnatus', 'state_id' => 35],
                ['name' => 'Cortland', 'state_id' => 35],
                ['name' => 'East Homer', 'state_id' => 35],
                ['name' => 'Homer', 'state_id' => 35],
                ['name' => 'Little York', 'state_id' => 35],
                ['name' => 'Mc Graw', 'state_id' => 35],
                ['name' => 'Preble', 'state_id' => 35],
                ['name' => 'Truxton', 'state_id' => 35],
                ['name' => 'Blodgett Mills', 'state_id' => 35],
                ['name' => 'Harford', 'state_id' => 35],
                ['name' => 'Marathon', 'state_id' => 35],
                ['name' => 'Willet', 'state_id' => 35],
                ['name' => 'Stamford', 'state_id' => 35],
                ['name' => 'Arkville', 'state_id' => 35],
                ['name' => 'Denver', 'state_id' => 35],
                ['name' => 'Fleischmanns', 'state_id' => 35],
                ['name' => 'Grand Gorge', 'state_id' => 35],
                ['name' => 'Halcottsville', 'state_id' => 35],
                ['name' => 'Margaretville', 'state_id' => 35],
                ['name' => 'New Kingston', 'state_id' => 35],
                ['name' => 'Roxbury', 'state_id' => 35],
                ['name' => 'Andes', 'state_id' => 35],
                ['name' => 'Bloomville', 'state_id' => 35],
                ['name' => 'Bovina Center', 'state_id' => 35],
                ['name' => 'Davenport', 'state_id' => 35],
                ['name' => 'Davenport Center', 'state_id' => 35],
                ['name' => 'Delancey', 'state_id' => 35],
                ['name' => 'Delhi', 'state_id' => 35],
                ['name' => 'Downsville', 'state_id' => 35],
                ['name' => 'East Branch', 'state_id' => 35],
                ['name' => 'East Meredith', 'state_id' => 35],
                ['name' => 'Fishs Eddy', 'state_id' => 35],
                ['name' => 'Franklin', 'state_id' => 35],
                ['name' => 'Hamden', 'state_id' => 35],
                ['name' => 'Hancock', 'state_id' => 35],
                ['name' => 'Harpersfield', 'state_id' => 35],
                ['name' => 'Hobart', 'state_id' => 35],
                ['name' => 'Masonville', 'state_id' => 35],
                ['name' => 'Meridale', 'state_id' => 35],
                ['name' => 'Sidney', 'state_id' => 35],
                ['name' => 'Sidney Center', 'state_id' => 35],
                ['name' => 'South Kortright', 'state_id' => 35],
                ['name' => 'Treadwell', 'state_id' => 35],
                ['name' => 'Trout Creek', 'state_id' => 35],
                ['name' => 'Walton', 'state_id' => 35],
                ['name' => 'West Davenport', 'state_id' => 35],
                ['name' => 'Amenia', 'state_id' => 35],
                ['name' => 'Annandale On Hudson', 'state_id' => 35],
                ['name' => 'Bangall', 'state_id' => 35],
                ['name' => 'Barrytown', 'state_id' => 35],
                ['name' => 'Beacon', 'state_id' => 35],
                ['name' => 'Billings', 'state_id' => 35],
                ['name' => 'Castle Point', 'state_id' => 35],
                ['name' => 'Chelsea', 'state_id' => 35],
                ['name' => 'Clinton Corners', 'state_id' => 35],
                ['name' => 'Dover Plains', 'state_id' => 35],
                ['name' => 'Fishkill', 'state_id' => 35],
                ['name' => 'Glenham', 'state_id' => 35],
                ['name' => 'Holmes', 'state_id' => 35],
                ['name' => 'Hopewell Junction', 'state_id' => 35],
                ['name' => 'Hughsonville', 'state_id' => 35],
                ['name' => 'Hyde Park', 'state_id' => 35],
                ['name' => 'Lagrangeville', 'state_id' => 35],
                ['name' => 'Millbrook', 'state_id' => 35],
                ['name' => 'Millerton', 'state_id' => 35],
                ['name' => 'Pawling', 'state_id' => 35],
                ['name' => 'Pine Plains', 'state_id' => 35],
                ['name' => 'Pleasant Valley', 'state_id' => 35],
                ['name' => 'Poughquag', 'state_id' => 35],
                ['name' => 'Red Hook', 'state_id' => 35],
                ['name' => 'Rhinebeck', 'state_id' => 35],
                ['name' => 'Rhinecliff', 'state_id' => 35],
                ['name' => 'Salt Point', 'state_id' => 35],
                ['name' => 'Staatsburg', 'state_id' => 35],
                ['name' => 'Stanfordville', 'state_id' => 35],
                ['name' => 'Stormville', 'state_id' => 35],
                ['name' => 'Tivoli', 'state_id' => 35],
                ['name' => 'Verbank', 'state_id' => 35],
                ['name' => 'Wappingers Falls', 'state_id' => 35],
                ['name' => 'Wassaic', 'state_id' => 35],
                ['name' => 'Wingdale', 'state_id' => 35],
                ['name' => 'Poughkeepsie', 'state_id' => 35],
                ['name' => 'Akron', 'state_id' => 35],
                ['name' => 'Alden', 'state_id' => 35],
                ['name' => 'Angola', 'state_id' => 35],
                ['name' => 'Athol Springs', 'state_id' => 35],
                ['name' => 'Boston', 'state_id' => 35],
                ['name' => 'Bowmansville', 'state_id' => 35],
                ['name' => 'Brant', 'state_id' => 35],
                ['name' => 'Chaffee', 'state_id' => 35],
                ['name' => 'Clarence', 'state_id' => 35],
                ['name' => 'Clarence Center', 'state_id' => 35],
                ['name' => 'Colden', 'state_id' => 35],
                ['name' => 'Collins', 'state_id' => 35],
                ['name' => 'Collins Center', 'state_id' => 35],
                ['name' => 'Crittenden', 'state_id' => 35],
                ['name' => 'Depew', 'state_id' => 35],
                ['name' => 'Derby', 'state_id' => 35],
                ['name' => 'East Amherst', 'state_id' => 35],
                ['name' => 'East Aurora', 'state_id' => 35],
                ['name' => 'East Concord', 'state_id' => 35],
                ['name' => 'Eden', 'state_id' => 35],
                ['name' => 'Elma', 'state_id' => 35],
                ['name' => 'Farnham', 'state_id' => 35],
                ['name' => 'Getzville', 'state_id' => 35],
                ['name' => 'Glenwood', 'state_id' => 35],
                ['name' => 'Grand Island', 'state_id' => 35],
                ['name' => 'Hamburg', 'state_id' => 35],
                ['name' => 'Holland', 'state_id' => 35],
                ['name' => 'Lake View', 'state_id' => 35],
                ['name' => 'Lancaster', 'state_id' => 35],
                ['name' => 'Lawtons', 'state_id' => 35],
                ['name' => 'Marilla', 'state_id' => 35],
                ['name' => 'North Boston', 'state_id' => 35],
                ['name' => 'North Collins', 'state_id' => 35],
                ['name' => 'North Evans', 'state_id' => 35],
                ['name' => 'Orchard Park', 'state_id' => 35],
                ['name' => 'Sardinia', 'state_id' => 35],
                ['name' => 'South Wales', 'state_id' => 35],
                ['name' => 'Spring Brook', 'state_id' => 35],
                ['name' => 'Springville', 'state_id' => 35],
                ['name' => 'Tonawanda', 'state_id' => 35],
                ['name' => 'Wales Center', 'state_id' => 35],
                ['name' => 'West Falls', 'state_id' => 35],
                ['name' => 'Buffalo', 'state_id' => 35],
                ['name' => 'Minerva', 'state_id' => 35],
                ['name' => 'Newcomb', 'state_id' => 35],
                ['name' => 'North Hudson', 'state_id' => 35],
                ['name' => 'Olmstedville', 'state_id' => 35],
                ['name' => 'Paradox', 'state_id' => 35],
                ['name' => 'Schroon Lake', 'state_id' => 35],
                ['name' => 'Severance', 'state_id' => 35],
                ['name' => 'Ticonderoga', 'state_id' => 35],
                ['name' => 'Bloomingdale', 'state_id' => 35],
                ['name' => 'Crown Point', 'state_id' => 35],
                ['name' => 'Elizabethtown', 'state_id' => 35],
                ['name' => 'Essex', 'state_id' => 35],
                ['name' => 'Jay', 'state_id' => 35],
                ['name' => 'Keene', 'state_id' => 35],
                ['name' => 'Keene Valley', 'state_id' => 35],
                ['name' => 'Lake Placid', 'state_id' => 35],
                ['name' => 'Lewis', 'state_id' => 35],
                ['name' => 'Mineville', 'state_id' => 35],
                ['name' => 'Moriah', 'state_id' => 35],
                ['name' => 'Moriah Center', 'state_id' => 35],
                ['name' => 'New Russia', 'state_id' => 35],
                ['name' => 'Port Henry', 'state_id' => 35],
                ['name' => 'Port Kent', 'state_id' => 35],
                ['name' => 'Ray Brook', 'state_id' => 35],
                ['name' => 'Upper Jay', 'state_id' => 35],
                ['name' => 'Westport', 'state_id' => 35],
                ['name' => 'Willsboro', 'state_id' => 35],
                ['name' => 'Wilmington', 'state_id' => 35],
                ['name' => 'Witherbee', 'state_id' => 35],
                ['name' => 'Bombay', 'state_id' => 35],
                ['name' => 'Brainardsville', 'state_id' => 35],
                ['name' => 'Brushton', 'state_id' => 35],
                ['name' => 'Burke', 'state_id' => 35],
                ['name' => 'Chateaugay', 'state_id' => 35],
                ['name' => 'Constable', 'state_id' => 35],
                ['name' => 'Dickinson Center', 'state_id' => 35],
                ['name' => 'Fort Covington', 'state_id' => 35],
                ['name' => 'Gabriels', 'state_id' => 35],
                ['name' => 'Lake Clear', 'state_id' => 35],
                ['name' => 'Malone', 'state_id' => 35],
                ['name' => 'Moira', 'state_id' => 35],
                ['name' => 'North Bangor', 'state_id' => 35],
                ['name' => 'Owls Head', 'state_id' => 35],
                ['name' => 'Paul Smiths', 'state_id' => 35],
                ['name' => 'Rainbow Lake', 'state_id' => 35],
                ['name' => 'Saint Regis Falls', 'state_id' => 35],
                ['name' => 'Saranac Lake', 'state_id' => 35],
                ['name' => 'Tupper Lake', 'state_id' => 35],
                ['name' => 'Vermontville', 'state_id' => 35],
                ['name' => 'Whippleville', 'state_id' => 35],
                ['name' => 'Hogansburg', 'state_id' => 35],
                ['name' => 'Broadalbin', 'state_id' => 35],
                ['name' => 'Caroga Lake', 'state_id' => 35],
                ['name' => 'Gloversville', 'state_id' => 35],
                ['name' => 'Johnstown', 'state_id' => 35],
                ['name' => 'Mayfield', 'state_id' => 35],
                ['name' => 'Northville', 'state_id' => 35],
                ['name' => 'Stratford', 'state_id' => 35],
                ['name' => 'Alexander', 'state_id' => 35],
                ['name' => 'Basom', 'state_id' => 35],
                ['name' => 'Batavia', 'state_id' => 35],
                ['name' => 'Corfu', 'state_id' => 35],
                ['name' => 'Darien Center', 'state_id' => 35],
                ['name' => 'East Bethany', 'state_id' => 35],
                ['name' => 'East Pembroke', 'state_id' => 35],
                ['name' => 'Elba', 'state_id' => 35],
                ['name' => 'Oakfield', 'state_id' => 35],
                ['name' => 'Stafford', 'state_id' => 35],
                ['name' => 'Bergen', 'state_id' => 35],
                ['name' => 'Byron', 'state_id' => 35],
                ['name' => 'Le Roy', 'state_id' => 35],
                ['name' => 'Linwood', 'state_id' => 35],
                ['name' => 'Pavilion', 'state_id' => 35],
                ['name' => 'South Byron', 'state_id' => 35],
                ['name' => 'Athens', 'state_id' => 35],
                ['name' => 'Climax', 'state_id' => 35],
                ['name' => 'Coxsackie', 'state_id' => 35],
                ['name' => 'Earlton', 'state_id' => 35],
                ['name' => 'Greenville', 'state_id' => 35],
                ['name' => 'Hannacroix', 'state_id' => 35],
                ['name' => 'New Baltimore', 'state_id' => 35],
                ['name' => 'Surprise', 'state_id' => 35],
                ['name' => 'West Coxsackie', 'state_id' => 35],
                ['name' => 'Acra', 'state_id' => 35],
                ['name' => 'Ashland', 'state_id' => 35],
                ['name' => 'Cairo', 'state_id' => 35],
                ['name' => 'Catskill', 'state_id' => 35],
                ['name' => 'Cornwallville', 'state_id' => 35],
                ['name' => 'Durham', 'state_id' => 35],
                ['name' => 'East Durham', 'state_id' => 35],
                ['name' => 'East Jewett', 'state_id' => 35],
                ['name' => 'Elka Park', 'state_id' => 35],
                ['name' => 'Freehold', 'state_id' => 35],
                ['name' => 'Haines Falls', 'state_id' => 35],
                ['name' => 'Hensonville', 'state_id' => 35],
                ['name' => 'Hunter', 'state_id' => 35],
                ['name' => 'Jewett', 'state_id' => 35],
                ['name' => 'Lanesville', 'state_id' => 35],
                ['name' => 'Leeds', 'state_id' => 35],
                ['name' => 'Lexington', 'state_id' => 35],
                ['name' => 'Maplecrest', 'state_id' => 35],
                ['name' => 'Oak Hill', 'state_id' => 35],
                ['name' => 'Palenville', 'state_id' => 35],
                ['name' => 'Prattsville', 'state_id' => 35],
                ['name' => 'Purling', 'state_id' => 35],
                ['name' => 'Round Top', 'state_id' => 35],
                ['name' => 'South Cairo', 'state_id' => 35],
                ['name' => 'Tannersville', 'state_id' => 35],
                ['name' => 'West Kill', 'state_id' => 35],
                ['name' => 'Windham', 'state_id' => 35],
                ['name' => 'Lake Pleasant', 'state_id' => 35],
                ['name' => 'Piseco', 'state_id' => 35],
                ['name' => 'Speculator', 'state_id' => 35],
                ['name' => 'Wells', 'state_id' => 35],
                ['name' => 'Blue Mountain Lake', 'state_id' => 35],
                ['name' => 'Indian Lake', 'state_id' => 35],
                ['name' => 'Long Lake', 'state_id' => 35],
                ['name' => 'Sabael', 'state_id' => 35],
                ['name' => 'Hoffmeister', 'state_id' => 35],
                ['name' => 'Inlet', 'state_id' => 35],
                ['name' => 'Raquette Lake', 'state_id' => 35],
                ['name' => 'Cold Brook', 'state_id' => 35],
                ['name' => 'Dolgeville', 'state_id' => 35],
                ['name' => 'Eagle Bay', 'state_id' => 35],
                ['name' => 'Frankfort', 'state_id' => 35],
                ['name' => 'Herkimer', 'state_id' => 35],
                ['name' => 'Ilion', 'state_id' => 35],
                ['name' => 'Jordanville', 'state_id' => 35],
                ['name' => 'Little Falls', 'state_id' => 35],
                ['name' => 'Middleville', 'state_id' => 35],
                ['name' => 'Mohawk', 'state_id' => 35],
                ['name' => 'Newport', 'state_id' => 35],
                ['name' => 'Old Forge', 'state_id' => 35],
                ['name' => 'Poland', 'state_id' => 35],
                ['name' => 'Salisbury Center', 'state_id' => 35],
                ['name' => 'Thendara', 'state_id' => 35],
                ['name' => 'Van Hornesville', 'state_id' => 35],
                ['name' => 'West Winfield', 'state_id' => 35],
                ['name' => 'Watertown', 'state_id' => 35],
                ['name' => 'Fort Drum', 'state_id' => 35],
                ['name' => 'Adams', 'state_id' => 35],
                ['name' => 'Adams Center', 'state_id' => 35],
                ['name' => 'Alexandria Bay', 'state_id' => 35],
                ['name' => 'Antwerp', 'state_id' => 35],
                ['name' => 'Belleville', 'state_id' => 35],
                ['name' => 'Black River', 'state_id' => 35],
                ['name' => 'Brownville', 'state_id' => 35],
                ['name' => 'Calcium', 'state_id' => 35],
                ['name' => 'Cape Vincent', 'state_id' => 35],
                ['name' => 'Carthage', 'state_id' => 35],
                ['name' => 'Chaumont', 'state_id' => 35],
                ['name' => 'Clayton', 'state_id' => 35],
                ['name' => 'Deferiet', 'state_id' => 35],
                ['name' => 'Depauville', 'state_id' => 35],
                ['name' => 'Dexter', 'state_id' => 35],
                ['name' => 'Ellisburg', 'state_id' => 35],
                ['name' => 'Evans Mills', 'state_id' => 35],
                ['name' => 'Felts Mills', 'state_id' => 35],
                ['name' => 'Wellesley Island', 'state_id' => 35],
                ['name' => 'Fishers Landing', 'state_id' => 35],
                ['name' => 'Great Bend', 'state_id' => 35],
                ['name' => 'Henderson', 'state_id' => 35],
                ['name' => 'Henderson Harbor', 'state_id' => 35],
                ['name' => 'La Fargeville', 'state_id' => 35],
                ['name' => 'Limerick', 'state_id' => 35],
                ['name' => 'Lorraine', 'state_id' => 35],
                ['name' => 'Mannsville', 'state_id' => 35],
                ['name' => 'Natural Bridge', 'state_id' => 35],
                ['name' => 'Oxbow', 'state_id' => 35],
                ['name' => 'Philadelphia', 'state_id' => 35],
                ['name' => 'Pierrepont Manor', 'state_id' => 35],
                ['name' => 'Plessis', 'state_id' => 35],
                ['name' => 'Redwood', 'state_id' => 35],
                ['name' => 'Rodman', 'state_id' => 35],
                ['name' => 'Sackets Harbor', 'state_id' => 35],
                ['name' => 'Theresa', 'state_id' => 35],
                ['name' => 'Thousand Island Park', 'state_id' => 35],
                ['name' => 'Three Mile Bay', 'state_id' => 35],
                ['name' => 'Brooklyn', 'state_id' => 35],
                ['name' => 'Beaver Falls', 'state_id' => 35],
                ['name' => 'Brantingham', 'state_id' => 35],
                ['name' => 'Constableville', 'state_id' => 35],
                ['name' => 'Croghan', 'state_id' => 35],
                ['name' => 'Glenfield', 'state_id' => 35],
                ['name' => 'Greig', 'state_id' => 35],
                ['name' => 'Lowville', 'state_id' => 35],
                ['name' => 'Lyons Falls', 'state_id' => 35],
                ['name' => 'Martinsburg', 'state_id' => 35],
                ['name' => 'Port Leyden', 'state_id' => 35],
                ['name' => 'Turin', 'state_id' => 35],
                ['name' => 'West Leyden', 'state_id' => 35],
                ['name' => 'Castorland', 'state_id' => 35],
                ['name' => 'Copenhagen', 'state_id' => 35],
                ['name' => 'Deer River', 'state_id' => 35],
                ['name' => 'Denmark', 'state_id' => 35],
                ['name' => 'Harrisville', 'state_id' => 35],
                ['name' => 'Avon', 'state_id' => 35],
                ['name' => 'Caledonia', 'state_id' => 35],
                ['name' => 'Conesus', 'state_id' => 35],
                ['name' => 'Dansville', 'state_id' => 35],
                ['name' => 'Geneseo', 'state_id' => 35],
                ['name' => 'Groveland', 'state_id' => 35],
                ['name' => 'Hemlock', 'state_id' => 35],
                ['name' => 'Lakeville', 'state_id' => 35],
                ['name' => 'Leicester', 'state_id' => 35],
                ['name' => 'Lima', 'state_id' => 35],
                ['name' => 'Livonia', 'state_id' => 35],
                ['name' => 'Livonia Center', 'state_id' => 35],
                ['name' => 'Mount Morris', 'state_id' => 35],
                ['name' => 'Nunda', 'state_id' => 35],
                ['name' => 'Piffard', 'state_id' => 35],
                ['name' => 'Retsof', 'state_id' => 35],
                ['name' => 'Scottsburg', 'state_id' => 35],
                ['name' => 'Sonyea', 'state_id' => 35],
                ['name' => 'South Lima', 'state_id' => 35],
                ['name' => 'Springwater', 'state_id' => 35],
                ['name' => 'York', 'state_id' => 35],
                ['name' => 'Dalton', 'state_id' => 35],
                ['name' => 'Hunt', 'state_id' => 35],
                ['name' => 'Canastota', 'state_id' => 35],
                ['name' => 'Cazenovia', 'state_id' => 35],
                ['name' => 'Chittenango', 'state_id' => 35],
                ['name' => 'Clockville', 'state_id' => 35],
                ['name' => 'De Ruyter', 'state_id' => 35],
                ['name' => 'Erieville', 'state_id' => 35],
                ['name' => 'Georgetown', 'state_id' => 35],
                ['name' => 'New Woodstock', 'state_id' => 35],
                ['name' => 'Peterboro', 'state_id' => 35],
                ['name' => 'Wampsville', 'state_id' => 35],
                ['name' => 'Bouckville', 'state_id' => 35],
                ['name' => 'Brookfield', 'state_id' => 35],
                ['name' => 'Eaton', 'state_id' => 35],
                ['name' => 'Hamilton', 'state_id' => 35],
                ['name' => 'Hubbardsville', 'state_id' => 35],
                ['name' => 'Leonardsville', 'state_id' => 35],
                ['name' => 'Madison', 'state_id' => 35],
                ['name' => 'Morrisville', 'state_id' => 35],
                ['name' => 'Munnsville', 'state_id' => 35],
                ['name' => 'North Brookfield', 'state_id' => 35],
                ['name' => 'Oneida', 'state_id' => 35],
                ['name' => 'Solsville', 'state_id' => 35],
                ['name' => 'West Eaton', 'state_id' => 35],
                ['name' => 'Adams Basin', 'state_id' => 35],
                ['name' => 'Brockport', 'state_id' => 35],
                ['name' => 'Churchville', 'state_id' => 35],
                ['name' => 'Clarkson', 'state_id' => 35],
                ['name' => 'East Rochester', 'state_id' => 35],
                ['name' => 'Fairport', 'state_id' => 35],
                ['name' => 'Hamlin', 'state_id' => 35],
                ['name' => 'Henrietta', 'state_id' => 35],
                ['name' => 'Hilton', 'state_id' => 35],
                ['name' => 'Honeoye Falls', 'state_id' => 35],
                ['name' => 'Mendon', 'state_id' => 35],
                ['name' => 'Mumford', 'state_id' => 35],
                ['name' => 'North Chili', 'state_id' => 35],
                ['name' => 'North Greece', 'state_id' => 35],
                ['name' => 'Penfield', 'state_id' => 35],
                ['name' => 'Pittsford', 'state_id' => 35],
                ['name' => 'Rush', 'state_id' => 35],
                ['name' => 'Scottsville', 'state_id' => 35],
                ['name' => 'Spencerport', 'state_id' => 35],
                ['name' => 'Webster', 'state_id' => 35],
                ['name' => 'West Henrietta', 'state_id' => 35],
                ['name' => 'Rochester', 'state_id' => 35],
                ['name' => 'Amsterdam', 'state_id' => 35],
                ['name' => 'Auriesville', 'state_id' => 35],
                ['name' => 'Esperance', 'state_id' => 35],
                ['name' => 'Fonda', 'state_id' => 35],
                ['name' => 'Fort Hunter', 'state_id' => 35],
                ['name' => 'Fort Johnson', 'state_id' => 35],
                ['name' => 'Fultonville', 'state_id' => 35],
                ['name' => 'Hagaman', 'state_id' => 35],
                ['name' => 'Sprakers', 'state_id' => 35],
                ['name' => 'Tribes Hill', 'state_id' => 35],
                ['name' => 'Canajoharie', 'state_id' => 35],
                ['name' => 'Fort Plain', 'state_id' => 35],
                ['name' => 'Nelliston', 'state_id' => 35],
                ['name' => 'Palatine Bridge', 'state_id' => 35],
                ['name' => 'Saint Johnsville', 'state_id' => 35],
                ['name' => 'Floral Park', 'state_id' => 35],
                ['name' => 'Elmont', 'state_id' => 35],
                ['name' => 'Franklin Square', 'state_id' => 35],
                ['name' => 'Great Neck', 'state_id' => 35],
                ['name' => 'Manhasset', 'state_id' => 35],
                ['name' => 'New Hyde Park', 'state_id' => 35],
                ['name' => 'Port Washington', 'state_id' => 35],
                ['name' => 'Inwood', 'state_id' => 35],
                ['name' => 'Mineola', 'state_id' => 35],
                ['name' => 'Albertson', 'state_id' => 35],
                ['name' => 'Atlantic Beach', 'state_id' => 35],
                ['name' => 'Baldwin', 'state_id' => 35],
                ['name' => 'Carle Place', 'state_id' => 35],
                ['name' => 'Cedarhurst', 'state_id' => 35],
                ['name' => 'East Rockaway', 'state_id' => 35],
                ['name' => 'Freeport', 'state_id' => 35],
                ['name' => 'Garden City', 'state_id' => 35],
                ['name' => 'Glen Cove', 'state_id' => 35],
                ['name' => 'Glen Head', 'state_id' => 35],
                ['name' => 'Glenwood Landing', 'state_id' => 35],
                ['name' => 'Greenvale', 'state_id' => 35],
                ['name' => 'Hempstead', 'state_id' => 35],
                ['name' => 'West Hempstead', 'state_id' => 35],
                ['name' => 'Uniondale', 'state_id' => 35],
                ['name' => 'East Meadow', 'state_id' => 35],
                ['name' => 'Hewlett', 'state_id' => 35],
                ['name' => 'Island Park', 'state_id' => 35],
                ['name' => 'Lawrence', 'state_id' => 35],
                ['name' => 'Locust Valley', 'state_id' => 35],
                ['name' => 'Long Beach', 'state_id' => 35],
                ['name' => 'Lynbrook', 'state_id' => 35],
                ['name' => 'Malverne', 'state_id' => 35],
                ['name' => 'Merrick', 'state_id' => 35],
                ['name' => 'Old Westbury', 'state_id' => 35],
                ['name' => 'Point Lookout', 'state_id' => 35],
                ['name' => 'Rockville Centre', 'state_id' => 35],
                ['name' => 'Oceanside', 'state_id' => 35],
                ['name' => 'Roosevelt', 'state_id' => 35],
                ['name' => 'Roslyn', 'state_id' => 35],
                ['name' => 'Roslyn Heights', 'state_id' => 35],
                ['name' => 'Sea Cliff', 'state_id' => 35],
                ['name' => 'Valley Stream', 'state_id' => 35],
                ['name' => 'Westbury', 'state_id' => 35],
                ['name' => 'Williston Park', 'state_id' => 35],
                ['name' => 'Woodmere', 'state_id' => 35],
                ['name' => 'Bayville', 'state_id' => 35],
                ['name' => 'Bellmore', 'state_id' => 35],
                ['name' => 'Bethpage', 'state_id' => 35],
                ['name' => 'East Norwich', 'state_id' => 35],
                ['name' => 'Farmingdale', 'state_id' => 35],
                ['name' => 'Jericho', 'state_id' => 35],
                ['name' => 'Levittown', 'state_id' => 35],
                ['name' => 'Massapequa', 'state_id' => 35],
                ['name' => 'Massapequa Park', 'state_id' => 35],
                ['name' => 'Mill Neck', 'state_id' => 35],
                ['name' => 'Oyster Bay', 'state_id' => 35],
                ['name' => 'Syosset', 'state_id' => 35],
                ['name' => 'Seaford', 'state_id' => 35],
                ['name' => 'Wantagh', 'state_id' => 35],
                ['name' => 'Woodbury', 'state_id' => 35],
                ['name' => 'Hicksville', 'state_id' => 35],
                ['name' => 'Plainview', 'state_id' => 35],
                ['name' => 'Old Bethpage', 'state_id' => 35],
                ['name' => 'New York', 'state_id' => 35],
                ['name' => 'Appleton', 'state_id' => 35],
                ['name' => 'Barker', 'state_id' => 35],
                ['name' => 'Burt', 'state_id' => 35],
                ['name' => 'Gasport', 'state_id' => 35],
                ['name' => 'Lewiston', 'state_id' => 35],
                ['name' => 'Lockport', 'state_id' => 35],
                ['name' => 'Middleport', 'state_id' => 35],
                ['name' => 'Model City', 'state_id' => 35],
                ['name' => 'Newfane', 'state_id' => 35],
                ['name' => 'Niagara University', 'state_id' => 35],
                ['name' => 'North Tonawanda', 'state_id' => 35],
                ['name' => 'Olcott', 'state_id' => 35],
                ['name' => 'Ransomville', 'state_id' => 35],
                ['name' => 'Sanborn', 'state_id' => 35],
                ['name' => 'Stella Niagara', 'state_id' => 35],
                ['name' => 'Wilson', 'state_id' => 35],
                ['name' => 'Youngstown', 'state_id' => 35],
                ['name' => 'Niagara Falls', 'state_id' => 35],
                ['name' => 'Durhamville', 'state_id' => 35],
                ['name' => 'North Bay', 'state_id' => 35],
                ['name' => 'Sylvan Beach', 'state_id' => 35],
                ['name' => 'Verona Beach', 'state_id' => 35],
                ['name' => 'Alder Creek', 'state_id' => 35],
                ['name' => 'Ava', 'state_id' => 35],
                ['name' => 'Barneveld', 'state_id' => 35],
                ['name' => 'Blossvale', 'state_id' => 35],
                ['name' => 'Boonville', 'state_id' => 35],
                ['name' => 'Bridgewater', 'state_id' => 35],
                ['name' => 'Camden', 'state_id' => 35],
                ['name' => 'Cassville', 'state_id' => 35],
                ['name' => 'Chadwicks', 'state_id' => 35],
                ['name' => 'Clark Mills', 'state_id' => 35],
                ['name' => 'Clayville', 'state_id' => 35],
                ['name' => 'Clinton', 'state_id' => 35],
                ['name' => 'Deansboro', 'state_id' => 35],
                ['name' => 'Forestport', 'state_id' => 35],
                ['name' => 'Franklin Springs', 'state_id' => 35],
                ['name' => 'Hinckley', 'state_id' => 35],
                ['name' => 'Holland Patent', 'state_id' => 35],
                ['name' => 'Knoxboro', 'state_id' => 35],
                ['name' => 'Lee Center', 'state_id' => 35],
                ['name' => 'Mc Connellsville', 'state_id' => 35],
                ['name' => 'Marcy', 'state_id' => 35],
                ['name' => 'New Hartford', 'state_id' => 35],
                ['name' => 'New York Mills', 'state_id' => 35],
                ['name' => 'Oriskany', 'state_id' => 35],
                ['name' => 'Oriskany Falls', 'state_id' => 35],
                ['name' => 'Prospect', 'state_id' => 35],
                ['name' => 'Remsen', 'state_id' => 35],
                ['name' => 'Rome', 'state_id' => 35],
                ['name' => 'Sangerfield', 'state_id' => 35],
                ['name' => 'Sauquoit', 'state_id' => 35],
                ['name' => 'Sherrill', 'state_id' => 35],
                ['name' => 'Stittville', 'state_id' => 35],
                ['name' => 'Taberg', 'state_id' => 35],
                ['name' => 'Vernon', 'state_id' => 35],
                ['name' => 'Vernon Center', 'state_id' => 35],
                ['name' => 'Verona', 'state_id' => 35],
                ['name' => 'Washington Mills', 'state_id' => 35],
                ['name' => 'Waterville', 'state_id' => 35],
                ['name' => 'Westdale', 'state_id' => 35],
                ['name' => 'Westernville', 'state_id' => 35],
                ['name' => 'Westmoreland', 'state_id' => 35],
                ['name' => 'Whitesboro', 'state_id' => 35],
                ['name' => 'Woodgate', 'state_id' => 35],
                ['name' => 'Yorkville', 'state_id' => 35],
                ['name' => 'Utica', 'state_id' => 35],
                ['name' => 'Apulia Station', 'state_id' => 35],
                ['name' => 'Baldwinsville', 'state_id' => 35],
                ['name' => 'Brewerton', 'state_id' => 35],
                ['name' => 'Bridgeport', 'state_id' => 35],
                ['name' => 'Camillus', 'state_id' => 35],
                ['name' => 'Cicero', 'state_id' => 35],
                ['name' => 'Clay', 'state_id' => 35],
                ['name' => 'Delphi Falls', 'state_id' => 35],
                ['name' => 'East Syracuse', 'state_id' => 35],
                ['name' => 'Elbridge', 'state_id' => 35],
                ['name' => 'Fabius', 'state_id' => 35],
                ['name' => 'Fayetteville', 'state_id' => 35],
                ['name' => 'Jamesville', 'state_id' => 35],
                ['name' => 'Jordan', 'state_id' => 35],
                ['name' => 'Kirkville', 'state_id' => 35],
                ['name' => 'La Fayette', 'state_id' => 35],
                ['name' => 'Liverpool', 'state_id' => 35],
                ['name' => 'Manlius', 'state_id' => 35],
                ['name' => 'Marcellus', 'state_id' => 35],
                ['name' => 'Marietta', 'state_id' => 35],
                ['name' => 'Memphis', 'state_id' => 35],
                ['name' => 'Minoa', 'state_id' => 35],
                ['name' => 'Mottville', 'state_id' => 35],
                ['name' => 'Nedrow', 'state_id' => 35],
                ['name' => 'Plainville', 'state_id' => 35],
                ['name' => 'Pompey', 'state_id' => 35],
                ['name' => 'Skaneateles', 'state_id' => 35],
                ['name' => 'Skaneateles Falls', 'state_id' => 35],
                ['name' => 'Tully', 'state_id' => 35],
                ['name' => 'Warners', 'state_id' => 35],
                ['name' => 'Syracuse', 'state_id' => 35],
                ['name' => 'Canandaigua', 'state_id' => 35],
                ['name' => 'Farmington', 'state_id' => 35],
                ['name' => 'Clifton Springs', 'state_id' => 35],
                ['name' => 'East Bloomfield', 'state_id' => 35],
                ['name' => 'Fishers', 'state_id' => 35],
                ['name' => 'Geneva', 'state_id' => 35],
                ['name' => 'Gorham', 'state_id' => 35],
                ['name' => 'Hall', 'state_id' => 35],
                ['name' => 'Bloomfield', 'state_id' => 35],
                ['name' => 'Honeoye', 'state_id' => 35],
                ['name' => 'Ionia', 'state_id' => 35],
                ['name' => 'Manchester', 'state_id' => 35],
                ['name' => 'Naples', 'state_id' => 35],
                ['name' => 'Oaks Corners', 'state_id' => 35],
                ['name' => 'Phelps', 'state_id' => 35],
                ['name' => 'Port Gibson', 'state_id' => 35],
                ['name' => 'Seneca Castle', 'state_id' => 35],
                ['name' => 'Shortsville', 'state_id' => 35],
                ['name' => 'Stanley', 'state_id' => 35],
                ['name' => 'Victor', 'state_id' => 35],
                ['name' => 'West Bloomfield', 'state_id' => 35],
                ['name' => 'Arden', 'state_id' => 35],
                ['name' => 'Bellvale', 'state_id' => 35],
                ['name' => 'Blooming Grove', 'state_id' => 35],
                ['name' => 'Bullville', 'state_id' => 35],
                ['name' => 'Campbell Hall', 'state_id' => 35],
                ['name' => 'Central Valley', 'state_id' => 35],
                ['name' => 'Chester', 'state_id' => 35],
                ['name' => 'Circleville', 'state_id' => 35],
                ['name' => 'Florida', 'state_id' => 35],
                ['name' => 'Fort Montgomery', 'state_id' => 35],
                ['name' => 'Goshen', 'state_id' => 35],
                ['name' => 'Greenwood Lake', 'state_id' => 35],
                ['name' => 'Harriman', 'state_id' => 35],
                ['name' => 'Highland Falls', 'state_id' => 35],
                ['name' => 'Highland Mills', 'state_id' => 35],
                ['name' => 'Howells', 'state_id' => 35],
                ['name' => 'Johnson', 'state_id' => 35],
                ['name' => 'Middletown', 'state_id' => 35],
                ['name' => 'Monroe', 'state_id' => 35],
                ['name' => 'Mountainville', 'state_id' => 35],
                ['name' => 'New Hampton', 'state_id' => 35],
                ['name' => 'New Milford', 'state_id' => 35],
                ['name' => 'Otisville', 'state_id' => 35],
                ['name' => 'Pine Island', 'state_id' => 35],
                ['name' => 'Slate Hill', 'state_id' => 35],
                ['name' => 'Southfields', 'state_id' => 35],
                ['name' => 'Sterling Forest', 'state_id' => 35],
                ['name' => 'Sugar Loaf', 'state_id' => 35],
                ['name' => 'Thompson Ridge', 'state_id' => 35],
                ['name' => 'Tuxedo Park', 'state_id' => 35],
                ['name' => 'Unionville', 'state_id' => 35],
                ['name' => 'Warwick', 'state_id' => 35],
                ['name' => 'Washingtonville', 'state_id' => 35],
                ['name' => 'West Point', 'state_id' => 35],
                ['name' => 'Westtown', 'state_id' => 35],
                ['name' => 'Cornwall', 'state_id' => 35],
                ['name' => 'Cornwall On Hudson', 'state_id' => 35],
                ['name' => 'Maybrook', 'state_id' => 35],
                ['name' => 'Montgomery', 'state_id' => 35],
                ['name' => 'Newburgh', 'state_id' => 35],
                ['name' => 'New Windsor', 'state_id' => 35],
                ['name' => 'Pine Bush', 'state_id' => 35],
                ['name' => 'Rock Tavern', 'state_id' => 35],
                ['name' => 'Salisbury Mills', 'state_id' => 35],
                ['name' => 'Vails Gate', 'state_id' => 35],
                ['name' => 'Walden', 'state_id' => 35],
                ['name' => 'Cuddebackville', 'state_id' => 35],
                ['name' => 'Huguenot', 'state_id' => 35],
                ['name' => 'Port Jervis', 'state_id' => 35],
                ['name' => 'Sparrow Bush', 'state_id' => 35],
                ['name' => 'Lyndonville', 'state_id' => 35],
                ['name' => 'Medina', 'state_id' => 35],
                ['name' => 'Albion', 'state_id' => 35],
                ['name' => 'Clarendon', 'state_id' => 35],
                ['name' => 'Fancher', 'state_id' => 35],
                ['name' => 'Holley', 'state_id' => 35],
                ['name' => 'Kendall', 'state_id' => 35],
                ['name' => 'Kent', 'state_id' => 35],
                ['name' => 'Knowlesville', 'state_id' => 35],
                ['name' => 'Morton', 'state_id' => 35],
                ['name' => 'Waterport', 'state_id' => 35],
                ['name' => 'Bernhards Bay', 'state_id' => 35],
                ['name' => 'Central Square', 'state_id' => 35],
                ['name' => 'Cleveland', 'state_id' => 35],
                ['name' => 'Constantia', 'state_id' => 35],
                ['name' => 'Fair Haven', 'state_id' => 35],
                ['name' => 'Fulton', 'state_id' => 35],
                ['name' => 'Hannibal', 'state_id' => 35],
                ['name' => 'Hastings', 'state_id' => 35],
                ['name' => 'Lacona', 'state_id' => 35],
                ['name' => 'Lycoming', 'state_id' => 35],
                ['name' => 'Mallory', 'state_id' => 35],
                ['name' => 'Maple View', 'state_id' => 35],
                ['name' => 'Mexico', 'state_id' => 35],
                ['name' => 'Minetto', 'state_id' => 35],
                ['name' => 'New Haven', 'state_id' => 35],
                ['name' => 'Oswego', 'state_id' => 35],
                ['name' => 'Parish', 'state_id' => 35],
                ['name' => 'Pennellville', 'state_id' => 35],
                ['name' => 'Phoenix', 'state_id' => 35],
                ['name' => 'Pulaski', 'state_id' => 35],
                ['name' => 'Richland', 'state_id' => 35],
                ['name' => 'Sandy Creek', 'state_id' => 35],
                ['name' => 'West Monroe', 'state_id' => 35],
                ['name' => 'Altmar', 'state_id' => 35],
                ['name' => 'Orwell', 'state_id' => 35],
                ['name' => 'Redfield', 'state_id' => 35],
                ['name' => 'Williamstown', 'state_id' => 35],
                ['name' => 'East Worcester', 'state_id' => 35],
                ['name' => 'Maryland', 'state_id' => 35],
                ['name' => 'Schenevus', 'state_id' => 35],
                ['name' => 'Worcester', 'state_id' => 35],
                ['name' => 'Burlington Flats', 'state_id' => 35],
                ['name' => 'Cherry Valley', 'state_id' => 35],
                ['name' => 'Cooperstown', 'state_id' => 35],
                ['name' => 'East Springfield', 'state_id' => 35],
                ['name' => 'Edmeston', 'state_id' => 35],
                ['name' => 'Fly Creek', 'state_id' => 35],
                ['name' => 'Garrattsville', 'state_id' => 35],
                ['name' => 'Hartwick', 'state_id' => 35],
                ['name' => 'New Lisbon', 'state_id' => 35],
                ['name' => 'Richfield Springs', 'state_id' => 35],
                ['name' => 'Roseboom', 'state_id' => 35],
                ['name' => 'Schuyler Lake', 'state_id' => 35],
                ['name' => 'Springfield Center', 'state_id' => 35],
                ['name' => 'West Burlington', 'state_id' => 35],
                ['name' => 'West Edmeston', 'state_id' => 35],
                ['name' => 'Westford', 'state_id' => 35],
                ['name' => 'Colliersville', 'state_id' => 35],
                ['name' => 'Gilbertsville', 'state_id' => 35],
                ['name' => 'Laurens', 'state_id' => 35],
                ['name' => 'Milford', 'state_id' => 35],
                ['name' => 'Morris', 'state_id' => 35],
                ['name' => 'Mount Vision', 'state_id' => 35],
                ['name' => 'Oneonta', 'state_id' => 35],
                ['name' => 'Otego', 'state_id' => 35],
                ['name' => 'Portlandville', 'state_id' => 35],
                ['name' => 'Unadilla', 'state_id' => 35],
                ['name' => 'Wells Bridge', 'state_id' => 35],
                ['name' => 'West Oneonta', 'state_id' => 35],
                ['name' => 'Brewster', 'state_id' => 35],
                ['name' => 'Carmel', 'state_id' => 35],
                ['name' => 'Cold Spring', 'state_id' => 35],
                ['name' => 'Garrison', 'state_id' => 35],
                ['name' => 'Lake Peekskill', 'state_id' => 35],
                ['name' => 'Mahopac', 'state_id' => 35],
                ['name' => 'Mahopac Falls', 'state_id' => 35],
                ['name' => 'Putnam Valley', 'state_id' => 35],
                ['name' => 'Patterson', 'state_id' => 35],
                ['name' => 'Glen Oaks', 'state_id' => 35],
                ['name' => 'Long Island City', 'state_id' => 35],
                ['name' => 'Astoria', 'state_id' => 35],
                ['name' => 'Sunnyside', 'state_id' => 35],
                ['name' => 'Flushing', 'state_id' => 35],
                ['name' => 'College Point', 'state_id' => 35],
                ['name' => 'Whitestone', 'state_id' => 35],
                ['name' => 'Bayside', 'state_id' => 35],
                ['name' => 'Little Neck', 'state_id' => 35],
                ['name' => 'Oakland Gardens', 'state_id' => 35],
                ['name' => 'Fresh Meadows', 'state_id' => 35],
                ['name' => 'Corona', 'state_id' => 35],
                ['name' => 'East Elmhurst', 'state_id' => 35],
                ['name' => 'Jackson Heights', 'state_id' => 35],
                ['name' => 'Elmhurst', 'state_id' => 35],
                ['name' => 'Rego Park', 'state_id' => 35],
                ['name' => 'Forest Hills', 'state_id' => 35],
                ['name' => 'Woodside', 'state_id' => 35],
                ['name' => 'Maspeth', 'state_id' => 35],
                ['name' => 'Middle Village', 'state_id' => 35],
                ['name' => 'Ridgewood', 'state_id' => 35],
                ['name' => 'Jamaica', 'state_id' => 35],
                ['name' => 'Cambria Heights', 'state_id' => 35],
                ['name' => 'Saint Albans', 'state_id' => 35],
                ['name' => 'Springfield Gardens', 'state_id' => 35],
                ['name' => 'Howard Beach', 'state_id' => 35],
                ['name' => 'Kew Gardens', 'state_id' => 35],
                ['name' => 'Ozone Park', 'state_id' => 35],
                ['name' => 'Richmond Hill', 'state_id' => 35],
                ['name' => 'South Richmond Hill', 'state_id' => 35],
                ['name' => 'South Ozone Park', 'state_id' => 35],
                ['name' => 'Woodhaven', 'state_id' => 35],
                ['name' => 'Rosedale', 'state_id' => 35],
                ['name' => 'Hollis', 'state_id' => 35],
                ['name' => 'Bellerose', 'state_id' => 35],
                ['name' => 'Queens Village', 'state_id' => 35],
                ['name' => 'Far Rockaway', 'state_id' => 35],
                ['name' => 'Arverne', 'state_id' => 35],
                ['name' => 'Rockaway Park', 'state_id' => 35],
                ['name' => 'Breezy Point', 'state_id' => 35],
                ['name' => 'Averill Park', 'state_id' => 35],
                ['name' => 'Berlin', 'state_id' => 35],
                ['name' => 'Brainard', 'state_id' => 35],
                ['name' => 'Buskirk', 'state_id' => 35],
                ['name' => 'Castleton On Hudson', 'state_id' => 35],
                ['name' => 'Cherry Plain', 'state_id' => 35],
                ['name' => 'Cropseyville', 'state_id' => 35],
                ['name' => 'East Greenbush', 'state_id' => 35],
                ['name' => 'East Nassau', 'state_id' => 35],
                ['name' => 'East Schodack', 'state_id' => 35],
                ['name' => 'Grafton', 'state_id' => 35],
                ['name' => 'Hoosick', 'state_id' => 35],
                ['name' => 'Hoosick Falls', 'state_id' => 35],
                ['name' => 'Johnsonville', 'state_id' => 35],
                ['name' => 'Melrose', 'state_id' => 35],
                ['name' => 'Nassau', 'state_id' => 35],
                ['name' => 'North Hoosick', 'state_id' => 35],
                ['name' => 'Petersburg', 'state_id' => 35],
                ['name' => 'Poestenkill', 'state_id' => 35],
                ['name' => 'Rensselaer', 'state_id' => 35],
                ['name' => 'Sand Lake', 'state_id' => 35],
                ['name' => 'Schaghticoke', 'state_id' => 35],
                ['name' => 'Schodack Landing', 'state_id' => 35],
                ['name' => 'Stephentown', 'state_id' => 35],
                ['name' => 'Valley Falls', 'state_id' => 35],
                ['name' => 'West Sand Lake', 'state_id' => 35],
                ['name' => 'Wynantskill', 'state_id' => 35],
                ['name' => 'Staten Island', 'state_id' => 35],
                ['name' => 'Suffern', 'state_id' => 35],
                ['name' => 'Bear Mountain', 'state_id' => 35],
                ['name' => 'Blauvelt', 'state_id' => 35],
                ['name' => 'Congers', 'state_id' => 35],
                ['name' => 'Garnerville', 'state_id' => 35],
                ['name' => 'Haverstraw', 'state_id' => 35],
                ['name' => 'Hillburn', 'state_id' => 35],
                ['name' => 'Monsey', 'state_id' => 35],
                ['name' => 'Nanuet', 'state_id' => 35],
                ['name' => 'New City', 'state_id' => 35],
                ['name' => 'Nyack', 'state_id' => 35],
                ['name' => 'Orangeburg', 'state_id' => 35],
                ['name' => 'Palisades', 'state_id' => 35],
                ['name' => 'Pearl River', 'state_id' => 35],
                ['name' => 'Piermont', 'state_id' => 35],
                ['name' => 'Pomona', 'state_id' => 35],
                ['name' => 'Sloatsburg', 'state_id' => 35],
                ['name' => 'Sparkill', 'state_id' => 35],
                ['name' => 'Spring Valley', 'state_id' => 35],
                ['name' => 'Stony Point', 'state_id' => 35],
                ['name' => 'Tallman', 'state_id' => 35],
                ['name' => 'Tappan', 'state_id' => 35],
                ['name' => 'Thiells', 'state_id' => 35],
                ['name' => 'Tomkins Cove', 'state_id' => 35],
                ['name' => 'Valley Cottage', 'state_id' => 35],
                ['name' => 'West Haverstraw', 'state_id' => 35],
                ['name' => 'West Nyack', 'state_id' => 35],
                ['name' => 'Childwold', 'state_id' => 35],
                ['name' => 'Cranberry Lake', 'state_id' => 35],
                ['name' => 'Lawrenceville', 'state_id' => 35],
                ['name' => 'Nicholville', 'state_id' => 35],
                ['name' => 'North Lawrence', 'state_id' => 35],
                ['name' => 'Piercefield', 'state_id' => 35],
                ['name' => 'Brasher Falls', 'state_id' => 35],
                ['name' => 'Brier Hill', 'state_id' => 35],
                ['name' => 'Canton', 'state_id' => 35],
                ['name' => 'Chase Mills', 'state_id' => 35],
                ['name' => 'Chippewa Bay', 'state_id' => 35],
                ['name' => 'Colton', 'state_id' => 35],
                ['name' => 'De Kalb Junction', 'state_id' => 35],
                ['name' => 'De Peyster', 'state_id' => 35],
                ['name' => 'Edwards', 'state_id' => 35],
                ['name' => 'Fine', 'state_id' => 35],
                ['name' => 'Gouverneur', 'state_id' => 35],
                ['name' => 'Hailesboro', 'state_id' => 35],
                ['name' => 'Hammond', 'state_id' => 35],
                ['name' => 'Hannawa Falls', 'state_id' => 35],
                ['name' => 'Helena', 'state_id' => 35],
                ['name' => 'Hermon', 'state_id' => 35],
                ['name' => 'Heuvelton', 'state_id' => 35],
                ['name' => 'Lisbon', 'state_id' => 35],
                ['name' => 'Madrid', 'state_id' => 35],
                ['name' => 'Massena', 'state_id' => 35],
                ['name' => 'Morristown', 'state_id' => 35],
                ['name' => 'Newton Falls', 'state_id' => 35],
                ['name' => 'Norfolk', 'state_id' => 35],
                ['name' => 'Norwood', 'state_id' => 35],
                ['name' => 'Ogdensburg', 'state_id' => 35],
                ['name' => 'Oswegatchie', 'state_id' => 35],
                ['name' => 'Parishville', 'state_id' => 35],
                ['name' => 'Potsdam', 'state_id' => 35],
                ['name' => 'Pyrites', 'state_id' => 35],
                ['name' => 'Raymondville', 'state_id' => 35],
                ['name' => 'Rensselaer Falls', 'state_id' => 35],
                ['name' => 'Richville', 'state_id' => 35],
                ['name' => 'Rooseveltown', 'state_id' => 35],
                ['name' => 'Russell', 'state_id' => 35],
                ['name' => 'South Colton', 'state_id' => 35],
                ['name' => 'Star Lake', 'state_id' => 35],
                ['name' => 'Waddington', 'state_id' => 35],
                ['name' => 'Wanakena', 'state_id' => 35],
                ['name' => 'West Stockholm', 'state_id' => 35],
                ['name' => 'Winthrop', 'state_id' => 35],
                ['name' => 'Ballston Lake', 'state_id' => 35],
                ['name' => 'Ballston Spa', 'state_id' => 35],
                ['name' => 'Burnt Hills', 'state_id' => 35],
                ['name' => 'Clifton Park', 'state_id' => 35],
                ['name' => 'Galway', 'state_id' => 35],
                ['name' => 'Mechanicville', 'state_id' => 35],
                ['name' => 'Rexford', 'state_id' => 35],
                ['name' => 'Round Lake', 'state_id' => 35],
                ['name' => 'Stillwater', 'state_id' => 35],
                ['name' => 'Waterford', 'state_id' => 35],
                ['name' => 'South Glens Falls', 'state_id' => 35],
                ['name' => 'Corinth', 'state_id' => 35],
                ['name' => 'Gansevoort', 'state_id' => 35],
                ['name' => 'Greenfield Center', 'state_id' => 35],
                ['name' => 'Hadley', 'state_id' => 35],
                ['name' => 'Middle Grove', 'state_id' => 35],
                ['name' => 'Porter Corners', 'state_id' => 35],
                ['name' => 'Rock City Falls', 'state_id' => 35],
                ['name' => 'Saratoga Springs', 'state_id' => 35],
                ['name' => 'Schuylerville', 'state_id' => 35],
                ['name' => 'Victory Mills', 'state_id' => 35],
                ['name' => 'Alplaus', 'state_id' => 35],
                ['name' => 'Delanson', 'state_id' => 35],
                ['name' => 'Duanesburg', 'state_id' => 35],
                ['name' => 'Pattersonville', 'state_id' => 35],
                ['name' => 'Quaker Street', 'state_id' => 35],
                ['name' => 'Rotterdam Junction', 'state_id' => 35],
                ['name' => 'Schenectady', 'state_id' => 35],
                ['name' => 'Carlisle', 'state_id' => 35],
                ['name' => 'Central Bridge', 'state_id' => 35],
                ['name' => 'Charlotteville', 'state_id' => 35],
                ['name' => 'Cobleskill', 'state_id' => 35],
                ['name' => 'Fultonham', 'state_id' => 35],
                ['name' => 'Gallupville', 'state_id' => 35],
                ['name' => 'Gilboa', 'state_id' => 35],
                ['name' => 'Howes Cave', 'state_id' => 35],
                ['name' => 'Jefferson', 'state_id' => 35],
                ['name' => 'Middleburgh', 'state_id' => 35],
                ['name' => 'North Blenheim', 'state_id' => 35],
                ['name' => 'Richmondville', 'state_id' => 35],
                ['name' => 'Schoharie', 'state_id' => 35],
                ['name' => 'Sloansville', 'state_id' => 35],
                ['name' => 'Summit', 'state_id' => 35],
                ['name' => 'Warnerville', 'state_id' => 35],
                ['name' => 'West Fulton', 'state_id' => 35],
                ['name' => 'Sharon Springs', 'state_id' => 35],
                ['name' => 'Alpine', 'state_id' => 35],
                ['name' => 'Beaver Dams', 'state_id' => 35],
                ['name' => 'Burdett', 'state_id' => 35],
                ['name' => 'Cayuta', 'state_id' => 35],
                ['name' => 'Hector', 'state_id' => 35],
                ['name' => 'Mecklenburg', 'state_id' => 35],
                ['name' => 'Montour Falls', 'state_id' => 35],
                ['name' => 'Odessa', 'state_id' => 35],
                ['name' => 'Reading Center', 'state_id' => 35],
                ['name' => 'Tyrone', 'state_id' => 35],
                ['name' => 'Watkins Glen', 'state_id' => 35],
                ['name' => 'Wayne', 'state_id' => 35],
                ['name' => 'Fayette', 'state_id' => 35],
                ['name' => 'Seneca Falls', 'state_id' => 35],
                ['name' => 'Waterloo', 'state_id' => 35],
                ['name' => 'Ovid', 'state_id' => 35],
                ['name' => 'Romulus', 'state_id' => 35],
                ['name' => 'Willard', 'state_id' => 35],
                ['name' => 'Interlaken', 'state_id' => 35],
                ['name' => 'Lodi', 'state_id' => 35],
                ['name' => 'Perkinsville', 'state_id' => 35],
                ['name' => 'Wayland', 'state_id' => 35],
                ['name' => 'Addison', 'state_id' => 35],
                ['name' => 'Arkport', 'state_id' => 35],
                ['name' => 'Atlanta', 'state_id' => 35],
                ['name' => 'Avoca', 'state_id' => 35],
                ['name' => 'Bath', 'state_id' => 35],
                ['name' => 'Bradford', 'state_id' => 35],
                ['name' => 'Cameron', 'state_id' => 35],
                ['name' => 'Cameron Mills', 'state_id' => 35],
                ['name' => 'Campbell', 'state_id' => 35],
                ['name' => 'Canisteo', 'state_id' => 35],
                ['name' => 'Cohocton', 'state_id' => 35],
                ['name' => 'Coopers Plains', 'state_id' => 35],
                ['name' => 'Corning', 'state_id' => 35],
                ['name' => 'Greenwood', 'state_id' => 35],
                ['name' => 'Hammondsport', 'state_id' => 35],
                ['name' => 'Hornell', 'state_id' => 35],
                ['name' => 'Jasper', 'state_id' => 35],
                ['name' => 'Kanona', 'state_id' => 35],
                ['name' => 'Lindley', 'state_id' => 35],
                ['name' => 'Painted Post', 'state_id' => 35],
                ['name' => 'Prattsburgh', 'state_id' => 35],
                ['name' => 'Pulteney', 'state_id' => 35],
                ['name' => 'Rexville', 'state_id' => 35],
                ['name' => 'Savona', 'state_id' => 35],
                ['name' => 'Troupsburg', 'state_id' => 35],
                ['name' => 'Woodhull', 'state_id' => 35],
                ['name' => 'Holtsville', 'state_id' => 35],
                ['name' => 'Fishers Island', 'state_id' => 35],
                ['name' => 'Amityville', 'state_id' => 35],
                ['name' => 'Babylon', 'state_id' => 35],
                ['name' => 'North Babylon', 'state_id' => 35],
                ['name' => 'West Babylon', 'state_id' => 35],
                ['name' => 'Bayport', 'state_id' => 35],
                ['name' => 'Bay Shore', 'state_id' => 35],
                ['name' => 'Bellport', 'state_id' => 35],
                ['name' => 'Blue Point', 'state_id' => 35],
                ['name' => 'Bohemia', 'state_id' => 35],
                ['name' => 'Brentwood', 'state_id' => 35],
                ['name' => 'Brightwaters', 'state_id' => 35],
                ['name' => 'Brookhaven', 'state_id' => 35],
                ['name' => 'Centereach', 'state_id' => 35],
                ['name' => 'Centerport', 'state_id' => 35],
                ['name' => 'Central Islip', 'state_id' => 35],
                ['name' => 'Cold Spring Harbor', 'state_id' => 35],
                ['name' => 'Commack', 'state_id' => 35],
                ['name' => 'Copiague', 'state_id' => 35],
                ['name' => 'Coram', 'state_id' => 35],
                ['name' => 'Deer Park', 'state_id' => 35],
                ['name' => 'East Islip', 'state_id' => 35],
                ['name' => 'East Northport', 'state_id' => 35],
                ['name' => 'East Setauket', 'state_id' => 35],
                ['name' => 'Farmingville', 'state_id' => 35],
                ['name' => 'Great River', 'state_id' => 35],
                ['name' => 'Greenlawn', 'state_id' => 35],
                ['name' => 'Holbrook', 'state_id' => 35],
                ['name' => 'Huntington', 'state_id' => 35],
                ['name' => 'Huntington Station', 'state_id' => 35],
                ['name' => 'Melville', 'state_id' => 35],
                ['name' => 'Islandia', 'state_id' => 35],
                ['name' => 'Islip', 'state_id' => 35],
                ['name' => 'Islip Terrace', 'state_id' => 35],
                ['name' => 'Kings Park', 'state_id' => 35],
                ['name' => 'Lake Grove', 'state_id' => 35],
                ['name' => 'Lindenhurst', 'state_id' => 35],
                ['name' => 'Medford', 'state_id' => 35],
                ['name' => 'Miller Place', 'state_id' => 35],
                ['name' => 'Mount Sinai', 'state_id' => 35],
                ['name' => 'Nesconset', 'state_id' => 35],
                ['name' => 'Northport', 'state_id' => 35],
                ['name' => 'Oakdale', 'state_id' => 35],
                ['name' => 'Ocean Beach', 'state_id' => 35],
                ['name' => 'Patchogue', 'state_id' => 35],
                ['name' => 'Port Jefferson Station', 'state_id' => 35],
                ['name' => 'Port Jefferson', 'state_id' => 35],
                ['name' => 'Rocky Point', 'state_id' => 35],
                ['name' => 'Ronkonkoma', 'state_id' => 35],
                ['name' => 'Saint James', 'state_id' => 35],
                ['name' => 'Sayville', 'state_id' => 35],
                ['name' => 'Selden', 'state_id' => 35],
                ['name' => 'Shoreham', 'state_id' => 35],
                ['name' => 'Smithtown', 'state_id' => 35],
                ['name' => 'Hauppauge', 'state_id' => 35],
                ['name' => 'Sound Beach', 'state_id' => 35],
                ['name' => 'Stony Brook', 'state_id' => 35],
                ['name' => 'Wading River', 'state_id' => 35],
                ['name' => 'West Islip', 'state_id' => 35],
                ['name' => 'West Sayville', 'state_id' => 35],
                ['name' => 'Wyandanch', 'state_id' => 35],
                ['name' => 'Riverhead', 'state_id' => 35],
                ['name' => 'Amagansett', 'state_id' => 35],
                ['name' => 'Aquebogue', 'state_id' => 35],
                ['name' => 'Bridgehampton', 'state_id' => 35],
                ['name' => 'Calverton', 'state_id' => 35],
                ['name' => 'Center Moriches', 'state_id' => 35],
                ['name' => 'Cutchogue', 'state_id' => 35],
                ['name' => 'East Hampton', 'state_id' => 35],
                ['name' => 'East Marion', 'state_id' => 35],
                ['name' => 'East Moriches', 'state_id' => 35],
                ['name' => 'Eastport', 'state_id' => 35],
                ['name' => 'East Quogue', 'state_id' => 35],
                ['name' => 'Greenport', 'state_id' => 35],
                ['name' => 'Hampton Bays', 'state_id' => 35],
                ['name' => 'Jamesport', 'state_id' => 35],
                ['name' => 'Laurel', 'state_id' => 35],
                ['name' => 'Manorville', 'state_id' => 35],
                ['name' => 'Mastic', 'state_id' => 35],
                ['name' => 'Mastic Beach', 'state_id' => 35],
                ['name' => 'Mattituck', 'state_id' => 35],
                ['name' => 'Middle Island', 'state_id' => 35],
                ['name' => 'Montauk', 'state_id' => 35],
                ['name' => 'Moriches', 'state_id' => 35],
                ['name' => 'New Suffolk', 'state_id' => 35],
                ['name' => 'Orient', 'state_id' => 35],
                ['name' => 'Peconic', 'state_id' => 35],
                ['name' => 'Quogue', 'state_id' => 35],
                ['name' => 'Remsenburg', 'state_id' => 35],
                ['name' => 'Ridge', 'state_id' => 35],
                ['name' => 'Sagaponack', 'state_id' => 35],
                ['name' => 'Sag Harbor', 'state_id' => 35],
                ['name' => 'Shelter Island', 'state_id' => 35],
                ['name' => 'Shelter Island Heights', 'state_id' => 35],
                ['name' => 'Shirley', 'state_id' => 35],
                ['name' => 'Southampton', 'state_id' => 35],
                ['name' => 'South Jamesport', 'state_id' => 35],
                ['name' => 'Southold', 'state_id' => 35],
                ['name' => 'Speonk', 'state_id' => 35],
                ['name' => 'Upton', 'state_id' => 35],
                ['name' => 'Wainscott', 'state_id' => 35],
                ['name' => 'Water Mill', 'state_id' => 35],
                ['name' => 'Westhampton', 'state_id' => 35],
                ['name' => 'Westhampton Beach', 'state_id' => 35],
                ['name' => 'Yaphank', 'state_id' => 35],
                ['name' => 'Monticello', 'state_id' => 35],
                ['name' => 'Barryville', 'state_id' => 35],
                ['name' => 'Bethel', 'state_id' => 35],
                ['name' => 'Bloomingburg', 'state_id' => 35],
                ['name' => 'Burlingham', 'state_id' => 35],
                ['name' => 'Callicoon', 'state_id' => 35],
                ['name' => 'Callicoon Center', 'state_id' => 35],
                ['name' => 'Claryville', 'state_id' => 35],
                ['name' => 'Cochecton', 'state_id' => 35],
                ['name' => 'Cochecton Center', 'state_id' => 35],
                ['name' => 'Eldred', 'state_id' => 35],
                ['name' => 'Fallsburg', 'state_id' => 35],
                ['name' => 'Ferndale', 'state_id' => 35],
                ['name' => 'Fremont Center', 'state_id' => 35],
                ['name' => 'Glen Spey', 'state_id' => 35],
                ['name' => 'Glen Wild', 'state_id' => 35],
                ['name' => 'Grahamsville', 'state_id' => 35],
                ['name' => 'Hankins', 'state_id' => 35],
                ['name' => 'Harris', 'state_id' => 35],
                ['name' => 'Highland Lake', 'state_id' => 35],
                ['name' => 'Hortonville', 'state_id' => 35],
                ['name' => 'Hurleyville', 'state_id' => 35],
                ['name' => 'Jeffersonville', 'state_id' => 35],
                ['name' => 'Kauneonga Lake', 'state_id' => 35],
                ['name' => 'Kenoza Lake', 'state_id' => 35],
                ['name' => 'Kiamesha Lake', 'state_id' => 35],
                ['name' => 'Lake Huntington', 'state_id' => 35],
                ['name' => 'Liberty', 'state_id' => 35],
                ['name' => 'Livingston Manor', 'state_id' => 35],
                ['name' => 'Loch Sheldrake', 'state_id' => 35],
                ['name' => 'Long Eddy', 'state_id' => 35],
                ['name' => 'Mongaup Valley', 'state_id' => 35],
                ['name' => 'Mountain Dale', 'state_id' => 35],
                ['name' => 'Narrowsburg', 'state_id' => 35],
                ['name' => 'Neversink', 'state_id' => 35],
                ['name' => 'North Branch', 'state_id' => 35],
                ['name' => 'Obernburg', 'state_id' => 35],
                ['name' => 'Parksville', 'state_id' => 35],
                ['name' => 'Phillipsport', 'state_id' => 35],
                ['name' => 'Pond Eddy', 'state_id' => 35],
                ['name' => 'Rock Hill', 'state_id' => 35],
                ['name' => 'Roscoe', 'state_id' => 35],
                ['name' => 'Forestburgh', 'state_id' => 35],
                ['name' => 'Smallwood', 'state_id' => 35],
                ['name' => 'South Fallsburg', 'state_id' => 35],
                ['name' => 'Summitville', 'state_id' => 35],
                ['name' => 'Swan Lake', 'state_id' => 35],
                ['name' => 'Thompsonville', 'state_id' => 35],
                ['name' => 'Westbrookville', 'state_id' => 35],
                ['name' => 'White Lake', 'state_id' => 35],
                ['name' => 'White Sulphur Springs', 'state_id' => 35],
                ['name' => 'Woodbourne', 'state_id' => 35],
                ['name' => 'Woodridge', 'state_id' => 35],
                ['name' => 'Wurtsboro', 'state_id' => 35],
                ['name' => 'Youngsville', 'state_id' => 35],
                ['name' => 'Yulan', 'state_id' => 35],
                ['name' => 'Apalachin', 'state_id' => 35],
                ['name' => 'Barton', 'state_id' => 35],
                ['name' => 'Berkshire', 'state_id' => 35],
                ['name' => 'Candor', 'state_id' => 35],
                ['name' => 'Newark Valley', 'state_id' => 35],
                ['name' => 'Nichols', 'state_id' => 35],
                ['name' => 'Owego', 'state_id' => 35],
                ['name' => 'Richford', 'state_id' => 35],
                ['name' => 'Smithboro', 'state_id' => 35],
                ['name' => 'Tioga Center', 'state_id' => 35],
                ['name' => 'Willseyville', 'state_id' => 35],
                ['name' => 'Lockwood', 'state_id' => 35],
                ['name' => 'Spencer', 'state_id' => 35],
                ['name' => 'Waverly', 'state_id' => 35],
                ['name' => 'Dryden', 'state_id' => 35],
                ['name' => 'Etna', 'state_id' => 35],
                ['name' => 'Freeville', 'state_id' => 35],
                ['name' => 'Groton', 'state_id' => 35],
                ['name' => 'Mc Lean', 'state_id' => 35],
                ['name' => 'Brooktondale', 'state_id' => 35],
                ['name' => 'Ithaca', 'state_id' => 35],
                ['name' => 'Jacksonville', 'state_id' => 35],
                ['name' => 'Newfield', 'state_id' => 35],
                ['name' => 'Slaterville Springs', 'state_id' => 35],
                ['name' => 'Lansing', 'state_id' => 35],
                ['name' => 'Trumansburg', 'state_id' => 35],
                ['name' => 'Kingston', 'state_id' => 35],
                ['name' => 'Accord', 'state_id' => 35],
                ['name' => 'Bearsville', 'state_id' => 35],
                ['name' => 'Big Indian', 'state_id' => 35],
                ['name' => 'Bloomington', 'state_id' => 35],
                ['name' => 'Boiceville', 'state_id' => 35],
                ['name' => 'Chichester', 'state_id' => 35],
                ['name' => 'Connelly', 'state_id' => 35],
                ['name' => 'Cottekill', 'state_id' => 35],
                ['name' => 'Cragsmoor', 'state_id' => 35],
                ['name' => 'Ellenville', 'state_id' => 35],
                ['name' => 'Esopus', 'state_id' => 35],
                ['name' => 'Glasco', 'state_id' => 35],
                ['name' => 'Glenford', 'state_id' => 35],
                ['name' => 'Greenfield Park', 'state_id' => 35],
                ['name' => 'High Falls', 'state_id' => 35],
                ['name' => 'Highmount', 'state_id' => 35],
                ['name' => 'Hurley', 'state_id' => 35],
                ['name' => 'Kerhonkson', 'state_id' => 35],
                ['name' => 'Lake Hill', 'state_id' => 35],
                ['name' => 'Lake Katrine', 'state_id' => 35],
                ['name' => 'Malden On Hudson', 'state_id' => 35],
                ['name' => 'Mount Marion', 'state_id' => 35],
                ['name' => 'Mount Tremper', 'state_id' => 35],
                ['name' => 'Napanoch', 'state_id' => 35],
                ['name' => 'Olivebridge', 'state_id' => 35],
                ['name' => 'Phoenicia', 'state_id' => 35],
                ['name' => 'Pine Hill', 'state_id' => 35],
                ['name' => 'Port Ewen', 'state_id' => 35],
                ['name' => 'Rifton', 'state_id' => 35],
                ['name' => 'Rosendale', 'state_id' => 35],
                ['name' => 'Ruby', 'state_id' => 35],
                ['name' => 'Saugerties', 'state_id' => 35],
                ['name' => 'Shandaken', 'state_id' => 35],
                ['name' => 'Shokan', 'state_id' => 35],
                ['name' => 'Spring Glen', 'state_id' => 35],
                ['name' => 'Stone Ridge', 'state_id' => 35],
                ['name' => 'Tillson', 'state_id' => 35],
                ['name' => 'Ulster Park', 'state_id' => 35],
                ['name' => 'Wawarsing', 'state_id' => 35],
                ['name' => 'West Camp', 'state_id' => 35],
                ['name' => 'West Hurley', 'state_id' => 35],
                ['name' => 'West Park', 'state_id' => 35],
                ['name' => 'West Shokan', 'state_id' => 35],
                ['name' => 'Willow', 'state_id' => 35],
                ['name' => 'Woodstock', 'state_id' => 35],
                ['name' => 'Clintondale', 'state_id' => 35],
                ['name' => 'Gardiner', 'state_id' => 35],
                ['name' => 'Highland', 'state_id' => 35],
                ['name' => 'Marlboro', 'state_id' => 35],
                ['name' => 'Milton', 'state_id' => 35],
                ['name' => 'Modena', 'state_id' => 35],
                ['name' => 'New Paltz', 'state_id' => 35],
                ['name' => 'Plattekill', 'state_id' => 35],
                ['name' => 'Walker Valley', 'state_id' => 35],
                ['name' => 'Wallkill', 'state_id' => 35],
                ['name' => 'Glens Falls', 'state_id' => 35],
                ['name' => 'Queensbury', 'state_id' => 35],
                ['name' => 'Adirondack', 'state_id' => 35],
                ['name' => 'Athol', 'state_id' => 35],
                ['name' => 'Bakers Mills', 'state_id' => 35],
                ['name' => 'Bolton Landing', 'state_id' => 35],
                ['name' => 'Brant Lake', 'state_id' => 35],
                ['name' => 'Chestertown', 'state_id' => 35],
                ['name' => 'Cleverdale', 'state_id' => 35],
                ['name' => 'Diamond Point', 'state_id' => 35],
                ['name' => 'Hague', 'state_id' => 35],
                ['name' => 'Johnsburg', 'state_id' => 35],
                ['name' => 'Kattskill Bay', 'state_id' => 35],
                ['name' => 'Lake George', 'state_id' => 35],
                ['name' => 'Lake Luzerne', 'state_id' => 35],
                ['name' => 'North Creek', 'state_id' => 35],
                ['name' => 'North River', 'state_id' => 35],
                ['name' => 'Pottersville', 'state_id' => 35],
                ['name' => 'Riparius', 'state_id' => 35],
                ['name' => 'Silver Bay', 'state_id' => 35],
                ['name' => 'Stony Creek', 'state_id' => 35],
                ['name' => 'Warrensburg', 'state_id' => 35],
                ['name' => 'Wevertown', 'state_id' => 35],
                ['name' => 'Eagle Bridge', 'state_id' => 35],
                ['name' => 'Argyle', 'state_id' => 35],
                ['name' => 'Cambridge', 'state_id' => 35],
                ['name' => 'Clemons', 'state_id' => 35],
                ['name' => 'Comstock', 'state_id' => 35],
                ['name' => 'Cossayuna', 'state_id' => 35],
                ['name' => 'Fort Ann', 'state_id' => 35],
                ['name' => 'Fort Edward', 'state_id' => 35],
                ['name' => 'Granville', 'state_id' => 35],
                ['name' => 'Greenwich', 'state_id' => 35],
                ['name' => 'Hampton', 'state_id' => 35],
                ['name' => 'Hartford', 'state_id' => 35],
                ['name' => 'Hudson Falls', 'state_id' => 35],
                ['name' => 'Huletts Landing', 'state_id' => 35],
                ['name' => 'Middle Falls', 'state_id' => 35],
                ['name' => 'Middle Granville', 'state_id' => 35],
                ['name' => 'North Granville', 'state_id' => 35],
                ['name' => 'Putnam Station', 'state_id' => 35],
                ['name' => 'Salem', 'state_id' => 35],
                ['name' => 'Shushan', 'state_id' => 35],
                ['name' => 'Whitehall', 'state_id' => 35],
                ['name' => 'Red Creek', 'state_id' => 35],
                ['name' => 'Savannah', 'state_id' => 35],
                ['name' => 'South Butler', 'state_id' => 35],
                ['name' => 'Alton', 'state_id' => 35],
                ['name' => 'Clyde', 'state_id' => 35],
                ['name' => 'East Williamson', 'state_id' => 35],
                ['name' => 'Lyons', 'state_id' => 35],
                ['name' => 'Macedon', 'state_id' => 35],
                ['name' => 'Marion', 'state_id' => 35],
                ['name' => 'Newark', 'state_id' => 35],
                ['name' => 'North Rose', 'state_id' => 35],
                ['name' => 'Ontario', 'state_id' => 35],
                ['name' => 'Ontario Center', 'state_id' => 35],
                ['name' => 'Palmyra', 'state_id' => 35],
                ['name' => 'Pultneyville', 'state_id' => 35],
                ['name' => 'Rose', 'state_id' => 35],
                ['name' => 'Sodus', 'state_id' => 35],
                ['name' => 'Sodus Point', 'state_id' => 35],
                ['name' => 'Union Hill', 'state_id' => 35],
                ['name' => 'Walworth', 'state_id' => 35],
                ['name' => 'Williamson', 'state_id' => 35],
                ['name' => 'Wolcott', 'state_id' => 35],
                ['name' => 'Amawalk', 'state_id' => 35],
                ['name' => 'Ardsley', 'state_id' => 35],
                ['name' => 'Ardsley On Hudson', 'state_id' => 35],
                ['name' => 'Armonk', 'state_id' => 35],
                ['name' => 'Baldwin Place', 'state_id' => 35],
                ['name' => 'Bedford', 'state_id' => 35],
                ['name' => 'Bedford Hills', 'state_id' => 35],
                ['name' => 'Briarcliff Manor', 'state_id' => 35],
                ['name' => 'Buchanan', 'state_id' => 35],
                ['name' => 'Chappaqua', 'state_id' => 35],
                ['name' => 'Crompond', 'state_id' => 35],
                ['name' => 'Cross River', 'state_id' => 35],
                ['name' => 'Croton Falls', 'state_id' => 35],
                ['name' => 'Croton On Hudson', 'state_id' => 35],
                ['name' => 'Dobbs Ferry', 'state_id' => 35],
                ['name' => 'Elmsford', 'state_id' => 35],
                ['name' => 'Goldens Bridge', 'state_id' => 35],
                ['name' => 'Granite Springs', 'state_id' => 35],
                ['name' => 'Harrison', 'state_id' => 35],
                ['name' => 'Hartsdale', 'state_id' => 35],
                ['name' => 'Hawthorne', 'state_id' => 35],
                ['name' => 'Irvington', 'state_id' => 35],
                ['name' => 'Jefferson Valley', 'state_id' => 35],
                ['name' => 'Katonah', 'state_id' => 35],
                ['name' => 'Larchmont', 'state_id' => 35],
                ['name' => 'Lincolndale', 'state_id' => 35],
                ['name' => 'Mamaroneck', 'state_id' => 35],
                ['name' => 'Maryknoll', 'state_id' => 35],
                ['name' => 'Millwood', 'state_id' => 35],
                ['name' => 'Mohegan Lake', 'state_id' => 35],
                ['name' => 'Montrose', 'state_id' => 35],
                ['name' => 'Mount Kisco', 'state_id' => 35],
                ['name' => 'Mount Vernon', 'state_id' => 35],
                ['name' => 'North Salem', 'state_id' => 35],
                ['name' => 'Ossining', 'state_id' => 35],
                ['name' => 'Peekskill', 'state_id' => 35],
                ['name' => 'Cortlandt Manor', 'state_id' => 35],
                ['name' => 'Pleasantville', 'state_id' => 35],
                ['name' => 'Port Chester', 'state_id' => 35],
                ['name' => 'Pound Ridge', 'state_id' => 35],
                ['name' => 'Purchase', 'state_id' => 35],
                ['name' => 'Purdys', 'state_id' => 35],
                ['name' => 'Rye', 'state_id' => 35],
                ['name' => 'Scarsdale', 'state_id' => 35],
                ['name' => 'Shenorock', 'state_id' => 35],
                ['name' => 'Shrub Oak', 'state_id' => 35],
                ['name' => 'Somers', 'state_id' => 35],
                ['name' => 'South Salem', 'state_id' => 35],
                ['name' => 'Tarrytown', 'state_id' => 35],
                ['name' => 'Thornwood', 'state_id' => 35],
                ['name' => 'Valhalla', 'state_id' => 35],
                ['name' => 'Verplanck', 'state_id' => 35],
                ['name' => 'Waccabuc', 'state_id' => 35],
                ['name' => 'Yorktown Heights', 'state_id' => 35],
                ['name' => 'White Plains', 'state_id' => 35],
                ['name' => 'West Harrison', 'state_id' => 35],
                ['name' => 'Yonkers', 'state_id' => 35],
                ['name' => 'Hastings On Hudson', 'state_id' => 35],
                ['name' => 'Tuckahoe', 'state_id' => 35],
                ['name' => 'Bronxville', 'state_id' => 35],
                ['name' => 'Eastchester', 'state_id' => 35],
                ['name' => 'New Rochelle', 'state_id' => 35],
                ['name' => 'Pelham', 'state_id' => 35],
                ['name' => 'Arcade', 'state_id' => 35],
                ['name' => 'Attica', 'state_id' => 35],
                ['name' => 'Bliss', 'state_id' => 35],
                ['name' => 'Cowlesville', 'state_id' => 35],
                ['name' => 'Dale', 'state_id' => 35],
                ['name' => 'Gainesville', 'state_id' => 35],
                ['name' => 'Java Center', 'state_id' => 35],
                ['name' => 'Java Village', 'state_id' => 35],
                ['name' => 'North Java', 'state_id' => 35],
                ['name' => 'Pike', 'state_id' => 35],
                ['name' => 'Strykersville', 'state_id' => 35],
                ['name' => 'Varysburg', 'state_id' => 35],
                ['name' => 'Castile', 'state_id' => 35],
                ['name' => 'Perry', 'state_id' => 35],
                ['name' => 'Portageville', 'state_id' => 35],
                ['name' => 'Silver Lake', 'state_id' => 35],
                ['name' => 'Silver Springs', 'state_id' => 35],
                ['name' => 'Warsaw', 'state_id' => 35],
                ['name' => 'Wyoming', 'state_id' => 35],
                ['name' => 'Bellona', 'state_id' => 35],
                ['name' => 'Branchport', 'state_id' => 35],
                ['name' => 'Dresden', 'state_id' => 35],
                ['name' => 'Keuka Park', 'state_id' => 35],
                ['name' => 'Middlesex', 'state_id' => 35],
                ['name' => 'Penn Yan', 'state_id' => 35],
                ['name' => 'Rushville', 'state_id' => 35],
                ['name' => 'Dundee', 'state_id' => 35],
                ['name' => 'Himrod', 'state_id' => 35],
                ['name' => 'Lakemont', 'state_id' => 35],
                ['name' => 'Rock Stream', 'state_id' => 35]
            ]);
        }
    }
}
