<?php

use Illuminate\Database\Seeder;

class state45TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of UT - Utah.
        //If the table 'cities' exists, insert the data to the table.
        if (DB::table('cities')->get()->count() >= 0) {
            DB::table('cities')->insert([
                ['name' => 'Beaver', 'state_id' => 45],
                ['name' => 'Greenville', 'state_id' => 45],
                ['name' => 'Milford', 'state_id' => 45],
                ['name' => 'Minersville', 'state_id' => 45],
                ['name' => 'Bear River City', 'state_id' => 45],
                ['name' => 'Brigham City', 'state_id' => 45],
                ['name' => 'Collinston', 'state_id' => 45],
                ['name' => 'Corinne', 'state_id' => 45],
                ['name' => 'Deweyville', 'state_id' => 45],
                ['name' => 'Fielding', 'state_id' => 45],
                ['name' => 'Garland', 'state_id' => 45],
                ['name' => 'Grouse Creek', 'state_id' => 45],
                ['name' => 'Honeyville', 'state_id' => 45],
                ['name' => 'Howell', 'state_id' => 45],
                ['name' => 'Mantua', 'state_id' => 45],
                ['name' => 'Park Valley', 'state_id' => 45],
                ['name' => 'Plymouth', 'state_id' => 45],
                ['name' => 'Portage', 'state_id' => 45],
                ['name' => 'Riverside', 'state_id' => 45],
                ['name' => 'Snowville', 'state_id' => 45],
                ['name' => 'Tremonton', 'state_id' => 45],
                ['name' => 'Willard', 'state_id' => 45],
                ['name' => 'Cache Junction', 'state_id' => 45],
                ['name' => 'Clarkston', 'state_id' => 45],
                ['name' => 'Cornish', 'state_id' => 45],
                ['name' => 'Hyde Park', 'state_id' => 45],
                ['name' => 'Hyrum', 'state_id' => 45],
                ['name' => 'Lewiston', 'state_id' => 45],
                ['name' => 'Logan', 'state_id' => 45],
                ['name' => 'Mendon', 'state_id' => 45],
                ['name' => 'Millville', 'state_id' => 45],
                ['name' => 'Newton', 'state_id' => 45],
                ['name' => 'Paradise', 'state_id' => 45],
                ['name' => 'Providence', 'state_id' => 45],
                ['name' => 'Richmond', 'state_id' => 45],
                ['name' => 'Smithfield', 'state_id' => 45],
                ['name' => 'Trenton', 'state_id' => 45],
                ['name' => 'Wellsville', 'state_id' => 45],
                ['name' => 'Price', 'state_id' => 45],
                ['name' => 'East Carbon', 'state_id' => 45],
                ['name' => 'Helper', 'state_id' => 45],
                ['name' => 'Kenilworth', 'state_id' => 45],
                ['name' => 'Sunnyside', 'state_id' => 45],
                ['name' => 'Wellington', 'state_id' => 45],
                ['name' => 'Dutch John', 'state_id' => 45],
                ['name' => 'Manila', 'state_id' => 45],
                ['name' => 'Bountiful', 'state_id' => 45],
                ['name' => 'Centerville', 'state_id' => 45],
                ['name' => 'Clearfield', 'state_id' => 45],
                ['name' => 'Farmington', 'state_id' => 45],
                ['name' => 'Kaysville', 'state_id' => 45],
                ['name' => 'Layton', 'state_id' => 45],
                ['name' => 'North Salt Lake', 'state_id' => 45],
                ['name' => 'Hill Afb', 'state_id' => 45],
                ['name' => 'Syracuse', 'state_id' => 45],
                ['name' => 'Woods Cross', 'state_id' => 45],
                ['name' => 'Altamont', 'state_id' => 45],
                ['name' => 'Altonah', 'state_id' => 45],
                ['name' => 'Bluebell', 'state_id' => 45],
                ['name' => 'Duchesne', 'state_id' => 45],
                ['name' => 'Fruitland', 'state_id' => 45],
                ['name' => 'Hanna', 'state_id' => 45],
                ['name' => 'Mountain Home', 'state_id' => 45],
                ['name' => 'Myton', 'state_id' => 45],
                ['name' => 'Neola', 'state_id' => 45],
                ['name' => 'Roosevelt', 'state_id' => 45],
                ['name' => 'Tabiona', 'state_id' => 45],
                ['name' => 'Talmage', 'state_id' => 45],
                ['name' => 'Castle Dale', 'state_id' => 45],
                ['name' => 'Clawson', 'state_id' => 45],
                ['name' => 'Cleveland', 'state_id' => 45],
                ['name' => 'Elmo', 'state_id' => 45],
                ['name' => 'Emery', 'state_id' => 45],
                ['name' => 'Ferron', 'state_id' => 45],
                ['name' => 'Green River', 'state_id' => 45],
                ['name' => 'Huntington', 'state_id' => 45],
                ['name' => 'Orangeville', 'state_id' => 45],
                ['name' => 'Antimony', 'state_id' => 45],
                ['name' => 'Boulder', 'state_id' => 45],
                ['name' => 'Cannonville', 'state_id' => 45],
                ['name' => 'Escalante', 'state_id' => 45],
                ['name' => 'Hatch', 'state_id' => 45],
                ['name' => 'Henrieville', 'state_id' => 45],
                ['name' => 'Panguitch', 'state_id' => 45],
                ['name' => 'Bryce', 'state_id' => 45],
                ['name' => 'Tropic', 'state_id' => 45],
                ['name' => 'Cisco', 'state_id' => 45],
                ['name' => 'Moab', 'state_id' => 45],
                ['name' => 'Thompson', 'state_id' => 45],
                ['name' => 'Beryl', 'state_id' => 45],
                ['name' => 'Brian Head', 'state_id' => 45],
                ['name' => 'Cedar City', 'state_id' => 45],
                ['name' => 'Kanarraville', 'state_id' => 45],
                ['name' => 'Modena', 'state_id' => 45],
                ['name' => 'Newcastle', 'state_id' => 45],
                ['name' => 'Paragonah', 'state_id' => 45],
                ['name' => 'Parowan', 'state_id' => 45],
                ['name' => 'Summit', 'state_id' => 45],
                ['name' => 'Eureka', 'state_id' => 45],
                ['name' => 'Levan', 'state_id' => 45],
                ['name' => 'Mona', 'state_id' => 45],
                ['name' => 'Nephi', 'state_id' => 45],
                ['name' => 'Alton', 'state_id' => 45],
                ['name' => 'Glendale', 'state_id' => 45],
                ['name' => 'Kanab', 'state_id' => 45],
                ['name' => 'Mount Carmel', 'state_id' => 45],
                ['name' => 'Orderville', 'state_id' => 45],
                ['name' => 'Duck Creek Village', 'state_id' => 45],
                ['name' => 'Delta', 'state_id' => 45],
                ['name' => 'Fillmore', 'state_id' => 45],
                ['name' => 'Hinckley', 'state_id' => 45],
                ['name' => 'Holden', 'state_id' => 45],
                ['name' => 'Kanosh', 'state_id' => 45],
                ['name' => 'Leamington', 'state_id' => 45],
                ['name' => 'Lynndyl', 'state_id' => 45],
                ['name' => 'Meadow', 'state_id' => 45],
                ['name' => 'Oak City', 'state_id' => 45],
                ['name' => 'Scipio', 'state_id' => 45],
                ['name' => 'Garrison', 'state_id' => 45],
                ['name' => 'Croydon', 'state_id' => 45],
                ['name' => 'Morgan', 'state_id' => 45],
                ['name' => 'Circleville', 'state_id' => 45],
                ['name' => 'Greenwich', 'state_id' => 45],
                ['name' => 'Junction', 'state_id' => 45],
                ['name' => 'Kingston', 'state_id' => 45],
                ['name' => 'Marysvale', 'state_id' => 45],
                ['name' => 'Garden City', 'state_id' => 45],
                ['name' => 'Laketown', 'state_id' => 45],
                ['name' => 'Randolph', 'state_id' => 45],
                ['name' => 'Woodruff', 'state_id' => 45],
                ['name' => 'Bingham Canyon', 'state_id' => 45],
                ['name' => 'South Jordan', 'state_id' => 45],
                ['name' => 'Draper', 'state_id' => 45],
                ['name' => 'Magna', 'state_id' => 45],
                ['name' => 'Midvale', 'state_id' => 45],
                ['name' => 'Riverton', 'state_id' => 45],
                ['name' => 'Sandy', 'state_id' => 45],
                ['name' => 'West Jordan', 'state_id' => 45],
                ['name' => 'Herriman', 'state_id' => 45],
                ['name' => 'Salt Lake City', 'state_id' => 45],
                ['name' => 'West Valley City', 'state_id' => 45],
                ['name' => 'Aneth', 'state_id' => 45],
                ['name' => 'Blanding', 'state_id' => 45],
                ['name' => 'Bluff', 'state_id' => 45],
                ['name' => 'La Sal', 'state_id' => 45],
                ['name' => 'Mexican Hat', 'state_id' => 45],
                ['name' => 'Lake Powell', 'state_id' => 45],
                ['name' => 'Montezuma Creek', 'state_id' => 45],
                ['name' => 'Monticello', 'state_id' => 45],
                ['name' => 'Monument Valley', 'state_id' => 45],
                ['name' => 'Axtell', 'state_id' => 45],
                ['name' => 'Centerfield', 'state_id' => 45],
                ['name' => 'Chester', 'state_id' => 45],
                ['name' => 'Ephraim', 'state_id' => 45],
                ['name' => 'Fairview', 'state_id' => 45],
                ['name' => 'Fayette', 'state_id' => 45],
                ['name' => 'Fountain Green', 'state_id' => 45],
                ['name' => 'Gunnison', 'state_id' => 45],
                ['name' => 'Manti', 'state_id' => 45],
                ['name' => 'Mayfield', 'state_id' => 45],
                ['name' => 'Moroni', 'state_id' => 45],
                ['name' => 'Mount Pleasant', 'state_id' => 45],
                ['name' => 'Spring City', 'state_id' => 45],
                ['name' => 'Sterling', 'state_id' => 45],
                ['name' => 'Wales', 'state_id' => 45],
                ['name' => 'Aurora', 'state_id' => 45],
                ['name' => 'Redmond', 'state_id' => 45],
                ['name' => 'Salina', 'state_id' => 45],
                ['name' => 'Sigurd', 'state_id' => 45],
                ['name' => 'Richfield', 'state_id' => 45],
                ['name' => 'Annabella', 'state_id' => 45],
                ['name' => 'Elsinore', 'state_id' => 45],
                ['name' => 'Glenwood', 'state_id' => 45],
                ['name' => 'Joseph', 'state_id' => 45],
                ['name' => 'Koosharem', 'state_id' => 45],
                ['name' => 'Monroe', 'state_id' => 45],
                ['name' => 'Sevier', 'state_id' => 45],
                ['name' => 'Coalville', 'state_id' => 45],
                ['name' => 'Echo', 'state_id' => 45],
                ['name' => 'Henefer', 'state_id' => 45],
                ['name' => 'Kamas', 'state_id' => 45],
                ['name' => 'Oakley', 'state_id' => 45],
                ['name' => 'Park City', 'state_id' => 45],
                ['name' => 'Peoa', 'state_id' => 45],
                ['name' => 'Dugway', 'state_id' => 45],
                ['name' => 'Grantsville', 'state_id' => 45],
                ['name' => 'Ibapah', 'state_id' => 45],
                ['name' => 'Rush Valley', 'state_id' => 45],
                ['name' => 'Stockton', 'state_id' => 45],
                ['name' => 'Tooele', 'state_id' => 45],
                ['name' => 'Vernon', 'state_id' => 45],
                ['name' => 'Wendover', 'state_id' => 45],
                ['name' => 'Bonanza', 'state_id' => 45],
                ['name' => 'Fort Duchesne', 'state_id' => 45],
                ['name' => 'Jensen', 'state_id' => 45],
                ['name' => 'Lapoint', 'state_id' => 45],
                ['name' => 'Randlett', 'state_id' => 45],
                ['name' => 'Tridell', 'state_id' => 45],
                ['name' => 'Vernal', 'state_id' => 45],
                ['name' => 'Whiterocks', 'state_id' => 45],
                ['name' => 'American Fork', 'state_id' => 45],
                ['name' => 'Alpine', 'state_id' => 45],
                ['name' => 'Eagle Mountain', 'state_id' => 45],
                ['name' => 'Cedar Valley', 'state_id' => 45],
                ['name' => 'Lindon', 'state_id' => 45],
                ['name' => 'Lehi', 'state_id' => 45],
                ['name' => 'Saratoga Springs', 'state_id' => 45],
                ['name' => 'Orem', 'state_id' => 45],
                ['name' => 'Pleasant Grove', 'state_id' => 45],
                ['name' => 'Provo', 'state_id' => 45],
                ['name' => 'Elberta', 'state_id' => 45],
                ['name' => 'Goshen', 'state_id' => 45],
                ['name' => 'Payson', 'state_id' => 45],
                ['name' => 'Salem', 'state_id' => 45],
                ['name' => 'Santaquin', 'state_id' => 45],
                ['name' => 'Spanish Fork', 'state_id' => 45],
                ['name' => 'Springville', 'state_id' => 45],
                ['name' => 'Mapleton', 'state_id' => 45],
                ['name' => 'Heber City', 'state_id' => 45],
                ['name' => 'Midway', 'state_id' => 45],
                ['name' => 'Wallsburg', 'state_id' => 45],
                ['name' => 'Central', 'state_id' => 45],
                ['name' => 'Enterprise', 'state_id' => 45],
                ['name' => 'Gunlock', 'state_id' => 45],
                ['name' => 'Hurricane', 'state_id' => 45],
                ['name' => 'Ivins', 'state_id' => 45],
                ['name' => 'La Verkin', 'state_id' => 45],
                ['name' => 'Leeds', 'state_id' => 45],
                ['name' => 'New Harmony', 'state_id' => 45],
                ['name' => 'Rockville', 'state_id' => 45],
                ['name' => 'Santa Clara', 'state_id' => 45],
                ['name' => 'Springdale', 'state_id' => 45],
                ['name' => 'Saint George', 'state_id' => 45],
                ['name' => 'Toquerville', 'state_id' => 45],
                ['name' => 'Virgin', 'state_id' => 45],
                ['name' => 'Washington', 'state_id' => 45],
                ['name' => 'Pine Valley', 'state_id' => 45],
                ['name' => 'Veyo', 'state_id' => 45],
                ['name' => 'Dammeron Valley', 'state_id' => 45],
                ['name' => 'Hildale', 'state_id' => 45],
                ['name' => 'Bicknell', 'state_id' => 45],
                ['name' => 'Hanksville', 'state_id' => 45],
                ['name' => 'Loa', 'state_id' => 45],
                ['name' => 'Lyman', 'state_id' => 45],
                ['name' => 'Teasdale', 'state_id' => 45],
                ['name' => 'Torrey', 'state_id' => 45],
                ['name' => 'Roy', 'state_id' => 45],
                ['name' => 'Ogden', 'state_id' => 45],
                ['name' => 'Eden', 'state_id' => 45],
                ['name' => 'Hooper', 'state_id' => 45],
                ['name' => 'Huntsville', 'state_id' => 45]
            ]);
        }
    }
}
