<?php

use Illuminate\Database\Seeder;

class state36TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of OH - Ohio.
        //If the table 'cities' exists, insert the data to the table.
        if (DB::table('cities')->get()->count() >= 0) {
            DB::table('cities')->insert([
                ['name' => 'Bentonville', 'state_id' => 36],
                ['name' => 'Manchester', 'state_id' => 36],
                ['name' => 'Blue Creek', 'state_id' => 36],
                ['name' => 'Cherry Fork', 'state_id' => 36],
                ['name' => 'Lynx', 'state_id' => 36],
                ['name' => 'Peebles', 'state_id' => 36],
                ['name' => 'Seaman', 'state_id' => 36],
                ['name' => 'West Union', 'state_id' => 36],
                ['name' => 'Winchester', 'state_id' => 36],
                ['name' => 'Lima', 'state_id' => 36],
                ['name' => 'Beaverdam', 'state_id' => 36],
                ['name' => 'Gomer', 'state_id' => 36],
                ['name' => 'Bluffton', 'state_id' => 36],
                ['name' => 'Cairo', 'state_id' => 36],
                ['name' => 'Delphos', 'state_id' => 36],
                ['name' => 'Harrod', 'state_id' => 36],
                ['name' => 'Lafayette', 'state_id' => 36],
                ['name' => 'Spencerville', 'state_id' => 36],
                ['name' => 'Ashland', 'state_id' => 36],
                ['name' => 'Hayesville', 'state_id' => 36],
                ['name' => 'Jeromesville', 'state_id' => 36],
                ['name' => 'Loudonville', 'state_id' => 36],
                ['name' => 'Nankin', 'state_id' => 36],
                ['name' => 'Nova', 'state_id' => 36],
                ['name' => 'Perrysville', 'state_id' => 36],
                ['name' => 'Polk', 'state_id' => 36],
                ['name' => 'Savannah', 'state_id' => 36],
                ['name' => 'Sullivan', 'state_id' => 36],
                ['name' => 'Andover', 'state_id' => 36],
                ['name' => 'Ashtabula', 'state_id' => 36],
                ['name' => 'Austinburg', 'state_id' => 36],
                ['name' => 'Conneaut', 'state_id' => 36],
                ['name' => 'Dorset', 'state_id' => 36],
                ['name' => 'Geneva', 'state_id' => 36],
                ['name' => 'Jefferson', 'state_id' => 36],
                ['name' => 'Kingsville', 'state_id' => 36],
                ['name' => 'North Kingsville', 'state_id' => 36],
                ['name' => 'Orwell', 'state_id' => 36],
                ['name' => 'Pierpont', 'state_id' => 36],
                ['name' => 'Rock Creek', 'state_id' => 36],
                ['name' => 'Rome', 'state_id' => 36],
                ['name' => 'Unionville', 'state_id' => 36],
                ['name' => 'Williamsfield', 'state_id' => 36],
                ['name' => 'Windsor', 'state_id' => 36],
                ['name' => 'Athens', 'state_id' => 36],
                ['name' => 'Albany', 'state_id' => 36],
                ['name' => 'Amesville', 'state_id' => 36],
                ['name' => 'Buchtel', 'state_id' => 36],
                ['name' => 'Carbondale', 'state_id' => 36],
                ['name' => 'Chauncey', 'state_id' => 36],
                ['name' => 'Coolville', 'state_id' => 36],
                ['name' => 'Glouster', 'state_id' => 36],
                ['name' => 'Guysville', 'state_id' => 36],
                ['name' => 'Hockingport', 'state_id' => 36],
                ['name' => 'Jacksonville', 'state_id' => 36],
                ['name' => 'Millfield', 'state_id' => 36],
                ['name' => 'Nelsonville', 'state_id' => 36],
                ['name' => 'New Marshfield', 'state_id' => 36],
                ['name' => 'Shade', 'state_id' => 36],
                ['name' => 'Sharpsburg', 'state_id' => 36],
                ['name' => 'Stewart', 'state_id' => 36],
                ['name' => 'The Plains', 'state_id' => 36],
                ['name' => 'Trimble', 'state_id' => 36],
                ['name' => 'Buckland', 'state_id' => 36],
                ['name' => 'Minster', 'state_id' => 36],
                ['name' => 'New Bremen', 'state_id' => 36],
                ['name' => 'New Hampshire', 'state_id' => 36],
                ['name' => 'New Knoxville', 'state_id' => 36],
                ['name' => 'Saint Johns', 'state_id' => 36],
                ['name' => 'Saint Marys', 'state_id' => 36],
                ['name' => 'Uniopolis', 'state_id' => 36],
                ['name' => 'Wapakoneta', 'state_id' => 36],
                ['name' => 'Waynesfield', 'state_id' => 36],
                ['name' => 'Barnesville', 'state_id' => 36],
                ['name' => 'Belmont', 'state_id' => 36],
                ['name' => 'Bethesda', 'state_id' => 36],
                ['name' => 'Morristown', 'state_id' => 36],
                ['name' => 'Alledonia', 'state_id' => 36],
                ['name' => 'Barton', 'state_id' => 36],
                ['name' => 'Bellaire', 'state_id' => 36],
                ['name' => 'Blaine', 'state_id' => 36],
                ['name' => 'Bridgeport', 'state_id' => 36],
                ['name' => 'Colerain', 'state_id' => 36],
                ['name' => 'Fairpoint', 'state_id' => 36],
                ['name' => 'Glencoe', 'state_id' => 36],
                ['name' => 'Jacobsburg', 'state_id' => 36],
                ['name' => 'Lansing', 'state_id' => 36],
                ['name' => 'Martins Ferry', 'state_id' => 36],
                ['name' => 'Maynard', 'state_id' => 36],
                ['name' => 'Neffs', 'state_id' => 36],
                ['name' => 'Powhatan Point', 'state_id' => 36],
                ['name' => 'Shadyside', 'state_id' => 36],
                ['name' => 'Saint Clairsville', 'state_id' => 36],
                ['name' => 'Lafferty', 'state_id' => 36],
                ['name' => 'Warnock', 'state_id' => 36],
                ['name' => 'Bannock', 'state_id' => 36],
                ['name' => 'Flushing', 'state_id' => 36],
                ['name' => 'Piedmont', 'state_id' => 36],
                ['name' => 'Holloway', 'state_id' => 36],
                ['name' => 'Aberdeen', 'state_id' => 36],
                ['name' => 'Decatur', 'state_id' => 36],
                ['name' => 'Fayetteville', 'state_id' => 36],
                ['name' => 'Feesburg', 'state_id' => 36],
                ['name' => 'Georgetown', 'state_id' => 36],
                ['name' => 'Hamersville', 'state_id' => 36],
                ['name' => 'Higginsport', 'state_id' => 36],
                ['name' => 'Mount Orab', 'state_id' => 36],
                ['name' => 'Ripley', 'state_id' => 36],
                ['name' => 'Russellville', 'state_id' => 36],
                ['name' => 'Sardinia', 'state_id' => 36],
                ['name' => 'Cincinnati', 'state_id' => 36],
                ['name' => 'College Corner', 'state_id' => 36],
                ['name' => 'Collinsville', 'state_id' => 36],
                ['name' => 'Hamilton', 'state_id' => 36],
                ['name' => 'Fairfield', 'state_id' => 36],
                ['name' => 'Middletown', 'state_id' => 36],
                ['name' => 'Monroe', 'state_id' => 36],
                ['name' => 'Okeana', 'state_id' => 36],
                ['name' => 'Overpeck', 'state_id' => 36],
                ['name' => 'Oxford', 'state_id' => 36],
                ['name' => 'Ross', 'state_id' => 36],
                ['name' => 'Seven Mile', 'state_id' => 36],
                ['name' => 'Shandon', 'state_id' => 36],
                ['name' => 'Somerville', 'state_id' => 36],
                ['name' => 'Trenton', 'state_id' => 36],
                ['name' => 'West Chester', 'state_id' => 36],
                ['name' => 'Augusta', 'state_id' => 36],
                ['name' => 'Carrollton', 'state_id' => 36],
                ['name' => 'Dellroy', 'state_id' => 36],
                ['name' => 'Leesville', 'state_id' => 36],
                ['name' => 'Malvern', 'state_id' => 36],
                ['name' => 'Mechanicstown', 'state_id' => 36],
                ['name' => 'Sherrodsville', 'state_id' => 36],
                ['name' => 'Cable', 'state_id' => 36],
                ['name' => 'Mechanicsburg', 'state_id' => 36],
                ['name' => 'Mingo', 'state_id' => 36],
                ['name' => 'North Lewisburg', 'state_id' => 36],
                ['name' => 'Rosewood', 'state_id' => 36],
                ['name' => 'Saint Paris', 'state_id' => 36],
                ['name' => 'Urbana', 'state_id' => 36],
                ['name' => 'Westville', 'state_id' => 36],
                ['name' => 'Woodstock', 'state_id' => 36],
                ['name' => 'Christiansburg', 'state_id' => 36],
                ['name' => 'Catawba', 'state_id' => 36],
                ['name' => 'Donnelsville', 'state_id' => 36],
                ['name' => 'Enon', 'state_id' => 36],
                ['name' => 'Medway', 'state_id' => 36],
                ['name' => 'New Carlisle', 'state_id' => 36],
                ['name' => 'North Hampton', 'state_id' => 36],
                ['name' => 'South Charleston', 'state_id' => 36],
                ['name' => 'South Vienna', 'state_id' => 36],
                ['name' => 'Tremont City', 'state_id' => 36],
                ['name' => 'Springfield', 'state_id' => 36],
                ['name' => 'Amelia', 'state_id' => 36],
                ['name' => 'Batavia', 'state_id' => 36],
                ['name' => 'Bethel', 'state_id' => 36],
                ['name' => 'Chilo', 'state_id' => 36],
                ['name' => 'Felicity', 'state_id' => 36],
                ['name' => 'Goshen', 'state_id' => 36],
                ['name' => 'Loveland', 'state_id' => 36],
                ['name' => 'Miamiville', 'state_id' => 36],
                ['name' => 'Milford', 'state_id' => 36],
                ['name' => 'Moscow', 'state_id' => 36],
                ['name' => 'Neville', 'state_id' => 36],
                ['name' => 'New Richmond', 'state_id' => 36],
                ['name' => 'Newtonsville', 'state_id' => 36],
                ['name' => 'Owensville', 'state_id' => 36],
                ['name' => 'Williamsburg', 'state_id' => 36],
                ['name' => 'Blanchester', 'state_id' => 36],
                ['name' => 'Clarksville', 'state_id' => 36],
                ['name' => 'Cuba', 'state_id' => 36],
                ['name' => 'Martinsville', 'state_id' => 36],
                ['name' => 'Midland', 'state_id' => 36],
                ['name' => 'New Vienna', 'state_id' => 36],
                ['name' => 'Port William', 'state_id' => 36],
                ['name' => 'Reesville', 'state_id' => 36],
                ['name' => 'Sabina', 'state_id' => 36],
                ['name' => 'Wilmington', 'state_id' => 36],
                ['name' => 'East Liverpool', 'state_id' => 36],
                ['name' => 'Salineville', 'state_id' => 36],
                ['name' => 'Summitville', 'state_id' => 36],
                ['name' => 'Wellsville', 'state_id' => 36],
                ['name' => 'Columbiana', 'state_id' => 36],
                ['name' => 'East Palestine', 'state_id' => 36],
                ['name' => 'Elkton', 'state_id' => 36],
                ['name' => 'Hanoverton', 'state_id' => 36],
                ['name' => 'Kensington', 'state_id' => 36],
                ['name' => 'Leetonia', 'state_id' => 36],
                ['name' => 'Lisbon', 'state_id' => 36],
                ['name' => 'Negley', 'state_id' => 36],
                ['name' => 'New Waterford', 'state_id' => 36],
                ['name' => 'Rogers', 'state_id' => 36],
                ['name' => 'Salem', 'state_id' => 36],
                ['name' => 'Washingtonville', 'state_id' => 36],
                ['name' => 'West Point', 'state_id' => 36],
                ['name' => 'Winona', 'state_id' => 36],
                ['name' => 'East Rochester', 'state_id' => 36],
                ['name' => 'Homeworth', 'state_id' => 36],
                ['name' => 'North Georgetown', 'state_id' => 36],
                ['name' => 'Bakersville', 'state_id' => 36],
                ['name' => 'Blissfield', 'state_id' => 36],
                ['name' => 'Conesville', 'state_id' => 36],
                ['name' => 'Coshocton', 'state_id' => 36],
                ['name' => 'Fresno', 'state_id' => 36],
                ['name' => 'Keene', 'state_id' => 36],
                ['name' => 'Plainfield', 'state_id' => 36],
                ['name' => 'Walhonding', 'state_id' => 36],
                ['name' => 'Warsaw', 'state_id' => 36],
                ['name' => 'West Lafayette', 'state_id' => 36],
                ['name' => 'Bucyrus', 'state_id' => 36],
                ['name' => 'Chatfield', 'state_id' => 36],
                ['name' => 'Crestline', 'state_id' => 36],
                ['name' => 'Galion', 'state_id' => 36],
                ['name' => 'New Washington', 'state_id' => 36],
                ['name' => 'North Robinson', 'state_id' => 36],
                ['name' => 'Oceola', 'state_id' => 36],
                ['name' => 'Sulphur Springs', 'state_id' => 36],
                ['name' => 'Tiro', 'state_id' => 36],
                ['name' => 'Berea', 'state_id' => 36],
                ['name' => 'Chagrin Falls', 'state_id' => 36],
                ['name' => 'Gates Mills', 'state_id' => 36],
                ['name' => 'North Olmsted', 'state_id' => 36],
                ['name' => 'Cleveland', 'state_id' => 36],
                ['name' => 'Lakewood', 'state_id' => 36],
                ['name' => 'Rocky River', 'state_id' => 36],
                ['name' => 'Euclid', 'state_id' => 36],
                ['name' => 'Beachwood', 'state_id' => 36],
                ['name' => 'Independence', 'state_id' => 36],
                ['name' => 'North Royalton', 'state_id' => 36],
                ['name' => 'Strongsville', 'state_id' => 36],
                ['name' => 'Maple Heights', 'state_id' => 36],
                ['name' => 'Olmsted Falls', 'state_id' => 36],
                ['name' => 'Solon', 'state_id' => 36],
                ['name' => 'Bay Village', 'state_id' => 36],
                ['name' => 'Brecksville', 'state_id' => 36],
                ['name' => 'Brookpark', 'state_id' => 36],
                ['name' => 'Westlake', 'state_id' => 36],
                ['name' => 'Bedford', 'state_id' => 36],
                ['name' => 'Broadview Heights', 'state_id' => 36],
                ['name' => 'Ansonia', 'state_id' => 36],
                ['name' => 'Arcanum', 'state_id' => 36],
                ['name' => 'Gettysburg', 'state_id' => 36],
                ['name' => 'Greenville', 'state_id' => 36],
                ['name' => 'Hollansburg', 'state_id' => 36],
                ['name' => 'New Madison', 'state_id' => 36],
                ['name' => 'New Weston', 'state_id' => 36],
                ['name' => 'North Star', 'state_id' => 36],
                ['name' => 'Osgood', 'state_id' => 36],
                ['name' => 'Palestine', 'state_id' => 36],
                ['name' => 'Pitsburg', 'state_id' => 36],
                ['name' => 'Rossburg', 'state_id' => 36],
                ['name' => 'Versailles', 'state_id' => 36],
                ['name' => 'Yorkshire', 'state_id' => 36],
                ['name' => 'Union City', 'state_id' => 36],
                ['name' => 'Defiance', 'state_id' => 36],
                ['name' => 'Evansport', 'state_id' => 36],
                ['name' => 'Farmer', 'state_id' => 36],
                ['name' => 'Hicksville', 'state_id' => 36],
                ['name' => 'Jewell', 'state_id' => 36],
                ['name' => 'Mark Center', 'state_id' => 36],
                ['name' => 'Ney', 'state_id' => 36],
                ['name' => 'Sherwood', 'state_id' => 36],
                ['name' => 'Ashley', 'state_id' => 36],
                ['name' => 'Delaware', 'state_id' => 36],
                ['name' => 'Galena', 'state_id' => 36],
                ['name' => 'Kilbourne', 'state_id' => 36],
                ['name' => 'Lewis Center', 'state_id' => 36],
                ['name' => 'Ostrander', 'state_id' => 36],
                ['name' => 'Powell', 'state_id' => 36],
                ['name' => 'Radnor', 'state_id' => 36],
                ['name' => 'Sunbury', 'state_id' => 36],
                ['name' => 'Westerville', 'state_id' => 36],
                ['name' => 'Kelleys Island', 'state_id' => 36],
                ['name' => 'Vermilion', 'state_id' => 36],
                ['name' => 'Berlin Heights', 'state_id' => 36],
                ['name' => 'Birmingham', 'state_id' => 36],
                ['name' => 'Castalia', 'state_id' => 36],
                ['name' => 'Huron', 'state_id' => 36],
                ['name' => 'Milan', 'state_id' => 36],
                ['name' => 'Sandusky', 'state_id' => 36],
                ['name' => 'Millersport', 'state_id' => 36],
                ['name' => 'Amanda', 'state_id' => 36],
                ['name' => 'Baltimore', 'state_id' => 36],
                ['name' => 'Bremen', 'state_id' => 36],
                ['name' => 'Canal Winchester', 'state_id' => 36],
                ['name' => 'Carroll', 'state_id' => 36],
                ['name' => 'Lancaster', 'state_id' => 36],
                ['name' => 'Lithopolis', 'state_id' => 36],
                ['name' => 'Pickerington', 'state_id' => 36],
                ['name' => 'Pleasantville', 'state_id' => 36],
                ['name' => 'Rushville', 'state_id' => 36],
                ['name' => 'Stoutsville', 'state_id' => 36],
                ['name' => 'Sugar Grove', 'state_id' => 36],
                ['name' => 'Thurston', 'state_id' => 36],
                ['name' => 'Bloomingburg', 'state_id' => 36],
                ['name' => 'Jeffersonville', 'state_id' => 36],
                ['name' => 'Milledgeville', 'state_id' => 36],
                ['name' => 'Washington Court House', 'state_id' => 36],
                ['name' => 'Amlin', 'state_id' => 36],
                ['name' => 'Blacklick', 'state_id' => 36],
                ['name' => 'Dublin', 'state_id' => 36],
                ['name' => 'Hilliard', 'state_id' => 36],
                ['name' => 'New Albany', 'state_id' => 36],
                ['name' => 'Reynoldsburg', 'state_id' => 36],
                ['name' => 'Columbus', 'state_id' => 36],
                ['name' => 'Brice', 'state_id' => 36],
                ['name' => 'Galloway', 'state_id' => 36],
                ['name' => 'Grove City', 'state_id' => 36],
                ['name' => 'Groveport', 'state_id' => 36],
                ['name' => 'Harrisburg', 'state_id' => 36],
                ['name' => 'Lockbourne', 'state_id' => 36],
                ['name' => 'Archbold', 'state_id' => 36],
                ['name' => 'Delta', 'state_id' => 36],
                ['name' => 'Fayette', 'state_id' => 36],
                ['name' => 'Lyons', 'state_id' => 36],
                ['name' => 'Metamora', 'state_id' => 36],
                ['name' => 'Pettisville', 'state_id' => 36],
                ['name' => 'Swanton', 'state_id' => 36],
                ['name' => 'Wauseon', 'state_id' => 36],
                ['name' => 'Bidwell', 'state_id' => 36],
                ['name' => 'Cheshire', 'state_id' => 36],
                ['name' => 'Crown City', 'state_id' => 36],
                ['name' => 'Gallipolis', 'state_id' => 36],
                ['name' => 'Kerr', 'state_id' => 36],
                ['name' => 'Patriot', 'state_id' => 36],
                ['name' => 'Rio Grande', 'state_id' => 36],
                ['name' => 'Thurman', 'state_id' => 36],
                ['name' => 'Vinton', 'state_id' => 36],
                ['name' => 'Burton', 'state_id' => 36],
                ['name' => 'Chardon', 'state_id' => 36],
                ['name' => 'Chesterland', 'state_id' => 36],
                ['name' => 'East Claridon', 'state_id' => 36],
                ['name' => 'Huntsburg', 'state_id' => 36],
                ['name' => 'Middlefield', 'state_id' => 36],
                ['name' => 'Montville', 'state_id' => 36],
                ['name' => 'Newbury', 'state_id' => 36],
                ['name' => 'Novelty', 'state_id' => 36],
                ['name' => 'Parkman', 'state_id' => 36],
                ['name' => 'Thompson', 'state_id' => 36],
                ['name' => 'Alpha', 'state_id' => 36],
                ['name' => 'Bellbrook', 'state_id' => 36],
                ['name' => 'Bowersville', 'state_id' => 36],
                ['name' => 'Cedarville', 'state_id' => 36],
                ['name' => 'Clifton', 'state_id' => 36],
                ['name' => 'Fairborn', 'state_id' => 36],
                ['name' => 'Jamestown', 'state_id' => 36],
                ['name' => 'Spring Valley', 'state_id' => 36],
                ['name' => 'Wilberforce', 'state_id' => 36],
                ['name' => 'Xenia', 'state_id' => 36],
                ['name' => 'Yellow Springs', 'state_id' => 36],
                ['name' => 'Dayton', 'state_id' => 36],
                ['name' => 'Buffalo', 'state_id' => 36],
                ['name' => 'Byesville', 'state_id' => 36],
                ['name' => 'Cambridge', 'state_id' => 36],
                ['name' => 'Cumberland', 'state_id' => 36],
                ['name' => 'Derwent', 'state_id' => 36],
                ['name' => 'Fairview', 'state_id' => 36],
                ['name' => 'Kimbolton', 'state_id' => 36],
                ['name' => 'Kipling', 'state_id' => 36],
                ['name' => 'Lore City', 'state_id' => 36],
                ['name' => 'Old Washington', 'state_id' => 36],
                ['name' => 'Pleasant City', 'state_id' => 36],
                ['name' => 'Quaker City', 'state_id' => 36],
                ['name' => 'Salesville', 'state_id' => 36],
                ['name' => 'Senecaville', 'state_id' => 36],
                ['name' => 'Addyston', 'state_id' => 36],
                ['name' => 'Cleves', 'state_id' => 36],
                ['name' => 'Harrison', 'state_id' => 36],
                ['name' => 'Hooven', 'state_id' => 36],
                ['name' => 'Miamitown', 'state_id' => 36],
                ['name' => 'Mount Saint Joseph', 'state_id' => 36],
                ['name' => 'North Bend', 'state_id' => 36],
                ['name' => 'Camp Dennison', 'state_id' => 36],
                ['name' => 'Terrace Park', 'state_id' => 36],
                ['name' => 'Arcadia', 'state_id' => 36],
                ['name' => 'Arlington', 'state_id' => 36],
                ['name' => 'Benton Ridge', 'state_id' => 36],
                ['name' => 'Findlay', 'state_id' => 36],
                ['name' => 'Jenera', 'state_id' => 36],
                ['name' => 'Mc Comb', 'state_id' => 36],
                ['name' => 'Mount Blanchard', 'state_id' => 36],
                ['name' => 'Mount Cory', 'state_id' => 36],
                ['name' => 'Rawson', 'state_id' => 36],
                ['name' => 'Van Buren', 'state_id' => 36],
                ['name' => 'Vanlue', 'state_id' => 36],
                ['name' => 'Williamstown', 'state_id' => 36],
                ['name' => 'Kenton', 'state_id' => 36],
                ['name' => 'Mount Victory', 'state_id' => 36],
                ['name' => 'Ridgeway', 'state_id' => 36],
                ['name' => 'Roundhead', 'state_id' => 36],
                ['name' => 'Ada', 'state_id' => 36],
                ['name' => 'Alger', 'state_id' => 36],
                ['name' => 'Dola', 'state_id' => 36],
                ['name' => 'Dunkirk', 'state_id' => 36],
                ['name' => 'Forest', 'state_id' => 36],
                ['name' => 'Mc Guffey', 'state_id' => 36],
                ['name' => 'Cadiz', 'state_id' => 36],
                ['name' => 'Freeport', 'state_id' => 36],
                ['name' => 'Harrisville', 'state_id' => 36],
                ['name' => 'Hopedale', 'state_id' => 36],
                ['name' => 'New Athens', 'state_id' => 36],
                ['name' => 'New Rumley', 'state_id' => 36],
                ['name' => 'Jewett', 'state_id' => 36],
                ['name' => 'Scio', 'state_id' => 36],
                ['name' => 'Deersville', 'state_id' => 36],
                ['name' => 'Bowerston', 'state_id' => 36],
                ['name' => 'Tippecanoe', 'state_id' => 36],
                ['name' => 'Colton', 'state_id' => 36],
                ['name' => 'Deshler', 'state_id' => 36],
                ['name' => 'Grelton', 'state_id' => 36],
                ['name' => 'Hamler', 'state_id' => 36],
                ['name' => 'Holgate', 'state_id' => 36],
                ['name' => 'Liberty Center', 'state_id' => 36],
                ['name' => 'Mc Clure', 'state_id' => 36],
                ['name' => 'Malinta', 'state_id' => 36],
                ['name' => 'Napoleon', 'state_id' => 36],
                ['name' => 'New Bavaria', 'state_id' => 36],
                ['name' => 'Okolona', 'state_id' => 36],
                ['name' => 'Ridgeville Corners', 'state_id' => 36],
                ['name' => 'Greenfield', 'state_id' => 36],
                ['name' => 'Highland', 'state_id' => 36],
                ['name' => 'Hillsboro', 'state_id' => 36],
                ['name' => 'Leesburg', 'state_id' => 36],
                ['name' => 'Lynchburg', 'state_id' => 36],
                ['name' => 'Mowrystown', 'state_id' => 36],
                ['name' => 'Sinking Spring', 'state_id' => 36],
                ['name' => 'Carbon Hill', 'state_id' => 36],
                ['name' => 'Haydenville', 'state_id' => 36],
                ['name' => 'Laurelville', 'state_id' => 36],
                ['name' => 'Logan', 'state_id' => 36],
                ['name' => 'Murray City', 'state_id' => 36],
                ['name' => 'Rockbridge', 'state_id' => 36],
                ['name' => 'South Bloomingville', 'state_id' => 36],
                ['name' => 'Union Furnace', 'state_id' => 36],
                ['name' => 'Berlin', 'state_id' => 36],
                ['name' => 'Big Prairie', 'state_id' => 36],
                ['name' => 'Charm', 'state_id' => 36],
                ['name' => 'Glenmont', 'state_id' => 36],
                ['name' => 'Holmesville', 'state_id' => 36],
                ['name' => 'Killbuck', 'state_id' => 36],
                ['name' => 'Lakeville', 'state_id' => 36],
                ['name' => 'Millersburg', 'state_id' => 36],
                ['name' => 'Mount Hope', 'state_id' => 36],
                ['name' => 'Nashville', 'state_id' => 36],
                ['name' => 'Walnut Creek', 'state_id' => 36],
                ['name' => 'Winesburg', 'state_id' => 36],
                ['name' => 'Bellevue', 'state_id' => 36],
                ['name' => 'Collins', 'state_id' => 36],
                ['name' => 'Greenwich', 'state_id' => 36],
                ['name' => 'Monroeville', 'state_id' => 36],
                ['name' => 'New Haven', 'state_id' => 36],
                ['name' => 'New London', 'state_id' => 36],
                ['name' => 'North Fairfield', 'state_id' => 36],
                ['name' => 'Norwalk', 'state_id' => 36],
                ['name' => 'Willard', 'state_id' => 36],
                ['name' => 'Wakeman', 'state_id' => 36],
                ['name' => 'Coalton', 'state_id' => 36],
                ['name' => 'Jackson', 'state_id' => 36],
                ['name' => 'Oak Hill', 'state_id' => 36],
                ['name' => 'Wellston', 'state_id' => 36],
                ['name' => 'Adena', 'state_id' => 36],
                ['name' => 'Amsterdam', 'state_id' => 36],
                ['name' => 'Bergholz', 'state_id' => 36],
                ['name' => 'Bloomingdale', 'state_id' => 36],
                ['name' => 'Brilliant', 'state_id' => 36],
                ['name' => 'Dillonvale', 'state_id' => 36],
                ['name' => 'East Springfield', 'state_id' => 36],
                ['name' => 'Empire', 'state_id' => 36],
                ['name' => 'Hammondsville', 'state_id' => 36],
                ['name' => 'Irondale', 'state_id' => 36],
                ['name' => 'Mingo Junction', 'state_id' => 36],
                ['name' => 'Mount Pleasant', 'state_id' => 36],
                ['name' => 'Piney Fork', 'state_id' => 36],
                ['name' => 'Rayland', 'state_id' => 36],
                ['name' => 'Richmond', 'state_id' => 36],
                ['name' => 'Smithfield', 'state_id' => 36],
                ['name' => 'Steubenville', 'state_id' => 36],
                ['name' => 'Stratton', 'state_id' => 36],
                ['name' => 'Tiltonsville', 'state_id' => 36],
                ['name' => 'Toronto', 'state_id' => 36],
                ['name' => 'Wolf Run', 'state_id' => 36],
                ['name' => 'Yorkville', 'state_id' => 36],
                ['name' => 'Bladensburg', 'state_id' => 36],
                ['name' => 'Brinkhaven', 'state_id' => 36],
                ['name' => 'Centerburg', 'state_id' => 36],
                ['name' => 'Danville', 'state_id' => 36],
                ['name' => 'Fredericktown', 'state_id' => 36],
                ['name' => 'Gambier', 'state_id' => 36],
                ['name' => 'Howard', 'state_id' => 36],
                ['name' => 'Martinsburg', 'state_id' => 36],
                ['name' => 'Mount Liberty', 'state_id' => 36],
                ['name' => 'Mount Vernon', 'state_id' => 36],
                ['name' => 'Grand River', 'state_id' => 36],
                ['name' => 'Madison', 'state_id' => 36],
                ['name' => 'Mentor', 'state_id' => 36],
                ['name' => 'Painesville', 'state_id' => 36],
                ['name' => 'Perry', 'state_id' => 36],
                ['name' => 'Wickliffe', 'state_id' => 36],
                ['name' => 'Willoughby', 'state_id' => 36],
                ['name' => 'Eastlake', 'state_id' => 36],
                ['name' => 'Chesapeake', 'state_id' => 36],
                ['name' => 'Ironton', 'state_id' => 36],
                ['name' => 'Kitts Hill', 'state_id' => 36],
                ['name' => 'Pedro', 'state_id' => 36],
                ['name' => 'Proctorville', 'state_id' => 36],
                ['name' => 'Rock Camp', 'state_id' => 36],
                ['name' => 'Scottown', 'state_id' => 36],
                ['name' => 'South Point', 'state_id' => 36],
                ['name' => 'Waterloo', 'state_id' => 36],
                ['name' => 'Willow Wood', 'state_id' => 36],
                ['name' => 'Alexandria', 'state_id' => 36],
                ['name' => 'Buckeye Lake', 'state_id' => 36],
                ['name' => 'Croton', 'state_id' => 36],
                ['name' => 'Etna', 'state_id' => 36],
                ['name' => 'Granville', 'state_id' => 36],
                ['name' => 'Hebron', 'state_id' => 36],
                ['name' => 'Homer', 'state_id' => 36],
                ['name' => 'Jacksontown', 'state_id' => 36],
                ['name' => 'Johnstown', 'state_id' => 36],
                ['name' => 'Kirkersville', 'state_id' => 36],
                ['name' => 'Newark', 'state_id' => 36],
                ['name' => 'Heath', 'state_id' => 36],
                ['name' => 'Pataskala', 'state_id' => 36],
                ['name' => 'Saint Louisville', 'state_id' => 36],
                ['name' => 'Summit Station', 'state_id' => 36],
                ['name' => 'Utica', 'state_id' => 36],
                ['name' => 'Brownsville', 'state_id' => 36],
                ['name' => 'Gratiot', 'state_id' => 36],
                ['name' => 'Belle Center', 'state_id' => 36],
                ['name' => 'Bellefontaine', 'state_id' => 36],
                ['name' => 'De Graff', 'state_id' => 36],
                ['name' => 'East Liberty', 'state_id' => 36],
                ['name' => 'Huntsville', 'state_id' => 36],
                ['name' => 'Lakeview', 'state_id' => 36],
                ['name' => 'Lewistown', 'state_id' => 36],
                ['name' => 'Middleburg', 'state_id' => 36],
                ['name' => 'Quincy', 'state_id' => 36],
                ['name' => 'Rushsylvania', 'state_id' => 36],
                ['name' => 'Russells Point', 'state_id' => 36],
                ['name' => 'West Liberty', 'state_id' => 36],
                ['name' => 'West Mansfield', 'state_id' => 36],
                ['name' => 'Zanesfield', 'state_id' => 36],
                ['name' => 'Amherst', 'state_id' => 36],
                ['name' => 'Avon', 'state_id' => 36],
                ['name' => 'Avon Lake', 'state_id' => 36],
                ['name' => 'Columbia Station', 'state_id' => 36],
                ['name' => 'Elyria', 'state_id' => 36],
                ['name' => 'North Ridgeville', 'state_id' => 36],
                ['name' => 'Grafton', 'state_id' => 36],
                ['name' => 'Kipton', 'state_id' => 36],
                ['name' => 'Lagrange', 'state_id' => 36],
                ['name' => 'Lorain', 'state_id' => 36],
                ['name' => 'Sheffield Lake', 'state_id' => 36],
                ['name' => 'Oberlin', 'state_id' => 36],
                ['name' => 'Wellington', 'state_id' => 36],
                ['name' => 'Harbor View', 'state_id' => 36],
                ['name' => 'Berkey', 'state_id' => 36],
                ['name' => 'Holland', 'state_id' => 36],
                ['name' => 'Maumee', 'state_id' => 36],
                ['name' => 'Monclova', 'state_id' => 36],
                ['name' => 'Neapolis', 'state_id' => 36],
                ['name' => 'Sylvania', 'state_id' => 36],
                ['name' => 'Waterville', 'state_id' => 36],
                ['name' => 'Whitehouse', 'state_id' => 36],
                ['name' => 'Toledo', 'state_id' => 36],
                ['name' => 'Oregon', 'state_id' => 36],
                ['name' => 'Plain City', 'state_id' => 36],
                ['name' => 'London', 'state_id' => 36],
                ['name' => 'Mount Sterling', 'state_id' => 36],
                ['name' => 'Sedalia', 'state_id' => 36],
                ['name' => 'South Solon', 'state_id' => 36],
                ['name' => 'West Jefferson', 'state_id' => 36],
                ['name' => 'Berlin Center', 'state_id' => 36],
                ['name' => 'Campbell', 'state_id' => 36],
                ['name' => 'Canfield', 'state_id' => 36],
                ['name' => 'Ellsworth', 'state_id' => 36],
                ['name' => 'Greenford', 'state_id' => 36],
                ['name' => 'Lake Milton', 'state_id' => 36],
                ['name' => 'Lowellville', 'state_id' => 36],
                ['name' => 'New Middletown', 'state_id' => 36],
                ['name' => 'New Springfield', 'state_id' => 36],
                ['name' => 'North Benton', 'state_id' => 36],
                ['name' => 'North Jackson', 'state_id' => 36],
                ['name' => 'North Lima', 'state_id' => 36],
                ['name' => 'Petersburg', 'state_id' => 36],
                ['name' => 'Struthers', 'state_id' => 36],
                ['name' => 'Youngstown', 'state_id' => 36],
                ['name' => 'Beloit', 'state_id' => 36],
                ['name' => 'Damascus', 'state_id' => 36],
                ['name' => 'Sebring', 'state_id' => 36],
                ['name' => 'Marion', 'state_id' => 36],
                ['name' => 'Caledonia', 'state_id' => 36],
                ['name' => 'Green Camp', 'state_id' => 36],
                ['name' => 'La Rue', 'state_id' => 36],
                ['name' => 'Martel', 'state_id' => 36],
                ['name' => 'Morral', 'state_id' => 36],
                ['name' => 'New Bloomington', 'state_id' => 36],
                ['name' => 'Prospect', 'state_id' => 36],
                ['name' => 'Waldo', 'state_id' => 36],
                ['name' => 'Brunswick', 'state_id' => 36],
                ['name' => 'Chippewa Lake', 'state_id' => 36],
                ['name' => 'Hinckley', 'state_id' => 36],
                ['name' => 'Homerville', 'state_id' => 36],
                ['name' => 'Westfield Center', 'state_id' => 36],
                ['name' => 'Litchfield', 'state_id' => 36],
                ['name' => 'Lodi', 'state_id' => 36],
                ['name' => 'Medina', 'state_id' => 36],
                ['name' => 'Seville', 'state_id' => 36],
                ['name' => 'Sharon Center', 'state_id' => 36],
                ['name' => 'Spencer', 'state_id' => 36],
                ['name' => 'Valley City', 'state_id' => 36],
                ['name' => 'Wadsworth', 'state_id' => 36],
                ['name' => 'Chester', 'state_id' => 36],
                ['name' => 'Langsville', 'state_id' => 36],
                ['name' => 'Long Bottom', 'state_id' => 36],
                ['name' => 'Middleport', 'state_id' => 36],
                ['name' => 'Pomeroy', 'state_id' => 36],
                ['name' => 'Portland', 'state_id' => 36],
                ['name' => 'Racine', 'state_id' => 36],
                ['name' => 'Reedsville', 'state_id' => 36],
                ['name' => 'Rutland', 'state_id' => 36],
                ['name' => 'Syracuse', 'state_id' => 36],
                ['name' => 'Tuppers Plains', 'state_id' => 36],
                ['name' => 'Burkettsville', 'state_id' => 36],
                ['name' => 'Celina', 'state_id' => 36],
                ['name' => 'Chickasaw', 'state_id' => 36],
                ['name' => 'Coldwater', 'state_id' => 36],
                ['name' => 'Fort Recovery', 'state_id' => 36],
                ['name' => 'Maria Stein', 'state_id' => 36],
                ['name' => 'Mendon', 'state_id' => 36],
                ['name' => 'Montezuma', 'state_id' => 36],
                ['name' => 'Rockford', 'state_id' => 36],
                ['name' => 'Saint Henry', 'state_id' => 36],
                ['name' => 'Bradford', 'state_id' => 36],
                ['name' => 'Casstown', 'state_id' => 36],
                ['name' => 'Conover', 'state_id' => 36],
                ['name' => 'Covington', 'state_id' => 36],
                ['name' => 'Fletcher', 'state_id' => 36],
                ['name' => 'Laura', 'state_id' => 36],
                ['name' => 'Ludlow Falls', 'state_id' => 36],
                ['name' => 'Piqua', 'state_id' => 36],
                ['name' => 'Pleasant Hill', 'state_id' => 36],
                ['name' => 'Potsdam', 'state_id' => 36],
                ['name' => 'Tipp City', 'state_id' => 36],
                ['name' => 'Troy', 'state_id' => 36],
                ['name' => 'West Milton', 'state_id' => 36],
                ['name' => 'Beallsville', 'state_id' => 36],
                ['name' => 'Jerusalem', 'state_id' => 36],
                ['name' => 'Laings', 'state_id' => 36],
                ['name' => 'Lewisville', 'state_id' => 36],
                ['name' => 'Malaga', 'state_id' => 36],
                ['name' => 'Stafford', 'state_id' => 36],
                ['name' => 'Woodsfield', 'state_id' => 36],
                ['name' => 'Cameron', 'state_id' => 36],
                ['name' => 'Clarington', 'state_id' => 36],
                ['name' => 'Hannibal', 'state_id' => 36],
                ['name' => 'Sardis', 'state_id' => 36],
                ['name' => 'Graysville', 'state_id' => 36],
                ['name' => 'Brookville', 'state_id' => 36],
                ['name' => 'Clayton', 'state_id' => 36],
                ['name' => 'Englewood', 'state_id' => 36],
                ['name' => 'Farmersville', 'state_id' => 36],
                ['name' => 'Germantown', 'state_id' => 36],
                ['name' => 'Miamisburg', 'state_id' => 36],
                ['name' => 'New Lebanon', 'state_id' => 36],
                ['name' => 'Phillipsburg', 'state_id' => 36],
                ['name' => 'Vandalia', 'state_id' => 36],
                ['name' => 'Chesterhill', 'state_id' => 36],
                ['name' => 'Mcconnelsville', 'state_id' => 36],
                ['name' => 'Malta', 'state_id' => 36],
                ['name' => 'Stockport', 'state_id' => 36],
                ['name' => 'Cardington', 'state_id' => 36],
                ['name' => 'Chesterville', 'state_id' => 36],
                ['name' => 'Edison', 'state_id' => 36],
                ['name' => 'Fulton', 'state_id' => 36],
                ['name' => 'Iberia', 'state_id' => 36],
                ['name' => 'Marengo', 'state_id' => 36],
                ['name' => 'Mount Gilead', 'state_id' => 36],
                ['name' => 'Shauck', 'state_id' => 36],
                ['name' => 'Sparta', 'state_id' => 36],
                ['name' => 'Zanesville', 'state_id' => 36],
                ['name' => 'Blue Rock', 'state_id' => 36],
                ['name' => 'Chandlersville', 'state_id' => 36],
                ['name' => 'Duncan Falls', 'state_id' => 36],
                ['name' => 'East Fultonham', 'state_id' => 36],
                ['name' => 'Fultonham', 'state_id' => 36],
                ['name' => 'Hopewell', 'state_id' => 36],
                ['name' => 'New Concord', 'state_id' => 36],
                ['name' => 'Norwich', 'state_id' => 36],
                ['name' => 'Philo', 'state_id' => 36],
                ['name' => 'Roseville', 'state_id' => 36],
                ['name' => 'White Cottage', 'state_id' => 36],
                ['name' => 'Adamsville', 'state_id' => 36],
                ['name' => 'Dresden', 'state_id' => 36],
                ['name' => 'Frazeysburg', 'state_id' => 36],
                ['name' => 'Nashport', 'state_id' => 36],
                ['name' => 'Trinway', 'state_id' => 36],
                ['name' => 'Ava', 'state_id' => 36],
                ['name' => 'Belle Valley', 'state_id' => 36],
                ['name' => 'Caldwell', 'state_id' => 36],
                ['name' => 'Sarahsville', 'state_id' => 36],
                ['name' => 'Summerfield', 'state_id' => 36],
                ['name' => 'Dexter City', 'state_id' => 36],
                ['name' => 'Clay Center', 'state_id' => 36],
                ['name' => 'Curtice', 'state_id' => 36],
                ['name' => 'Elmore', 'state_id' => 36],
                ['name' => 'Genoa', 'state_id' => 36],
                ['name' => 'Graytown', 'state_id' => 36],
                ['name' => 'Gypsum', 'state_id' => 36],
                ['name' => 'Isle Saint George', 'state_id' => 36],
                ['name' => 'Lacarne', 'state_id' => 36],
                ['name' => 'Lakeside Marblehead', 'state_id' => 36],
                ['name' => 'Martin', 'state_id' => 36],
                ['name' => 'Middle Bass', 'state_id' => 36],
                ['name' => 'Oak Harbor', 'state_id' => 36],
                ['name' => 'Port Clinton', 'state_id' => 36],
                ['name' => 'Put In Bay', 'state_id' => 36],
                ['name' => 'Rocky Ridge', 'state_id' => 36],
                ['name' => 'Williston', 'state_id' => 36],
                ['name' => 'Antwerp', 'state_id' => 36],
                ['name' => 'Cecil', 'state_id' => 36],
                ['name' => 'Grover Hill', 'state_id' => 36],
                ['name' => 'Haviland', 'state_id' => 36],
                ['name' => 'Latty', 'state_id' => 36],
                ['name' => 'Melrose', 'state_id' => 36],
                ['name' => 'Oakwood', 'state_id' => 36],
                ['name' => 'Paulding', 'state_id' => 36],
                ['name' => 'Payne', 'state_id' => 36],
                ['name' => 'Thornville', 'state_id' => 36],
                ['name' => 'Corning', 'state_id' => 36],
                ['name' => 'Crooksville', 'state_id' => 36],
                ['name' => 'Glenford', 'state_id' => 36],
                ['name' => 'Junction City', 'state_id' => 36],
                ['name' => 'Mount Perry', 'state_id' => 36],
                ['name' => 'Moxahala', 'state_id' => 36],
                ['name' => 'New Lexington', 'state_id' => 36],
                ['name' => 'New Straitsville', 'state_id' => 36],
                ['name' => 'Shawnee', 'state_id' => 36],
                ['name' => 'Somerset', 'state_id' => 36],
                ['name' => 'Ashville', 'state_id' => 36],
                ['name' => 'Circleville', 'state_id' => 36],
                ['name' => 'Commercial Point', 'state_id' => 36],
                ['name' => 'Derby', 'state_id' => 36],
                ['name' => 'New Holland', 'state_id' => 36],
                ['name' => 'Orient', 'state_id' => 36],
                ['name' => 'Tarlton', 'state_id' => 36],
                ['name' => 'Williamsport', 'state_id' => 36],
                ['name' => 'Beaver', 'state_id' => 36],
                ['name' => 'Cynthiana', 'state_id' => 36],
                ['name' => 'Jasper', 'state_id' => 36],
                ['name' => 'Latham', 'state_id' => 36],
                ['name' => 'Piketon', 'state_id' => 36],
                ['name' => 'Stockdale', 'state_id' => 36],
                ['name' => 'Wakefield', 'state_id' => 36],
                ['name' => 'Waverly', 'state_id' => 36],
                ['name' => 'Atwater', 'state_id' => 36],
                ['name' => 'Aurora', 'state_id' => 36],
                ['name' => 'Brady Lake', 'state_id' => 36],
                ['name' => 'Garrettsville', 'state_id' => 36],
                ['name' => 'Hiram', 'state_id' => 36],
                ['name' => 'Kent', 'state_id' => 36],
                ['name' => 'Streetsboro', 'state_id' => 36],
                ['name' => 'Mantua', 'state_id' => 36],
                ['name' => 'Randolph', 'state_id' => 36],
                ['name' => 'Ravenna', 'state_id' => 36],
                ['name' => 'Rootstown', 'state_id' => 36],
                ['name' => 'Wayland', 'state_id' => 36],
                ['name' => 'Windham', 'state_id' => 36],
                ['name' => 'Deerfield', 'state_id' => 36],
                ['name' => 'Diamond', 'state_id' => 36],
                ['name' => 'West Elkton', 'state_id' => 36],
                ['name' => 'Camden', 'state_id' => 36],
                ['name' => 'Eaton', 'state_id' => 36],
                ['name' => 'Eldorado', 'state_id' => 36],
                ['name' => 'Gratis', 'state_id' => 36],
                ['name' => 'Lewisburg', 'state_id' => 36],
                ['name' => 'New Paris', 'state_id' => 36],
                ['name' => 'Verona', 'state_id' => 36],
                ['name' => 'West Alexandria', 'state_id' => 36],
                ['name' => 'West Manchester', 'state_id' => 36],
                ['name' => 'Belmore', 'state_id' => 36],
                ['name' => 'Cloverdale', 'state_id' => 36],
                ['name' => 'Columbus Grove', 'state_id' => 36],
                ['name' => 'Continental', 'state_id' => 36],
                ['name' => 'Dupont', 'state_id' => 36],
                ['name' => 'Fort Jennings', 'state_id' => 36],
                ['name' => 'Glandorf', 'state_id' => 36],
                ['name' => 'Kalida', 'state_id' => 36],
                ['name' => 'Leipsic', 'state_id' => 36],
                ['name' => 'Miller City', 'state_id' => 36],
                ['name' => 'Ottawa', 'state_id' => 36],
                ['name' => 'Ottoville', 'state_id' => 36],
                ['name' => 'Pandora', 'state_id' => 36],
                ['name' => 'Vaughnsville', 'state_id' => 36],
                ['name' => 'Bellville', 'state_id' => 36],
                ['name' => 'Butler', 'state_id' => 36],
                ['name' => 'Lucas', 'state_id' => 36],
                ['name' => 'Ontario', 'state_id' => 36],
                ['name' => 'Plymouth', 'state_id' => 36],
                ['name' => 'Shelby', 'state_id' => 36],
                ['name' => 'Shiloh', 'state_id' => 36],
                ['name' => 'Mansfield', 'state_id' => 36],
                ['name' => 'Adelphi', 'state_id' => 36],
                ['name' => 'Clarksburg', 'state_id' => 36],
                ['name' => 'Chillicothe', 'state_id' => 36],
                ['name' => 'Bainbridge', 'state_id' => 36],
                ['name' => 'Bourneville', 'state_id' => 36],
                ['name' => 'Frankfort', 'state_id' => 36],
                ['name' => 'Hallsville', 'state_id' => 36],
                ['name' => 'Kingston', 'state_id' => 36],
                ['name' => 'Londonderry', 'state_id' => 36],
                ['name' => 'Richmond Dale', 'state_id' => 36],
                ['name' => 'South Salem', 'state_id' => 36],
                ['name' => 'Burgoon', 'state_id' => 36],
                ['name' => 'Clyde', 'state_id' => 36],
                ['name' => 'Fremont', 'state_id' => 36],
                ['name' => 'Gibsonburg', 'state_id' => 36],
                ['name' => 'Helena', 'state_id' => 36],
                ['name' => 'Lindsey', 'state_id' => 36],
                ['name' => 'Vickery', 'state_id' => 36],
                ['name' => 'Woodville', 'state_id' => 36],
                ['name' => 'Franklin Furnace', 'state_id' => 36],
                ['name' => 'Friendship', 'state_id' => 36],
                ['name' => 'Haverhill', 'state_id' => 36],
                ['name' => 'Lucasville', 'state_id' => 36],
                ['name' => 'Mc Dermott', 'state_id' => 36],
                ['name' => 'Minford', 'state_id' => 36],
                ['name' => 'Otway', 'state_id' => 36],
                ['name' => 'Portsmouth', 'state_id' => 36],
                ['name' => 'West Portsmouth', 'state_id' => 36],
                ['name' => 'Rarden', 'state_id' => 36],
                ['name' => 'Scioto Furnace', 'state_id' => 36],
                ['name' => 'South Webster', 'state_id' => 36],
                ['name' => 'Stout', 'state_id' => 36],
                ['name' => 'Wheelersburg', 'state_id' => 36],
                ['name' => 'Alvada', 'state_id' => 36],
                ['name' => 'Attica', 'state_id' => 36],
                ['name' => 'Bascom', 'state_id' => 36],
                ['name' => 'Bettsville', 'state_id' => 36],
                ['name' => 'Bloomville', 'state_id' => 36],
                ['name' => 'Flat Rock', 'state_id' => 36],
                ['name' => 'Fostoria', 'state_id' => 36],
                ['name' => 'Green Springs', 'state_id' => 36],
                ['name' => 'Kansas', 'state_id' => 36],
                ['name' => 'Melmore', 'state_id' => 36],
                ['name' => 'New Riegel', 'state_id' => 36],
                ['name' => 'Old Fort', 'state_id' => 36],
                ['name' => 'Republic', 'state_id' => 36],
                ['name' => 'Tiffin', 'state_id' => 36],
                ['name' => 'Anna', 'state_id' => 36],
                ['name' => 'Botkins', 'state_id' => 36],
                ['name' => 'Houston', 'state_id' => 36],
                ['name' => 'Jackson Center', 'state_id' => 36],
                ['name' => 'Kettlersville', 'state_id' => 36],
                ['name' => 'Maplewood', 'state_id' => 36],
                ['name' => 'Pemberton', 'state_id' => 36],
                ['name' => 'Port Jefferson', 'state_id' => 36],
                ['name' => 'Russia', 'state_id' => 36],
                ['name' => 'Sidney', 'state_id' => 36],
                ['name' => 'Fort Loramie', 'state_id' => 36],
                ['name' => 'Alliance', 'state_id' => 36],
                ['name' => 'Beach City', 'state_id' => 36],
                ['name' => 'Brewster', 'state_id' => 36],
                ['name' => 'Canal Fulton', 'state_id' => 36],
                ['name' => 'East Sparta', 'state_id' => 36],
                ['name' => 'Greentown', 'state_id' => 36],
                ['name' => 'Hartville', 'state_id' => 36],
                ['name' => 'Limaville', 'state_id' => 36],
                ['name' => 'Louisville', 'state_id' => 36],
                ['name' => 'Magnolia', 'state_id' => 36],
                ['name' => 'Massillon', 'state_id' => 36],
                ['name' => 'Maximo', 'state_id' => 36],
                ['name' => 'Middlebranch', 'state_id' => 36],
                ['name' => 'Minerva', 'state_id' => 36],
                ['name' => 'Navarre', 'state_id' => 36],
                ['name' => 'North Lawrence', 'state_id' => 36],
                ['name' => 'Paris', 'state_id' => 36],
                ['name' => 'Robertsville', 'state_id' => 36],
                ['name' => 'Waynesburg', 'state_id' => 36],
                ['name' => 'Wilmot', 'state_id' => 36],
                ['name' => 'Canton', 'state_id' => 36],
                ['name' => 'North Canton', 'state_id' => 36],
                ['name' => 'East Canton', 'state_id' => 36],
                ['name' => 'Macedonia', 'state_id' => 36],
                ['name' => 'Northfield', 'state_id' => 36],
                ['name' => 'Twinsburg', 'state_id' => 36],
                ['name' => 'Barberton', 'state_id' => 36],
                ['name' => 'Bath', 'state_id' => 36],
                ['name' => 'Clinton', 'state_id' => 36],
                ['name' => 'Cuyahoga Falls', 'state_id' => 36],
                ['name' => 'Stow', 'state_id' => 36],
                ['name' => 'Green', 'state_id' => 36],
                ['name' => 'Hudson', 'state_id' => 36],
                ['name' => 'Lakemore', 'state_id' => 36],
                ['name' => 'Mogadore', 'state_id' => 36],
                ['name' => 'Munroe Falls', 'state_id' => 36],
                ['name' => 'Peninsula', 'state_id' => 36],
                ['name' => 'Tallmadge', 'state_id' => 36],
                ['name' => 'Richfield', 'state_id' => 36],
                ['name' => 'Akron', 'state_id' => 36],
                ['name' => 'Fairlawn', 'state_id' => 36],
                ['name' => 'Uniontown', 'state_id' => 36],
                ['name' => 'Bristolville', 'state_id' => 36],
                ['name' => 'Brookfield', 'state_id' => 36],
                ['name' => 'Burghill', 'state_id' => 36],
                ['name' => 'Cortland', 'state_id' => 36],
                ['name' => 'Farmdale', 'state_id' => 36],
                ['name' => 'Fowler', 'state_id' => 36],
                ['name' => 'Girard', 'state_id' => 36],
                ['name' => 'Hartford', 'state_id' => 36],
                ['name' => 'Hubbard', 'state_id' => 36],
                ['name' => 'Kinsman', 'state_id' => 36],
                ['name' => 'Leavittsburg', 'state_id' => 36],
                ['name' => 'Mc Donald', 'state_id' => 36],
                ['name' => 'Masury', 'state_id' => 36],
                ['name' => 'Mesopotamia', 'state_id' => 36],
                ['name' => 'Mineral Ridge', 'state_id' => 36],
                ['name' => 'Newton Falls', 'state_id' => 36],
                ['name' => 'Niles', 'state_id' => 36],
                ['name' => 'North Bloomfield', 'state_id' => 36],
                ['name' => 'Orangeville', 'state_id' => 36],
                ['name' => 'Southington', 'state_id' => 36],
                ['name' => 'Vienna', 'state_id' => 36],
                ['name' => 'Warren', 'state_id' => 36],
                ['name' => 'West Farmington', 'state_id' => 36],
                ['name' => 'Baltic', 'state_id' => 36],
                ['name' => 'Newcomerstown', 'state_id' => 36],
                ['name' => 'Port Washington', 'state_id' => 36],
                ['name' => 'Stone Creek', 'state_id' => 36],
                ['name' => 'Bolivar', 'state_id' => 36],
                ['name' => 'Dennison', 'state_id' => 36],
                ['name' => 'Dover', 'state_id' => 36],
                ['name' => 'Dundee', 'state_id' => 36],
                ['name' => 'Gnadenhutten', 'state_id' => 36],
                ['name' => 'Midvale', 'state_id' => 36],
                ['name' => 'Mineral City', 'state_id' => 36],
                ['name' => 'New Philadelphia', 'state_id' => 36],
                ['name' => 'Sandyville', 'state_id' => 36],
                ['name' => 'Somerdale', 'state_id' => 36],
                ['name' => 'Stillwater', 'state_id' => 36],
                ['name' => 'Strasburg', 'state_id' => 36],
                ['name' => 'Sugarcreek', 'state_id' => 36],
                ['name' => 'Tuscarawas', 'state_id' => 36],
                ['name' => 'Uhrichsville', 'state_id' => 36],
                ['name' => 'Zoar', 'state_id' => 36],
                ['name' => 'Broadway', 'state_id' => 36],
                ['name' => 'Irwin', 'state_id' => 36],
                ['name' => 'Magnetic Springs', 'state_id' => 36],
                ['name' => 'Marysville', 'state_id' => 36],
                ['name' => 'Milford Center', 'state_id' => 36],
                ['name' => 'Raymond', 'state_id' => 36],
                ['name' => 'Unionville Center', 'state_id' => 36],
                ['name' => 'Richwood', 'state_id' => 36],
                ['name' => 'Convoy', 'state_id' => 36],
                ['name' => 'Elgin', 'state_id' => 36],
                ['name' => 'Middle Point', 'state_id' => 36],
                ['name' => 'Ohio City', 'state_id' => 36],
                ['name' => 'Scott', 'state_id' => 36],
                ['name' => 'Van Wert', 'state_id' => 36],
                ['name' => 'Venedocia', 'state_id' => 36],
                ['name' => 'Willshire', 'state_id' => 36],
                ['name' => 'Wren', 'state_id' => 36],
                ['name' => 'Creola', 'state_id' => 36],
                ['name' => 'Hamden', 'state_id' => 36],
                ['name' => 'Mc Arthur', 'state_id' => 36],
                ['name' => 'New Plymouth', 'state_id' => 36],
                ['name' => 'Ray', 'state_id' => 36],
                ['name' => 'Wilkesville', 'state_id' => 36],
                ['name' => 'Zaleski', 'state_id' => 36],
                ['name' => 'Franklin', 'state_id' => 36],
                ['name' => 'Harveysburg', 'state_id' => 36],
                ['name' => 'Kings Mills', 'state_id' => 36],
                ['name' => 'Lebanon', 'state_id' => 36],
                ['name' => 'Maineville', 'state_id' => 36],
                ['name' => 'Mason', 'state_id' => 36],
                ['name' => 'Oregonia', 'state_id' => 36],
                ['name' => 'South Lebanon', 'state_id' => 36],
                ['name' => 'Springboro', 'state_id' => 36],
                ['name' => 'Waynesville', 'state_id' => 36],
                ['name' => 'Morrow', 'state_id' => 36],
                ['name' => 'Pleasant Plain', 'state_id' => 36],
                ['name' => 'Barlow', 'state_id' => 36],
                ['name' => 'Bartlett', 'state_id' => 36],
                ['name' => 'Belpre', 'state_id' => 36],
                ['name' => 'Beverly', 'state_id' => 36],
                ['name' => 'Coal Run', 'state_id' => 36],
                ['name' => 'Cutler', 'state_id' => 36],
                ['name' => 'Fleming', 'state_id' => 36],
                ['name' => 'Little Hocking', 'state_id' => 36],
                ['name' => 'Lowell', 'state_id' => 36],
                ['name' => 'Lower Salem', 'state_id' => 36],
                ['name' => 'Macksburg', 'state_id' => 36],
                ['name' => 'Marietta', 'state_id' => 36],
                ['name' => 'New Matamoras', 'state_id' => 36],
                ['name' => 'Newport', 'state_id' => 36],
                ['name' => 'Reno', 'state_id' => 36],
                ['name' => 'Vincent', 'state_id' => 36],
                ['name' => 'Waterford', 'state_id' => 36],
                ['name' => 'Watertown', 'state_id' => 36],
                ['name' => 'Whipple', 'state_id' => 36],
                ['name' => 'Wingett Run', 'state_id' => 36],
                ['name' => 'Burbank', 'state_id' => 36],
                ['name' => 'Creston', 'state_id' => 36],
                ['name' => 'Doylestown', 'state_id' => 36],
                ['name' => 'Rittman', 'state_id' => 36],
                ['name' => 'Sterling', 'state_id' => 36],
                ['name' => 'West Salem', 'state_id' => 36],
                ['name' => 'Apple Creek', 'state_id' => 36],
                ['name' => 'Dalton', 'state_id' => 36],
                ['name' => 'Fredericksburg', 'state_id' => 36],
                ['name' => 'Kidron', 'state_id' => 36],
                ['name' => 'Marshallville', 'state_id' => 36],
                ['name' => 'Mount Eaton', 'state_id' => 36],
                ['name' => 'Orrville', 'state_id' => 36],
                ['name' => 'Shreve', 'state_id' => 36],
                ['name' => 'Smithville', 'state_id' => 36],
                ['name' => 'Wooster', 'state_id' => 36],
                ['name' => 'Alvordton', 'state_id' => 36],
                ['name' => 'Blakeslee', 'state_id' => 36],
                ['name' => 'Bryan', 'state_id' => 36],
                ['name' => 'Edgerton', 'state_id' => 36],
                ['name' => 'Edon', 'state_id' => 36],
                ['name' => 'Kunkle', 'state_id' => 36],
                ['name' => 'Montpelier', 'state_id' => 36],
                ['name' => 'Pioneer', 'state_id' => 36],
                ['name' => 'Stryker', 'state_id' => 36],
                ['name' => 'West Unity', 'state_id' => 36],
                ['name' => 'Bowling Green', 'state_id' => 36],
                ['name' => 'Bradner', 'state_id' => 36],
                ['name' => 'Cygnet', 'state_id' => 36],
                ['name' => 'Dunbridge', 'state_id' => 36],
                ['name' => 'Jerry City', 'state_id' => 36],
                ['name' => 'Lemoyne', 'state_id' => 36],
                ['name' => 'Luckey', 'state_id' => 36],
                ['name' => 'Millbury', 'state_id' => 36],
                ['name' => 'Pemberville', 'state_id' => 36],
                ['name' => 'Portage', 'state_id' => 36],
                ['name' => 'Risingsun', 'state_id' => 36],
                ['name' => 'Rossford', 'state_id' => 36],
                ['name' => 'Rudolph', 'state_id' => 36],
                ['name' => 'Stony Ridge', 'state_id' => 36],
                ['name' => 'Walbridge', 'state_id' => 36],
                ['name' => 'Wayne', 'state_id' => 36],
                ['name' => 'West Millgrove', 'state_id' => 36],
                ['name' => 'Custar', 'state_id' => 36],
                ['name' => 'Grand Rapids', 'state_id' => 36],
                ['name' => 'Haskins', 'state_id' => 36],
                ['name' => 'Hoytville', 'state_id' => 36],
                ['name' => 'Milton Center', 'state_id' => 36],
                ['name' => 'Perrysburg', 'state_id' => 36],
                ['name' => 'Tontogany', 'state_id' => 36],
                ['name' => 'Weston', 'state_id' => 36],
                ['name' => 'Northwood', 'state_id' => 36],
                ['name' => 'Bloomdale', 'state_id' => 36],
                ['name' => 'North Baltimore', 'state_id' => 36],
                ['name' => 'Carey', 'state_id' => 36],
                ['name' => 'Harpster', 'state_id' => 36],
                ['name' => 'Kirby', 'state_id' => 36],
                ['name' => 'Upper Sandusky', 'state_id' => 36],
                ['name' => 'Wharton', 'state_id' => 36],
                ['name' => 'Mc Cutchenville', 'state_id' => 36],
                ['name' => 'Nevada', 'state_id' => 36],
                ['name' => 'Sycamore', 'state_id' => 36]
            ]);
        }
    }
}
